# NPKit instrumentation compile definitions (RCCL-only).
#
# This module is an RCCL delta with no NCCL CMake counterpart. It was extracted
# verbatim from src/CMakeLists.txt so the NCCL-aligned regions there stay small
# and easy to merge from upstream. Behaviour is unchanged: when ENABLE_NPKIT is
# set, every ENABLE_NPKIT* macro is defined PRIVATE on the given target.

function(rccl_configure_npkit TARGET)
  if(NOT ENABLE_NPKIT)
    return()
  endif()

  message(WARNING "NPKit is deprecated and will be removed in a future version of RCCL. Please consider using alternative profiling tools.")

  set(_npkit_defs
    ENABLE_NPKIT
    ENABLE_NPKIT_EVENT_TIME_SYNC_GPU
    ENABLE_NPKIT_EVENT_TIME_SYNC_CPU
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_EXIT
    ENABLE_NPKIT_EVENT_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_DIRECT_RECV_ENTRY
    ENABLE_NPKIT_EVENT_DIRECT_RECV_EXIT
    ENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_DIRECT_SEND_ENTRY
    ENABLE_NPKIT_EVENT_DIRECT_SEND_EXIT
    ENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_ENTRY
    ENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_EXIT
    ENABLE_NPKIT_EVENT_RECV_ENTRY
    ENABLE_NPKIT_EVENT_RECV_EXIT
    ENABLE_NPKIT_EVENT_RECV_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_RECV_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_ENTRY
    ENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_EXIT
    ENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_ENTRY
    ENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_EXIT
    ENABLE_NPKIT_EVENT_SEND_ENTRY
    ENABLE_NPKIT_EVENT_SEND_EXIT
    ENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_ENTRY
    ENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_EXIT
    ENABLE_NPKIT_EVENT_PRIM_SIMPLE_WAIT_PEER_ENTRY
    ENABLE_NPKIT_EVENT_PRIM_SIMPLE_WAIT_PEER_EXIT
    ENABLE_NPKIT_EVENT_PRIM_SIMPLE_REDUCE_OR_COPY_MULTI_ENTRY
    ENABLE_NPKIT_EVENT_PRIM_SIMPLE_REDUCE_OR_COPY_MULTI_EXIT
    ENABLE_NPKIT_EVENT_PRIM_LL_WAIT_SEND_ENTRY
    ENABLE_NPKIT_EVENT_PRIM_LL_WAIT_SEND_EXIT
    ENABLE_NPKIT_EVENT_PRIM_LL_DATA_PROCESS_ENTRY
    ENABLE_NPKIT_EVENT_PRIM_LL_DATA_PROCESS_EXIT
    ENABLE_NPKIT_EVENT_PRIM_LL128_WAIT_SEND_ENTRY
    ENABLE_NPKIT_EVENT_PRIM_LL128_WAIT_SEND_EXIT
    ENABLE_NPKIT_EVENT_PRIM_LL128_DATA_PROCESS_ENTRY
    ENABLE_NPKIT_EVENT_PRIM_LL128_DATA_PROCESS_EXIT
    ENABLE_NPKIT_EVENT_NET_SEND_ENTRY
    ENABLE_NPKIT_EVENT_NET_SEND_EXIT
    ENABLE_NPKIT_EVENT_NET_TEST_ENTRY
    ENABLE_NPKIT_EVENT_NET_TEST_EXIT
    ENABLE_NPKIT_EVENT_NET_RECV_ENTRY
    ENABLE_NPKIT_EVENT_NET_RECV_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_SEND_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_SEND_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_RECV_REDUCE_SEND_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_RECV_REDUCE_SEND_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_REDUCE_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_REDUCE_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_REDUCE_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_BROADCAST_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_BROADCAST_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_BROADCAST_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_BROADCAST_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_EXIT
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_BROADCAST_ENTRY
    ENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_BROADCAST_EXIT
    ENABLE_NPKIT_EVENT_SEND_RECV_LOCAL_COPY_ENTRY
    ENABLE_NPKIT_EVENT_SEND_RECV_LOCAL_COPY_EXIT
    ENABLE_NPKIT_EVENT_SEND_RECV_SEND_ENTRY
    ENABLE_NPKIT_EVENT_SEND_RECV_SEND_EXIT
    ENABLE_NPKIT_EVENT_SEND_RECV_RECV_ENTRY
    ENABLE_NPKIT_EVENT_SEND_RECV_RECV_EXIT
    ENABLE_NPKIT_EVENT_ALL_GATHER_RING_ENTRY
    ENABLE_NPKIT_EVENT_ALL_GATHER_RING_EXIT
    ENABLE_NPKIT_EVENT_ALL_GATHER_RING_SEND_ENTRY
    ENABLE_NPKIT_EVENT_ALL_GATHER_RING_SEND_EXIT
    ENABLE_NPKIT_EVENT_ALL_GATHER_RING_RECV_COPY_SEND_ENTRY
    ENABLE_NPKIT_EVENT_ALL_GATHER_RING_RECV_COPY_SEND_EXIT
    ENABLE_NPKIT_EVENT_ALL_GATHER_RING_DIRECT_RECV_ENTRY
    ENABLE_NPKIT_EVENT_ALL_GATHER_RING_DIRECT_RECV_EXIT
    ENABLE_NPKIT_EVENT_BROADCAST_RING_ENTRY
    ENABLE_NPKIT_EVENT_BROADCAST_RING_EXIT
    ENABLE_NPKIT_EVENT_REDUCE_SCATTER_RING_ENTRY
    ENABLE_NPKIT_EVENT_REDUCE_SCATTER_RING_EXIT
    ENABLE_NPKIT_EVENT_REDUCE_SCATTER_RING_SEND_ENTRY
    ENABLE_NPKIT_EVENT_REDUCE_SCATTER_RING_SEND_EXIT
    ENABLE_NPKIT_EVENT_REDUCE_SCATTER_RING_RECV_REDUCE_SEND_ENTRY
    ENABLE_NPKIT_EVENT_REDUCE_SCATTER_RING_RECV_REDUCE_SEND_EXIT
    ENABLE_NPKIT_EVENT_REDUCE_SCATTER_RING_RECV_REDUCE_COPY_ENTRY
    ENABLE_NPKIT_EVENT_REDUCE_SCATTER_RING_RECV_REDUCE_COPY_EXIT
    ENABLE_NPKIT_PRIM_COLLECT_DATA_PROCESS_TIME
  )

  foreach(_def IN LISTS _npkit_defs)
    target_compile_definitions(${TARGET} PRIVATE ${_def})
  endforeach()
endfunction()
