services:
  doctest: # service name
    build:
      context: ../
      dockerfile: docker/Dockerfile.doctest
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../:/app
    tty: true
    stdin_open: true
