services:
  test:
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../:/app