services:
  customrocmtest: # service name
    build:
      context: ../
      dockerfile: docker/Dockerfile.customrocmtest
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../:/app
      - ../../rocprofiler-sdk:/rocprofiler-sdk
    ports:
      - 8050:8050
    tty: true
    stdin_open: true
