name: Keywords Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [ amd-staging, amd-mainline ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  keyword-search:
    strategy:
      fail-fast: true
      matrix:
        runner: [ubuntu-latest]

    runs-on: ${{ matrix.runner }}
    env:
      KEYWORDS: ${{ vars.KEYWORDS }}
    steps:
      - uses: actions/checkout@v4
      - name: find-keywords
        shell: bash
        run: ./source/scripts/scan-script.sh
