################################################################################
##
## The University of Illinois/NCSA
## Open Source License (NCSA)
##
## Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
##
## Developed by:
##
##                 AMD Research and AMD HSA Software Development
##
##                 Advanced Micro Devices, Inc.
##
##                 www.amd.com
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal with the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
##  - Redistributions of source code must retain the above copyright notice,
##    this list of conditions and the following disclaimers.
##  - Redistributions in binary form must reproduce the above copyright
##    notice, this list of conditions and the following disclaimers in
##    the documentation and/or other materials provided with the distribution.
##  - Neither the names of Advanced Micro Devices, Inc,
##    nor the names of its contributors may be used to endorse or promote
##    products derived from this Software without specific prior written
##    permission.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
## THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
## OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
## ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS WITH THE SOFTWARE.
##
################################################################################
import sys

def GetSize(fileobject):
    fileobject.seek(0,2) # move the cursor to the end of the file
    size = fileobject.tell()
    return size

def DumpFile(header, input_name):
  try:
    with open(input_name, "rb") as binary_file:
        # Read the entire content of the file as bytes
        binary_data = binary_file.read()
        file_size = GetSize(binary_file)
        #print(f"Binary size: {file_size}")
        # Reset file pointer
        binary_file.seek(0)
        parts = input_name.split('.')
        file_name = parts[0]
        content = f"unsigned char {file_name}""[] = {\n  "

        header.write(content)
        line = 0
        count = 0
        for byte_value in binary_data:
          count += 1
          padded_hex = '{:02x}'.format(byte_value)
          if (count != file_size):
            header.write(f"0x{padded_hex},")
          else:
            header.write(f"0x{padded_hex}")
          line += 1
          if (line == 12):
            header.write(f"\n  ")
            line = 0
          else:
            header.write(f" ")

        header.write("\n};\nunsigned int "f"{file_name}_len = {file_size};\n")

  except FileNotFoundError:
    print(f"Error: The file {input_name} was not found.")
  except Exception as e:
    print(f"An error occurred: {e}")


if len(sys.argv) > 1:
  header_name = sys.argv[1];
  with open(header_name, 'w') as header:
    header.write("//==============================================================================\n")
    header.write("//  This file is automatically generated during build process, don't modify it\n")
    header.write("//==============================================================================\n\n")
    header.write("namespace rocr {\n")
    header.write("namespace AMD {\n\n")

    for i, arg in enumerate(sys.argv):
      if (i > 1):
        #print(f"File {i}: {arg}\n")
        DumpFile(header, arg)
    header.write("} // namespace AMD\n")
    header.write("} // namespace rocr\n\n")

else:
  print("Empty arguments!")
  