#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc.
# SPDX-License-Identifier:  MIT
"""
Static instruction execution pipeline table generator for rocprofiler-compute.

Builds ``src/rocprof_compute_soc/analysis_configs/instruction_pipelines.yaml``,
which groups every instruction mnemonic under the execution pipeline that runs
it. The mnemonic is the first word of a disassembly line, so the line
``v_add_f32_e32 v0, v1, v2`` is listed under VALU as ``v_add_f32_e32``.

The mapping comes from the AMDGPU TableGen files of the LLVM commit TheRock
pins, so the table holds the mnemonics the installed disassembler prints.

Everything happens in a temporary directory that is removed on exit. LLVM is
needed to build the file, not to read it.

Usage (from the ``rocprofiler-compute`` project root):
    ./tools/instruction_pipeline_generator.py [--output PATH]
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from collections.abc import Iterable
from enum import Enum
from pathlib import Path
from typing import NamedTuple, Optional

import yaml

DEFAULT_OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "rocprof_compute_soc"
    / "analysis_configs"
    / "instruction_pipelines.yaml"
)

HEADER = """\
# Generated by tools/instruction_pipeline_generator.py. Do not edit by hand.
#
# pipelines: each execution pipeline, listing the instruction mnemonics that
# run on it. A mnemonic is the first word of a disassembly line, so
#
#     v_add_f32_e32 v0, v1, v2
#
# is listed under VALU as v_add_f32_e32. Each mnemonic appears exactly once,
# and the pipelines are in the order the generator tries them.
#
# repo, commit: the llvm-project checkout the mnemonics were read from.
# rules.flags: TableGen encoding flag -> pipeline.
# rules.prefixes: pipeline -> the mnemonic prefixes assigned to it.
"""


class Pipeline(str, Enum):
    """The execution pipelines, declared in the order rules are tried.

    An instruction can match more than one rule, and the first match wins.
    SCALAR and VALU come last because nearly every instruction matches one of
    them. Members are strings, so they land in the YAML as written.
    """

    MATRIX = "MATRIX"
    BRANCH = "BRANCH"
    BARRIER = "BARRIER"
    EXP = "EXP"
    INTERNAL = "INTERNAL"
    LDS = "LDS"
    VMEM = "VMEM"
    FLAT = "FLAT"
    SCALAR = "SCALAR"
    VALU = "VALU"


class InstructionRecord(NamedTuple):
    """One TableGen instruction record, reduced to what classification needs."""

    record_name: str
    mnemonics: frozenset[str]
    flags: frozenset[str]


def run_git(repository_path: Path, *arguments: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repository_path), *arguments],
        capture_output=True,
        text=True,
        check=True,
    ).stdout


class TableGen:
    """Reads the AMDGPU instruction definitions out of LLVM."""

    therock_repo = "https://github.com/ROCm/TheRock.git"
    therock_llvm_submodule = "compiler/amd-llvm"
    llvm_repo = "https://github.com/ROCm/llvm-project"
    sparse_paths = ("llvm/lib/Target/AMDGPU", "llvm/include/llvm")

    # Printed encoding suffixes, appended to a record's base mnemonic so it can
    # be looked up just as it is printed, with nothing to strip off.
    encoding_suffix_tokens = ("e32", "e64", "sdwa", "dpp", "dpp8")
    mnemonic_pattern = re.compile(r"^[a-z][a-z0-9_]*")

    @staticmethod
    def fetch_sources(work_path: Path) -> tuple:
        """Check out the pinned AMDGPU TableGen files, returning path and commit.

        TheRock pins the compiler as a submodule, and ls-tree reads that pin
        straight out of the object store, so nothing is checked out for it. The
        LLVM checkout is sparse, but takes the whole ``llvm/include/llvm``
        tree: the TableGen includes chain, and listing the exact
        subdirectories breaks whenever LLVM adds one.
        """
        therock_path = work_path / "therock"
        therock_path.mkdir(parents=True)
        run_git(therock_path, "init", "--quiet")
        run_git(therock_path, "remote", "add", "origin", TableGen.therock_repo)
        print(f"Reading the compiler pin from {TableGen.therock_repo}")
        run_git(therock_path, "fetch", "--quiet", "--depth", "1", "origin", "main")
        listing = run_git(
            therock_path, "ls-tree", "FETCH_HEAD", TableGen.therock_llvm_submodule
        )
        commit = listing.split()[2]

        llvm_path = work_path / "llvm"
        llvm_path.mkdir(parents=True)
        run_git(llvm_path, "init", "--quiet")
        run_git(llvm_path, "remote", "add", "origin", f"{TableGen.llvm_repo}.git")
        run_git(llvm_path, "sparse-checkout", "init", "--cone")
        run_git(llvm_path, "sparse-checkout", "set", *TableGen.sparse_paths)
        print(f"Fetching {commit[:12]} of {TableGen.llvm_repo}")
        run_git(
            llvm_path,
            "fetch",
            "--quiet",
            "--depth",
            "1",
            "--filter=blob:none",
            "origin",
            commit,
        )
        run_git(llvm_path, "checkout", "--quiet", "FETCH_HEAD")
        return llvm_path / "llvm", commit

    @staticmethod
    def dump(tblgen: Path, llvm_path: Path, dump_path: Path) -> dict:
        """Dump every AMDGPU TableGen record as JSON and load it."""
        target_path = llvm_path / "lib" / "Target" / "AMDGPU"
        subprocess.run(
            [
                str(tblgen),
                "--dump-json",
                "-I",
                str(target_path),
                "-I",
                str(llvm_path / "include"),
                str(target_path / "AMDGPU.td"),
                "-o",
                str(dump_path),
            ],
            check=True,
        )
        with open(dump_path, encoding="utf-8") as dump_file:
            return json.load(dump_file)

    @staticmethod
    def records(dump: dict) -> list[InstructionRecord]:
        """Reduce a tblgen JSON dump to one InstructionRecord per instruction.

        A dump record reads ``{"Mnemonic": "v_add_f32", "VALU": 1, "VOP3": 1}``,
        with a field per property LLVM tracks. Only the mnemonic and the flags
        Rules classifies on are kept.
        """
        records: list[InstructionRecord] = []
        for record_name in dump.get("!instanceof", {}).get("Instruction", []):
            record = dump[record_name]
            mnemonics = TableGen.mnemonics_for_record(record_name, record)
            if not mnemonics:
                continue
            records.append(
                InstructionRecord(
                    record_name=record_name,
                    mnemonics=frozenset(mnemonics),
                    flags=frozenset(
                        flag for flag in Rules.flag_to_pipeline if record.get(flag)
                    ),
                )
            )
        return records

    @staticmethod
    def mnemonics_for_record(record_name: str, record: dict) -> set[str]:
        """Return every mnemonic the disassembler may print for one record.

        A mnemonic is spread over three fields: ``Mnemonic`` holds the short
        form, ``PseudoInstr`` the encoding-suffixed form, and ``AsmString`` the
        form after any per-family rename. Each is also combined with the
        encoding suffix in the record name, which is how ``v_add_f32_e32`` gets
        a key of its own.
        """
        bases: set[str] = set()
        for field in ("Mnemonic", "PseudoInstr", "AsmString"):
            base = TableGen.leading_mnemonic(record.get(field))
            if base is not None:
                bases.add(base)

        suffix = TableGen.encoding_suffix(record_name)
        if suffix is None:
            return bases
        return bases | {
            f"{base}_{suffix}" for base in bases if not base.endswith(f"_{suffix}")
        }

    @staticmethod
    def leading_mnemonic(value: object) -> Optional[str]:
        """Return the mnemonic a field starts with, dropping what follows it.

        Operands follow the mnemonic in several fields, sometimes with no
        separating space (``v_add_co_ci_u32$vdst``), and pseudo records carry
        placeholder text that is never printed.
        """
        if not isinstance(value, str):
            return None
        match = TableGen.mnemonic_pattern.match(value.strip().lower())
        return match.group(0) if match else None

    @staticmethod
    def encoding_suffix(record_name: str) -> Optional[str]:
        """Return the printed encoding suffix of a record name, if it has one.

        The suffix is not at the end: a per-family suffix follows it, as in
        ``V_ADD_CO_CI_U32_e64_dpp_gfx12``.
        """
        tokens = [
            token
            for token in record_name.lower().split("_")
            if token in TableGen.encoding_suffix_tokens
        ]
        return "_".join(tokens) if tokens else None


class Rules:
    """Decides which pipeline runs an instruction."""

    # TableGen encoding-class flag -> execution pipeline. SCALAR covers scalar
    # ALU and scalar memory because the hardware serves both from one pipeline.
    flag_to_pipeline = {
        "IsMAI": Pipeline.MATRIX,
        "IsWMMA": Pipeline.MATRIX,
        "IsSWMMAC": Pipeline.MATRIX,
        "isBranch": Pipeline.BRANCH,
        "EXP": Pipeline.EXP,
        "DS": Pipeline.LDS,
        "LDSDIR": Pipeline.LDS,
        "MUBUF": Pipeline.VMEM,
        "MTBUF": Pipeline.VMEM,
        "MIMG": Pipeline.VMEM,
        "FLAT": Pipeline.FLAT,
        "SMRD": Pipeline.SCALAR,
        "SALU": Pipeline.SCALAR,
        "VALU": Pipeline.VALU,
    }

    # Mnemonic prefixes, for the pipelines no TableGen flag can tell apart.
    mnemonic_prefixes = {
        Pipeline.BARRIER: ("s_barrier", "s_wakeup_barrier", "s_get_barrier_state"),
        Pipeline.EXP: ("s_sendmsg",),
        Pipeline.INTERNAL: (
            "s_wait",
            "s_soft_wait",
            "s_delay",
            "s_set",
            "s_sleep",
            "s_monitor_sleep",
            "s_ttrace",
            "s_clause",
            "s_inst_prefetch",
            "s_incperflevel",
            "s_decperflevel",
            "s_icache_inv",
            "s_denorm_mode",
            "s_round_mode",
            "s_singleuse_vdst",
            "s_endpgm",
            "s_code_end",
            "s_nop",
            "s_trap",
            "s_wakeup",
        ),
        Pipeline.VMEM: ("global_", "scratch_"),
        Pipeline.FLAT: ("flat_",),
    }

    @staticmethod
    def classify(mnemonic: str, flags: Iterable[str]) -> Optional[Pipeline]:
        """Return the execution pipeline for a mnemonic and its merged flags.

        Each pipeline in turn claims the instruction if either its flags or its
        prefixes match, so the enum order is the only thing deciding who wins.

        Returns None when no rule matches, which leaves the type unset rather
        than guessing a pipeline.
        """
        flag_set = set(flags)
        for pipeline in Pipeline:
            by_flag = any(
                Rules.flag_to_pipeline.get(flag) == pipeline for flag in flag_set
            )
            by_prefix = mnemonic.startswith(Rules.mnemonic_prefixes.get(pipeline, ()))
            if by_flag or by_prefix:
                return pipeline
        return None

    @staticmethod
    def build_table(records: Iterable[InstructionRecord]) -> dict[str, Pipeline]:
        """Classify every mnemonic, dropping the ones no rule claims.

        The flags of all records printing a mnemonic are merged first. One
        mnemonic has many records, one per encoding variant per GPU family, and
        a variant carrying no flags of its own would otherwise classify as
        something weaker than the instruction really is.
        """
        merged_flags: dict[str, set[str]] = {}
        for record in records:
            for mnemonic in record.mnemonics:
                merged_flags.setdefault(mnemonic, set()).update(record.flags)

        table: dict[str, Pipeline] = {}
        for mnemonic, flags in merged_flags.items():
            pipeline = Rules.classify(mnemonic, flags)
            if pipeline is not None:
                table[mnemonic] = pipeline
        return table


class Corpus:
    """What the code objects of the local ROCm install actually contain."""

    code_object_suffixes = ("*.hsaco", "*.co")
    # A disassembly line is "<mnemonic> <operands>" possibly followed by an
    # encoding comment; the mnemonic is always the first token.
    disassembly_line_pattern = re.compile(r"^([a-z][a-z0-9_]*)\s")

    @staticmethod
    def collect(rocm_path: Path, objdump: Path) -> set[str]:
        """Disassemble a ROCm install to see what mnemonics real code emits."""
        mnemonics: set[str] = set()
        for suffix in Corpus.code_object_suffixes:
            for code_object in sorted(rocm_path.rglob(suffix)):
                disassembly = subprocess.run(
                    [str(objdump), "-d", str(code_object)],
                    capture_output=True,
                    text=True,
                    check=False,
                ).stdout
                mnemonics |= Corpus.parse_mnemonics(disassembly)
        print(f"Corpus holds {len(mnemonics)} distinct mnemonics")
        return mnemonics

    @staticmethod
    def parse_mnemonics(disassembly: str) -> set[str]:
        """Collect the mnemonics of an llvm-objdump disassembly listing.

        A listing line reads ``s_endpgm  // 00000000191C: BF810000``, so its
        mnemonic is the first word.
        """
        mnemonics: set[str] = set()
        for line in disassembly.splitlines():
            match = Corpus.disassembly_line_pattern.match(line.strip())
            if match:
                mnemonics.add(match.group(1))
        return mnemonics


class Table:
    """The generated file."""

    @staticmethod
    def build_document(commit: str, table: dict[str, Pipeline]) -> dict:
        """Group the mnemonics under their pipeline, with the rules behind them.

        Every rule the classifier applies is recorded, the flag ones and the
        prefix ones alike, so a reader can tell where any entry came from and a
        regenerated file shows in its diff what moved.
        """
        by_pipeline = {}
        for pipeline in Pipeline:
            mnemonics = sorted(m for m, p in table.items() if p == pipeline)
            if mnemonics:
                by_pipeline[pipeline.value] = mnemonics
        return {
            "repo": TableGen.llvm_repo,
            "commit": commit,
            "rules": {
                "flags": {
                    flag: pipeline.value
                    for flag, pipeline in Rules.flag_to_pipeline.items()
                },
                "prefixes": {
                    pipeline.value: list(prefixes)
                    for pipeline, prefixes in Rules.mnemonic_prefixes.items()
                },
            },
            "pipelines": by_pipeline,
        }

    @staticmethod
    def write(output_path: Path, commit: str, table: dict[str, Pipeline]) -> None:
        """Write the generated document under the explanatory header."""
        with open(output_path, "w", encoding="utf-8") as output_file:
            output_file.write(HEADER)
            yaml.safe_dump(
                Table.build_document(commit, table),
                output_file,
                sort_keys=False,
                default_flow_style=False,
            )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Where to write the generated table.",
    )
    args = parser.parse_args()

    rocm_path = Path(os.getenv("ROCM_PATH", "/opt/rocm"))
    tblgen = rocm_path / "lib" / "llvm" / "bin" / "llvm-tblgen"
    objdump = rocm_path / "lib" / "llvm" / "bin" / "llvm-objdump"
    for binary in (tblgen, objdump):
        if not binary.is_file():
            print(f"error: {binary} not found; set ROCM_PATH", file=sys.stderr)
            return 1

    corpus_mnemonics = Corpus.collect(rocm_path, objdump)
    if not corpus_mnemonics:
        print(
            f"error: no code objects found under {rocm_path}; "
            "coverage cannot be checked",
            file=sys.stderr,
        )
        return 1

    with tempfile.TemporaryDirectory(prefix="instruction_pipelines_") as work_dir:
        work_path = Path(work_dir)
        llvm_path, commit = TableGen.fetch_sources(work_path)
        print(f"Running llvm-tblgen on the AMDGPU target of {commit[:12]}")
        dump = TableGen.dump(tblgen, llvm_path, work_path / "amdgpu.json")
        records = TableGen.records(dump)

    table = Rules.build_table(records)
    print(f"Classified {len(table)} mnemonics from {len(records)} records")

    uncovered = sorted(corpus_mnemonics - set(table))
    if uncovered:
        print(
            f"error: {len(uncovered)} corpus mnemonics missing from the table: "
            f"{uncovered[:10]}",
            file=sys.stderr,
        )
        return 1

    Table.write(args.output, commit, table)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
