#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc.
# SPDX-License-Identifier:  MIT

"""Analysis config YAML linter for rocprofiler-compute pre-commit hook.

Checks:
  1. Metric equations are in canonical format (auto-fixable with --fix).
  2. Every metric_table metric entry has exactly the keys declared in the
     table header (see src/utils/parser.py _build_metric_table_df). A missing
     key crashes analyze; an extra key is silently dropped.
"""

import argparse
import re
import sys
from dataclasses import dataclass
from enum import Enum, auto
from pathlib import Path
from typing import Any, Optional

import yaml

# =============================================================================
# Configuration - Edit these to accommodate future YAML updates
# =============================================================================

# Path patterns of analysis configs to lint (substrings matched against path)
ANALYSIS_CONFIG_PATTERNS = [
    "analysis_configs/gfx",
]

# Path suffixes to exclude from linting
ANALYSIS_CONFIG_EXCLUDE_SUFFIXES = [
    "_template.yaml",
]

# Path patterns to skip entirely (substrings matched against path)
SKIP_FILE_PATTERNS = [
    "/build/",
    "profiling_config.yaml",
]

# YAML keys that contain metric equations
EQUATION_KEYS = {"value", "avg", "min", "max", "peak"}

# Literal string values that should not be parsed as equations
LITERAL_VALUES = {"N/A", "None", "null", "true", "false", "Peak (Empirical)"}

# Aggregation functions where constants should be factored out
AGGREGATION_FUNCTIONS = {"SUM", "MIN", "MAX", "AVG"}

# Operator precedence for parentheses minimization
OPERATOR_PRECEDENCE = {"+": 1, "-": 1, "*": 2, "/": 2}

# Metric entry keys consumed outside the header columns
METRIC_METADATA_KEYS = {"coll_level", "alias"}

# Memory chart (panel 03xx) metrics carry "unit" for the chart renderer only
MEMORY_CHART_PANEL = 3
MEMORY_CHART_EXTRA_KEYS = {"unit"}

# =============================================================================
# Public functions
# =============================================================================


def main() -> int:
    args = _build_arg_parser().parse_args()
    files = args.files or [Path(line.strip()) for line in sys.stdin if line.strip()]

    if not files:
        print("No files to check")
        return 0

    all_valid = True
    total_issues = 0

    for file_path in files:
        if not file_path.exists() or file_path.suffix.lower() not in {".yaml", ".yml"}:
            continue

        is_valid, issues = check_file(file_path, fix=args.fix, show_diff=args.diff)

        if not is_valid:
            all_valid = False
            total_issues += len(issues)
            print(f"{file_path}:")
            print("\n".join(issues))
        elif args.verbose:
            print(f"{file_path}: OK")

    if not all_valid:
        print(f"\n{total_issues} lint issue(s) found")
        return 1

    if args.verbose:
        print(f"\nAll {len(files)} files passed lint checks")
    return 0


def check_file(
    path: Path, fix: bool = False, show_diff: bool = False
) -> tuple[bool, list[str]]:
    """Lint one YAML file and return (is_valid, issues).

    With fix, normalized equations are written back to the file and only
    header/metric key mismatches, which are not auto-fixable, fail the check.
    """
    if _should_skip_file(path):
        return True, []

    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return True, []

    try:
        config = yaml.safe_load(content)
    except yaml.YAMLError as error:
        return False, [f"Failed to parse YAML: {error}"]

    if not isinstance(config, dict) or not _is_analysis_config(path):
        return True, []

    lint_result = lint_config(config, content, show_diff)

    if fix and lint_result.fixed_count:
        path.write_text(lint_result.fixed_content, encoding="utf-8")
        fixed_message = f"  Fixed {lint_result.fixed_count} equation(s)"
        return not lint_result.key_issues, [*lint_result.key_issues, fixed_message]

    issues = lint_result.key_issues + lint_result.equation_issues
    return not issues, issues


def lint_config(
    config: dict[str, Any], content: str, show_diff: bool = False
) -> "LintResult":
    """Lint a parsed analysis config against its raw text."""
    # Autogenerated files are exempt from equation formatting only; key
    # mismatches crash analyze regardless of how the file was produced.
    equations = [] if _is_autogenerated(content) else extract_metric_equations(config)
    replacements = _find_unnormalized_equations(equations)

    return LintResult(
        key_issues=check_metric_table_keys(config),
        equation_issues=_format_equation_issues(replacements, show_diff),
        fixed_content=_apply_fixes(content, replacements),
        fixed_count=len(replacements),
    )


def check_metric_table_keys(config: dict[str, Any]) -> list[str]:
    """Return issues for metric entries whose keys don't match the table header."""
    panel_config = config.get("Panel Config") or {}
    issues = []
    for data_source in panel_config.get("data source") or []:
        if not isinstance(data_source, dict):
            continue
        metric_table = data_source.get("metric_table")
        if isinstance(metric_table, dict):
            issues.extend(_check_table_keys(metric_table))
    return issues


def normalize_equation(equation: str) -> str:
    """Parse, normalize, and serialize a metric equation string."""
    stripped = equation.strip()
    if stripped in LITERAL_VALUES or stripped.startswith(('"', "'")):
        return equation

    try:
        tokens = Tokenizer(equation).tokenize()
        tree = Parser(tokens).parse()
        return _serialize_ast(_normalize_ast(tree))
    except (ValueError, IndexError):
        return equation


def extract_metric_equations(
    node: object, path: str = ""
) -> list[tuple[str, str, str]]:
    """Extract (path, key, value) tuples for equation fields from YAML data."""
    if isinstance(node, list):
        return [
            equation
            for index, item in enumerate(node)
            for equation in extract_metric_equations(item, f"{path}[{index}]")
        ]
    if not isinstance(node, dict):
        return []

    equations = []
    for key, value in node.items():
        current_path = f"{path}.{key}" if path else key
        if key in EQUATION_KEYS and isinstance(value, str):
            equations.append((current_path, key, value))
        else:
            equations.extend(extract_metric_equations(value, current_path))
    return equations


# =============================================================================
# Private helpers
# =============================================================================


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Analysis config YAML linter for rocprofiler-compute"
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Check without modifying")
    mode.add_argument("--fix", action="store_true", help="Auto-fix in place")
    mode.add_argument("--diff", action="store_true", help="Show proposed changes")
    parser.add_argument("files", nargs="*", type=Path, help="Files to check")
    parser.add_argument("-v", "--verbose", action="store_true")
    return parser


def _should_skip_file(path: Path) -> bool:
    """Return True if the file should be skipped entirely."""
    path_str = str(path)
    return any(pattern in path_str for pattern in SKIP_FILE_PATTERNS)


def _is_analysis_config(path: Path) -> bool:
    """Return True if the file is a per-arch analysis config to lint."""
    path_str = str(path)
    if any(path_str.endswith(suffix) for suffix in ANALYSIS_CONFIG_EXCLUDE_SUFFIXES):
        return False
    return any(pattern in path_str for pattern in ANALYSIS_CONFIG_PATTERNS)


def _is_autogenerated(content: str) -> bool:
    """Return True if the first line marks the file as autogenerated."""
    return "AUTOGENERATED" in content.partition("\n")[0].upper()


def _check_table_keys(metric_table: dict[str, Any]) -> list[str]:
    """Return key mismatch issues for one metric_table."""
    header = metric_table.get("header")
    metrics = metric_table.get("metric")
    if not isinstance(header, dict) or not isinstance(metrics, dict):
        return []

    header_keys = set(header) - {"metric", "expr"}
    ignored_keys = _ignored_metric_keys(metric_table, header_keys)
    table_id = metric_table.get("id")
    table_label = f'  table {table_id} "{metric_table.get("title", "")}"'
    header_note = f"(header: {sorted(header_keys)})"

    issues = []
    for metric_name, metric_entry in metrics.items():
        if metric_name == "placeholder_range" or not isinstance(metric_entry, dict):
            continue
        metric_keys = set(metric_entry) - ignored_keys
        location = f'{table_label} metric "{metric_name}"'
        if missing_keys := sorted(header_keys - metric_keys):
            issues.append(
                f"{location}: missing header key(s) {missing_keys} {header_note}"
            )
        if extra_keys := sorted(metric_keys - header_keys):
            issues.append(
                f"{location}: key(s) not in header {extra_keys} {header_note}"
            )
    return issues


def _ignored_metric_keys(
    metric_table: dict[str, Any], header_keys: set[str]
) -> set[str]:
    """Return metric entry keys that are not matched against the header."""
    ignored_keys = set(METRIC_METADATA_KEYS)
    if metric_table.get("cli_style") == "simple_box":
        ignored_keys.add("expr")
    table_id = metric_table.get("id")
    if isinstance(table_id, int) and table_id // 100 == MEMORY_CHART_PANEL:
        ignored_keys |= MEMORY_CHART_EXTRA_KEYS - header_keys
    return ignored_keys


def _find_unnormalized_equations(
    equations: list[tuple[str, str, str]],
) -> list[tuple[str, str, str]]:
    """Return (path, original, normalized) for equations not in canonical form."""
    replacements = []
    for equation_path, _, original in equations:
        normalized = normalize_equation(original)
        if normalized != original:
            replacements.append((equation_path, original, normalized))
    return replacements


def _format_equation_issues(
    replacements: list[tuple[str, str, str]], show_diff: bool
) -> list[str]:
    issues = []
    for equation_path, original, normalized in replacements:
        issues.append(f"  {equation_path}: equation needs normalization")
        if show_diff:
            issues.extend([f"    - {original}", f"    + {normalized}"])
    return issues


def _apply_fixes(content: str, replacements: list[tuple[str, str, str]]) -> str:
    """Apply equation normalizations using regex to handle multi-line YAML."""
    fixed_content = content
    for _, original, normalized in replacements:
        pattern = re.escape(original).replace(r"\ ", r"\s+")
        fixed_content = re.sub(pattern, normalized, fixed_content, count=1)
    return fixed_content


def _normalize_ast(node: "ASTNode") -> "ASTNode":
    """Recursively normalize AST: factor constants out of aggregation functions."""
    if isinstance(node, UnaryOpNode):
        return UnaryOpNode(node.operator, _normalize_ast(node.operand))

    if isinstance(node, BinaryOpNode):
        return BinaryOpNode(
            node.operator, _normalize_ast(node.left), _normalize_ast(node.right)
        )

    if isinstance(node, FunctionCallNode):
        normalized_args = [_normalize_ast(arg) for arg in node.args]
        if node.name in AGGREGATION_FUNCTIONS and len(normalized_args) == 1:
            factored = _factor_constant_out(node.name, normalized_args[0])
            if factored is not None:
                return factored
        return FunctionCallNode(node.name, normalized_args)

    return node


def _factor_constant_out(
    function_name: str, argument: "ASTNode"
) -> Optional["ASTNode"]:
    """Rewrite FUNC(c * x) or FUNC(x * c) as c * FUNC(x); None if not applicable."""
    if not isinstance(argument, BinaryOpNode) or argument.operator != "*":
        return None
    if isinstance(argument.left, NumberNode):
        constant, operand = argument.left, argument.right
    elif isinstance(argument.right, NumberNode):
        constant, operand = argument.right, argument.left
    else:
        return None
    return BinaryOpNode("*", constant, FunctionCallNode(function_name, [operand]))


def _serialize_ast(
    node: "ASTNode", parent_operator: Optional[str] = None, is_right: bool = False
) -> str:
    """Serialize AST to string with minimal parentheses."""
    if isinstance(node, NumberNode):
        return node.value
    if isinstance(node, (IdentifierNode, VariableNode)):
        return node.name
    if isinstance(node, UnaryOpNode):
        operand_str = _serialize_ast(node.operand, node.operator, False)
        # Parenthesize binary operands to preserve semantics: -(a + b) not -a + b
        if isinstance(node.operand, BinaryOpNode):
            operand_str = f"({operand_str})"
        return f"{node.operator}{operand_str}"

    if isinstance(node, BinaryOpNode):
        left = _serialize_ast(node.left, node.operator, False)
        right = _serialize_ast(node.right, node.operator, True)
        expression = f"{left} {node.operator} {right}"
        if _needs_parentheses(node.operator, parent_operator, is_right):
            return f"({expression})"
        return expression

    if isinstance(node, FunctionCallNode):
        args = ", ".join(_serialize_ast(arg) for arg in node.args)
        return f"{node.name}({args})"

    return str(node)


def _needs_parentheses(
    operator: str, parent_operator: Optional[str], is_right: bool
) -> bool:
    """Return True if a binary expression must be parenthesized under its parent."""
    if parent_operator is None:
        return False
    precedence = OPERATOR_PRECEDENCE.get(operator, 0)
    parent_precedence = OPERATOR_PRECEDENCE.get(parent_operator, 0)
    if precedence < parent_precedence:
        return True
    return precedence == parent_precedence and is_right and parent_operator in "-/"


# =============================================================================
# Classes: lint result, tokenizer, parser, AST
# =============================================================================


@dataclass
class LintResult:
    key_issues: list[str]
    equation_issues: list[str]
    fixed_content: str
    fixed_count: int


class TokenType(Enum):
    NUMBER = auto()
    IDENTIFIER = auto()
    VARIABLE = auto()
    OPERATOR = auto()
    LPAREN = auto()
    RPAREN = auto()
    COMMA = auto()
    EOF = auto()


@dataclass
class Token:
    type: TokenType
    value: str
    position: int


class Tokenizer:
    """Tokenize metric equations into tokens."""

    OPERATORS = {"+", "-", "*", "/"}

    def __init__(self, text: str) -> None:
        self.text = text
        self.position = 0

    def tokenize(self) -> list[Token]:
        tokens = []
        while self.position < len(self.text):
            self._skip_whitespace()
            if self.position >= len(self.text):
                break

            start = self.position
            char = self._peek()

            if char.isdigit() or (char == "." and self._peek(1).isdigit()):
                tokens.append(Token(TokenType.NUMBER, self._read_number(), start))
            elif char == "$":
                tokens.append(Token(TokenType.VARIABLE, self._read_variable(), start))
            elif char.isalpha() or char == "_":
                tokens.append(
                    Token(TokenType.IDENTIFIER, self._read_identifier(), start)
                )
            elif char in self.OPERATORS:
                self._advance()
                tokens.append(Token(TokenType.OPERATOR, char, start))
            elif char == "(":
                self._advance()
                tokens.append(Token(TokenType.LPAREN, "(", start))
            elif char == ")":
                self._advance()
                tokens.append(Token(TokenType.RPAREN, ")", start))
            elif char == ",":
                self._advance()
                tokens.append(Token(TokenType.COMMA, ",", start))
            else:
                raise ValueError(f"Unknown character '{char}' at position {start}")

        tokens.append(Token(TokenType.EOF, "", self.position))
        return tokens

    def _peek(self, offset: int = 0) -> str:
        index = self.position + offset
        return self.text[index] if index < len(self.text) else ""

    def _advance(self) -> str:
        char = self._peek()
        self.position += 1
        return char

    def _skip_whitespace(self) -> None:
        while self._peek().isspace():
            self.position += 1

    def _read_number(self) -> str:
        start = self.position
        while self._peek() and self._peek() in "0123456789.":
            self.position += 1
        if self._peek() and self._peek() in "eE":
            self.position += 1
            if self._peek() and self._peek() in "+-":
                self.position += 1
            while self._peek().isdigit():
                self.position += 1
        return self.text[start : self.position]

    def _read_identifier(self) -> str:
        start = self.position
        while self._peek().isalnum() or self._peek() == "_":
            self.position += 1
        return self.text[start : self.position]

    def _read_variable(self) -> str:
        start = self.position
        self._advance()
        while self._peek().isalnum() or self._peek() == "_":
            self.position += 1
        return self.text[start : self.position]


@dataclass
class ASTNode:
    pass


@dataclass
class NumberNode(ASTNode):
    value: str


@dataclass
class IdentifierNode(ASTNode):
    name: str


@dataclass
class VariableNode(ASTNode):
    name: str


@dataclass
class BinaryOpNode(ASTNode):
    operator: str
    left: ASTNode
    right: ASTNode


@dataclass
class UnaryOpNode(ASTNode):
    operator: str
    operand: ASTNode


@dataclass
class FunctionCallNode(ASTNode):
    name: str
    args: list[ASTNode]


class Parser:
    """Recursive descent parser for metric equations."""

    def __init__(self, tokens: list[Token]) -> None:
        self.tokens = tokens
        self.position = 0

    def parse(self) -> ASTNode:
        tree = self._parse_additive()
        token = self._current()
        if token.type != TokenType.EOF:
            raise ValueError(
                f"Unexpected token after expression: {token.type} "
                f"at position {token.position}"
            )
        return tree

    def _current(self) -> Token:
        return self.tokens[self.position]

    def _advance(self) -> Token:
        token = self._current()
        if self.position < len(self.tokens) - 1:
            self.position += 1
        return token

    def _expect(self, token_type: TokenType) -> Token:
        token = self._current()
        if token.type != token_type:
            raise ValueError(f"Expected {token_type}, got {token.type}")
        return self._advance()

    def _at_operator(self, operators: str) -> bool:
        token = self._current()
        return token.type == TokenType.OPERATOR and token.value in operators

    def _parse_additive(self) -> ASTNode:
        left = self._parse_multiplicative()
        while self._at_operator("+-"):
            operator = self._advance().value
            left = BinaryOpNode(operator, left, self._parse_multiplicative())
        return left

    def _parse_multiplicative(self) -> ASTNode:
        left = self._parse_unary()
        while self._at_operator("*/"):
            operator = self._advance().value
            left = BinaryOpNode(operator, left, self._parse_unary())
        return left

    def _parse_unary(self) -> ASTNode:
        if self._at_operator("-"):
            operator = self._advance().value
            return UnaryOpNode(operator, self._parse_unary())
        return self._parse_primary()

    def _parse_primary(self) -> ASTNode:
        token = self._current()

        if token.type == TokenType.NUMBER:
            self._advance()
            return NumberNode(token.value)

        if token.type == TokenType.VARIABLE:
            self._advance()
            return VariableNode(token.value)

        if token.type == TokenType.IDENTIFIER:
            return self._parse_identifier_or_call()

        if token.type == TokenType.LPAREN:
            self._advance()
            expression = self._parse_additive()
            self._expect(TokenType.RPAREN)
            return expression

        raise ValueError(f"Unexpected token {token.type} at position {token.position}")

    def _parse_identifier_or_call(self) -> ASTNode:
        name = self._advance().value
        if self._current().type != TokenType.LPAREN:
            return IdentifierNode(name)
        self._advance()
        args = self._parse_args()
        self._expect(TokenType.RPAREN)
        return FunctionCallNode(name, args)

    def _parse_args(self) -> list[ASTNode]:
        if self._current().type == TokenType.RPAREN:
            return []
        args = [self._parse_additive()]
        while self._current().type == TokenType.COMMA:
            self._advance()
            args.append(self._parse_additive())
        return args


if __name__ == "__main__":
    sys.exit(main())
