/* AUTO-GENERATED by lttng_curated_codegen.py from curated_apis.yaml.
 * Do not edit by hand — regenerate instead (see command below).
 *
 * SHA256(curated_apis.yaml) at generation: c53e000b153508938687be66aeb993d6e2a70d1b9d3ca1edde14acb2b9b81d5a
 *
 * Per-API typed emit helpers for curated parameter capture. Every
 * helper takes (<captured-args...>, <status_type> status); status is
 * the call's success result, used to gate OUT-param deref. All-IN
 * APIs accept it but mark it unused.
 *
 * Regenerate with:
 *   python3 shared/lttng/scripts/lttng_curated_codegen.py \
 *       --provider hsa \
 *       --yaml projects/rocr-runtime/runtime/hsa-runtime/scripts/curated_apis.yaml \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa.h \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa_ext_amd.h \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa_api_trace.h \
 *       --extra-arg=-Iprojects/rocr-runtime/runtime/hsa-runtime/inc \
 *       --tp-out projects/rocr-runtime/runtime/hsa-runtime/lttng/rocm_hsa_curated_tp.h \
 *       --emit-out projects/rocr-runtime/runtime/hsa-runtime/lttng/rocm_trace_emit_curated.h
 */
#ifndef ROCM_HSA_TRACE_EMIT_CURATED_H_
#define ROCM_HSA_TRACE_EMIT_CURATED_H_

#include <stdint.h>
#include <stddef.h>
/* HSA headers: the rocr-runtime source layout has these flat in
 * runtime/hsa-runtime/inc/ (not under an hsa/ subdir), and that directory
 * is on the include path while building libhsa-runtime64. The
 * angle-bracket <hsa/hsa.h> form is what consumers see after install;
 * this internal tracepoint emit header is only included from within
 * rocr-runtime's own compile units, so use the quoted form so the
 * in-tree build works. */
#include "hsa.h"
#include "hsa_ext_amd.h"

#if defined(HSA_ENABLE_LTTNG_UST) && HSA_ENABLE_LTTNG_UST

#include <atomic>
#include "rocm_hsa_curated_tp.h"

extern std::atomic<bool> rocm_hsa_trace_g_disabled;
#ifndef ROCM_TRACE_DISABLED_DEFINED
#define ROCM_TRACE_DISABLED_DEFINED
static inline bool rocm_trace_disabled(void) {
    return rocm_hsa_trace_g_disabled.load(std::memory_order_relaxed);
}
#endif

        static inline void rocm_trace_emit_hsa_queue_create_args(
            uint64_t agent,
    uint32_t size,
    uint32_t type,
    const void* callback,
    const void* data,
    uint32_t private_segment_size,
    uint32_t group_segment_size,
    hsa_queue_t ** queue_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_create_args)) {
        const uint64_t queue_val =
    (status == HSA_STATUS_SUCCESS && queue_out_ptr != NULL)
        ? (uint64_t)((uint64_t)(uintptr_t)(*queue_out_ptr)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_create_args,
(uint64_t)(uintptr_t)(agent),
(uint32_t)(size),
(uint32_t)(type),
(uint64_t)(uintptr_t)(callback),
(uint64_t)(uintptr_t)(data),
(uint32_t)(private_segment_size),
(uint32_t)(group_segment_size),
queue_val);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_destroy_args(
            uint64_t queue,
    hsa_status_t /*status*/ /* unused: all-IN API */) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_destroy_args)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_destroy_args,
(uint64_t)(uintptr_t)(queue));
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_intercept_create_args(
            uint64_t agent_handle,
    uint32_t size,
    uint32_t type,
    const void* callback,
    const void* data,
    uint32_t private_segment_size,
    uint32_t group_segment_size,
    hsa_queue_t ** queue_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_intercept_create_args)) {
        const uint64_t queue_val =
    (status == HSA_STATUS_SUCCESS && queue_out_ptr != NULL)
        ? (uint64_t)((uint64_t)(uintptr_t)(*queue_out_ptr)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_intercept_create_args,
(uint64_t)(uintptr_t)(agent_handle),
(uint32_t)(size),
(uint32_t)(type),
(uint64_t)(uintptr_t)(callback),
(uint64_t)(uintptr_t)(data),
(uint32_t)(private_segment_size),
(uint32_t)(group_segment_size),
queue_val);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_create_args(
            int64_t initial_value,
    uint32_t num_consumers,
    const void* consumers,
    hsa_signal_t * signal_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_create_args)) {
        const uint64_t signal_val =
    (status == HSA_STATUS_SUCCESS && signal_out_ptr != NULL)
        ? (uint64_t)((signal_out_ptr->handle)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_create_args,
(int64_t)(initial_value),
(uint32_t)(num_consumers),
(uint64_t)(uintptr_t)(consumers),
signal_val);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_destroy_args(
            uint64_t signal,
    hsa_status_t /*status*/ /* unused: all-IN API */) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_destroy_args)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_destroy_args,
(uint64_t)(uintptr_t)(signal));
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_create_args(
            int64_t initial_value,
    uint32_t num_consumers,
    const void* consumers,
    uint64_t attributes,
    hsa_signal_t * signal_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_create_args)) {
        const uint64_t signal_val =
    (status == HSA_STATUS_SUCCESS && signal_out_ptr != NULL)
        ? (uint64_t)((signal_out_ptr->handle)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_create_args,
(int64_t)(initial_value),
(uint32_t)(num_consumers),
(uint64_t)(uintptr_t)(consumers),
(uint64_t)(attributes),
signal_val);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_memory_pool_allocate_args(
            uint64_t memory_pool,
    size_t size,
    uint32_t flags,
    void ** ptr_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_memory_pool_allocate_args)) {
        const uint64_t ptr_val =
    (status == HSA_STATUS_SUCCESS && ptr_out_ptr != NULL)
        ? (uint64_t)((uint64_t)(uintptr_t)(*ptr_out_ptr)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_memory_pool_allocate_args,
(uint64_t)(uintptr_t)(memory_pool),
(uint64_t)(size),
(uint32_t)(flags),
ptr_val);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_memory_pool_free_args(
            const void* ptr,
    hsa_status_t /*status*/ /* unused: all-IN API */) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_memory_pool_free_args)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_memory_pool_free_args,
(uint64_t)(uintptr_t)(ptr));
            }
        }

        static inline void rocm_trace_emit_hsa_amd_memory_async_copy_args(
            const void* dst,
    uint64_t dst_agent,
    const void* src,
    uint64_t src_agent,
    size_t size,
    uint32_t num_dep_signals,
    const void* dep_signals,
    uint64_t completion_signal,
    hsa_status_t /*status*/ /* unused: all-IN API */) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_memory_async_copy_args)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_memory_async_copy_args,
(uint64_t)(uintptr_t)(dst),
(uint64_t)(uintptr_t)(dst_agent),
(uint64_t)(uintptr_t)(src),
(uint64_t)(uintptr_t)(src_agent),
(uint64_t)(size),
(uint32_t)(num_dep_signals),
(uint64_t)(uintptr_t)(dep_signals),
(uint64_t)(uintptr_t)(completion_signal));
            }
        }

        static inline void rocm_trace_emit_hsa_amd_memory_async_copy_on_engine_args(
            const void* dst,
    uint64_t dst_agent,
    const void* src,
    uint64_t src_agent,
    size_t size,
    uint32_t num_dep_signals,
    uint64_t completion_signal,
    int32_t engine_id,
    int force_copy_on_sdma,
    hsa_status_t /*status*/ /* unused: all-IN API */) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_memory_async_copy_on_engine_args)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_memory_async_copy_on_engine_args,
(uint64_t)(uintptr_t)(dst),
(uint64_t)(uintptr_t)(dst_agent),
(uint64_t)(uintptr_t)(src),
(uint64_t)(uintptr_t)(src_agent),
(uint64_t)(size),
(uint32_t)(num_dep_signals),
(uint64_t)(uintptr_t)(completion_signal),
(int32_t)(engine_id),
(uint32_t)(!!(force_copy_on_sdma)));
            }
        }


#else  /* HSA_ENABLE_LTTNG_UST not defined — all helpers are no-ops */

static inline void rocm_trace_emit_hsa_queue_create_args(uint64_t, uint32_t, uint32_t, const void*, const void*, uint32_t, uint32_t, hsa_queue_t **, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_queue_destroy_args(uint64_t, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_intercept_create_args(uint64_t, uint32_t, uint32_t, const void*, const void*, uint32_t, uint32_t, hsa_queue_t **, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_create_args(int64_t, uint32_t, const void*, hsa_signal_t *, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_destroy_args(uint64_t, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_signal_create_args(int64_t, uint32_t, const void*, uint64_t, hsa_signal_t *, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_memory_pool_allocate_args(uint64_t, size_t, uint32_t, void **, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_memory_pool_free_args(const void*, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_memory_async_copy_args(const void*, uint64_t, const void*, uint64_t, size_t, uint32_t, const void*, uint64_t, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_memory_async_copy_on_engine_args(const void*, uint64_t, const void*, uint64_t, size_t, uint32_t, uint64_t, int32_t, int, hsa_status_t) {}

#endif  /* HSA_ENABLE_LTTNG_UST */

#endif  /* ROCM_HSA_TRACE_EMIT_CURATED_H_ */
