/* AUTO-GENERATED by lttng_curated_codegen.py from curated_apis.yaml.
 * Do not edit by hand — regenerate instead (see command below).
 *
 * SHA256(curated_apis.yaml) at generation: b404b3a62015b8303613ea37e50d68e3eece72bbd2d77f3aec14475cbc7e884e
 * Provider: rocm_hsa
 * API count: 31
 *
 * Regenerate with:
 *   python3 shared/lttng/scripts/lttng_curated_codegen.py \
 *       --provider hsa \
 *       --yaml projects/rocr-runtime/runtime/hsa-runtime/scripts/curated_apis.yaml \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa.h \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa_ext_amd.h \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa_api_trace.h \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/core/inc/hsa_table_interface.h \
 *       --extra-arg=-Iprojects/rocr-runtime/runtime/hsa-runtime/inc \
 *       --extra-arg=-Iprojects/rocr-runtime/runtime/hsa-runtime \
 *       --tp-out projects/rocr-runtime/runtime/hsa-runtime/lttng/rocm_hsa_curated_tp.h \
 *       --emit-out projects/rocr-runtime/runtime/hsa-runtime/lttng/rocm_trace_emit_curated.h
 */
#if !defined(_ROCM_HSA_CURATED_TP_H) || defined(LTTNG_UST_TRACEPOINT_HEADER_MULTI_READ)
#define _ROCM_HSA_CURATED_TP_H

/* Schema v1: each curated API is ONE combined event `<api>` (`<api>_N`
 * for high-arity chunk overflow), fired TWICE per call. The leading
 * `phase` field discriminates the record: 0 = ENTER (IN args populated,
 * OUT args and return value 0), 1 = EXIT (IN args 0, OUT args populated,
 * return value populated). Enabling the single event name turns on BOTH
 * records at the LTTng level. Per-event identity (vpid, vtid, timestamp)
 * comes from LTTng-UST channel contexts; consumers pair ENTER/EXIT by
 * (vpid, vtid, timestamp, event-name). */

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_create,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, agent, uint32_t, size, uint32_t, type, uint64_t, callback, uint64_t, data, uint32_t, private_segment_size, uint32_t, group_segment_size, uint64_t, queue, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, agent, agent)
lttng_ust_field_integer(uint32_t, size, size)
lttng_ust_field_integer(uint32_t, type, type)
lttng_ust_field_integer_hex(uint64_t, callback, callback)
lttng_ust_field_integer_hex(uint64_t, data, data)
lttng_ust_field_integer(uint32_t, private_segment_size, private_segment_size)
lttng_ust_field_integer(uint32_t, group_segment_size, group_segment_size)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_destroy,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_intercept_create,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, agent_handle, uint32_t, size, uint32_t, type, uint64_t, callback, uint64_t, data, uint32_t, private_segment_size, uint32_t, group_segment_size, uint64_t, queue, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, agent_handle, agent_handle)
lttng_ust_field_integer(uint32_t, size, size)
lttng_ust_field_integer(uint32_t, type, type)
lttng_ust_field_integer_hex(uint64_t, callback, callback)
lttng_ust_field_integer_hex(uint64_t, data, data)
lttng_ust_field_integer(uint32_t, private_segment_size, private_segment_size)
lttng_ust_field_integer(uint32_t, group_segment_size, group_segment_size)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_soft_queue_create,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, region, uint32_t, size, uint32_t, type, uint32_t, features, uint64_t, doorbell_signal, uint64_t, queue, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, region, region)
lttng_ust_field_integer(uint32_t, size, size)
lttng_ust_field_integer(uint32_t, type, type)
lttng_ust_field_integer(uint32_t, features, features)
lttng_ust_field_integer_hex(uint64_t, doorbell_signal, doorbell_signal)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_inactivate,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_load_read_index_scacquire,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_load_read_index_relaxed,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_load_write_index_scacquire,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_load_write_index_relaxed,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_store_write_index_relaxed,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, value),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, value, value)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_store_write_index_screlease,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, value),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, value, value)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_cas_write_index_scacq_screl,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, expected, uint64_t, value, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, expected, expected)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_cas_write_index_scacquire,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, expected, uint64_t, value, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, expected, expected)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_cas_write_index_relaxed,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, expected, uint64_t, value, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, expected, expected)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_cas_write_index_screlease,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, expected, uint64_t, value, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, expected, expected)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_add_write_index_scacq_screl,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, value, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_add_write_index_scacquire,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, value, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_add_write_index_relaxed,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, value, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_add_write_index_screlease,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, value, uint64_t, retval),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(uint64_t, retval, retval)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_store_read_index_relaxed,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, value),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, value, value)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_queue_store_read_index_screlease,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, value),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint64_t, value, value)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_cu_set_mask,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint32_t, num_cu_mask_count, uint64_t, cu_mask, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint32_t, num_cu_mask_count, num_cu_mask_count)
lttng_ust_field_integer_hex(uint64_t, cu_mask, cu_mask)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_cu_get_mask,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint32_t, num_cu_mask_count, uint64_t, cu_mask, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(uint32_t, num_cu_mask_count, num_cu_mask_count)
lttng_ust_field_integer_hex(uint64_t, cu_mask, cu_mask)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_set_priority,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, int32_t, priority, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, priority, priority)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_get_info,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, int32_t, attribute, uint64_t, value, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, attribute, attribute)
lttng_ust_field_integer_hex(uint64_t, value, value)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_counted_queue_acquire,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, agent, int32_t, type, int32_t, priority, uint64_t, callback, uint64_t, data, uint64_t, flags, uint64_t, queue, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, agent, agent)
lttng_ust_field_integer(int32_t, type, type)
lttng_ust_field_integer(int32_t, priority, priority)
lttng_ust_field_integer_hex(uint64_t, callback, callback)
lttng_ust_field_integer_hex(uint64_t, data, data)
lttng_ust_field_integer(uint64_t, flags, flags)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_counted_queue_release,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_intercept_register,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, callback, uint64_t, user_data, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer_hex(uint64_t, callback, callback)
lttng_ust_field_integer_hex(uint64_t, user_data, user_data)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_create,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, agent, uint64_t, descs, uint32_t, num_descs, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, agent, agent)
lttng_ust_field_integer_hex(uint64_t, descs, descs)
lttng_ust_field_integer(uint32_t, num_descs, num_descs)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_signal_external_semaphore,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, sem, uint64_t, value, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer_hex(uint64_t, sem, sem)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)

LTTNG_UST_TRACEPOINT_EVENT(
    rocm_hsa, hsa_amd_queue_wait_external_semaphore,
    LTTNG_UST_TP_ARGS(int32_t, phase, uint64_t, queue, uint64_t, sem, uint64_t, value, int32_t, retstatus),
    LTTNG_UST_TP_FIELDS(
lttng_ust_field_integer(int32_t, phase, phase)
lttng_ust_field_integer_hex(uint64_t, queue, queue)
lttng_ust_field_integer_hex(uint64_t, sem, sem)
lttng_ust_field_integer(uint64_t, value, value)
lttng_ust_field_integer(int32_t, retstatus, retstatus)
    )
)


#endif /* _ROCM_HSA_CURATED_TP_H */
