/* AUTO-GENERATED by lttng_curated_codegen.py from curated_apis.yaml.
 * Do not edit by hand — regenerate instead (see command below).
 *
 * SHA256(curated_apis.yaml) at generation: 66cd254d71a963a6fc7ba0d5a2e1cc1f3d8c60c497c5ceec03c4a55f17f89b24
 *
 * Per-API typed emit helpers for curated parameter capture. Every
 * helper takes (<captured-args...>, <status_type> status); status is
 * the call's success result, used to gate OUT-param deref. All-IN
 * APIs accept it but mark it unused.
 *
 * Regenerate with:
 *   python3 shared/lttng/scripts/lttng_curated_codegen.py \
 *       --provider hsa \
 *       --yaml projects/rocr-runtime/runtime/hsa-runtime/scripts/curated_apis.yaml \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa.h \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa_ext_amd.h \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/inc/hsa_api_trace.h \
 *       --header projects/rocr-runtime/runtime/hsa-runtime/core/inc/hsa_table_interface.h \
 *       --extra-arg=-Iprojects/rocr-runtime/runtime/hsa-runtime/inc \
 *       --extra-arg=-Iprojects/rocr-runtime/runtime/hsa-runtime \
 *       --tp-out projects/rocr-runtime/runtime/hsa-runtime/lttng/rocm_hsa_curated_tp.h \
 *       --emit-out projects/rocr-runtime/runtime/hsa-runtime/lttng/rocm_trace_emit_curated.h
 */
#ifndef ROCM_HSA_TRACE_EMIT_CURATED_H_
#define ROCM_HSA_TRACE_EMIT_CURATED_H_

#include <stdint.h>
#include <stddef.h>
/* HSA headers: the rocr-runtime source layout has these flat in
 * runtime/hsa-runtime/inc/ (not under an hsa/ subdir), and that directory
 * is on the include path while building libhsa-runtime64. The
 * angle-bracket <hsa/hsa.h> form is what consumers see after install;
 * this internal tracepoint emit header is only included from within
 * rocr-runtime's own compile units, so use the quoted form so the
 * in-tree build works. */
#include "hsa.h"
#include "hsa_ext_amd.h"

#if defined(HSA_ENABLE_LTTNG_UST) && HSA_ENABLE_LTTNG_UST

#include <atomic>
#include "rocm_hsa_curated_tp.h"

extern std::atomic<bool> rocm_hsa_trace_g_disabled;
#ifndef ROCM_TRACE_DISABLED_DEFINED
#define ROCM_TRACE_DISABLED_DEFINED
static inline bool rocm_trace_disabled(void) {
    return rocm_hsa_trace_g_disabled.load(std::memory_order_relaxed);
}
#endif

        static inline void rocm_trace_emit_hsa_queue_create_enter(
            uint64_t agent,
    uint32_t size,
    uint32_t type,
    const void* callback,
    const void* data,
    uint32_t private_segment_size,
    uint32_t group_segment_size) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_create,
(int32_t)0,
(uint64_t)(uintptr_t)(agent),
(uint32_t)(size),
(uint32_t)(type),
(uint64_t)(uintptr_t)(callback),
(uint64_t)(uintptr_t)(data),
(uint32_t)(private_segment_size),
(uint32_t)(group_segment_size),
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_create_exit(
            hsa_queue_t ** queue_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_create)) {
        const uint64_t queue_val =
    (status == HSA_STATUS_SUCCESS && queue_out_ptr != NULL)
        ? (uint64_t)((uint64_t)(uintptr_t)(*queue_out_ptr)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_create,
(int32_t)1,
0,
0,
0,
0,
0,
0,
0,
queue_val,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_destroy_enter(
            uint64_t queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_destroy)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_destroy,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_destroy_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_destroy)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_destroy,
(int32_t)1,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_intercept_create_enter(
            uint64_t agent_handle,
    uint32_t size,
    uint32_t type,
    const void* callback,
    const void* data,
    uint32_t private_segment_size,
    uint32_t group_segment_size) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_intercept_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_intercept_create,
(int32_t)0,
(uint64_t)(uintptr_t)(agent_handle),
(uint32_t)(size),
(uint32_t)(type),
(uint64_t)(uintptr_t)(callback),
(uint64_t)(uintptr_t)(data),
(uint32_t)(private_segment_size),
(uint32_t)(group_segment_size),
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_intercept_create_exit(
            hsa_queue_t ** queue_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_intercept_create)) {
        const uint64_t queue_val =
    (status == HSA_STATUS_SUCCESS && queue_out_ptr != NULL)
        ? (uint64_t)((uint64_t)(uintptr_t)(*queue_out_ptr)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_intercept_create,
(int32_t)1,
0,
0,
0,
0,
0,
0,
0,
queue_val,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_soft_queue_create_enter(
            uint64_t region,
    uint32_t size,
    uint32_t type,
    uint32_t features,
    uint64_t doorbell_signal,
    const void* queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_soft_queue_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_soft_queue_create,
(int32_t)0,
(uint64_t)(uintptr_t)(region),
(uint32_t)(size),
(uint32_t)(type),
(uint32_t)(features),
(uint64_t)(uintptr_t)(doorbell_signal),
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_soft_queue_create_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_soft_queue_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_soft_queue_create,
(int32_t)1,
0,
0,
0,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_inactivate_enter(
            uint64_t queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_inactivate)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_inactivate,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_inactivate_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_inactivate)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_inactivate,
(int32_t)1,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_load_read_index_scacquire_enter(
            uint64_t queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_load_read_index_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_load_read_index_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_load_read_index_scacquire_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_load_read_index_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_load_read_index_scacquire,
(int32_t)1,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_load_read_index_relaxed_enter(
            uint64_t queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_load_read_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_load_read_index_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_load_read_index_relaxed_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_load_read_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_load_read_index_relaxed,
(int32_t)1,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_load_write_index_scacquire_enter(
            uint64_t queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_load_write_index_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_load_write_index_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_load_write_index_scacquire_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_load_write_index_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_load_write_index_scacquire,
(int32_t)1,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_load_write_index_relaxed_enter(
            uint64_t queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_load_write_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_load_write_index_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_load_write_index_relaxed_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_load_write_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_load_write_index_relaxed,
(int32_t)1,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_store_write_index_relaxed_enter(
            uint64_t queue,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_store_write_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_store_write_index_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_queue_store_write_index_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_store_write_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_store_write_index_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_store_write_index_screlease_enter(
            uint64_t queue,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_store_write_index_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_store_write_index_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_queue_store_write_index_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_store_write_index_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_store_write_index_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_cas_write_index_scacq_screl_enter(
            uint64_t queue,
    uint64_t expected,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_cas_write_index_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_cas_write_index_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(expected),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_cas_write_index_scacq_screl_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_cas_write_index_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_cas_write_index_scacq_screl,
(int32_t)1,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_cas_write_index_scacquire_enter(
            uint64_t queue,
    uint64_t expected,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_cas_write_index_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_cas_write_index_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(expected),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_cas_write_index_scacquire_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_cas_write_index_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_cas_write_index_scacquire,
(int32_t)1,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_cas_write_index_relaxed_enter(
            uint64_t queue,
    uint64_t expected,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_cas_write_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_cas_write_index_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(expected),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_cas_write_index_relaxed_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_cas_write_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_cas_write_index_relaxed,
(int32_t)1,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_cas_write_index_screlease_enter(
            uint64_t queue,
    uint64_t expected,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_cas_write_index_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_cas_write_index_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(expected),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_cas_write_index_screlease_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_cas_write_index_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_cas_write_index_screlease,
(int32_t)1,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_add_write_index_scacq_screl_enter(
            uint64_t queue,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_add_write_index_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_add_write_index_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_add_write_index_scacq_screl_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_add_write_index_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_add_write_index_scacq_screl,
(int32_t)1,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_add_write_index_scacquire_enter(
            uint64_t queue,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_add_write_index_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_add_write_index_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_add_write_index_scacquire_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_add_write_index_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_add_write_index_scacquire,
(int32_t)1,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_add_write_index_relaxed_enter(
            uint64_t queue,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_add_write_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_add_write_index_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_add_write_index_relaxed_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_add_write_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_add_write_index_relaxed,
(int32_t)1,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_add_write_index_screlease_enter(
            uint64_t queue,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_add_write_index_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_add_write_index_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_add_write_index_screlease_exit(
            uint64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_add_write_index_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_add_write_index_screlease,
(int32_t)1,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_store_read_index_relaxed_enter(
            uint64_t queue,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_store_read_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_store_read_index_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_queue_store_read_index_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_store_read_index_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_store_read_index_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_queue_store_read_index_screlease_enter(
            uint64_t queue,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_store_read_index_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_store_read_index_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_queue_store_read_index_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_queue_store_read_index_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_queue_store_read_index_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_cu_set_mask_enter(
            uint64_t queue,
    uint32_t num_cu_mask_count,
    const void* cu_mask) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_cu_set_mask)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_cu_set_mask,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint32_t)(num_cu_mask_count),
(uint64_t)(uintptr_t)(cu_mask),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_cu_set_mask_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_cu_set_mask)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_cu_set_mask,
(int32_t)1,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_cu_get_mask_enter(
            uint64_t queue,
    uint32_t num_cu_mask_count,
    const void* cu_mask) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_cu_get_mask)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_cu_get_mask,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint32_t)(num_cu_mask_count),
(uint64_t)(uintptr_t)(cu_mask),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_cu_get_mask_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_cu_get_mask)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_cu_get_mask,
(int32_t)1,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_set_priority_enter(
            uint64_t queue,
    int32_t priority) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_set_priority)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_set_priority,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(int32_t)(priority),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_set_priority_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_set_priority)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_set_priority,
(int32_t)1,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_get_info_enter(
            uint64_t queue,
    int32_t attribute,
    const void* value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_get_info)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_get_info,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(int32_t)(attribute),
(uint64_t)(uintptr_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_get_info_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_get_info)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_get_info,
(int32_t)1,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_counted_queue_acquire_enter(
            uint64_t agent,
    int32_t type,
    int32_t priority,
    const void* callback,
    const void* data,
    uint64_t flags,
    const void* queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_counted_queue_acquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_counted_queue_acquire,
(int32_t)0,
(uint64_t)(uintptr_t)(agent),
(int32_t)(type),
(int32_t)(priority),
(uint64_t)(uintptr_t)(callback),
(uint64_t)(uintptr_t)(data),
(uint64_t)(flags),
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_counted_queue_acquire_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_counted_queue_acquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_counted_queue_acquire,
(int32_t)1,
0,
0,
0,
0,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_counted_queue_release_enter(
            uint64_t queue) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_counted_queue_release)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_counted_queue_release,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_counted_queue_release_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_counted_queue_release)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_counted_queue_release,
(int32_t)1,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_intercept_register_enter(
            uint64_t queue,
    const void* callback,
    const void* user_data) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_intercept_register)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_intercept_register,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(uintptr_t)(callback),
(uint64_t)(uintptr_t)(user_data),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_intercept_register_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_intercept_register)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_intercept_register,
(int32_t)1,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_create_enter(
            uint64_t agent,
    const void* descs,
    uint32_t num_descs) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_create,
(int32_t)0,
(uint64_t)(uintptr_t)(agent),
(uint64_t)(uintptr_t)(descs),
(uint32_t)(num_descs),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_create_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_create,
(int32_t)1,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_signal_external_semaphore_enter(
            uint64_t queue,
    uint64_t sem,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_signal_external_semaphore)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_signal_external_semaphore,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(uintptr_t)(sem),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_signal_external_semaphore_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_signal_external_semaphore)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_signal_external_semaphore,
(int32_t)1,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_wait_external_semaphore_enter(
            uint64_t queue,
    uint64_t sem,
    uint64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_wait_external_semaphore)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_wait_external_semaphore,
(int32_t)0,
(uint64_t)(uintptr_t)(queue),
(uint64_t)(uintptr_t)(sem),
(uint64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_queue_wait_external_semaphore_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_queue_wait_external_semaphore)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_queue_wait_external_semaphore,
(int32_t)1,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_create_enter(
            int64_t initial_value,
    uint32_t num_consumers,
    const void* consumers) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_create,
(int32_t)0,
(int64_t)(initial_value),
(uint32_t)(num_consumers),
(uint64_t)(uintptr_t)(consumers),
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_create_exit(
            hsa_signal_t * signal_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_create)) {
        const uint64_t signal_val =
    (status == HSA_STATUS_SUCCESS && signal_out_ptr != NULL)
        ? (uint64_t)((signal_out_ptr->handle)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_create,
(int32_t)1,
0,
0,
0,
signal_val,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_destroy_enter(
            uint64_t signal) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_destroy)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_destroy,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_destroy_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_destroy)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_destroy,
(int32_t)1,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_create_enter(
            int64_t initial_value,
    uint32_t num_consumers,
    const void* consumers,
    uint64_t attributes) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_create,
(int32_t)0,
(int64_t)(initial_value),
(uint32_t)(num_consumers),
(uint64_t)(uintptr_t)(consumers),
(uint64_t)(attributes),
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_create_exit(
            hsa_signal_t * signal_out_ptr,
    hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_create)) {
        const uint64_t signal_val =
    (status == HSA_STATUS_SUCCESS && signal_out_ptr != NULL)
        ? (uint64_t)((signal_out_ptr->handle)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_create,
(int32_t)1,
0,
0,
0,
0,
signal_val,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_load_relaxed_enter(
            uint64_t signal) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_load_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_load_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_load_relaxed_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_load_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_load_relaxed,
(int32_t)1,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_load_scacquire_enter(
            uint64_t signal) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_load_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_load_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_load_scacquire_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_load_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_load_scacquire,
(int32_t)1,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_store_relaxed_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_store_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_store_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_store_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_store_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_store_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_store_screlease_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_store_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_store_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_store_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_store_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_store_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_silent_store_relaxed_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_silent_store_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_silent_store_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_silent_store_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_silent_store_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_silent_store_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_silent_store_screlease_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_silent_store_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_silent_store_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_silent_store_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_silent_store_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_silent_store_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_wait_relaxed_enter(
            uint64_t signal,
    int32_t condition,
    int64_t compare_value,
    uint64_t timeout_hint,
    int32_t wait_state_hint) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_wait_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_wait_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int32_t)(condition),
(int64_t)(compare_value),
(uint64_t)(timeout_hint),
(int32_t)(wait_state_hint),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_wait_relaxed_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_wait_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_wait_relaxed,
(int32_t)1,
0,
0,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_wait_scacquire_enter(
            uint64_t signal,
    int32_t condition,
    int64_t compare_value,
    uint64_t timeout_hint,
    int32_t wait_state_hint) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_wait_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_wait_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int32_t)(condition),
(int64_t)(compare_value),
(uint64_t)(timeout_hint),
(int32_t)(wait_state_hint),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_wait_scacquire_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_wait_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_wait_scacquire,
(int32_t)1,
0,
0,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_group_create_enter(
            uint32_t num_signals,
    const void* signals,
    uint32_t num_consumers,
    const void* consumers,
    const void* signal_group) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_group_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_group_create,
(int32_t)0,
(uint32_t)(num_signals),
(uint64_t)(uintptr_t)(signals),
(uint32_t)(num_consumers),
(uint64_t)(uintptr_t)(consumers),
(uint64_t)(uintptr_t)(signal_group),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_group_create_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_group_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_group_create,
(int32_t)1,
0,
0,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_group_destroy_enter(
            uint64_t signal_group) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_group_destroy)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_group_destroy,
(int32_t)0,
(uint64_t)(uintptr_t)(signal_group),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_group_destroy_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_group_destroy)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_group_destroy,
(int32_t)1,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_group_wait_any_relaxed_enter(
            uint64_t signal_group,
    const void* conditions,
    const void* compare_values,
    int32_t wait_state_hint,
    const void* signal,
    const void* value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_group_wait_any_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_group_wait_any_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal_group),
(uint64_t)(uintptr_t)(conditions),
(uint64_t)(uintptr_t)(compare_values),
(int32_t)(wait_state_hint),
(uint64_t)(uintptr_t)(signal),
(uint64_t)(uintptr_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_group_wait_any_relaxed_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_group_wait_any_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_group_wait_any_relaxed,
(int32_t)1,
0,
0,
0,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_group_wait_any_scacquire_enter(
            uint64_t signal_group,
    const void* conditions,
    const void* compare_values,
    int32_t wait_state_hint,
    const void* signal,
    const void* value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_group_wait_any_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_group_wait_any_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal_group),
(uint64_t)(uintptr_t)(conditions),
(uint64_t)(uintptr_t)(compare_values),
(int32_t)(wait_state_hint),
(uint64_t)(uintptr_t)(signal),
(uint64_t)(uintptr_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_group_wait_any_scacquire_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_group_wait_any_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_group_wait_any_scacquire,
(int32_t)1,
0,
0,
0,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_and_relaxed_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_and_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_and_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_and_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_and_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_and_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_and_scacquire_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_and_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_and_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_and_scacquire_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_and_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_and_scacquire,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_and_screlease_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_and_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_and_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_and_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_and_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_and_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_and_scacq_screl_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_and_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_and_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_and_scacq_screl_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_and_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_and_scacq_screl,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_or_relaxed_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_or_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_or_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_or_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_or_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_or_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_or_scacquire_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_or_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_or_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_or_scacquire_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_or_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_or_scacquire,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_or_screlease_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_or_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_or_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_or_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_or_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_or_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_or_scacq_screl_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_or_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_or_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_or_scacq_screl_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_or_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_or_scacq_screl,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_xor_relaxed_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_xor_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_xor_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_xor_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_xor_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_xor_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_xor_scacquire_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_xor_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_xor_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_xor_scacquire_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_xor_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_xor_scacquire,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_xor_screlease_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_xor_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_xor_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_xor_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_xor_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_xor_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_xor_scacq_screl_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_xor_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_xor_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_xor_scacq_screl_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_xor_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_xor_scacq_screl,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_add_relaxed_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_add_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_add_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_add_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_add_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_add_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_add_scacquire_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_add_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_add_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_add_scacquire_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_add_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_add_scacquire,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_add_screlease_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_add_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_add_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_add_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_add_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_add_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_add_scacq_screl_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_add_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_add_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_add_scacq_screl_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_add_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_add_scacq_screl,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_subtract_relaxed_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_subtract_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_subtract_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_subtract_relaxed_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_subtract_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_subtract_relaxed,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_subtract_scacquire_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_subtract_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_subtract_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_subtract_scacquire_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_subtract_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_subtract_scacquire,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_subtract_screlease_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_subtract_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_subtract_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_subtract_screlease_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_subtract_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_subtract_screlease,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_subtract_scacq_screl_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_subtract_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_subtract_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value));
            }
        }

        static inline void rocm_trace_emit_hsa_signal_subtract_scacq_screl_exit(
            void) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_subtract_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_subtract_scacq_screl,
(int32_t)1,
0,
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_exchange_relaxed_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_exchange_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_exchange_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_exchange_relaxed_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_exchange_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_exchange_relaxed,
(int32_t)1,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_exchange_scacquire_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_exchange_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_exchange_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_exchange_scacquire_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_exchange_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_exchange_scacquire,
(int32_t)1,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_exchange_screlease_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_exchange_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_exchange_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_exchange_screlease_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_exchange_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_exchange_screlease,
(int32_t)1,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_exchange_scacq_screl_enter(
            uint64_t signal,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_exchange_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_exchange_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_exchange_scacq_screl_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_exchange_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_exchange_scacq_screl,
(int32_t)1,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_cas_relaxed_enter(
            uint64_t signal,
    int64_t expected,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_cas_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_cas_relaxed,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(expected),
(int64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_cas_relaxed_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_cas_relaxed)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_cas_relaxed,
(int32_t)1,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_cas_scacquire_enter(
            uint64_t signal,
    int64_t expected,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_cas_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_cas_scacquire,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(expected),
(int64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_cas_scacquire_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_cas_scacquire)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_cas_scacquire,
(int32_t)1,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_cas_screlease_enter(
            uint64_t signal,
    int64_t expected,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_cas_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_cas_screlease,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(expected),
(int64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_cas_screlease_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_cas_screlease)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_cas_screlease,
(int32_t)1,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_cas_scacq_screl_enter(
            uint64_t signal,
    int64_t expected,
    int64_t value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_cas_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_cas_scacq_screl,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int64_t)(expected),
(int64_t)(value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_signal_cas_scacq_screl_exit(
            int64_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_signal_cas_scacq_screl)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_signal_cas_scacq_screl,
(int32_t)1,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_async_handler_enter(
            uint64_t signal,
    int32_t cond,
    int64_t value,
    const void* handler,
    const void* arg) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_async_handler)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_async_handler,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(int32_t)(cond),
(int64_t)(value),
(uint64_t)(uintptr_t)(handler),
(uint64_t)(uintptr_t)(arg),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_async_handler_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_async_handler)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_async_handler,
(int32_t)1,
0,
0,
0,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_wait_all_enter(
            uint32_t signal_count,
    const void* signals,
    const void* conds,
    const void* values,
    uint64_t timeout_hint,
    int32_t wait_hint,
    const void* satisfying_values) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_wait_all)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_wait_all,
(int32_t)0,
(uint32_t)(signal_count),
(uint64_t)(uintptr_t)(signals),
(uint64_t)(uintptr_t)(conds),
(uint64_t)(uintptr_t)(values),
(uint64_t)(timeout_hint),
(int32_t)(wait_hint),
(uint64_t)(uintptr_t)(satisfying_values),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_wait_all_exit(
            uint32_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_wait_all)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_wait_all,
(int32_t)1,
0,
0,
0,
0,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_wait_any_enter(
            uint32_t signal_count,
    const void* signals,
    const void* conds,
    const void* values,
    uint64_t timeout_hint,
    int32_t wait_hint,
    const void* satisfying_value) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_wait_any)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_wait_any,
(int32_t)0,
(uint32_t)(signal_count),
(uint64_t)(uintptr_t)(signals),
(uint64_t)(uintptr_t)(conds),
(uint64_t)(uintptr_t)(values),
(uint64_t)(timeout_hint),
(int32_t)(wait_hint),
(uint64_t)(uintptr_t)(satisfying_value),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_wait_any_exit(
            uint32_t retval) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_wait_any)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_wait_any,
(int32_t)1,
0,
0,
0,
0,
0,
0,
0,
retval);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_ipc_signal_create_enter(
            uint64_t signal,
    const void* handle) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_ipc_signal_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_ipc_signal_create,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(uint64_t)(uintptr_t)(handle),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_ipc_signal_create_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_ipc_signal_create)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_ipc_signal_create,
(int32_t)1,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_ipc_signal_attach_enter(
            const void* handle,
    const void* signal) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_ipc_signal_attach)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_ipc_signal_attach,
(int32_t)0,
(uint64_t)(uintptr_t)(handle),
(uint64_t)(uintptr_t)(signal),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_ipc_signal_attach_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_ipc_signal_attach)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_ipc_signal_attach,
(int32_t)1,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_value_pointer_enter(
            uint64_t signal,
    const void* value_ptr) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_value_pointer)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_value_pointer,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(uint64_t)(uintptr_t)(value_ptr),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_value_pointer_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_value_pointer)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_value_pointer,
(int32_t)1,
0,
0,
(int32_t)status);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_get_event_id_enter(
            uint64_t signal,
    const void* event_id) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_get_event_id)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_get_event_id,
(int32_t)0,
(uint64_t)(uintptr_t)(signal),
(uint64_t)(uintptr_t)(event_id),
0);
            }
        }

        static inline void rocm_trace_emit_hsa_amd_signal_get_event_id_exit(
            hsa_status_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hsa, hsa_amd_signal_get_event_id)) {
            lttng_ust_do_tracepoint(rocm_hsa, hsa_amd_signal_get_event_id,
(int32_t)1,
0,
0,
(int32_t)status);
            }
        }


#else  /* HSA_ENABLE_LTTNG_UST not defined — all helpers are no-ops */

static inline void rocm_trace_emit_hsa_queue_create_enter(uint64_t, uint32_t, uint32_t, const void*, const void*, uint32_t, uint32_t) {}
static inline void rocm_trace_emit_hsa_queue_create_exit(hsa_queue_t **, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_queue_destroy_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_destroy_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_intercept_create_enter(uint64_t, uint32_t, uint32_t, const void*, const void*, uint32_t, uint32_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_intercept_create_exit(hsa_queue_t **, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_soft_queue_create_enter(uint64_t, uint32_t, uint32_t, uint32_t, uint64_t, const void*) {}
static inline void rocm_trace_emit_hsa_soft_queue_create_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_queue_inactivate_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_inactivate_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_queue_load_read_index_scacquire_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_load_read_index_scacquire_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_load_read_index_relaxed_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_load_read_index_relaxed_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_load_write_index_scacquire_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_load_write_index_scacquire_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_load_write_index_relaxed_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_load_write_index_relaxed_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_store_write_index_relaxed_enter(uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_store_write_index_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_queue_store_write_index_screlease_enter(uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_store_write_index_screlease_exit() {}
static inline void rocm_trace_emit_hsa_queue_cas_write_index_scacq_screl_enter(uint64_t, uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_cas_write_index_scacq_screl_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_cas_write_index_scacquire_enter(uint64_t, uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_cas_write_index_scacquire_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_cas_write_index_relaxed_enter(uint64_t, uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_cas_write_index_relaxed_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_cas_write_index_screlease_enter(uint64_t, uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_cas_write_index_screlease_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_add_write_index_scacq_screl_enter(uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_add_write_index_scacq_screl_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_add_write_index_scacquire_enter(uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_add_write_index_scacquire_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_add_write_index_relaxed_enter(uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_add_write_index_relaxed_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_add_write_index_screlease_enter(uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_add_write_index_screlease_exit(uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_store_read_index_relaxed_enter(uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_store_read_index_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_queue_store_read_index_screlease_enter(uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_queue_store_read_index_screlease_exit() {}
static inline void rocm_trace_emit_hsa_amd_queue_cu_set_mask_enter(uint64_t, uint32_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_queue_cu_set_mask_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_cu_get_mask_enter(uint64_t, uint32_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_queue_cu_get_mask_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_set_priority_enter(uint64_t, int32_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_set_priority_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_get_info_enter(uint64_t, int32_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_queue_get_info_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_counted_queue_acquire_enter(uint64_t, int32_t, int32_t, const void*, const void*, uint64_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_counted_queue_acquire_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_counted_queue_release_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_amd_counted_queue_release_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_intercept_register_enter(uint64_t, const void*, const void*) {}
static inline void rocm_trace_emit_hsa_amd_queue_intercept_register_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_create_enter(uint64_t, const void*, uint32_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_create_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_signal_external_semaphore_enter(uint64_t, uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_signal_external_semaphore_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_wait_external_semaphore_enter(uint64_t, uint64_t, uint64_t) {}
static inline void rocm_trace_emit_hsa_amd_queue_wait_external_semaphore_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_create_enter(int64_t, uint32_t, const void*) {}
static inline void rocm_trace_emit_hsa_signal_create_exit(hsa_signal_t *, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_destroy_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_signal_destroy_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_signal_create_enter(int64_t, uint32_t, const void*, uint64_t) {}
static inline void rocm_trace_emit_hsa_amd_signal_create_exit(hsa_signal_t *, hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_load_relaxed_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_signal_load_relaxed_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_load_scacquire_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_signal_load_scacquire_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_store_relaxed_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_store_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_signal_store_screlease_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_store_screlease_exit() {}
static inline void rocm_trace_emit_hsa_signal_silent_store_relaxed_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_silent_store_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_signal_silent_store_screlease_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_silent_store_screlease_exit() {}
static inline void rocm_trace_emit_hsa_signal_wait_relaxed_enter(uint64_t, int32_t, int64_t, uint64_t, int32_t) {}
static inline void rocm_trace_emit_hsa_signal_wait_relaxed_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_wait_scacquire_enter(uint64_t, int32_t, int64_t, uint64_t, int32_t) {}
static inline void rocm_trace_emit_hsa_signal_wait_scacquire_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_group_create_enter(uint32_t, const void*, uint32_t, const void*, const void*) {}
static inline void rocm_trace_emit_hsa_signal_group_create_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_group_destroy_enter(uint64_t) {}
static inline void rocm_trace_emit_hsa_signal_group_destroy_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_group_wait_any_relaxed_enter(uint64_t, const void*, const void*, int32_t, const void*, const void*) {}
static inline void rocm_trace_emit_hsa_signal_group_wait_any_relaxed_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_group_wait_any_scacquire_enter(uint64_t, const void*, const void*, int32_t, const void*, const void*) {}
static inline void rocm_trace_emit_hsa_signal_group_wait_any_scacquire_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_signal_and_relaxed_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_and_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_signal_and_scacquire_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_and_scacquire_exit() {}
static inline void rocm_trace_emit_hsa_signal_and_screlease_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_and_screlease_exit() {}
static inline void rocm_trace_emit_hsa_signal_and_scacq_screl_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_and_scacq_screl_exit() {}
static inline void rocm_trace_emit_hsa_signal_or_relaxed_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_or_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_signal_or_scacquire_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_or_scacquire_exit() {}
static inline void rocm_trace_emit_hsa_signal_or_screlease_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_or_screlease_exit() {}
static inline void rocm_trace_emit_hsa_signal_or_scacq_screl_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_or_scacq_screl_exit() {}
static inline void rocm_trace_emit_hsa_signal_xor_relaxed_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_xor_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_signal_xor_scacquire_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_xor_scacquire_exit() {}
static inline void rocm_trace_emit_hsa_signal_xor_screlease_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_xor_screlease_exit() {}
static inline void rocm_trace_emit_hsa_signal_xor_scacq_screl_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_xor_scacq_screl_exit() {}
static inline void rocm_trace_emit_hsa_signal_add_relaxed_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_add_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_signal_add_scacquire_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_add_scacquire_exit() {}
static inline void rocm_trace_emit_hsa_signal_add_screlease_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_add_screlease_exit() {}
static inline void rocm_trace_emit_hsa_signal_add_scacq_screl_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_add_scacq_screl_exit() {}
static inline void rocm_trace_emit_hsa_signal_subtract_relaxed_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_subtract_relaxed_exit() {}
static inline void rocm_trace_emit_hsa_signal_subtract_scacquire_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_subtract_scacquire_exit() {}
static inline void rocm_trace_emit_hsa_signal_subtract_screlease_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_subtract_screlease_exit() {}
static inline void rocm_trace_emit_hsa_signal_subtract_scacq_screl_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_subtract_scacq_screl_exit() {}
static inline void rocm_trace_emit_hsa_signal_exchange_relaxed_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_exchange_relaxed_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_exchange_scacquire_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_exchange_scacquire_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_exchange_screlease_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_exchange_screlease_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_exchange_scacq_screl_enter(uint64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_exchange_scacq_screl_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_cas_relaxed_enter(uint64_t, int64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_cas_relaxed_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_cas_scacquire_enter(uint64_t, int64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_cas_scacquire_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_cas_screlease_enter(uint64_t, int64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_cas_screlease_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_signal_cas_scacq_screl_enter(uint64_t, int64_t, int64_t) {}
static inline void rocm_trace_emit_hsa_signal_cas_scacq_screl_exit(int64_t) {}
static inline void rocm_trace_emit_hsa_amd_signal_async_handler_enter(uint64_t, int32_t, int64_t, const void*, const void*) {}
static inline void rocm_trace_emit_hsa_amd_signal_async_handler_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_signal_wait_all_enter(uint32_t, const void*, const void*, const void*, uint64_t, int32_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_signal_wait_all_exit(uint32_t) {}
static inline void rocm_trace_emit_hsa_amd_signal_wait_any_enter(uint32_t, const void*, const void*, const void*, uint64_t, int32_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_signal_wait_any_exit(uint32_t) {}
static inline void rocm_trace_emit_hsa_amd_ipc_signal_create_enter(uint64_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_ipc_signal_create_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_ipc_signal_attach_enter(const void*, const void*) {}
static inline void rocm_trace_emit_hsa_amd_ipc_signal_attach_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_signal_value_pointer_enter(uint64_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_signal_value_pointer_exit(hsa_status_t) {}
static inline void rocm_trace_emit_hsa_amd_signal_get_event_id_enter(uint64_t, const void*) {}
static inline void rocm_trace_emit_hsa_amd_signal_get_event_id_exit(hsa_status_t) {}

#endif  /* HSA_ENABLE_LTTNG_UST */

#endif  /* ROCM_HSA_TRACE_EMIT_CURATED_H_ */
