// Stub hip_version.h
#pragma once
#define HIP_VERSION_MAJOR 6
#define HIP_VERSION_MINOR 4
#define HIP_VERSION_PATCH 0
#define HIP_VERSION (HIP_VERSION_MAJOR * 10000000 + HIP_VERSION_MINOR * 100000 + HIP_VERSION_PATCH)
#define HIP_VERSION_GITHASH "stub"
