##############################################################################
# MIT License
#
# Copyright (c) 2021 - 2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

##############################################################################


import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union

import pandas as pd

from utils.logger import console_debug, console_warning
from utils.parser import apply_filters, eval_metric

# SUPPORTED_DATATYPES table is based on datatype support in rocm-amdgpu-bench repository
# Indicates which datatypes per gpu arch can be generated by the roofline binary
SUPPORTED_DATATYPES: dict[str, list[str]] = {
    "gfx90a": [
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported: F4, F6, F8
    "gfx940": [
        "FP8",
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported: F4, F6
    "gfx941": [
        "FP8",
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported: F4, F6
    "gfx942": [
        "FP8",
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported: F4, F6
    "gfx950": [
        "FP4",
        "FP6",
        "FP8",
        "FP16",
        "BF16",
        "FP32",
        "FP64",
        "I8",
        "I32",
        "I64",
    ],  # Unsupported:
}

PEAK_OPS_DATATYPES: list[str] = [
    "FP8",
    "FP16",
    "BF16",
    "FP32",
    "FP64",
    "I8",
    "I32",
    "I64",
]
MFMA_DATATYPES: list[str] = ["FP4", "FP6", "FP8", "FP16", "BF16", "FP32", "FP64", "I8"]


################################################
# Helper funcs
################################################
@dataclass
class AI_Data:
    kernel_name: str
    num_calls: float

    total_flops: float
    valu_flops: float
    mfma_flops_f6f4: float
    mfma_flops_f8: float
    mfma_flops_f16: float
    mfma_flops_bf16: float
    mfma_flops_f32: float
    mfma_flops_f64: float
    mfma_iops_i8: float
    lds_data: float
    L1cache_data: float
    L2cache_data: float
    hbm_data: float

    total_duration: float
    avg_duration: float


def get_font(
    font_size: int = 16, font_color: str = "black", font_weight: str = "bold"
) -> dict[str, Union[str, int]]:
    return {
        "size": font_size,
        "color": font_color,
        "weight": font_weight,
        "family": "serif",
    }


def get_color(category: str) -> str:
    if category == "ai_l1":
        return "green"
    elif category == "ai_l2":
        return "blue"
    elif category == "ai_hbm":
        return "red"
    else:
        raise RuntimeError("Invalid category passed to get_color()")


# -------------------------------------------------------------------------------------
#                           Plot BW at each cache level
# -------------------------------------------------------------------------------------
def calc_ceilings(
    roofline_parameters: dict[str, Any],
    dtype: str,
    benchmark_data: dict[str, list[str]],
    xmin: float = 0.01,
    xmax: float = 1000.0,
) -> dict[str, list[Union[list[float], float]]]:
    """Given benchmarking data, calculate ceilings (or peak performance) for
    empirical roofline"""

    # TODO: This is where filtering by memory level will need to occur for standalone
    graph_points: dict[str, list[Union[list[float], float]]] = {
        "hbm": [],
        "l2": [],
        "l1": [],
        "lds": [],
        "valu": [],
        "mfma": [],
    }

    cache_hierarchy: list[str] = (
        ["HBM", "L2", "L1", "LDS"]
        if roofline_parameters["mem_level"] == "ALL"
        else roofline_parameters["mem_level"]
    )

    x1 = y1 = x2 = y2 = -1
    x1_mfma = y1_mfma = x2_mfma = y2_mfma = -1

    ops_flops = "Ops" if dtype.startswith("I") else "Flops"

    peak_ops = 0.0
    if dtype in PEAK_OPS_DATATYPES:
        peak_ops = float(
            benchmark_data[f"{dtype}{ops_flops}"][roofline_parameters["device_id"]]
        )

    peak_mfma = 0.0
    for i in range(len(cache_hierarchy)):
        # Plot BW line
        console_debug("roofline", f"Current cache level is {cache_hierarchy[i]}")
        curr_bw = f"{cache_hierarchy[i]}Bw"
        peak_bw = float(benchmark_data[curr_bw][roofline_parameters["device_id"]])

        x1 = float(xmin)
        y1 = float(xmin) * peak_bw

        if dtype in PEAK_OPS_DATATYPES:
            x2 = peak_ops / peak_bw
            y2 = peak_ops  # noqa

            # Plot MFMA lines (NOTE: Assuming MI200 soc)
            x1_mfma = peak_ops / peak_bw
            y1_mfma = peak_ops
        if dtype in MFMA_DATATYPES:
            target_precision = dtype if dtype.startswith("I") else f"F{dtype[2:]}"

            peak_mfma = float(
                benchmark_data[f"MFMA{target_precision}{ops_flops}"][
                    roofline_parameters["device_id"]
                ]
            )
            x2_mfma = peak_mfma / peak_bw
            y2_mfma = peak_mfma

        # Check which peak is higher for formatting bandwidth lines
        if y2_mfma > y1_mfma:  # peak_mfma
            peak_x = x2_mfma
            peak_y = y2_mfma
        else:  # peakVALU
            peak_x = x1_mfma
            peak_y = y1_mfma

        # These are the points to use:
        console_debug("roofline", "coordinate points:")
        console_debug(f"x = [{x1}, {peak_x}]")
        console_debug(f"y = [{y1}, {peak_y}]")

        graph_points[cache_hierarchy[i].lower()].append([x1, peak_x])
        graph_points[cache_hierarchy[i].lower()].append([y1, peak_y])
        graph_points[cache_hierarchy[i].lower()].append(peak_bw)

    # ----------------------------------------------------------------------------------
    #                                     Plot computing roof
    # ----------------------------------------------------------------------------------
    if dtype in PEAK_OPS_DATATYPES:
        # Plot FMA roof
        x0 = xmax
        if x2 < x0:
            x0 = x2

        console_debug(f"FMA ROOF [{x0}, {xmax}], [{peak_ops},{peak_ops}]")
        graph_points["valu"].append([x0, xmax])
        graph_points["valu"].append([peak_ops, peak_ops])
        graph_points["valu"].append(peak_ops)

    # Plot MFMA roof
    if dtype in MFMA_DATATYPES:  # assert that mfma has been assigned
        x0_mfma = xmax
        if x2_mfma < x0_mfma:
            x0_mfma = x2_mfma

        console_debug(f"MFMA ROOF [{x0_mfma}, {xmax}], [{peak_mfma},{peak_mfma}]")
        graph_points["mfma"].append([x0_mfma, xmax])
        graph_points["mfma"].append([peak_mfma, peak_mfma])
        graph_points["mfma"].append(peak_mfma)

    return graph_points


# -------------------------------------------------------------------------------------
#                              Overlay application performance
# -------------------------------------------------------------------------------------
# Calculate relevant metrics for ai calculation
def calc_ai_analyze(
    workload: Any, config: Any, arch_config: Any
) -> dict[str, Union[list[list[float]], list[str]]]:
    """
    Calculate per-kernel metrics and AI points with Roofline yamls using eval_metric.
    """
    console_debug("calc_ai_analyze: Starting calc_ai analysis using Roofline yamls")
    plot_points: dict[str, Any] = {
        "ai_l1": [[], []],
        "ai_l2": [[], []],
        "ai_hbm": [[], []],
        "kernel_names": [],
    }

    workload.roofline_metrics = {}
    filtered_pmc = apply_filters(workload, workload.path, is_gui=False, debug=False)

    kernel_ids_to_process: list[int] = []
    kernel_top_table_id = 1

    if workload.filter_kernel_ids:
        kernel_ids_to_process = workload.filter_kernel_ids
    else:
        if kernel_top_table_id in workload.dfs:
            kernel_top_df = workload.dfs[kernel_top_table_id]
            kernel_ids_to_process = kernel_top_df.index.tolist()
            console_debug(
                "roofline", f"Found {len(kernel_ids_to_process)} kernels to process"
            )

    if not kernel_ids_to_process:
        console_warning("No kernels found to process for roofline")
        return plot_points

    for kernel_id in kernel_ids_to_process:
        if kernel_top_table_id in workload.dfs:
            kernel_top_df = workload.dfs[kernel_top_table_id]
            if kernel_id in kernel_top_df.index:
                kernel_name = kernel_top_df.loc[kernel_id, "Kernel_Name"]
            else:
                continue
        else:
            continue

        console_debug("roofline", f"Processing kernel {kernel_id}: {kernel_name[:50]}")

        # filter PMC data for specific kernel
        kernel_pmc_df = filtered_pmc[
            filtered_pmc["pmc_perf"]["Kernel_Name"] == kernel_name
        ]

        if kernel_pmc_df.empty:
            console_debug("roofline", f"No PMC data for kernel {kernel_id}")
            continue

        kernel_only_data = {"pmc_perf": kernel_pmc_df["pmc_perf"]}

        kernel_dfs: dict[int, Any] = {}
        kernel_dfs_type: dict[int, str] = {}

        for table_id in [401, 402]:
            if table_id in arch_config.dfs:
                kernel_dfs[table_id] = arch_config.dfs[table_id].copy()
                kernel_dfs_type[table_id] = arch_config.dfs_type[table_id]

        # eval metrics for single kernel only
        eval_metric(
            kernel_dfs,
            kernel_dfs_type,
            workload.sys_info.iloc[0],
            workload.roofline_peaks,
            kernel_only_data,
            debug=False,
            config=config,
        )

        # DEBUG
        if 402 in kernel_dfs:
            console_debug("roofline", f"Table 402 for kernel {kernel_id}:")
            for idx, row in kernel_dfs[402].iterrows():
                console_debug(
                    "roofline", f"  {row.get('Metric', '')}: {row.get('Value', '')}"
                )

        ai_hbm = ai_l2 = ai_l1 = performance = 0

        if 402 in kernel_dfs:
            for idx, row in kernel_dfs[402].iterrows():
                metric = row.get("Metric", "")
                value = row.get("Value", 0)
                if metric == "AI HBM":
                    ai_hbm = value if value and value != "" else 0
                elif metric == "AI L2":
                    ai_l2 = value if value and value != "" else 0
                elif metric == "AI L1":
                    ai_l1 = value if value and value != "" else 0
                elif metric == "Performance (GFLOPs)":
                    performance = value if value and value != "" else 0

        console_debug(
            "roofline",
            f"Kernel {kernel_id}: "
            f"AI_HBM={ai_hbm:.2f}, "
            f"AI_L2={ai_l2:.2f}, "
            f"AI_L1={ai_l1:.2f}, "
            f"Performance={performance:.2e} GFLOP/s",
        )

        # add to plot points if we have valid data
        if performance > 0:
            if ai_hbm > 0:
                plot_points["ai_hbm"][0].append(ai_hbm)
                plot_points["ai_hbm"][1].append(performance)
            if ai_l2 > 0:
                plot_points["ai_l2"][0].append(ai_l2)
                plot_points["ai_l2"][1].append(performance)
            if ai_l1 > 0:
                plot_points["ai_l1"][0].append(ai_l1)
                plot_points["ai_l1"][1].append(performance)

            plot_points["kernel_names"].append(f"K{kernel_id}")
            console_debug("roofline", f"Added kernel {kernel_id} to plot points")
        else:
            console_debug(
                "roofline", f"Skipping kernel {kernel_id} - no performance data"
            )

        # store metrics for display
        workload.roofline_metrics[kernel_id] = {
            "name": kernel_name,
            "ai_table": kernel_dfs.get(401, pd.DataFrame()),
            "calc_table": kernel_dfs.get(402, pd.DataFrame()),
        }

    console_debug(
        "roofline", f"Generated {len(plot_points['kernel_names'])} plot points"
    )
    console_debug("roofline", f"Plot points: {plot_points}")
    return plot_points


def calc_ai_profile(
    mspec: Any, sort_type: str, ret_df: dict[str, pd.DataFrame]
) -> dict[str, list[Union[list[float], str]]]:
    """Given counter data, calculate arithmetic intensity for each kernel
    in the application. Leverage hard-coded equations to calculate AI values.

    Used during profiling stage to generate roofline PDF, since Roofline yamls
    are not available in the profiling stage."""

    console_debug(
        "calc_ai_profile: Starting legacy roofline calculation (from roofline_calc)"
    )
    df = ret_df["pmc_perf"]
    # Sort by top kernels or top dispatches?
    df = df.sort_values(by=["Kernel_Name"])
    df = df.reset_index(drop=True)

    total_flops = valu_flops = mfma_flops_f6f4 = mfma_flops_f8 = mfma_flops_bf16 = (
        mfma_flops_f16
    ) = mfma_iops_i8 = mfma_flops_f32 = mfma_flops_f64 = lds_data = L1cache_data = (
        L2cache_data
    ) = hbm_data = calls = total_duration = avg_duration = 0.0

    kernel_name = ""

    ai_data_list: list[AI_Data] = []
    at_end = False
    next_kernel_name = ""

    supported_dt = SUPPORTED_DATATYPES[mspec.gpu_arch]

    for idx in df.index:
        # CASE: Top kernels
        # Calculate + append AI data if
        # a) current kernel_name is different than previous OR
        # b) We've reached the end of list
        if idx + 1 == df.shape[0]:
            at_end = True
        else:
            next_kernel_name = str(df.loc[idx + 1, "Kernel_Name"])

        kernel_name = str(df.loc[idx, "Kernel_Name"])
        try:
            total_flops += (
                (
                    64
                    * (
                        df["SQ_INSTS_VALU_ADD_F16"][idx]
                        + df["SQ_INSTS_VALU_MUL_F16"][idx]
                        + (2 * df["SQ_INSTS_VALU_FMA_F16"][idx])
                        + df["SQ_INSTS_VALU_TRANS_F16"][idx]
                    )
                )
                + (
                    64
                    * (
                        df["SQ_INSTS_VALU_ADD_F32"][idx]
                        + df["SQ_INSTS_VALU_MUL_F32"][idx]
                        + (2 * df["SQ_INSTS_VALU_FMA_F32"][idx])
                        + df["SQ_INSTS_VALU_TRANS_F32"][idx]
                    )
                )
                + (
                    64
                    * (
                        df["SQ_INSTS_VALU_ADD_F64"][idx]
                        + df["SQ_INSTS_VALU_MUL_F64"][idx]
                        + (2 * df["SQ_INSTS_VALU_FMA_F64"][idx])
                        + df["SQ_INSTS_VALU_TRANS_F64"][idx]
                    )
                )
                + (df["SQ_INSTS_VALU_MFMA_MOPS_F16"][idx] * 512)
                + (df["SQ_INSTS_VALU_MFMA_MOPS_BF16"][idx] * 512)
                + (df["SQ_INSTS_VALU_MFMA_MOPS_F32"][idx] * 512)
                + (df["SQ_INSTS_VALU_MFMA_MOPS_F64"][idx] * 512)
            )
            if "FP8" in supported_dt:
                total_flops += df["SQ_INSTS_VALU_MFMA_MOPS_F8"][idx] * 512
            if ("FP4" in supported_dt) or ("FP6" in supported_dt):
                total_flops += df["SQ_INSTS_VALU_MFMA_MOPS_F6F4"][idx] * 512
        except KeyError:
            console_debug(
                "roofline", f"{kernel_name[:35]}: Skipped total_flops at index {idx}"
            )
            pass
        try:
            valu_flops += (
                64
                * (
                    df["SQ_INSTS_VALU_ADD_F16"][idx]
                    + df["SQ_INSTS_VALU_MUL_F16"][idx]
                    + (2 * df["SQ_INSTS_VALU_FMA_F16"][idx])
                    + df["SQ_INSTS_VALU_TRANS_F16"][idx]
                )
                + 64
                * (
                    df["SQ_INSTS_VALU_ADD_F32"][idx]
                    + df["SQ_INSTS_VALU_MUL_F32"][idx]
                    + (2 * df["SQ_INSTS_VALU_FMA_F32"][idx])
                    + df["SQ_INSTS_VALU_TRANS_F32"][idx]
                )
                + 64
                * (
                    df["SQ_INSTS_VALU_ADD_F64"][idx]
                    + df["SQ_INSTS_VALU_MUL_F64"][idx]
                    + (2 * df["SQ_INSTS_VALU_FMA_F64"][idx])
                    + df["SQ_INSTS_VALU_TRANS_F64"][idx]
                )
            )
        except KeyError:
            console_debug(
                "roofline", f"{kernel_name[:35]}: Skipped valu_flops at index {idx}"
            )
            pass

        try:
            if "FP8" in supported_dt:
                mfma_flops_f8 += df["SQ_INSTS_VALU_MFMA_MOPS_F8"][idx] * 512
            if ("FP4" in supported_dt) or ("FP6" in supported_dt):
                mfma_flops_f6f4 += df["SQ_INSTS_VALU_MFMA_MOPS_F6F4"][idx] * 512
            mfma_flops_f16 += df["SQ_INSTS_VALU_MFMA_MOPS_F16"][idx] * 512
            mfma_flops_bf16 += df["SQ_INSTS_VALU_MFMA_MOPS_BF16"][idx] * 512
            mfma_flops_f32 += df["SQ_INSTS_VALU_MFMA_MOPS_F32"][idx] * 512
            mfma_flops_f64 += df["SQ_INSTS_VALU_MFMA_MOPS_F64"][idx] * 512
            mfma_iops_i8 += df["SQ_INSTS_VALU_MFMA_MOPS_I8"][idx] * 512
        except KeyError:
            console_debug(
                "roofline", f"{kernel_name[:35]}: Skipped mfma ops at index {idx}"
            )
            pass

        try:
            lds_data += (
                (df["SQ_LDS_IDX_ACTIVE"][idx] - df["SQ_LDS_BANK_CONFLICT"][idx])
                * 4
                * (mspec.lds_banks_per_cu)
            )
        except KeyError:
            console_debug(
                "roofline", f"{kernel_name[:35]}: Skipped lds_data at index {idx}"
            )
            pass

        try:
            L1cache_data += df["TCP_TOTAL_CACHE_ACCESSES_sum"][idx] * 64
        except KeyError:
            console_debug(
                "roofline", f"{kernel_name[:35]}: Skipped l1_cache_data at index {idx}"
            )
            pass

        try:
            L2cache_data += (
                df["TCP_TCC_WRITE_REQ_sum"][idx] * 64
                + df["TCP_TCC_ATOMIC_WITH_RET_REQ_sum"][idx] * 64
                + df["TCP_TCC_ATOMIC_WITHOUT_RET_REQ_sum"][idx] * 64
                + df["TCP_TCC_READ_REQ_sum"][idx] * 64
            )
        except KeyError:
            console_debug(
                "roofline", f"{kernel_name[:35]}: Skipped l2_cache_data at index {idx}"
            )
            pass
        try:
            if mspec.gpu_series == "MI200":
                hbm_data += (
                    (df["TCC_EA_RDREQ_32B_sum"][idx] * 32)
                    + (
                        (df["TCC_EA_RDREQ_sum"][idx] - df["TCC_EA_RDREQ_32B_sum"][idx])
                        * 64
                    )
                    + (df["TCC_EA_WRREQ_64B_sum"][idx] * 64)
                    + (
                        (df["TCC_EA_WRREQ_sum"][idx] - df["TCC_EA_WRREQ_64B_sum"][idx])
                        * 32
                    )
                )

            else:
                # Use TCC_BUBBLE_sum to calculate hbm_data
                hbm_data += (
                    (df["TCC_BUBBLE_sum"][idx] * 128)
                    + (df["TCC_EA0_RDREQ_32B_sum"][idx] * 32)
                    + (
                        (
                            df["TCC_EA0_RDREQ_sum"][idx]
                            - df["TCC_BUBBLE_sum"][idx]
                            - df["TCC_EA0_RDREQ_32B_sum"][idx]
                        )
                        * 64
                    )
                    + (
                        (
                            df["TCC_EA0_WRREQ_sum"][idx]
                            - df["TCC_EA0_WRREQ_64B_sum"][idx]
                        )
                        * 32
                    )
                    + (df["TCC_EA0_WRREQ_64B_sum"][idx] * 64)
                )
        except KeyError:
            console_debug(
                "roofline", f"{kernel_name[:35]}: Skipped hbm_data at index {idx}"
            )
            pass

        total_duration += df["End_Timestamp"][idx] - df["Start_Timestamp"][idx]
        avg_duration += df["End_Timestamp"][idx] - df["Start_Timestamp"][idx]

        calls += 1

        if sort_type == "kernels" and (at_end or (kernel_name != next_kernel_name)):
            ai_data_list.append(
                AI_Data(
                    str(kernel_name),
                    calls,
                    total_flops / calls,
                    valu_flops / calls,
                    mfma_flops_f6f4 / calls,
                    mfma_flops_f8 / calls,
                    mfma_flops_f16 / calls,
                    mfma_flops_bf16 / calls,
                    mfma_flops_f32 / calls,
                    mfma_flops_f64 / calls,
                    mfma_iops_i8 / calls,
                    lds_data / calls,
                    L1cache_data / calls,
                    L2cache_data / calls,
                    hbm_data / calls,
                    total_duration,
                    avg_duration / calls,
                )
            )
            console_debug(
                f"Just added {kernel_name} to AI_Data at index {idx}. # of calls: {calls}"
            )
            total_flops = valu_flops = mfma_flops_f6f4 = mfma_flops_f8 = (
                mfma_flops_bf16
            ) = mfma_flops_f16 = mfma_iops_i8 = mfma_flops_f32 = mfma_flops_f64 = (
                lds_data
            ) = L1cache_data = L2cache_data = hbm_data = calls = total_duration = (
                avg_duration
            ) = 0.0

        if sort_type == "dispatches":
            ai_data_list.append(
                AI_Data(
                    kernel_name,
                    calls,
                    total_flops,
                    valu_flops,
                    mfma_flops_f6f4,
                    mfma_flops_f8,
                    mfma_flops_f16,
                    mfma_flops_bf16,
                    mfma_flops_f32,
                    mfma_flops_f64,
                    mfma_iops_i8,
                    lds_data,
                    L1cache_data,
                    L2cache_data,
                    hbm_data,
                    total_duration,
                    avg_duration,
                )
            )
            total_flops = valu_flops = mfma_flops_f6f4 = mfma_flops_f8 = (
                mfma_flops_bf16
            ) = mfma_flops_f16 = mfma_iops_i8 = mfma_flops_f32 = mfma_flops_f64 = (
                lds_data
            ) = L1cache_data = L2cache_data = hbm_data = calls = total_duration = (
                avg_duration
            ) = 0.0

    ai_data_list.sort(key=lambda x: x.total_duration, reverse=True)

    intensities = {"ai_l1": [], "ai_l2": [], "ai_hbm": []}
    curr_perf = []
    kernel_names = []

    i = 0
    # Create list of top 5 intensities
    while i < 10 and i != len(ai_data_list):
        ai_data = ai_data_list[i]

        if ai_data.total_flops == 0:
            console_debug(
                f"No flops counted for {ai_data.kernel_name}, "
                "arithmetic intensities will not display on plots."
            )

        kernel_names.append(ai_data.kernel_name)

        ai_l1_val = (
            ai_data.total_flops / ai_data.L1cache_data if ai_data.L1cache_data else 0
        )
        intensities["ai_l1"].append(ai_l1_val)

        ai_l2_val = (
            ai_data.total_flops / ai_data.L2cache_data if ai_data.L2cache_data else 0
        )
        intensities["ai_l2"].append(ai_l2_val)

        ai_hbm_val = ai_data.total_flops / ai_data.hbm_data if ai_data.hbm_data else 0
        intensities["ai_hbm"].append(ai_hbm_val)

        perf_val = (
            ai_data.total_flops / ai_data.avg_duration if ai_data.avg_duration else 0
        )
        curr_perf.append(perf_val)

        i += 1

    intensity_points: dict[str, Any] = {"ai_l1": [], "ai_l2": [], "ai_hbm": []}

    for i in intensities:
        values = intensities[i]

        color = get_color(i)  # noqa
        x: list[float] = []
        y: list[float] = []

        for entry_idx in range(len(values)):
            x.append(values[entry_idx])
            y.append(curr_perf[entry_idx])

        intensity_points[i].append(x)
        intensity_points[i].append(y)

    # Add an entry for kernel names
    intensity_points["kernel_names"] = kernel_names

    return intensity_points


def construct_roof(roofline_parameters: dict[str, Any], dtype: str) -> dict[str, Any]:
    workload_dir = roofline_parameters.get("workload_dir")
    if isinstance(workload_dir, list):
        base_dir = str(
            workload_dir[0][0]
            if isinstance(workload_dir[0], (list, tuple))
            else workload_dir[0]
        )
    else:
        base_dir = str(workload_dir)

    benchmark_results = str(Path(base_dir) / "roofline.csv")

    # -----------------------------------------------------
    # Initialize roofline data dictionary from roofline.csv
    # -----------------------------------------------------
    # TODO: consider changing this to an ordered dict for consistency over py versions
    benchmark_data: dict[str, list[str]] = {}
    headers: list[str] = []

    try:
        with open(benchmark_results, "r") as csvfile:
            csvReader = csv.reader(csvfile, delimiter=",")
            rowCount = 0
            for row in csvReader:
                row.pop(0)  # remove devID
                if rowCount == 0:
                    headers = row
                    for header in headers:
                        benchmark_data[header] = []
                else:
                    for i, key in enumerate(headers):
                        benchmark_data[key].append(row[i])

                rowCount += 1
    except Exception:
        graph_points: dict[str, Any] = {
            "hbm": [None, None, None],
            "l2": [None, None, None],
            "l1": [None, None, None],
            "lds": [None, None, None],
            "valu": [None, None, None],
            "mfma": [None, None, None],
        }
        return graph_points

    # ------------------
    #  Generate Roofline
    # ------------------
    results = calc_ceilings(roofline_parameters, dtype, benchmark_data)

    return results
