name: Sync amd-staging to public repository

on:
  push:
    branches: [ amd-staging ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: zent-contrib/git-branch-sync-action@v1.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-branch: amd-staging
          destination-repo: "git@github.com:ROCm/rocprofiler-register.git"
