name: Sync amd-mainline to public repository

on:
  push:
    branches: [ amd-mainline ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: zent-contrib/git-branch-sync-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-branch: amd-mainline
          destination-repo: "git@github.com:ROCm/rocprofiler-register.git"
