version: 2
updates:

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "projects/hipcub/docs/sphinx" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "documentation"
      - "dependencies"
      - "ci:docs-only"
    reviewers:
      - "samjwu"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "projects/rocprim/docs/sphinx" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "documentation"
      - "dependencies"
      - "ci:docs-only"
    reviewers:
      - "samjwu"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "projects/rocrand/docs/sphinx" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "documentation"
      - "dependencies"
      - "ci:docs-only"
    reviewers:
      - "samjwu"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "projects/rocthrust/docs/sphinx" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    labels:
      - "documentation"
      - "dependencies"
      - "ci:docs-only"
    reviewers:
      - "samjwu"
