rocprofiler-compute:
  - 'projects/rocprofiler-compute/**'
  - '!projects/rocprofiler-compute/**/*.md'
  - '!projects/rocprofiler-compute/**/*.rtf'
  - '!projects/rocprofiler-compute/**/*.rst'
  #- '.github/workflows/rocprofiler-compute-formatting.yml'
rocprofiler-sdk:
  - 'projects/rocprofiler-sdk/**'
  - '!projects/rocprofiler-sdk/**/*.md'
  - '!projects/rocprofiler-sdk/**/*.rtf'
  - '!projects/rocprofiler-sdk/**/*.rst'
  - '.github/workflows/rocprofiler-sdk-formatting.yml'
rocprofiler-systems:
  - 'projects/rocprofiler-systems/**'
  - '!projects/rocprofiler-systems/**/*.md'
  - '!projects/rocprofiler-systems/**/*.rtf'
  - '!projects/rocprofiler-systems/**/*.rst'
  #- '.github/workflows/rocprofiler-systems-formatting.yml'
