## base docker image
ARG ROCM_IMAGE_NAME=rocm/dev-ubuntu-24.04
ARG ROCM_IMAGE_TAG=latest
FROM "${ROCM_IMAGE_NAME}:${ROCM_IMAGE_TAG}"

## creating scratch space
ENV WORKDIR /workspace
RUN mkdir -p ${WORKDIR}
WORKDIR ${WORKDIR}
ENV SRC /src
RUN mkdir -p ${SRC}

## install dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential autoconf libtool flex bison pkg-config cmake git wget curl ca-certificates \
    libibverbs-dev ibverbs-utils libibumad-dev libpci-dev librdmacm-dev rdma-core infiniband-diags \
    ca-certificates \
    git \
    make \
    rocm-cmake \
    ninja-build \
    gfortran \
    build-essential \
    libomp5 \
    libomp-dev \
    libbfd-dev \
    libboost-all-dev \
    libnuma1 \
    libnuma-dev \
    libpthread-stubs0-dev \
    libzstd-dev \
    lcov \
    zip \
    zlib1g-dev \
    wget \
    pkg-config \
    unzip \
    chrpath \
    doxygen \
    lshw \
    build-essential \
    libssl-dev \
    curl \
    libncursesw5-dev \
    xz-utils \
    liblzma-dev \
    python3-pip \
    python3-setuptools \
    python3-venv \
    python3-dev \
    python3-tk \
    python3-yaml \
    vim \
    less \
    openmpi-bin openmpi-common libopenmpi-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

## Not needed on Ubuntu 24, probably needed on Ubuntu22
#RUN wget https://github.com/Kitware/CMake/releases/download/v3.28.0/cmake-3.28.0-linux-x86_64.sh \
#    && chmod +x cmake-3.28.0-linux-x86_64.sh \
#    && bash ./cmake-3.28.0-linux-x86_64.sh --prefix=/usr --exclude-subdir --skip-license \
#    && rm cmake-3.28.0-linux-x86_64.sh

## Set ROCm path
ENV ROCM_PATH=/opt/rocm

# We use MPI only as a launcher, any MPI will do, use system install
## Install UCX
#ENV UCX_INSTALL_PREFIX=/opt/ucx
#RUN wget https://github.com/openucx/ucx/releases/download/v1.16.0/ucx-1.16.0.tar.gz \
#    && mkdir -p ucx \
#    && tar -zxf ucx-1.16.0.tar.gz -C ucx --strip-components=1 \
#    && cd ucx \
#    && mkdir build \
#    && cd build \
#    && ../configure --prefix=${UCX_INSTALL_PREFIX} --with-rocm=${ROCM_PATH} \
#    && make -j16 install \
#    && cd ../.. \
#    && rm -rf ucx ucx-1.16.0.tar.gz

## Install OpenMPI
#ENV MPI_INSTALL_PREFIX=/opt/ompi
#RUN wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.6.tar.gz \
#    && mkdir -p ompi4 \
#    && tar -zxf openmpi-4.1.6.tar.gz -C ompi4 --strip-components=1 \
#    && cd ompi4 \
#    && mkdir build \
#    && cd build \
#    && ../configure --prefix=${MPI_INSTALL_PREFIX} --with-ucx=${UCX_INSTALL_PREFIX} --disable-oshmem --disable-mpi-fortran --enable-orterun-prefix-by-default \
#    && make -j16 install \
#    && cd ../.. \
#    && rm -rf ompi4 openmpi-4.1.6.tar.gz
#ENV PATH="${MPI_INSTALL_PREFIX}/bin:${PATH}"

# OPTIONAL: Install rocm-enabled IB perftest (used to validate if network config is sane)
# The following block is OPTIONAL and can be commented out if you only want to run rocSHMEM
RUN git clone https://github.com/ROCm/rdma-perftest
RUN cd rdma-perftest \
 && ./autogen.sh \
 && ./configure --enable-rocm --with-rocm=/opt/rocm \
 && make -j 8 #install

## rccl repo
ARG ROCM_REPO=https://github.com/ROCm/rocm-systems.git

## AMD GPU Targets
ARG GPU_TARGETS=gfx950

## building rocSHMEM
ARG ROCSHMEM_BRANCH=users/abouteiller/gin-stage1
ENV ROCSHMEM_INSTALL_DIR=${WORKDIR}/rocshmem
RUN git clone --no-checkout --filter=blob:none ${ROCM_REPO} ${WORKDIR}/rocshmem/src && cd ${WORKDIR}/rocshmem/src \
 && git sparse-checkout set --cone projects/rocshmem \
 && git checkout ${ROCSHMEM_BRANCH}
RUN cd rocshmem/src/projects/rocshmem \
 && mkdir -p build && cd build \
 && ../scripts/build_configs/all_backends \
#      -DBUILD_DEBUG_TRACE_DEVICE=ON -DBUILD_DEBUG_DEVICE=ON -DBUILD_DEBUG_TRACE_HOST=ON \
      -DMPI_ROOT=${MPI_INSTALL_DIR} \
      -DUSE_EXTERNAL_MPI=OFF \
      -DGPU_TARGETS=${GPU_TARGETS} \
      -DCMAKE_INSTALL_PREFIX=${ROCSHMEM_INSTALL_DIR} \
      -DUSE_IPC=ON -DUSE_SDMA=ON

## building RCCL
ARG RCCL_BRANCH=users/prasanna-amd/nccl-sync-v2-28-9-gin-rebased-0501
ENV RCCL_INSTALL_PREFIX=${WORKDIR}/rccl
ENV ONLY_FUNCS="SendRecv|AlltoAllPivot|AlltoAllGda|AlltoAllvGda"
RUN git clone --no-checkout --filter=blob:none "${ROCM_REPO}" ${WORKDIR}/rccl/src/ && cd ${WORKDIR}/rccl/src \
 && git sparse-checkout set --cone projects/rccl \
 && git checkout ${RCCL_BRANCH}
# patch for SDMA enablement
RUN cd rccl/src/projects/rccl \
 && sed -i \
       -e '/target_link_libraries(rccl PRIVATE \${ROCSHMEM_LIBRARY})/i\  find_package(hsakmt REQUIRED PATHS /opt/rocm)' \
       -e '/target_link_libraries(rccl PRIVATE \${ROCSHMEM_LIBRARY})/i\  target_link_libraries(rccl PRIVATE hsakmt::hsakmt)' \
       src/CMakeLists.txt \
 && sed -i \
       's/if (comm->enableRocshmem && comm->nNodes > 1 && (comm->nRanks\/comm->nNodes == 8) && comm->rocshmemThreshold <= 1048576)/if (comm->enableRocshmem)/' \
       src/rccl_wrap.cc
RUN cd rccl/src/projects/rccl \
 && ./install.sh --amdgpu_targets=${GPU_TARGETS} --prefix=${RCCL_INSTALL_PREFIX} --rocshmem --no-device-linker

## building RCCL-Tests
RUN cd rccl/src/ \
 && git sparse-checkout add --cone projects/rccl-tests \
 && git checkout ${RCCL_BRANCH}
RUN mkdir rccl-tests \
    && cd rccl-tests \
    && cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MPI=ON -DCMAKE_PREFIX_PATH="${RCCL_INSTALL_PREFIX};${MPI_INSTALL_PREFIX}" -DGPU_TARGETS=${GPU_TARGETS} ${WORKDIR}/rccl/src/projects/rccl-tests \
    && make -j16 ENABLE_DEVICE_API=1

## set environment variables
ENV PATH="${MPI_INSTALL_PREFIX}/bin:${ROCM_PATH}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${RCCL_INSTALL_PREFIX}/lib:${MPI_INSTALL_PREFIX}/lib:${ROCM_PATH}/lib:${LD_LIBRARY_PATH}"
ENV UCX_WARN_UNUSED_ENV_VARS=n
ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
ENV NCL_DEBUG=VERSION
ENV ROCSHMEM_DEBUG_LEVEL=info:noversion
ENV ROCSHMEM_TEST_UUID=1

