name: Documentation 2.x

on:
  push:
    branches: ["2.x"]
    paths:
      - 'src/docs-2.x'
      - 'src/docs-1.x'
      - '.github/workflows/docs-2.x.yml'
      - 'VERSION'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    container:
       image: sphinxdoc/sphinx

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Additional python packages
        run: pip3 install -r requirements-doc.txt
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build 1.x docs
        run: |
          cd src/docs-1.x
          make html	
      - name: Build 2.x docs
        run: |
          cd src/docs-2.x
          make html
      - name: Relocate 2.x docs
        run: |
          mv src/docs-2.x/_build/html src/docs-1.x/_build/html/2.x
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/docs-1.x/_build/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

