name: Documentation

on:
  push:
    branches: ["docpub"]
    paths:
      - 'src/docs'
      - '.github/workflows/docs-2.x.yml'
      - 'VERSION'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    container:
       image: sphinxdoc/sphinx

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Additional python packages
        run: pip3 install -r requirements-doc.txt
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build html
        run: |
          cd src/docs
          make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./src/docs/_build/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/2.x
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

