#!/bin/bash -e

###############################################################################
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT
###############################################################################

amd_gpu_shaders="$1"

if ! command -v xxd >/dev/null
then
    echo "xxd not found!"
    exit 1
fi

# Create the file in a temporary location and then move it in atomically
{
cat <<EOF
//==============================================================================
//  This file is automatically generated during build process, don't modify it
//==============================================================================

namespace rocr {
namespace AMD {

EOF

shift
for file in "$@"
do
xxd -i $file
    echo -e '\n'
done

cat <<EOF
} // namespace AMD
} // namespace rocr

EOF

} > "$amd_gpu_shaders"

