{
 "title": "RCCL Inspector Job Performance",
 "description": "RCCL Inspector Prometheus dashboard for one or many clusters (Alola, smci, …). Panels query nccl_* metrics from librccl-profiler-inspector.so.\n\nRequired labels: cluster, slurm_job_id, n_nodes, nranks, message_size, plus collective/algo_proto or p2p_operation. Intra-node panels use n_nodes=\"1\" (xGMI); network panels use n_nodes!=\"1\".\n\ncluster comes from NCCL_INSPECTOR_CLUSTER or SLURM_CLUSTER_NAME (else unknown). Set prom_datasource, then Cluster, then Job ID. P2P rows need NCCL_INSPECTOR_ENABLE_P2P=1.",
 "tags": [
  "rccl-inspector",
  "template"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom_datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"nccl_bus_bandwidth_gbs|nccl_p2p_bus_bandwidth_gbs\"}, cluster)"
    }
   },
   {
    "name": "jobid",
    "label": "Job ID",
    "query": {
     "query": "label_values({__name__=~\"nccl_bus_bandwidth_gbs|nccl_p2p_bus_bandwidth_gbs\", cluster=~\"$cluster\"}, slurm_job_id)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({__name__=~\"nccl_bus_bandwidth_gbs|nccl_p2p_bus_bandwidth_gbs\", cluster=~\"$cluster\", slurm_job_id=~\"$jobid\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RCCL Inspector - P2P [Recv]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BusBw (GBs) intra-node (xGMI) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(message_size, nranks) (nccl_p2p_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", p2p_operation=\"Recv\", n_nodes=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exec Time (us) intra-node (xGMI) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by(message_size, nranks) (nccl_p2p_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", p2p_operation=\"Recv\", n_nodes=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BusBw (GBs) NET Only ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by(message_size, nranks, n_nodes) (nccl_p2p_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", p2p_operation=\"Recv\", n_nodes!=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exec Time (us) NET Only ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg by(message_size, nranks, n_nodes) (nccl_p2p_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", p2p_operation=\"Recv\", n_nodes!=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RCCL Inspector - P2P [Send]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "BusBw (GBs) intra-node (xGMI) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks) (nccl_p2p_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", p2p_operation=\"Send\", n_nodes=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exec Time (us) intra-node (xGMI) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks) (nccl_p2p_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", p2p_operation=\"Send\", n_nodes=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BusBw (GBs) NET Only ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks, n_nodes) (nccl_p2p_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", p2p_operation=\"Send\", n_nodes!=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exec Time (us) intra-node (xGMI) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks, n_nodes) (nccl_p2p_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", p2p_operation=\"Send\", n_nodes!=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "RCCL Inspector - ReduceScatter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "BusBw (GBs) intra-node (xGMI) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg by(message_size, nranks) (nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"ReduceScatter\", n_nodes=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exec Time (us) intra-node (xGMI) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "avg by(message_size, nranks) (nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"ReduceScatter\", n_nodes=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BusBw (GBs) NET Only ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg by(message_size, nranks, n_nodes) (nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"ReduceScatter\", n_nodes!=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exec Time (us) NET Only ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg by(message_size, nranks, n_nodes) (nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"ReduceScatter\", n_nodes!=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RCCL Inspector - AllReduce",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "BusBw (GBs) intra-node (xGMI) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 884 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks) (nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"AllReduce\", n_nodes=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exec Time (us) intra-node (xGMI) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 884 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks) (nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"AllReduce\", n_nodes=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BusBw (GBs) NET Only ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 892 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks, n_nodes) (nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"AllReduce\", n_nodes!=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exec Time (us) NET Only ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 892 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks, n_nodes) (nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"AllReduce\", n_nodes!=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RCCL Inspector - AllGather",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "BusBw (GBs) intra-node (xGMI) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 725 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks) (nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"AllGather\", n_nodes=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exec Time (us) intra-node (xGMI) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 725 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks) (nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"AllGather\", n_nodes=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BusBw (GBs) NET Only ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 733 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks, n_nodes) (nccl_bus_bandwidth_gbs{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"AllGather\", n_nodes!=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exec Time (us) NET Only ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 733 },
     "targets": [
      {
       "expr": "avg by(message_size, nranks, n_nodes) (nccl_collective_exec_time_microseconds{cluster=~\"$cluster\", slurm_job_id=~\"$jobid\", collective=\"AllGather\", n_nodes!=\"1\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}