{
 "title": "ROCm Data Center tool V1.0",
 "description": "Dashboard to monitor AMD GPUs using RDC",
 "tags": [ "IB" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Host", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Average GPU Package Power (Watt)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=\"0\"}",
     "legendFormat": "{{short_instance}}:gpu0"
    },
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=\"1\"}",
     "legendFormat": "{{short_instance}}:gpu1"
    },
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=\"2\"}",
     "legendFormat": "{{short_instance}}:gpu2"
    },
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=\"3\"}",
     "legendFormat": "{{short_instance}}:gpu3"
    },
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=\"4\"}",
     "legendFormat": "{{short_instance}}:gpu4"
    },
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=\"5\"}",
     "legendFormat": "{{short_instance}}:gpu5"
    },
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=\"6\"}",
     "legendFormat": "{{short_instance}}:gpu6"
    },
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=\"7\"}",
     "legendFormat": "{{short_instance}}:gpu7"
    }
   ]
  },
  {
   "title": "GPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=\"1\"}",
     "legendFormat": "{{short_instance}}:gpu1"
    },
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=\"2\"}",
     "legendFormat": "{{short_instance}}:gpu2"
    },
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=\"3\"}",
     "legendFormat": "{{short_instance}}:gpu3"
    },
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=\"4\"}",
     "legendFormat": "{{short_instance}}:gpu4"
    },
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=\"5\"}",
     "legendFormat": "{{short_instance}}:gpu5"
    },
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=\"6\"}",
     "legendFormat": "{{short_instance}}:gpu6"
    },
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=\"7\"}",
     "legendFormat": "{{short_instance}}:gpu7"
    },
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=\"0\"}",
     "legendFormat": "{{short_instance}}:gpu0"
    }
   ]
  },
  {
   "title": "GPU Clock Speed (MHz)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=\"1\"}",
     "legendFormat": "{{short_instance}}:gpu1"
    },
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=\"2\"}",
     "legendFormat": "{{short_instance}}:gpu2"
    },
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=\"3\"}",
     "legendFormat": "{{short_instance}}:gpu3"
    },
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=\"4\"}",
     "legendFormat": "{{short_instance}}:gpu4"
    },
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=\"5\"}",
     "legendFormat": "{{short_instance}}:gpu5"
    },
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=\"6\"}",
     "legendFormat": "{{short_instance}}:gpu6"
    },
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=\"7\"}",
     "legendFormat": "{{short_instance}}:gpu7"
    },
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=\"0\"}",
     "legendFormat": "{{short_instance}}:gpu0"
    }
   ]
  },
  {
   "title": "GPU Temperature (Celsius)",
   "type": "graph",
   "description": "The GPU temperature in degree",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=\"0\"}",
     "legendFormat": "{{short_instance}}:gpu0  - Allocated"
    },
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=\"7\"}",
     "legendFormat": "{{short_instance}}:gpu7  - Allocated"
    },
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=\"6\"}",
     "legendFormat": "{{short_instance}}:gpu6  - Allocated"
    },
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=\"5\"}",
     "legendFormat": "{{short_instance}}:gpu5  - Allocated"
    },
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=\"4\"}",
     "legendFormat": "{{short_instance}}:gpu4  - Allocated"
    },
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=\"3\"}",
     "legendFormat": "{{short_instance}}:gpu3  - Allocated"
    },
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=\"2\"}",
     "legendFormat": "{{short_instance}}:gpu2  - Allocated"
    },
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=\"1\"}",
     "legendFormat": "{{short_instance}}:gpu1  - Allocated"
    }
   ]
  },
  {
   "title": "GPU Memory Allocation (GB)",
   "type": "graph",
   "description": "the amount of total available and allocated VRAM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"0\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu0  - Allocated"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"7\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu7  - Allocated"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"6\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu6  - Allocated"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"5\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu5  - Allocated"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"4\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu4  - Allocated"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"3\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu3  - Allocated"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"2\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu2  - Allocated"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"1\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu1  - Allocated"
    }
   ]
  },
  {
   "title": "GPU Memory Activity Level (%)",
   "type": "graph",
   "description": "indicate how busy the respective mem blocks are",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"1\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=\"1\"}",
     "legendFormat": "{{short_instance}}:gpu1"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"2\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=\"2\"}",
     "legendFormat": "{{short_instance}}:gpu2"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"3\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=\"3\"}",
     "legendFormat": "{{short_instance}}:gpu3"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"4\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=\"4\"}",
     "legendFormat": "{{short_instance}}:gpu4"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"5\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=\"5\"}",
     "legendFormat": "{{short_instance}}:gpu5"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"6\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=\"6\"}",
     "legendFormat": "{{short_instance}}:gpu6"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"7\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=\"7\"}",
     "legendFormat": "{{short_instance}}:gpu7"
    },
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=\"0\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=\"0\"}",
     "legendFormat": "{{short_instance}}:gpu0"
    }
   ]
  }
 ]
}