/* AUTO-GENERATED by lttng_curated_codegen.py from curated_apis.yaml.
 * DO NOT EDIT BY HAND. SHA256(curated_apis.yaml) at generation: 0f2e1452d4da6a69b49b3845940d40ad5ed4db2273dc26d002291c5372a64250
 *
 * Per-API typed emit helpers for curated parameter capture. See spec §5.2.
 *
 * Helper signature invariant (spec §6.2): every helper takes
 *   (uint64_t corr_id, <captured-args...>, <status_type> status)
 * — status is the call's success status, used to gate OUT-param deref.
 * All-IN APIs accept it but mark it unused.
 */
#ifndef ROCM_HIP_TRACE_EMIT_CURATED_H_
#define ROCM_HIP_TRACE_EMIT_CURATED_H_

#include <stdint.h>
#include <stddef.h>
#include "rocm_trace_tid.h"

#if defined(HIP_ENABLE_LTTNG_UST) && HIP_ENABLE_LTTNG_UST

#include <atomic>
#include "rocm_hip_curated_tp.h"

extern std::atomic<bool> rocm_hip_trace_g_disabled;
#ifndef ROCM_TRACE_DISABLED_DEFINED
#define ROCM_TRACE_DISABLED_DEFINED
static inline bool rocm_trace_disabled(void) {
    return rocm_hip_trace_g_disabled.load(std::memory_order_relaxed);
}
#endif

        static inline void rocm_trace_emit_hipMemcpyAsync_args(
            uint64_t corr_id,
    const void* dst,
    const void* src,
    size_t sizeBytes,
    int32_t kind,
    uint64_t stream,
    hipError_t /*status*/ /* unused: all-IN API */) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hip, hipMemcpyAsync_args)) {
            lttng_ust_do_tracepoint(rocm_hip, hipMemcpyAsync_args, corr_id,
(uint64_t)(uintptr_t)(dst),
(uint64_t)(uintptr_t)(src),
(uint64_t)(sizeBytes),
(int32_t)(kind),
(uint64_t)(uintptr_t)(stream));
            }
        }

        static inline void rocm_trace_emit_hipMalloc_args(
            uint64_t corr_id,
    void ** ptr_out_ptr,
    size_t size,
    hipError_t status) {
            if (rocm_trace_disabled()) return;
            if (lttng_ust_tracepoint_enabled(rocm_hip, hipMalloc_args)) {
        const uint64_t ptr_val =
    (status == hipSuccess && ptr_out_ptr != NULL)
        ? (uint64_t)((uint64_t)(uintptr_t)(*ptr_out_ptr)) : 0ULL;
    lttng_ust_do_tracepoint(rocm_hip, hipMalloc_args, corr_id,
ptr_val,
(uint64_t)(size));
            }
        }

    static inline void rocm_trace_emit_hipDeviceSynchronize_args(
        uint64_t corr_id,
hipError_t /*status*/ /* unused: all-IN API */) {
        if (rocm_trace_disabled()) return;
        if (lttng_ust_tracepoint_enabled(rocm_hip, hipDeviceSynchronize_args)) {
    lttng_ust_do_tracepoint(rocm_hip, hipDeviceSynchronize_args, corr_id);
        }
    }


#else  /* HIP_ENABLE_LTTNG_UST not defined — all helpers are no-ops */

static inline void rocm_trace_emit_hipMemcpyAsync_args(uint64_t, const void*, const void*, size_t, int32_t, uint64_t, hipError_t) {}
static inline void rocm_trace_emit_hipMalloc_args(uint64_t, void **, size_t, hipError_t) {}
static inline void rocm_trace_emit_hipDeviceSynchronize_args(uint64_t, hipError_t) {}

#endif  /* HIP_ENABLE_LTTNG_UST */

#endif  /* ROCM_HIP_TRACE_EMIT_CURATED_H_ */
