/* AUTO-GENERATED by lttng_curated_codegen.py from curated_apis.yaml.
 * Do not edit by hand — regenerate instead (see command below).
 *
 * SHA256(curated_apis.yaml) at generation:
 * 3441b03b601e5cc2b105de3b19b7178c892d218019252621bd89ff249f3b94c1
 *
 * Per-API typed emit helpers for curated parameter capture. Every
 * helper takes (<captured-args...>, <status_type> status); status is
 * the call's success result, used to gate OUT-param deref. All-IN
 * APIs accept it but mark it unused.
 *
 * Regenerate with:
 *   python3 shared/lttng/scripts/lttng_curated_codegen.py \
 *       --provider hip \
 *       --yaml projects/clr/hipamd/scripts/curated_apis.yaml \
 *       --header projects/hip/include/hip/hip_runtime_api.h \
 *       --header projects/hip/include/hip/hip_ext.h \
 *       --source projects/clr/hipamd/src/hip_table_interface.cpp \
 *       --source projects/clr/hipamd/src/hip_table_interface_c.cpp \
 *       --source projects/clr/hipamd/src/hip_error.cpp \
 *       --source projects/clr/hipamd/src/profiler/hip_clr_profiler.cpp \
 *       --extra-arg=-D__HIP_PLATFORM_AMD__=1 \
 *       --extra-arg=-Iprojects/hip/include \
 *       --extra-arg=-Iprojects/clr/hipamd/src \
 *       --extra-arg=-Iprojects/clr/hipamd/include \
 *       --extra-arg=-Iprojects/clr/rocclr \
 *       --extra-arg=-Iprojects/rocr-runtime/runtime/hsa-runtime/inc \
 *       --tp-out projects/clr/hipamd/src/lttng/rocm_hip_curated_tp.h \
 *       --emit-out projects/clr/hipamd/src/lttng/rocm_trace_emit_curated.h
 */
#ifndef ROCM_HIP_TRACE_EMIT_CURATED_H_
#define ROCM_HIP_TRACE_EMIT_CURATED_H_

#include <stdint.h>
#include <stddef.h>
/* Force the AMD platform define so the host-only HIP runtime header is
 * self-contained. rocclr internal TUs that pull in rocm_trace_emit.h
 * (e.g. device/rocm/rocvirtual.cpp) don't set this themselves. This
 * file is built only into libamdhip64; there is no NVIDIA path. */
#ifndef __HIP_PLATFORM_AMD__
#define __HIP_PLATFORM_AMD__ 1
#endif
#include <hip/hip_runtime_api.h>

#if defined(HIP_ENABLE_LTTNG_UST) && HIP_ENABLE_LTTNG_UST

#include <atomic>
#include "rocm_hip_curated_tp.h"

extern std::atomic<bool> rocm_hip_trace_g_disabled;
#ifndef ROCM_TRACE_DISABLED_DEFINED
#define ROCM_TRACE_DISABLED_DEFINED
static inline bool rocm_trace_disabled(void) {
  return rocm_hip_trace_g_disabled.load(std::memory_order_relaxed);
}
#endif


#else /* HIP_ENABLE_LTTNG_UST not defined — all helpers are no-ops */


#endif /* HIP_ENABLE_LTTNG_UST */

#endif /* ROCM_HIP_TRACE_EMIT_CURATED_H_ */
