[tool.black]
line-length = 90
target-version = ['py38', 'py39']
include = '\.py$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.github
    | \.tox
    | \.venv
    | \.misc
    | \.vscode
    | \.pyc
    | dist
    | external
    | .pytest_cache
    | build
    | build-omniperf
  )/
)
'''
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

pythonpath = [
      ".",
      "src",
      "src/omniperf_soc",
      "src/utils",
      "src/omniperf_analyze/utils",
      "tests"
    ]

markers = [
	"kernel_execution",
	"ipblocks",
	"misc",
	"mem",
	"sort",
	"join",
	"verbosity",
	"dispatch",
]
