#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
"""Generate and apply contract-test case renames.

The target naming convention is:

  Contract_<DomainPascal>_<Subject>_<Scenario>_<ExpectedOutcome>

The tool is deliberately map-driven: generate a TSV, review/edit it, validate it,
then apply it. It only rewrites source files named by the map plus contract.yaml;
TEST_PLAN.md is regenerated by gen_test_plan.py after apply.
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

_THIS_DIR = Path(__file__).resolve().parent
CATCH_DIR = _THIS_DIR.parent
HIP_TESTS_DIR = CATCH_DIR.parent
CONTRACT_YAML = CATCH_DIR / "config" / "configs" / "contract.yaml"
DEFAULT_MAP = _THIS_DIR / "contract_case_rename_map.tsv"

sys.path.insert(0, str(_THIS_DIR))
import gen_test_plan  # noqa: E402

CASE_SHAPE_RE = re.compile(r"^Contract_[A-Za-z0-9]+(_[A-Za-z0-9]+){3}$")
CASE_TOKEN_RE = re.compile(r"\bContract_[A-Za-z0-9_]+\b")
YAML_KEY_RE = re.compile(r"^  (Contract_[A-Za-z0-9_]+):\s*$")


def _split_words(token: str) -> list[str]:
    # Handles CamelCase words, digit runs (Memcpy2D), and all-caps clusters.
    return re.findall(r"[A-Z]+(?=[A-Z][a-z]|\d|$)|[A-Z]?[a-z]+|\d+", token)


def _pascal_token(text: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", text)
    return "".join(w[:1].upper() + w[1:] for w in words)


def _pascal_from_api(api: str) -> str:
    # API field can be an API family or comma-separated string; keep the first API-ish token.
    m = re.search(r"hip[A-Za-z0-9_]*", api)
    if not m:
        return _pascal_token(api) or "Api"
    api_name = m.group(0)
    return "Hip" + _pascal_token(api_name[3:])


def _api_stem(api_subject: str) -> str:
    return api_subject[3:] if api_subject.startswith("Hip") else api_subject


def _strip_api_prefix(scenario: str, subject: str) -> str:
    stem = _api_stem(subject)
    if scenario == stem:
        return "Default"
    for candidate in (subject, stem):
        if candidate and scenario.startswith(candidate) and len(scenario) > len(candidate):
            rest = scenario[len(candidate):]
            if rest:
                return rest
    return scenario or "Default"


def _propose_name(case: str, api: str) -> tuple[str, str]:
    parts = case.split("_")
    if len(parts) < 3 or parts[0] != "Contract":
        return case, "NEEDS_REVIEW:unexpected_shape"

    domain = parts[1]
    tail = parts[2:]
    subject = _pascal_from_api(api)

    flags: list[str] = []
    if len(tail) >= 2:
        outcome = tail[-1]
        scenario = "_".join(tail[:-1])
    else:
        outcome = tail[0] if tail else "Behavior"
        scenario = "Default"
        flags.append("REVIEW:single_tail_token")

    # Remove the old API-ish prefix when the old scenario bundled subject+scenario.
    scenario_joined = "".join(scenario.split("_"))
    scenario_joined = _strip_api_prefix(scenario_joined, subject)

    # Scenario must be one Pascal token in the five-field convention; collapse any
    # old multi-token scenario into a single token after stripping an API prefix.
    scenario_tokens = scenario.split("_") if scenario != "Default" else ["Default"]
    if scenario_tokens:
        scenario_tokens[0] = _strip_api_prefix(scenario_tokens[0], subject)
        scenario_tokens = [t for t in scenario_tokens if t and t != subject and t != _api_stem(subject)]
    scenario = _pascal_token("".join(scenario_tokens)) or _pascal_token(scenario_joined) or "Default"
    outcome = _pascal_token(outcome) or "Outcome"
    proposed = f"Contract_{domain}_{subject}_{scenario}_{outcome}"
    if proposed == case:
        flags.append("IDENTITY")
    return proposed, ";".join(flags)


@dataclass(frozen=True)
class Row:
    current_name: str
    proposed_name: str
    domain_dir: str
    file: str
    api: str
    invariant: str
    flags: str


def _contract_cases() -> list[dict[str, object]]:
    return [c for c in gen_test_plan.collect_cases(["contract"])]


def _yaml_keys() -> list[str]:
    keys: list[str] = []
    for line in CONTRACT_YAML.read_text().splitlines():
        m = YAML_KEY_RE.match(line)
        if m:
            keys.append(m.group(1))
    return keys


def emit_map(path: Path) -> None:
    rows: list[Row] = []
    for case in _contract_cases():
        current = str(case["case"])
        proposed, flags = _propose_name(current, str(case["api"]))
        rows.append(
            Row(
                current_name=current,
                proposed_name=proposed,
                domain_dir=str(case["domain"]),
                file=str(case["file"]),
                api=str(case["api"]),
                invariant=str(case["invariant"]),
                flags=flags,
            )
        )
    with path.open("w", newline="") as f:
        writer = csv.writer(f, delimiter="\t", lineterminator="\n")
        writer.writerow(["current_name", "proposed_name", "domain_dir", "file", "api", "invariant", "flags"])
        for row in rows:
            writer.writerow([row.current_name, row.proposed_name, row.domain_dir, row.file,
                             row.api, row.invariant, row.flags])
    print(f"Wrote {path} ({len(rows)} rows).")


def read_map(path: Path) -> list[Row]:
    with path.open(newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        return [Row(**{k: (v or "") for k, v in row.items()}) for row in reader]


def check_map(path: Path) -> tuple[list[Row], int]:
    rows = read_map(path)
    errors: list[str] = []
    current_source = [str(c["case"]) for c in _contract_cases()]
    source_set = set(current_source)
    yaml_set = set(_yaml_keys())

    current_names = [r.current_name for r in rows]
    proposed_names = [r.proposed_name for r in rows]

    if len(rows) != len(current_source):
        errors.append(f"map row count {len(rows)} != source case count {len(current_source)}")
    if set(current_names) != source_set:
        errors.append("map current_name set does not match source case set")
    if source_set != yaml_set:
        errors.append("source case set does not match contract.yaml keys before rename")
    for name in sorted(set(current_names) - source_set):
        errors.append(f"unknown current_name in map: {name}")
    for name in sorted(source_set - set(current_names))[:20]:
        errors.append(f"missing current_name in map: {name}")

    seen: dict[str, str] = {}
    for row in rows:
        if not row.proposed_name:
            errors.append(f"blank proposed_name for {row.current_name}")
            continue
        if not CASE_SHAPE_RE.match(row.proposed_name):
            errors.append(f"bad proposed_name shape: {row.current_name} -> {row.proposed_name}")
        prev = seen.setdefault(row.proposed_name, row.current_name)
        if prev != row.current_name:
            errors.append(f"duplicate proposed_name {row.proposed_name}: {prev}, {row.current_name}")

    # Catch rename cycles that require temp tokens. The current auto-map should not produce them,
    # but fail loudly if reviewed edits do.
    current_to_proposed = {r.current_name: r.proposed_name for r in rows if r.current_name != r.proposed_name}
    for old, new in current_to_proposed.items():
        if new in current_to_proposed and current_to_proposed[new] != new:
            errors.append(f"unsafe rename collision/cycle: {old} -> {new}, and {new} is also renamed")

    changed = sum(1 for r in rows if r.current_name != r.proposed_name)
    identities = len(rows) - changed
    print(f"Rows: {len(rows)}; renames: {changed}; identity: {identities}")
    if errors:
        print("ERRORS:", file=sys.stderr)
        for error in errors:
            print(f"  {error}", file=sys.stderr)
        return rows, 1
    print("Map OK.")
    return rows, 0


def _replace_token(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    pattern = re.compile(rf"\b{re.escape(old)}\b")
    text2, count = pattern.subn(new, text)
    if count == 0:
        raise RuntimeError(f"{old} not found in {path}")
    path.write_text(text2)


def apply_map(path: Path) -> None:
    rows, rc = check_map(path)
    if rc:
        raise SystemExit(rc)
    renames = [(r.current_name, r.proposed_name, CATCH_DIR / r.file)
               for r in rows if r.current_name != r.proposed_name]

    for old, new, file_path in renames:
        _replace_token(file_path, old, new)

    yaml_text = CONTRACT_YAML.read_text()
    for old, new, _ in renames:
        old_key = f"  {old}:"
        new_key = f"  {new}:"
        if old_key not in yaml_text:
            raise RuntimeError(f"yaml key missing: {old_key}")
        yaml_text = yaml_text.replace(old_key, new_key, 1)
    CONTRACT_YAML.write_text(yaml_text)

    subprocess.run([sys.executable, str(_THIS_DIR / "gen_test_plan.py")], cwd=HIP_TESTS_DIR, check=True)
    print(f"Applied {len(renames)} renames and regenerated catch/TEST_PLAN.md.")


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--emit-map", action="store_true")
    group.add_argument("--check-map", action="store_true")
    group.add_argument("--apply", action="store_true")
    parser.add_argument("--map", type=Path, default=DEFAULT_MAP)
    args = parser.parse_args(argv)

    if args.emit_map:
        emit_map(args.map)
        return 0
    if args.check_map:
        _, rc = check_map(args.map)
        return rc
    if args.apply:
        apply_map(args.map)
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
