/* Copyright (c) 2026 Advanced Micro Devices, Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE. */

#include "spawn_hip_workload.h"

/* Generated by test/feature/CMakeLists.txt via file(GENERATE).  Wraps
   the workload path in a C++ raw string literal so native paths with
   backslashes / spaces / quotes survive intact — see the comment on
   the file(GENERATE) call for the full rationale.  */
#include "dbgapi_hip_workload_path.h"

#if defined(__linux__)
#  include <signal.h>
#  include <sys/wait.h>
#  include <unistd.h>

#  include <cstdio>
#  include <cstdlib>
#  include <cstring>
#  include <string>
#endif

namespace amd::dbgapi::test
{

using detail::hip_idle_workload_path;

bool
hip_workload_available ()
{
  return hip_idle_workload_path[0] != '\0';
}

#if defined(__linux__)

idle_child_t
spawn_hip_workload ()
{
  if (!hip_workload_available ())
    return idle_child_t{};

  int pipefd[2] = { -1, -1 };
  if (::pipe (pipefd) < 0)
    return idle_child_t{};

  ::pid_t pid = ::fork ();
  if (pid < 0)
    {
      ::close (pipefd[0]);
      ::close (pipefd[1]);
      return idle_child_t{};
    }

  if (pid == 0)
    {
      /* Child: rewire stdout into the pipe so the parent can read
         "READY\n", then exec.  */
      ::close (pipefd[0]);
      if (::dup2 (pipefd[1], STDOUT_FILENO) < 0)
        ::_exit (126);
      ::close (pipefd[1]);
      /* HSA_ENABLE_DEBUG=1 lets dbgapi report full wave info for
         pre-attach dispatches; harmless if unused.  */
      ::setenv ("HSA_ENABLE_DEBUG", "1", 1);
      ::execl (hip_idle_workload_path, "idle_kernel",
               static_cast<char *> (nullptr));
      ::_exit (127);
    }

  /* Parent: read until we see READY, the pipe closes, or the child
     dies.  Bounded read so a runaway workload can't hang us; if we
     don't see READY in ~30 KiB / a few seconds we kill the child and
     return invalid so the test can GTEST_SKIP.  */
  ::close (pipefd[1]);

  std::string buf;
  char chunk[256];
  bool ready = false;
  for (int i = 0; i < 120; ++i)
    {
      ssize_t n = ::read (pipefd[0], chunk, sizeof (chunk));
      if (n <= 0)
        break;
      buf.append (chunk, static_cast<size_t> (n));
      if (buf.find ("READY\n") != std::string::npos)
        {
          ready = true;
          break;
        }
      if (buf.size () > 32768)
        break;
    }
  ::close (pipefd[0]);

  if (!ready)
    {
      ::kill (pid, SIGKILL);
      int status = 0;
      ::waitpid (pid, &status, 0);
      return idle_child_t{};
    }

  return idle_child_t{ pid };
}

#else

idle_child_t
spawn_hip_workload ()
{
  return idle_child_t{};
}

#endif

} /* namespace amd::dbgapi::test */
