name: Dockers Cleanup

on:
  # allow triggering manually
  workflow_dispatch:
  # run on weekly schedule
  schedule:
  - cron: "0 0 * * 6"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup-dockers:

    strategy:
      fail-fast: false
      matrix:
        runner: ['vega20', mi200, mi100, navi21, navi31]

    runs-on: ${{ matrix.runner }}

    steps:
    - name: prune-dockers
      run: |
        docker system prune -f -a --volumes
