name: "Pull from Gerrit"
on:
  schedule:
  - cron: "* */23 * * *"

jobs:
  pull:
    runs-on: mi200
    steps:
      - name: Adding Gerrit Remote
        run: git remote add gerrit ssh://aelwazir@gerrit-git.amd.com:29418/compute/ec/rocprofiler
      - name: Fetching Gerrit
        run: git fetch --all
      - name: Checking out amd-staging
        run: git checkout amd-staging
      - name: Merging staging branches
        run: git merge gerrit/amd-staging
      - name: Pushing to amd-staging
        run: git push origin amd-staging