name: "Pull from Gerrit"

on:
  # allow triggering manually
  workflow_dispatch:
  schedule:
  - cron: "0 */23 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull:
    runs-on: navi32
    steps:
      - name: Pull from Gerrit to gerrit-amd-staging branch
        run: |
          cd ${{github.workspace}}
          git config --global --add safe.directory ${{github.workspace}}
          git remote add gerrit ssh://aelwazir@gerrit-git.amd.com:29418/compute/ec/rocprofiler
          git fetch --all
          git checkout gerrit/amd-staging
          git checkout -b gerrit-amd-staging
          git push origin gerrit-amd-staging
          git checkout amd-staging
