name: Get Latest Dockers

on:
  # allow triggering manually
  workflow_dispatch:
  # run when updated
  push:
    branches: '*'
    paths:
      - '.github/workflows/pull_latest_dockers.yml'
  # run when updated
  schedule:
  - cron: "0 */23 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-runner-mainline:

    strategy:
      fail-fast: false
      matrix:
        runner: ['mi200', 'mi100', 'vega20', 'navi32']
        os: ['ubuntu-22.04', 'ubuntu-20.04', 'sles', 'rhel-9.x', 'rhel-8.x']

    runs-on: ${{ matrix.runner }}

    steps:
    - name: pull-image
      run: |
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-${{ matrix.os }}-stg1

    - name: tag-image
      run: |
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-${{ matrix.os }}-stg1 localhost:5000/mainline-${{ matrix.os }}-stg1:latest
        docker push localhost:5000/mainline-${{ matrix.os }}-stg1:latest
