name: Get Latest Dockers

on:
  schedule:
  - cron: "* */23 * * *"

jobs:
  getting_latest_docker_mi200:
    runs-on: mi200

    steps:
    - uses: actions/checkout@v3
    - name: pull_the_latest_images
      run: |
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1

    - name: tag_the_latest_docker
      run: |
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1 localhost:5000/mainline-ubuntu-22.04-stg1:latest
        docker push localhost:5000/mainline-ubuntu-22.04-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1 localhost:5000/mainline-ubuntu-20.04-stg1:latest
        docker push localhost:5000/mainline-ubuntu-20.04-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1 localhost:5000/mainline-sles-stg1:latest
        docker push localhost:5000/mainline-sles-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1 localhost:5000/mainline-rhel-9.x-stg1:latest
        docker push localhost:5000/mainline-rhel-9.x-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1 localhost:5000/mainline-rhel-8.x-stg1:latest
        docker push localhost:5000/mainline-rhel-8.x-stg1:latest

  getting_latest_docker_mi100:
    runs-on: mi100

    steps:
    - uses: actions/checkout@v3
    - name: pull_the_latest_images
      run: |
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1

    - name: tag_the_latest_docker
      run: |
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1 localhost:5000/mainline-ubuntu-22.04-stg1:latest
        docker push localhost:5000/mainline-ubuntu-22.04-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1 localhost:5000/mainline-ubuntu-20.04-stg1:latest
        docker push localhost:5000/mainline-ubuntu-20.04-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1 localhost:5000/mainline-sles-stg1:latest
        docker push localhost:5000/mainline-sles-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1 localhost:5000/mainline-rhel-9.x-stg1:latest
        docker push localhost:5000/mainline-rhel-9.x-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1 localhost:5000/mainline-rhel-8.x-stg1:latest
        docker push localhost:5000/mainline-rhel-8.x-stg1:latest

  getting_latest_docker_vega20:
    runs-on: vega20

    steps:
    - uses: actions/checkout@v3
    - name: pull_the_latest_images
      run: |
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1

    - name: tag_the_latest_docker
      run: |
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1 localhost:5000/mainline-ubuntu-22.04-stg1:latest
        docker push localhost:5000/mainline-ubuntu-22.04-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1 localhost:5000/mainline-ubuntu-20.04-stg1:latest
        docker push localhost:5000/mainline-ubuntu-20.04-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1 localhost:5000/mainline-sles-stg1:latest
        docker push localhost:5000/mainline-sles-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1 localhost:5000/mainline-rhel-9.x-stg1:latest
        docker push localhost:5000/mainline-rhel-9.x-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1 localhost:5000/mainline-rhel-8.x-stg1:latest
        docker push localhost:5000/mainline-rhel-8.x-stg1:latest


  getting_latest_docker_navi32:
    runs-on: navi32

    steps:
    - uses: actions/checkout@v3
    - name: pull_the_latest_images
      run: |
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1
        docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1

    - name: tag_the_latest_docker
      run: |
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1 localhost:5000/mainline-ubuntu-22.04-stg1:latest
        docker push localhost:5000/mainline-ubuntu-22.04-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1 localhost:5000/mainline-ubuntu-20.04-stg1:latest
        docker push localhost:5000/mainline-ubuntu-20.04-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1 localhost:5000/mainline-sles-stg1:latest
        docker push localhost:5000/mainline-sles-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1 localhost:5000/mainline-rhel-9.x-stg1:latest
        docker push localhost:5000/mainline-rhel-9.x-stg1:latest
        docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1 localhost:5000/mainline-rhel-8.x-stg1:latest
        docker push localhost:5000/mainline-rhel-8.x-stg1:latest

  # getting_latest_docker_navi21:
  #   runs-on: navi21

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: pull_the_latest_images
  #     run: |
  #       docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1
  #       docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1
  #       docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1
  #       docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1
  #       docker pull compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1

  #   - name: tag_the_latest_docker
  #     run: |
  #       docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-22.04-stg1 localhost:5000/mainline-ubuntu-22.04-stg1:latest
  #       docker push localhost:5000/mainline-ubuntu-22.04-stg1:latest
  #       docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-ubuntu-20.04-stg1 localhost:5000/mainline-ubuntu-20.04-stg1:latest
  #       docker push localhost:5000/mainline-ubuntu-20.04-stg1:latest
  #       docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-sles-stg1 localhost:5000/mainline-sles-stg1:latest
  #       docker push localhost:5000/mainline-sles-stg1:latest
  #       docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-9.x-stg1 localhost:5000/mainline-rhel-9.x-stg1:latest
  #       docker push localhost:5000/mainline-rhel-9.x-stg1:latest
  #       docker tag compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:$(wget -qO- "http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/lastSuccessfulBuild/buildNumber")-rhel-8.x-stg1 localhost:5000/mainline-rhel-8.x-stg1:latest
  #       docker push localhost:5000/mainline-rhel-8.x-stg1:latest
