//! Build script: read the `KfdDeviceInfo` field defaults out of the
//! rocjitsu FlatBuffers schema.
//!
//! These are not rocjitsu's to choose. The schema is what the emulator
//! parses a config with, and a field a config omits takes the default
//! written there — `l1_assoc = 4`, `l2_line_size = 128`, and eighteen
//! others. The Rust side serialises every field it has, so a field it
//! leaves at `u32::default()` does not omit anything: it writes a zero,
//! and a zero is not the same answer as "unset". Three builtin profiles
//! shipped an emulated GPU with a 0 KB L1, 0-byte cache lines and
//! 0-way associativity that way.
//!
//! So the defaults are read from the schema rather than copied beside
//! the struct, and a schema that changes one takes the struct with it.
//!
//! Emitted as one constant per field, for every field in the table,
//! rather than as a finished `Default` — that keeps this script from
//! needing to know which subset of the table the Rust struct models.
//! A field the struct names and the schema drops fails the build, which
//! is the right way to hear about it.

// A build script may panic: a schema that is missing or has lost the
// table this reads is not something the crate can be built without, and
// there is no caller to return an error to.
#![allow(clippy::expect_used, clippy::panic)]

use std::fmt::Write as _;
use std::path::PathBuf;

/// The table whose defaults are published.
const TABLE: &str = "KfdDeviceInfo";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let schema =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../schemas/simulation_config.fbs");
    println!("cargo:rerun-if-changed={}", schema.display());

    let text = std::fs::read_to_string(&schema)
        .unwrap_or_else(|e| panic!("cannot read the rocjitsu schema {}: {e}", schema.display()));
    let body =
        table_body(&text).unwrap_or_else(|| panic!("{} has no `table {TABLE}`", schema.display()));

    let mut out = String::from(
        "// @generated by build.rs from schemas/simulation_config.fbs — do not edit.\n\
         // Regenerate by touching the schema or `build.rs`.\n\n",
    );
    let mut count = 0;
    for (name, ty, default) in fields(body) {
        // Only the scalar fields have a default worth publishing; a
        // string's is the empty string, which is what Rust already does.
        let Some(rust) = rust_type(&ty) else { continue };
        writeln!(
            out,
            "/// `{TABLE}.{name}` as the schema declares it.\n\
             pub(crate) const {}: {rust} = {default};",
            name.to_uppercase()
        )
        .expect("writing to a String cannot fail");
        count += 1;
    }
    assert!(count > 0, "{} declared no scalar fields", schema.display());

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"))
        .join("kfd_device_defaults.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

/// The body of `table <TABLE> { … }`, without the braces.
fn table_body(schema: &str) -> Option<&str> {
    let start = schema.find(&format!("table {TABLE} {{"))?;
    let open = schema[start..].find('{')? + start + 1;
    let close = schema[open..].find("\n}")? + open;
    Some(&schema[open..close])
}

/// Every `name: type [= default];` in `body`, with an absent default
/// read as zero — which is what FlatBuffers does with it.
fn fields(body: &str) -> Vec<(String, String, String)> {
    let mut out = Vec::new();
    for line in body.lines() {
        // Comments can follow a field on its own line, and do.
        let line = line.split("//").next().unwrap_or("").trim();
        let Some(decl) = line.strip_suffix(';') else {
            continue;
        };
        let Some((name, rest)) = decl.split_once(':') else {
            continue;
        };
        let (ty, default) = match rest.split_once('=') {
            Some((ty, value)) => (ty.trim(), value.trim()),
            None => (rest.trim(), "0"),
        };
        out.push((name.trim().to_string(), ty.to_string(), default.to_string()));
    }
    out
}

/// The Rust type a FlatBuffers scalar maps to, or `None` for everything
/// else — strings, vectors and tables, which have no scalar default.
fn rust_type(fbs: &str) -> Option<&'static str> {
    match fbs {
        "uint32" | "uint" => Some("u32"),
        "uint64" | "ulong" => Some("u64"),
        "int32" | "int" => Some("i32"),
        "bool" => Some("bool"),
        _ => None,
    }
}
