
// MIT License
//
// Copyright (c) 2017-2025 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef _GFX12_REG_INFO_MACROS_H_
#define _GFX12_REG_INFO_MACROS_H_

#define REG_INFO_ENTRY_FULL(BLOCK, INST, CTRL, INDEX) \
 {REG_32B_ADDR(GC, INST, reg##BLOCK##_PERFCOUNTER##INDEX##_SELECT), CTRL, REG_32B_ADDR(GC, INST, reg##BLOCK##_PERFCOUNTER##INDEX##_LO), REG_32B_ADDR(GC, INST, reg##BLOCK##_PERFCOUNTER##INDEX##_HI), REG_32B_NULL}
#define REG_INFO_ENTRY(BLOCK, INDEX) REG_INFO_ENTRY_FULL(BLOCK, 0, REG_32B_NULL, INDEX)
#define REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, INDEX) REG_INFO_ENTRY_FULL(BLOCK, 0, CTRL, INDEX)
#define REG_INFO_ENTRY_WITH_INST(BLOCK, INST, INDEX) REG_INFO_ENTRY_FULL(BLOCK, INST, REG_32B_NULL, INDEX)

#define REG_INFO_1(BLOCK) REG_INFO_ENTRY(BLOCK, 0)
#define REG_INFO_2(BLOCK) REG_INFO_1(BLOCK), REG_INFO_ENTRY(BLOCK, 1)
#define REG_INFO_3(BLOCK) REG_INFO_2(BLOCK), REG_INFO_ENTRY(BLOCK, 2)
#define REG_INFO_4(BLOCK) REG_INFO_3(BLOCK), REG_INFO_ENTRY(BLOCK, 3)
#define REG_INFO_5(BLOCK) REG_INFO_4(BLOCK), REG_INFO_ENTRY(BLOCK, 4)
#define REG_INFO_6(BLOCK) REG_INFO_5(BLOCK), REG_INFO_ENTRY(BLOCK, 5)
#define REG_INFO_7(BLOCK) REG_INFO_6(BLOCK), REG_INFO_ENTRY(BLOCK, 6)
#define REG_INFO_8(BLOCK) REG_INFO_7(BLOCK), REG_INFO_ENTRY(BLOCK, 7)

#define REG_INFO_WITH_CTRL_1(BLOCK, CTRL) REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, 0)
#define REG_INFO_WITH_CTRL_2(BLOCK, CTRL) REG_INFO_WITH_CTRL_1(BLOCK, CTRL), REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, 1)
#define REG_INFO_WITH_CTRL_3(BLOCK, CTRL) REG_INFO_WITH_CTRL_2(BLOCK, CTRL), REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, 2)
#define REG_INFO_WITH_CTRL_4(BLOCK, CTRL) REG_INFO_WITH_CTRL_3(BLOCK, CTRL), REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, 3)
#define REG_INFO_WITH_CTRL_5(BLOCK, CTRL) REG_INFO_WITH_CTRL_4(BLOCK, CTRL), REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, 4)
#define REG_INFO_WITH_CTRL_6(BLOCK, CTRL) REG_INFO_WITH_CTRL_5(BLOCK, CTRL), REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, 5)
#define REG_INFO_WITH_CTRL_7(BLOCK, CTRL) REG_INFO_WITH_CTRL_6(BLOCK, CTRL), REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, 6)
#define REG_INFO_WITH_CTRL_8(BLOCK, CTRL) REG_INFO_WITH_CTRL_7(BLOCK, CTRL), REG_INFO_ENTRY_WITH_CTRL(BLOCK, CTRL, 7)

#define REG_INFO_WITH_INST_1(BLOCK, INST) REG_INFO_ENTRY_WITH_INST(BLOCK, INST, 0)
#define REG_INFO_WITH_INST_2(BLOCK, INST) REG_INFO_WITH_INST_1(BLOCK, INST), REG_INFO_ENTRY_WITH_INST(BLOCK, INST, 1)
#define REG_INFO_WITH_INST_3(BLOCK, INST) REG_INFO_WITH_INST_2(BLOCK, INST), REG_INFO_ENTRY_WITH_INST(BLOCK, INST, 2)
#define REG_INFO_WITH_INST_4(BLOCK, INST) REG_INFO_WITH_INST_3(BLOCK, INST), REG_INFO_ENTRY_WITH_INST(BLOCK, INST, 3)

#define REG_INFO_WITH_CFG(IP, BLOCK, INDEX)				\
 {REG_32B_ADDR(IP, 0, reg##BLOCK##_PERFCOUNTER##INDEX##_CFG), REG_32B_ADDR(IP, 0, reg##BLOCK##_PERFCOUNTER_RSLT_CNTL), REG_32B_ADDR(IP, 0, reg##BLOCK##_PERFCOUNTER_LO), REG_32B_ADDR(IP, 0, reg##BLOCK##_PERFCOUNTER_HI), REG_32B_NULL}
#define REG_INFO_WITH_CFG_1(IP, BLOCK) REG_INFO_WITH_CFG(IP, BLOCK, 0)
#define REG_INFO_WITH_CFG_2(IP, BLOCK) REG_INFO_WITH_CFG_1(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 1)
#define REG_INFO_WITH_CFG_3(IP, BLOCK) REG_INFO_WITH_CFG_2(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 2)
#define REG_INFO_WITH_CFG_4(IP, BLOCK) REG_INFO_WITH_CFG_3(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 3)
#define REG_INFO_WITH_CFG_5(IP, BLOCK) REG_INFO_WITH_CFG_4(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 4)
#define REG_INFO_WITH_CFG_6(IP, BLOCK) REG_INFO_WITH_CFG_5(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 5)
#define REG_INFO_WITH_CFG_7(IP, BLOCK) REG_INFO_WITH_CFG_6(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 6)
#define REG_INFO_WITH_CFG_8(IP, BLOCK) REG_INFO_WITH_CFG_7(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 7)
#define REG_INFO_WITH_CFG_9(IP, BLOCK)  REG_INFO_WITH_CFG_8(IP, BLOCK),  REG_INFO_WITH_CFG(IP, BLOCK, 8)
#define REG_INFO_WITH_CFG_10(IP, BLOCK) REG_INFO_WITH_CFG_9(IP, BLOCK),  REG_INFO_WITH_CFG(IP, BLOCK, 9)
#define REG_INFO_WITH_CFG_11(IP, BLOCK) REG_INFO_WITH_CFG_10(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 10)
#define REG_INFO_WITH_CFG_12(IP, BLOCK) REG_INFO_WITH_CFG_11(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 11)
#define REG_INFO_WITH_CFG_13(IP, BLOCK) REG_INFO_WITH_CFG_12(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 12)
#define REG_INFO_WITH_CFG_14(IP, BLOCK) REG_INFO_WITH_CFG_13(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 13)
#define REG_INFO_WITH_CFG_15(IP, BLOCK) REG_INFO_WITH_CFG_14(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 14)
#define REG_INFO_WITH_CFG_16(IP, BLOCK) REG_INFO_WITH_CFG_15(IP, BLOCK), REG_INFO_WITH_CFG(IP, BLOCK, 15)

#endif  // _GFX12_REG_INFO_MACROS_H_
