# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT

# Install-time generator for the relocatable unit-test CTestTestfile.cmake.
#
# This runs during `cmake --install`, NOT at configure time, because it needs
# the built test binaries: it enumerates each binary's GoogleTest cases with
# --gtest_list_tests and emits one ctest entry per case. That preserves the
# per-case process isolation that gtest_discover_tests provides -- some internal
# tests leak state across cases and only pass when each runs in its own process.
#
# Each entry invokes the binary by RELATIVE path ("./<binary>") so the installed
# tree stays relocatable; ctest runs each test with its working directory set to
# the directory containing CTestTestfile.cmake.
#
# Expected inputs (set by the install(CODE ...) block in AISInstallTests.cmake):
#   HIPFILE_TEST_INSTALL_DIR   relative install dir, used in the header note
#   HIPFILE_TEST_NAMES         list of installed binary names (e.g. hipfile_tests),
#                              used as the relative ./<name> ctest invocation
#   HIPFILE_TEST_FILES         parallel list of BUILD-tree binary paths to query
#   HIPFILE_TEST_SUFFIXES      parallel list of per-binary label suffixes
#   HIPFILE_INSTALL_CTEST_FILE absolute path of the CTestTestfile.cmake to write
#
# Enumeration runs the BUILD-tree binaries (HIPFILE_TEST_FILES): the build-tree
# binary keeps its build RPATH and resolves every shared dependency (libhipfile
# and, when GTest is a shared library, libgtest/libgmock). The staged/installed
# copy cannot be launched here because CPack stages the 'tests' component in
# isolation, without those libraries. The emitted ctest entries still invoke the
# INSTALLED binary by relative path (./<name>); only the case-listing launch uses
# the build-tree path. The case set is identical.

set(_content "# hipFile unit tests (install-time, relocatable).\n")
string(APPEND _content "# Generated by cmake/AISGenerateInstallCTest.cmake -- do not edit.\n")
string(APPEND _content "# Run with: cd <install>/${HIPFILE_TEST_INSTALL_DIR} && ctest -L unit\n\n")

list(LENGTH HIPFILE_TEST_NAMES _n_tests)
math(EXPR _last_idx "${_n_tests} - 1")
foreach(_idx RANGE ${_last_idx})
    list(GET HIPFILE_TEST_NAMES ${_idx} _name)
    list(GET HIPFILE_TEST_FILES ${_idx} _file)
    list(GET HIPFILE_TEST_SUFFIXES ${_idx} _suffix)

    if(NOT EXISTS "${_file}")
        message(FATAL_ERROR "hipFile: build-tree test binary not found: '${_file}'")
    endif()

    execute_process(
        COMMAND "${_file}" --gtest_list_tests
        OUTPUT_VARIABLE _listing
        RESULT_VARIABLE _rc
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR "hipFile: failed to enumerate tests in '${_file}' (exit ${_rc})")
    endif()

    # --gtest_list_tests prints a suite header per line ("Suite.") followed by
    # its cases indented two spaces, each optionally trailed by a
    # " # GetParam() = ..." annotation we discard. The full ctest/gtest filter
    # name is the suite header concatenated with the case name.
    string(REPLACE "\n" ";" _lines "${_listing}")
    set(_suite "")
    foreach(_line IN LISTS _lines)
        string(REGEX REPLACE " +#.*$" "" _line "${_line}")
        if(_line MATCHES "^[^ ].*\\.$")
            string(STRIP "${_line}" _suite)
        elseif(_line MATCHES "^  +[^ ]")
            string(STRIP "${_line}" _case)
            set(_test "${_suite}${_case}")
            string(APPEND _content "add_test(\"${_test}\" \"./${_name}\" \"--gtest_filter=${_test}\")\n")
            string(APPEND _content
                "set_tests_properties(\"${_test}\" PROPERTIES TIMEOUT 300 LABELS \"unit;${_suffix}\")\n")
        endif()
    endforeach()
endforeach()

file(WRITE "${HIPFILE_INSTALL_CTEST_FILE}" "${_content}")
message(STATUS "hipFile: wrote ${HIPFILE_INSTALL_CTEST_FILE}")
