# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_create_environment:
      - ./source/scripts/update-doxygen.sh

conda:
  environment: source/docs/environment.yml

python:
  install:
  - requirements: source/docs/sphinx/requirements.txt

sphinx:
  configuration: source/docs/conf.py

formats: [htmlzip, pdf, epub]
