/*************************************************************************
 * Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

// Host-only dependency floor for src/rccl_wrap.cc's microtest, compiled
// into rccl-UnitTestsMicro alongside p2p.cc/rma_proxy_progress.cc's own
// tests. #include-ing the whole 1773-line rccl_wrap.cc (via WRAP_CC_PATH)
// pulls in the DDA / CE / symmetric-kernel / hierarchical backend-selection
// machinery even though the covered functions (see wrap-test.cc) don't reach
// all of it yet. Everything below satisfies the link closure. Controllable
// seams use conservative production-like defaults; tests override them with
// ScopedHook when a branch needs different behaviour.
//
// Dependencies with an established owner live in their canonical fake files:
// collectives_fakes, strongstream_stubs, dev_runtime_fakes, ce_fakes,
// sym_kernels_fakes, transport_stubs, and tuning_fakes. This file contains
// only the remaining rccl_wrap.cc link-closure seams that have no shared owner
// yet. nccl_stubs.cc is not linked because it defines commSetUnrollFactor,
// which is a real function supplied by the unit under test itself.
//
// RCCL_PARAM / NCCL_PARAM: every RCCL_PARAM(...) invocation textually inside
// rccl_wrap.cc is redirected by wrap-test.cc to route through a g_loadParam
// std::function hook (same mechanism as init-test.cc's redirect), so a test
// can flip one param's value between cases -- see wrap-test.cc's redirector
// comment. The few ncclParamXxx / rcclParamXxx symbols rccl_wrap.cc declares
// `extern` and calls without a local RCCL_PARAM/NCCL_PARAM invocation (their
// generator lives in another .cc) are stubbed below instead.

#include "wrap_fakes.h"

#include <cstdint>
#include <functional>

#include "algorithms/dda/all_gather/dda_all_gather.h"
#include "algorithms/dda/all_reduce/dda_all_reduce.h"
#include "algorithms/dda/reduce_scatter/dda_reduce_scatter.h"
#include "amdsmi_wrap.h"
#include "ce_coll.h"
#include "comm.h"
#include "debug.h"
#include "dev_runtime.h"
#include "enqueue.h"
#include "group.h"
#include "nccl.h"
#include "rccl_common.h"
#include "strongstream.h"
#include "sym_kernels.h"

// ---------------------------------------------------------------------------
// Logging infrastructure. WARN/INFO (debug.h) expand to ncclDebugLog(); three
// of the units under test (rcclGetAlgoProtoIndex, rcclGetAlgoName,
// rcclGetProtocolName) call WARN on their invalid-input arms, and tests assert
// on that text via gtest's stderr capture.
//
// ncclDebugLevel / ncclDebugMask / ncclDebugNoWarn / ncclDebugLog() itself
// are defined once, by fakes/nccl_fakes.cc, which this binary already links
// for p2p.cc's tests -- defining them again here would be a duplicate-symbol
// error. ncclDebugMask's default there (0) differs from what this file used
// when it was its own standalone binary (~0ULL). WARN(...) calls
// ncclDebugLog() unconditionally regardless of mask; INFO(...) call sites are
// tested with explicit ScopedDebugLogging settings in wrap-test.cc rather
// than relying on either fake's default.
// ---------------------------------------------------------------------------
FILE* ncclDebugFile = nullptr;
char  ncclLastError[1024] = {};

// ---------------------------------------------------------------------------
// ncclParamXxx / rcclParamXxx symbols NOT generated by an RCCL_PARAM/NCCL_PARAM
// invocation inside rccl_wrap.cc itself (see file header comment). Trivial
// real behaviour (return the production default) rather than abort(): these
// are read on essentially every call into the file's channel/DDA tuning
// paths, so an abort-floor here would make even unrelated tests crash before
// reaching the function they actually meant to exercise.
//
// Unlike NCCL_NUM_ALGORITHMS/ncclNumFuncs below, there's no importable
// constant for "the current default" here -- NCCL_PARAM/RCCL_PARAM bakes
// deftVal directly as an inline macro-argument literal (see param.h), not a
// separately declared symbol, so a static_assert can't check it. Instead,
// wrap-test.cc's ParamDefaults_MatchProductionSource test reads the real
// graph/connect.cc / enqueue.cc source at run time and confirms the exact
// NCCL_PARAM/RCCL_PARAM(...) invocation text below still matches -- a
// run-time tripwire where a compile-time one isn't possible.
// ---------------------------------------------------------------------------
static int64_t DefaultParamForceCe() { return 1; }          // enqueue.cc:3796
std::function<int64_t()> g_paramForceCe = DefaultParamForceCe;
int64_t rcclParamForceCe() { return g_paramForceCe(); }

// ncclParamLaunchOrderImplicit: a settable hook, like rcclParamForceCe above,
// so a test can drive rcclDdaEnabled's
// `ncclParamLaunchOrderImplicit() != 0` disjunct independently -- the real
// default (0, "explicit launch order") favors the common case, matching the
// other three.
static int64_t DefaultParamLaunchOrderImplicit() { return 0; }  // enqueue.cc:1985
std::function<int64_t()> g_paramLaunchOrderImplicit = DefaultParamLaunchOrderImplicit;
int64_t ncclParamLaunchOrderImplicit() { return g_paramLaunchOrderImplicit(); }

// The settable env-var fake (SetMicroEnv/SetMicroEnvAbsent/ClearMicroEnv,
// the bare-getenv() link-level interposer, and ncclGetEnv) is NOT defined
// here: fakes/env_fakes.cc is the shared owner of src/misc/param.cc + getenv
// interposition for every microtest binary (see MICROTEST_README.md's
// "Where a fake belongs"). rccl_wrap.cc's several bare getenv() call sites
// (rcclSetPxn, rcclSetP2pNetChunkSize, rcclUpdateCollectiveProtocol,
// rcclUpdateThreadThreshold, ...) are covered by that same interposer.
// ncclGroupDepth is NOT faked here: group-test.cc (also part of this binary
// since the rccl-UnitTestsMicro merge) compiles the real group.cc, which
// defines it -- a second copy here would be a duplicate-symbol error. Its
// real default (0, "not grouped") is what every rccl_wrap.cc test so far
// assumes, same as when this was a hand-copied stub.

// ncclDevFuncUnrollGenerated: extern bool const[NCCL_NUM_UNROLLS]. Real array,
// not abort-floor -- commSetUnrollFactor indexes it unconditionally on every
// call, including the manual-override path the commSetUnrollFactor tests
// exercise. All-true is the safe default: "every unroll factor was built".
//
// Confirmed NOT safely upgradeable to a test seam: device.h's `extern bool
// const [...]` declaration is transitively visible in this TU too (this
// file doesn't include device.h directly, but something in its include
// chain does) -- dropping `const` here is a hard redefinition-with-
// different-type compile error, not just a lurking runtime risk. Leaving
// this const and documented, not forced through.
//
// Drift watchdog: without one, a new unroll factor added to RCCL would not be
// caught here -- the extra array slot would silently zero-initialize to false,
// quietly changing behavior. The check is a RUNTIME test
// (FakeTableDrift_UnrollCountMatchesProduction in wrap-test.cc), not a
// static_assert, for the same reason as the enum-count checks below.
const bool ncclDevFuncUnrollGenerated[NCCL_NUM_UNROLLS] = {true, true, true, true, true, true};

// ncclCommCount: real behaviour by default (de-risks future tests),
// but a controllable seam so rcclGetAlgoInfo's NCCLCHECK(ncclCommCount(...))
// failure arm (never exercised -- every prior test let this succeed) can be
// proven too.
static ncclResult_t DefaultCommCount(const ncclComm_t comm, int* count) {
  if (count) *count = comm ? comm->nRanks : 0;
  return ncclSuccess;
}
std::function<ncclResult_t(const ncclComm_t, int*)> g_commCount = DefaultCommCount;
ncclResult_t ncclCommCount(const ncclComm_t comm, int* count) { return g_commCount(comm, count); }

// ---------------------------------------------------------------------------
// Controllable seams for the top-level dispatchers (rcclSelectAllReduce/
// AllGather/ReduceScatter, rcclHierarchicalAlgoInfo, rcclGetAlgoInfo,
// rcclGetCollImplInfo, rcclSymkQuery/rcclSymKGetInfo's deep path). Without
// these each would have exactly one reachable outcome (see
// MICROTEST_README.md, "Adding more controllable
// seams" for the pattern followed here); upgraded so wrap-test.cc can drive
// each branch of those dispatchers directly. Every default below reproduces
// the safe, common "this fast path doesn't apply" case so existing tests
// upstream of these seams are unaffected -- verified by rereading each real
// call site before choosing it.
// ---------------------------------------------------------------------------

// Drives `symEligible` in all three rcclSelectXxx functions. Default false:
// "no symmetric-window kernel requested," letting the DDA/CE/Direct/plain
// paths run, matching every existing (guard-only) test's expectations.
static bool DefaultIsSymmetricKernelRequested(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, const void*,
                                              void*) {
  return false;
}
std::function<bool(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, const void*, void*)>
    g_isSymmetricKernelRequested = DefaultIsSymmetricKernelRequested;
bool isSymmetricKernelRequested(struct ncclComm* comm, ncclFunc_t coll, int symkOp, ncclDataType_t datatype,
                                size_t nElts, const void* sendbuff, void* recvbuff) {
  return g_isSymmetricKernelRequested(comm, coll, symkOp, datatype, nElts, sendbuff, recvbuff);
}

// rcclAllReduceShouldTakeDdaPath: real body lives in collectives.cc (not
// linked here), same abort-floor-turned-seam treatment as the rest. Default
// false: DDA not taken, letting CE-registered/symmetric/plain-kernel run.
static bool DefaultAllReduceShouldTakeDdaPath(const struct ncclComm*, size_t, ncclDataType_t, bool, bool) {
  return false;
}
std::function<bool(const struct ncclComm*, size_t, ncclDataType_t, bool, bool)> g_allReduceShouldTakeDdaPath =
    DefaultAllReduceShouldTakeDdaPath;
bool rcclAllReduceShouldTakeDdaPath(const struct ncclComm* comm, size_t count, ncclDataType_t dt, bool symEligible,
                                    bool ceAllReduceAllowed) {
  return g_allReduceShouldTakeDdaPath(comm, count, dt, symEligible, ceAllReduceAllowed);
}

// getAlgoInfo / rcclKernelPackedChannels: rccl_wrap.cc `extern`-declares both
// itself (their real definitions live in enqueue.cc / device-side tuning,
// outside this TU's link closure), so no separate declaration is needed here.
// Default getAlgoInfo fills in a sane, generic Ring/Simple/1-channel answer
// (the universal plain-kernel fallback every rcclSelectXxx eventually falls
// to); default rcclKernelPackedChannels passes the tuning-cap channel count
// through unpacked, a safe no-op default.
static ncclResult_t DefaultGetAlgoInfo(struct ncclComm*, struct ncclTaskColl* task, int, int, int, ncclSimInfo_t*) {
  task->algorithm = NCCL_ALGO_RING;
  task->protocol = NCCL_PROTO_SIMPLE;
  task->nMaxChannels = 1;
  return ncclSuccess;
}
std::function<ncclResult_t(struct ncclComm*, struct ncclTaskColl*, int, int, int, ncclSimInfo_t*)> g_getAlgoInfo =
    DefaultGetAlgoInfo;
ncclResult_t getAlgoInfo(struct ncclComm* comm, struct ncclTaskColl* task, int collNetSupport, int nvlsSupport,
                         int numPipeOps, ncclSimInfo_t* simInfo) {
  return g_getAlgoInfo(comm, task, collNetSupport, nvlsSupport, numPipeOps, simInfo);
}

static int DefaultKernelPackedChannels(struct ncclComm*, ncclFunc_t, size_t, ncclDataType_t, int, int nMaxChannels) {
  return nMaxChannels;
}
std::function<int(struct ncclComm*, ncclFunc_t, size_t, ncclDataType_t, int, int)> g_kernelPackedChannels =
    DefaultKernelPackedChannels;
int rcclKernelPackedChannels(struct ncclComm* comm, ncclFunc_t func, size_t count, ncclDataType_t dt, int protocol,
                             int nMaxChannels) {
  return g_kernelPackedChannels(comm, func, count, dt, protocol, nMaxChannels);
}

// rcclLL128ElemsPerThreadFromArch is `inline` in archinfo.h (transitively
// included), so no stub is needed here.

// getFirmwareVersion()'s sole dependency. Settable hook, same std::function
// shape as fakes/nccl_fakes.cc's, so a test can script a canned firmware
// response or a failure without touching the real AMD-SMI layer.
static ncclResult_t DefaultAmdSmiGetFirmwareVersion(uint32_t /*devIdx*/, uint64_t* fwVersion) {
  *fwVersion = 0;
  return ncclSuccess;
}
std::function<ncclResult_t(uint32_t, uint64_t*)> g_amdSmiGetFirmwareVersion = DefaultAmdSmiGetFirmwareVersion;
ncclResult_t amd_smi_getFirmwareVersion(uint32_t devIdx, uint64_t* fwVersion) {
  return g_amdSmiGetFirmwareVersion(devIdx, fwVersion);
}

// --- Per-collective DDA eligibility/blocks (24 functions total) ---
// Every *Eligible defaults false (DDA path not eligible by default, letting
// CE-registered/symmetric/hierarchical/Direct/plain-kernel run, matching
// every existing test's expectations). Every reachable *Blocks hook has a
// distinct 11x/12x sentinel, and selecting tests assert those values to prove
// which path supplied nMaxChannels. The unused 13x hooks remain distinct so a
// future production call cannot silently agree with a neighboring path.

// --- AllReduce DDA (dda_all_reduce.h) ---
static bool DefaultAllReduceDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_allReduceDdaIpcEligible = DefaultAllReduceDdaIpcEligible;
bool ncclAllReduceDdaIpcEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                 ncclRedOp_t op) {
  return g_allReduceDdaIpcEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultAllReduceDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_allReduceDdaFabricEligible = DefaultAllReduceDdaFabricEligible;
bool ncclAllReduceDdaFabricEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                    ncclRedOp_t op) {
  return g_allReduceDdaFabricEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultAllReduceDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_allReduceDdaFabricLLEligible = DefaultAllReduceDdaFabricLLEligible;
bool ncclAllReduceDdaFabricLLEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                      ncclRedOp_t op) {
  return g_allReduceDdaFabricLLEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultAllReduceDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t,
                                                   ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_allReduceDdaFabricLL128Eligible = DefaultAllReduceDdaFabricLL128Eligible;
bool ncclAllReduceDdaFabricLL128Eligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                         ncclRedOp_t op) {
  return g_allReduceDdaFabricLL128Eligible(comm, sb, rb, count, dt, op);
}

// The twelve *DdaBlocks fakes below each return a DISTINCT sentinel rather
// than a shared value. Their results land in decision->nMaxChannels, so if
// they all returned the same number the tests could not tell which one a
// dispatcher actually called: swapping an LL blocks call for the LL128 one
// would be invisible, as would hardcoding the field. The AllReduce and
// AllGather tests that select each path assert its sentinel, which pins both.
//
// Numbering is 1yz: y = 1 AllReduce, 2 AllGather, 3 ReduceScatter;
// z = 1 Ipc, 2 Fabric/VMM, 3 FabricLL, 4 FabricLL128 (so 111-114,
// 121-124, 131-134).
//
// The four 13x (ReduceScatter) entries are link-only: rcclSelectReduceScatter
// sets algo and protocol on its DDA paths but never nMaxChannels, and nothing
// in rccl_wrap.cc calls those four symbols. They keep distinct values anyway
// so that if a channel count is ever wired up there, the existing tests fail
// loudly rather than silently agreeing with a neighbouring path's value.
static uint32_t DefaultAllReduceDdaIpcBlocks(ncclComm*, size_t, ncclDataType_t) { return 111; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allReduceDdaIpcBlocks = DefaultAllReduceDdaIpcBlocks;
uint32_t ncclAllReduceDdaIpcBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allReduceDdaIpcBlocks(comm, count, dt);
}

static uint32_t DefaultAllReduceDdaFabricBlocks(ncclComm*, size_t, ncclDataType_t) { return 112; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allReduceDdaFabricBlocks =
    DefaultAllReduceDdaFabricBlocks;
uint32_t ncclAllReduceDdaFabricBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allReduceDdaFabricBlocks(comm, count, dt);
}

static uint32_t DefaultAllReduceDdaFabricLLBlocks(ncclComm*, size_t, ncclDataType_t) { return 113; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allReduceDdaFabricLLBlocks =
    DefaultAllReduceDdaFabricLLBlocks;
uint32_t ncclAllReduceDdaFabricLLBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allReduceDdaFabricLLBlocks(comm, count, dt);
}

static uint32_t DefaultAllReduceDdaFabricLL128Blocks(ncclComm*, size_t, ncclDataType_t) { return 114; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allReduceDdaFabricLL128Blocks =
    DefaultAllReduceDdaFabricLL128Blocks;
uint32_t ncclAllReduceDdaFabricLL128Blocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allReduceDdaFabricLL128Blocks(comm, count, dt);
}

// --- AllGather DDA (dda_all_gather.h) ---
static bool DefaultAllGatherDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) { return false; }
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t)> g_allGatherDdaIpcEligible =
    DefaultAllGatherDdaIpcEligible;
bool ncclAllGatherDdaIpcEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaIpcEligible(comm, sb, rb, count, dt);
}

static bool DefaultAllGatherDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) { return false; }
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t)> g_allGatherDdaFabricEligible =
    DefaultAllGatherDdaFabricEligible;
bool ncclAllGatherDdaFabricEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricEligible(comm, sb, rb, count, dt);
}

static bool DefaultAllGatherDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t)> g_allGatherDdaFabricLLEligible =
    DefaultAllGatherDdaFabricLLEligible;
bool ncclAllGatherDdaFabricLLEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricLLEligible(comm, sb, rb, count, dt);
}

static bool DefaultAllGatherDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t)> g_allGatherDdaFabricLL128Eligible =
    DefaultAllGatherDdaFabricLL128Eligible;
bool ncclAllGatherDdaFabricLL128Eligible(ncclComm* comm, const void* sb, void* rb, size_t count,
                                         ncclDataType_t dt) {
  return g_allGatherDdaFabricLL128Eligible(comm, sb, rb, count, dt);
}

static uint32_t DefaultAllGatherDdaIpcBlocks(ncclComm*, size_t, ncclDataType_t) { return 121; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allGatherDdaIpcBlocks = DefaultAllGatherDdaIpcBlocks;
uint32_t ncclAllGatherDdaIpcBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaIpcBlocks(comm, count, dt);
}

static uint32_t DefaultAllGatherDdaFabricBlocks(ncclComm*, size_t, ncclDataType_t) { return 122; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allGatherDdaFabricBlocks =
    DefaultAllGatherDdaFabricBlocks;
uint32_t ncclAllGatherDdaFabricBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricBlocks(comm, count, dt);
}

static uint32_t DefaultAllGatherDdaFabricLLBlocks(ncclComm*, size_t, ncclDataType_t) { return 123; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allGatherDdaFabricLLBlocks =
    DefaultAllGatherDdaFabricLLBlocks;
uint32_t ncclAllGatherDdaFabricLLBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricLLBlocks(comm, count, dt);
}

static uint32_t DefaultAllGatherDdaFabricLL128Blocks(ncclComm*, size_t, ncclDataType_t) { return 124; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_allGatherDdaFabricLL128Blocks =
    DefaultAllGatherDdaFabricLL128Blocks;
uint32_t ncclAllGatherDdaFabricLL128Blocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_allGatherDdaFabricLL128Blocks(comm, count, dt);
}

// --- ReduceScatter DDA (dda_reduce_scatter.h) ---
static bool DefaultReduceScatterDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_reduceScatterDdaIpcEligible = DefaultReduceScatterDdaIpcEligible;
bool ncclReduceScatterDdaIpcEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                     ncclRedOp_t op) {
  return g_reduceScatterDdaIpcEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultReduceScatterDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t,
                                                  ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_reduceScatterDdaFabricEligible = DefaultReduceScatterDdaFabricEligible;
bool ncclReduceScatterDdaFabricEligible(ncclComm* comm, const void* sb, void* rb, size_t count, ncclDataType_t dt,
                                        ncclRedOp_t op) {
  return g_reduceScatterDdaFabricEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultReduceScatterDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t,
                                                    ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_reduceScatterDdaFabricLLEligible = DefaultReduceScatterDdaFabricLLEligible;
bool ncclReduceScatterDdaFabricLLEligible(ncclComm* comm, const void* sb, void* rb, size_t count,
                                          ncclDataType_t dt, ncclRedOp_t op) {
  return g_reduceScatterDdaFabricLLEligible(comm, sb, rb, count, dt, op);
}

static bool DefaultReduceScatterDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t,
                                                       ncclRedOp_t) {
  return false;
}
std::function<bool(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t)>
    g_reduceScatterDdaFabricLL128Eligible = DefaultReduceScatterDdaFabricLL128Eligible;
bool ncclReduceScatterDdaFabricLL128Eligible(ncclComm* comm, const void* sb, void* rb, size_t count,
                                             ncclDataType_t dt, ncclRedOp_t op) {
  return g_reduceScatterDdaFabricLL128Eligible(comm, sb, rb, count, dt, op);
}

static uint32_t DefaultReduceScatterDdaIpcBlocks(ncclComm*, size_t, ncclDataType_t) { return 131; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_reduceScatterDdaIpcBlocks =
    DefaultReduceScatterDdaIpcBlocks;
uint32_t ncclReduceScatterDdaIpcBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_reduceScatterDdaIpcBlocks(comm, count, dt);
}

static uint32_t DefaultReduceScatterDdaFabricBlocks(ncclComm*, size_t, ncclDataType_t) { return 132; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_reduceScatterDdaFabricBlocks =
    DefaultReduceScatterDdaFabricBlocks;
uint32_t ncclReduceScatterDdaFabricBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_reduceScatterDdaFabricBlocks(comm, count, dt);
}

static uint32_t DefaultReduceScatterDdaFabricLLBlocks(ncclComm*, size_t, ncclDataType_t) { return 133; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_reduceScatterDdaFabricLLBlocks =
    DefaultReduceScatterDdaFabricLLBlocks;
uint32_t ncclReduceScatterDdaFabricLLBlocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_reduceScatterDdaFabricLLBlocks(comm, count, dt);
}

static uint32_t DefaultReduceScatterDdaFabricLL128Blocks(ncclComm*, size_t, ncclDataType_t) { return 134; }
std::function<uint32_t(ncclComm*, size_t, ncclDataType_t)> g_reduceScatterDdaFabricLL128Blocks =
    DefaultReduceScatterDdaFabricLL128Blocks;
uint32_t ncclReduceScatterDdaFabricLL128Blocks(ncclComm* comm, size_t count, ncclDataType_t dt) {
  return g_reduceScatterDdaFabricLL128Blocks(comm, count, dt);
}
