#!/usr/bin/env python3

# MIT License
#
# Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Backwards compatibility validation for rocpd schema versions.

All test inputs (SQLite databases, CSV, Perfetto, and OTF2 outputs) are
pre-generated by CTest execute tests defined in CMakeLists.txt.  This file
contains only the validation assertions.

Expected output directory layout (rooted at --output-root):
    <root>/<version>/csv/out_kernel_trace.csv
    <root>/<version>/csv/out_graph_launch_trace.csv   (schema >= 3.0.2 only)
    <root>/<version>/pftrace/out_results.pftrace
    <root>/<version>/otf2/out_results.otf2

Key invariants verified:
  * CSV  — graph_exec_id / graph_node_id columns absent for pre-latest schemas;
           out_graph_launch_trace.csv not created for pre-latest schemas.
  * CSV  — above columns / file ARE present for the latest schema.
  * CSV  — counters_collection averages a counter over kernel-replay passes for the
           latest schema instead of summing them, and pmc_events reports each pass.
  * Perfetto — counter values for the latest schema are those pass means.
  * Perfetto — .pftrace exists and is non-empty for every schema.
  * OTF2 — "HIP Graph Launch" locations absent for pre-latest schemas;
            present for the latest schema (requires the ``otf2`` package).

Schema version sets and the output root are supplied via command-line options
defined in conftest.py and passed by CMakeLists.txt.
"""

import csv as csv_mod
import sqlite3
import sys
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_all_schemas() -> list:
    """Return all supported schema versions using the query_supported_schema_versions() function. This way, as new schemas are added, they will be automatically tested."""
    try:
        from rocpd.schema import query_supported_schema_versions

        return [str(v) for v in query_supported_schema_versions()]
    except Exception:
        return ["3.0.0", "3.0.1", "3.0.2"]


def _csv_columns(csv_path: Path) -> list:
    """Return lower-cased column names from a CSV file."""
    with open(csv_path) as fh:
        return [c.strip().lower() for c in next(csv_mod.reader(fh), [])]


def _otf2_location_names(otf2_path: Path) -> list:
    """Return all location names from an OTF2 trace archive."""
    from rocprofiler_sdk.pytest_utils.otf2_reader import OTF2Reader

    _, readers = OTF2Reader(str(otf2_path)).read()
    return [str(loc.name) for loc in readers[0].definitions.locations]


# ---------------------------------------------------------------------------
# Schema coverage
# ---------------------------------------------------------------------------


def test_unexpected_rocpd_schema_versions(tested_schemas):
    """Fail if a new schema version ships without backwards compatibility coverage.

    When a new version appears in query_supported_schema_versions(), add it to
    ROCPD_COMPAT_TESTED_SCHEMAS in rocpd-back-compat/CMakeLists.txt and add the
    corresponding tests.
    """
    all_schemas = set(_get_all_schemas())
    unhandled = all_schemas - set(tested_schemas)
    assert not unhandled, (
        f"New schema version(s) detected without backwards compatibility test coverage: "
        f"{sorted(unhandled)}.  Add entries to ROCPD_COMPAT_TESTED_SCHEMAS in "
        f"rocpd-back-compat/CMakeLists.txt and add the corresponding backwards compatibility tests."
    )


# ---------------------------------------------------------------------------
# CSV tests — old schemas (pre-latest, lack graph-launch tables)
# ---------------------------------------------------------------------------


def test_csv_for_schema_3_0_2_changes_absent(old_schema, output_root):
    """Schema 3.0.2 additions must be absent for pre-latest schemas.

    Verifies that:
    * graph_exec_id / graph_node_id columns are not in the kernel trace CSV.
    * out_graph_launch_trace.csv is not produced.
    """

    # Check if the schema is 3.0.2 and newer, then call the present test instead
    if tuple(map(int, old_schema.split("."))) >= (3, 0, 2):
        print(
            f"Schema {old_schema} is newer than 3.0.2, calling test_csv_for_schema_3_0_2_changes_present instead"
        )
        return test_csv_for_schema_3_0_2_changes_present(output_root, old_schema)

    # Otherwise, check for the absence of the changes
    kernel_csv = output_root / old_schema / "csv" / "out_kernel_trace.csv"
    assert (
        kernel_csv.exists()
    ), f"out_kernel_trace.csv not found for schema {old_schema}: {kernel_csv}"
    cols = _csv_columns(kernel_csv)
    assert (
        "graph_exec_id" not in cols
    ), f"graph_exec_id unexpectedly present in kernel CSV for schema {old_schema}"
    assert (
        "graph_node_id" not in cols
    ), f"graph_node_id unexpectedly present in kernel CSV for schema {old_schema}"
    assert not (
        output_root / old_schema / "csv" / "out_graph_launch_trace.csv"
    ).exists(), (
        f"out_graph_launch_trace.csv should not be created for schema {old_schema}"
    )


# ---------------------------------------------------------------------------
# CSV tests — latest schema (has graph-launch tables)
# ---------------------------------------------------------------------------


def test_csv_for_schema_3_0_2_changes_present(output_root, latest_schema):
    """Schema 3.0.2 additions must be present for the latest schema.

    Verifies that:
    * graph_exec_id / graph_node_id columns appear in the kernel trace CSV.
    * out_graph_launch_trace.csv is produced.
    """
    kernel_csv = output_root / latest_schema / "csv" / "out_kernel_trace.csv"
    assert (
        kernel_csv.exists()
    ), f"out_kernel_trace.csv not found for schema {latest_schema}: {kernel_csv}"
    cols = _csv_columns(kernel_csv)
    assert (
        "graph_exec_id" in cols
    ), f"graph_exec_id missing from kernel CSV for schema {latest_schema}"
    assert (
        "graph_node_id" in cols
    ), f"graph_node_id missing from kernel CSV for schema {latest_schema}"
    assert (
        output_root / latest_schema / "csv" / "out_graph_launch_trace.csv"
    ).exists(), f"out_graph_launch_trace.csv not found for schema {latest_schema}"


# ---------------------------------------------------------------------------
# CSV tests — schema 3.0.3 (does not have spm_counters view output to CSV)
# ---------------------------------------------------------------------------


def test_csv_for_schema_3_0_3_changes_absent(output_root, old_schema):
    """Schema 3.0.3 additions must be absent for the old schema.

    Verifies that:
    * spm_counters view output to CSV is not present.
    """

    # Check if the schema is 3.0.3 and newer, then call the present test instead
    if tuple(map(int, old_schema.split("."))) >= (3, 0, 3):
        print(
            f"Schema {old_schema} is newer than 3.0.3, calling test_csv_for_schema_3_0_3_changes_present instead"
        )
        return test_csv_for_schema_3_0_3_changes_present(output_root, old_schema)

    spm_counters_csv = (
        output_root / old_schema / "csv" / "out_spm_counter_collection_trace.csv"
    )
    assert (
        not spm_counters_csv.exists()
    ), f"out_spm_counter_collection_trace.csv found for schema {old_schema}: {spm_counters_csv}"


# ---------------------------------------------------------------------------
# CSV tests — schema 3.0.3 (has spm_counters view output to CSV)
# ---------------------------------------------------------------------------


def test_csv_for_schema_3_0_3_changes_present(output_root, latest_schema):
    """Schema 3.0.3 additions must be present for the latest schema.

    Verifies that:
    * SPM_counters view output to CSV.
    """

    spm_counters_csv = (
        output_root / latest_schema / "csv" / "out_spm_counter_collection_trace.csv"
    )
    assert (
        spm_counters_csv.exists()
    ), f"out_spm_counter_collection_trace.csv not found for schema {latest_schema}: {spm_counters_csv}"


# ---------------------------------------------------------------------------
# CSV tests — schema 3.0.4 (hip_event output)
# ---------------------------------------------------------------------------


def test_csv_for_schema_3_0_4_changes_absent(output_root, old_schema):
    """Schema 3.0.4 additions must be absent for pre-3.0.4 schemas.

    Verifies that out_hip_event_trace.csv is not produced for schemas < 3.0.4.
    """
    if tuple(map(int, old_schema.split("."))) >= (3, 0, 4):
        print(
            f"Schema {old_schema} is newer than 3.0.4, calling test_csv_for_schema_3_0_4_changes_present instead"
        )
        return test_csv_for_schema_3_0_4_changes_present(output_root, old_schema)

    hip_event_csv = output_root / old_schema / "csv" / "out_hip_event_trace.csv"
    assert (
        not hip_event_csv.exists()
    ), f"out_hip_event_trace.csv should not be created for schema {old_schema}"


def test_csv_for_schema_3_0_4_changes_present(output_root, latest_schema):
    """Schema 3.0.4 additions must be present for the latest schema.

    Verifies that out_hip_event_trace.csv is produced with expected columns.
    """
    hip_event_csv = output_root / latest_schema / "csv" / "out_hip_event_trace.csv"
    assert (
        hip_event_csv.exists()
    ), f"out_hip_event_trace.csv not found for schema {latest_schema}: {hip_event_csv}"
    cols = _csv_columns(hip_event_csv)
    for expected in ("kind", "operation", "event_handle", "source_queue_id"):
        assert (
            expected in cols
        ), f"Column '{expected}' missing from hip_event CSV for schema {latest_schema}"


def test_csv_counter_collection_averages_replay_passes(output_root, latest_schema):
    """counters_collection must average a counter over kernel-replay passes, not sum them.

    make_db.py gives dispatch 1 SQ_WAVES in three replay passes with per-pass sums 16, 18
    and 20, GRBM_COUNT in pass 0 only, and SQ_INSTS_SALU in passes 1 and 2 only with sums
    5 and 6, and gives dispatch 2 untagged SQ_WAVES rows that sum to 8.
    """
    counter_csv = output_root / latest_schema / "csv" / "out_counter_collection_trace.csv"
    assert (
        counter_csv.exists()
    ), f"out_counter_collection_trace.csv not found for schema {latest_schema}: {counter_csv}"
    with open(counter_csv) as fh:
        values = {
            (int(row["Dispatch_Id"]), row["Counter_Name"]): float(row["Counter_Value"])
            for row in csv_mod.DictReader(fh)
        }
    assert values == {
        (1, "SQ_WAVES"): 18.0,
        (1, "GRBM_COUNT"): 1000.0,
        (1, "SQ_INSTS_SALU"): 5.5,
        (2, "SQ_WAVES"): 8.0,
    }, f"unexpected counter_collection values for schema {latest_schema}: {values}"


def test_pmc_events_report_replay_pass(output_root, latest_schema):
    """pmc_events must report each row's kernel-replay pass, and pass 0 for untagged rows.

    SQ_WAVES of dispatch 1 is left out because the view also lists that dispatch's SPM
    samples, which have no pass.
    """
    db_path = (
        output_root
        / latest_schema
        / "db"
        / f"schema_{latest_schema.replace('.', '_')}.db"
    )
    assert db_path.exists(), f"database not found for schema {latest_schema}: {db_path}"
    with sqlite3.connect(db_path) as conn:
        rows = conn.execute(
            "SELECT dispatch_id, counter_name, replay_pass, SUM(counter_value) "
            "FROM pmc_events "
            "WHERE counter_name IN ('GRBM_COUNT', 'SQ_INSTS_SALU') OR dispatch_id = 2 "
            "GROUP BY dispatch_id, counter_name, replay_pass"
        ).fetchall()
    assert sorted(rows) == [
        (1, "GRBM_COUNT", 0, 1000.0),
        (1, "SQ_INSTS_SALU", 1, 5.0),
        (1, "SQ_INSTS_SALU", 2, 6.0),
        (2, "SQ_WAVES", 0, 8.0),
    ], f"unexpected pmc_events passes for schema {latest_schema}: {rows}"


# ---------------------------------------------------------------------------
# Perfetto tests — old schemas
# ---------------------------------------------------------------------------


def test_pftrace_completes_without_error(old_schema, output_root):
    """Perfetto output must exist and be non-empty for pre-latest schemas."""
    pftrace = output_root / old_schema / "pftrace" / "out_results.pftrace"
    assert pftrace.exists(), f".pftrace not found for schema {old_schema}: {pftrace}"
    assert pftrace.stat().st_size > 0, f".pftrace is empty for schema {old_schema}"


# ---------------------------------------------------------------------------
# Perfetto tests — latest schema
# ---------------------------------------------------------------------------


def test_pftrace_completes_without_error_latest(output_root, latest_schema):
    """Perfetto output must exist and be non-empty for the latest schema."""
    pftrace = output_root / latest_schema / "pftrace" / "out_results.pftrace"
    assert pftrace.exists(), f".pftrace not found for schema {latest_schema}: {pftrace}"
    assert pftrace.stat().st_size > 0, f".pftrace is empty for schema {latest_schema}"


def test_pftrace_counter_values_average_replay_passes(output_root, latest_schema):
    """Perfetto counter values must be the kernel-replay pass means, not the pass sums.

    The writer annotates every kernel slice with each counter's total over all dispatches,
    so only counters that make_db.py collects on a single dispatch are checked: GRBM_COUNT
    (pass 0 only) and SQ_INSTS_SALU (passes 1 and 2, with sums 5 and 6).
    """
    pytest.importorskip("perfetto", reason="perfetto package not installed")
    from rocprofiler_sdk.pytest_utils.perfetto_reader import PerfettoReader

    pftrace = output_root / latest_schema / "pftrace" / "out_results.pftrace"
    assert pftrace.exists(), f".pftrace not found for schema {latest_schema}: {pftrace}"
    with PerfettoReader(str(pftrace)) as reader:
        rows = reader.query_tp(
            "SELECT args.key AS key, COALESCE(args.real_value, args.int_value) AS value "
            "FROM slice JOIN args USING (arg_set_id) "
            "WHERE args.key IN ('debug.GRBM_COUNT', 'debug.SQ_INSTS_SALU')"
        )
    values = {}
    for key, value in zip(rows["key"], rows["value"]):
        values.setdefault(key, set()).add(float(value))
    assert values == {
        "debug.GRBM_COUNT": {1000.0},
        "debug.SQ_INSTS_SALU": {5.5},
    }, f"unexpected Perfetto counter values for schema {latest_schema}: {values}"


# ---------------------------------------------------------------------------
# OTF2 tests — old schemas
# ---------------------------------------------------------------------------


def test_otf2_completes_without_error(old_schema, output_root):
    """OTF2 output must exist for pre-latest schemas."""
    pytest.importorskip("otf2", reason="otf2 package not installed")
    otf2_path = output_root / old_schema / "otf2" / "out_results.otf2"
    assert (
        otf2_path.exists()
    ), f"OTF2 output not found for schema {old_schema}: {otf2_path}"


def test_otf2_no_graph_launch_locations(old_schema, output_root):
    """OTF2 trace must not contain 'HIP Graph Launch' locations for pre-latest schemas."""
    pytest.importorskip("otf2", reason="otf2 package not installed")

    # Check if the schema is 3.0.2 and newer, then call the present test instead
    if tuple(map(int, old_schema.split("."))) >= (3, 0, 2):
        print(
            f"Schema {old_schema} is newer than 3.0.2, calling test_otf2_graph_launch_locations_latest instead"
        )
        return test_otf2_graph_launch_locations_latest(output_root, old_schema)

    # Otherwise, check for the absence of the changes
    otf2_path = output_root / old_schema / "otf2" / "out_results.otf2"
    assert (
        otf2_path.exists()
    ), f"OTF2 output not found for schema {old_schema}: {otf2_path}"
    hip_graph_locs = [
        n for n in _otf2_location_names(otf2_path) if "HIP Graph Launch" in n
    ]
    assert not hip_graph_locs, (
        f"Unexpected 'HIP Graph Launch' OTF2 locations for schema {old_schema}: "
        f"{hip_graph_locs}"
    )


# ---------------------------------------------------------------------------
# OTF2 tests — latest schema
# ---------------------------------------------------------------------------


def test_otf2_completes_without_error_latest(output_root, latest_schema):
    """OTF2 output must exist for the latest schema."""
    pytest.importorskip("otf2", reason="otf2 package not installed")
    otf2_path = output_root / latest_schema / "otf2" / "out_results.otf2"
    assert (
        otf2_path.exists()
    ), f"OTF2 output not found for schema {latest_schema}: {otf2_path}"


def test_otf2_graph_launch_locations_latest(output_root, latest_schema):
    """OTF2 trace must contain 'HIP Graph Launch' locations for the latest schema."""
    pytest.importorskip("otf2", reason="otf2 package not installed")
    otf2_path = output_root / latest_schema / "otf2" / "out_results.otf2"
    assert (
        otf2_path.exists()
    ), f"OTF2 output not found for schema {latest_schema}: {otf2_path}"
    loc_names = _otf2_location_names(otf2_path)
    hip_graph_locs = [n for n in loc_names if "HIP Graph Launch" in n]
    assert hip_graph_locs, (
        f"Expected 'HIP Graph Launch' OTF2 locations for schema {latest_schema} "
        f"but none found.  All locations: {loc_names}"
    )


if __name__ == "__main__":
    sys.exit(pytest.main(["-x", __file__] + sys.argv[1:]))
