# This module handles platform detection and compiler setup

if(NOT DEFINED HIP_PLATFORM OR (NOT HIP_PLATFORM STREQUAL "amd" AND NOT HIP_PLATFORM STREQUAL "nvidia"))
    message(FATAL_ERROR "HIP_PLATFORM must be set to 'amd' or 'nvidia'. Got: '${HIP_PLATFORM}'")
endif()

if(NOT DEFINED ROCM_PATH)
    if(DEFINED ENV{ROCM_PATH})
        set(ROCM_PATH $ENV{ROCM_PATH} CACHE PATH "ROCm installation path")
    else()
        set(ROCM_PATH "/opt/rocm" CACHE PATH "ROCm installation path")
    endif()
endif()

if(HIP_PLATFORM STREQUAL "nvidia")
    if(NOT DEFINED CUDA_PATH)
        if(DEFINED ENV{CUDA_PATH})
            set(CUDA_PATH $ENV{CUDA_PATH} CACHE PATH "CUDA installation path")
        else()
            set(CUDA_PATH "/usr/local/cuda" CACHE PATH "CUDA installation path")
        endif()
    endif()
endif()

if(NOT DEFINED HIP_PATH)
    if(DEFINED ENV{HIP_PATH})
        set(HIP_PATH $ENV{HIP_PATH} CACHE PATH "HIP installation path")
    else()
        set(HIP_PATH ${ROCM_PATH} CACHE PATH "HIP installation path")
    endif()
endif()

if(WIN32)
    set(HIPCONFIG_EXEC "hipconfig.exe")
else()
    set(HIPCONFIG_EXEC "hipconfig")
endif()

if(HIP_PLATFORM STREQUAL "amd")
    if(WIN32)
        set(CMAKE_HIP_COMPILER "${ROCM_PATH}/../lc/bin/amdclang++.exe")
    else()
        set(CMAKE_HIP_COMPILER "${ROCM_PATH}/llvm/bin/amdclang++")
    endif()
endif()

message(STATUS "Selected HIP Platform   : ${HIP_PLATFORM}")
if(HIP_PLATFORM STREQUAL "amd")
    message(STATUS "ROCm Path               : ${ROCM_PATH}")
    message(STATUS "HIP Path                : ${HIP_PATH}")
    message(STATUS "HIP Compiler            : ${CMAKE_HIP_COMPILER}")
elseif(HIP_PLATFORM STREQUAL "nvidia")
    message(STATUS "CUDA Path               : ${CUDA_PATH}")
endif()
