---
c_compilation:
  Unit_hipGetDeviceProp_ctest:
    <<: *level_2
    tags: [integration, rtc]
  Unit_hipBf16Compile_ctest:
    <<: *level_2
    tags: [integration, rtc]
  Unit_hipFp8Compile_ctest:
    <<: *level_2
    tags: [integration, rtc]
  Unit_hipFp4Compile_ctest:
    <<: *level_2
    tags: [integration, rtc]
  Unit_hipFp6Compile_ctest:
    <<: *level_2
    tags: [integration, rtc]
