---
# NOTE: All tags must be prefixed with the YAML filename (e.g., 'hip_specific_alloc').
# This allows filtering by area: ctest -L 'hip_specific' or ctest -L 'hip_specific_multigpu'.
hip_specific:
  Unit_Device__hip_hc_add8pk_Sanity_Positive:
    <<: *level_2
    tags: [hip_specific_deviceLib, hip_specific_hip_ext]
  Unit_Device__hip_hc_sub8pk_Sanity_Positive:
    <<: *level_2
    tags: [hip_specific_deviceLib, hip_specific_hip_ext]
  Unit_Device__hip_hc_mul8pk_Sanity_Positive:
    <<: *level_2
    tags: [hip_specific_deviceLib, hip_specific_hip_ext]
  Unit_Device__hip_hc_8pk_Negative_Parameters_RTC:
    <<: *level_2
    tags: [hip_specific_deviceLib, hip_specific_hip_ext]
  Unit_Device__hip_check_VGPRs:
    <<: *level_2
    tags: [hip_specific]
