---
launchBounds:
  Unit_Kernel_Launch_bounds_Positive_Basic:
    <<: *level_default
    tags: [attributes, kernel]
  Unit_Kernel_Launch_bounds_Negative_OutOfBounds:
    <<: *level_default
    tags: [attributes, kernel]
  Unit_Kernel_Launch_bounds_Negative_Parameters_RTC:
    <<: *level_default
    tags: [attributes, kernel]
