---
sanityTests:
  Unit_AccessMallocAcrossKernels:
    <<: *level_2
    tags: [model_1250]
  Unit_hipHostRegister_RegisterUnregister:
    <<: *level_2
    tags: [model_1250]
  Unit_hipHostRegister_Nbuf_MultiFlag_RegisterUnregister:
    <<: *level_2
    tags: [model_1250]
