---
# NOTE: All tags must be prefixed with the YAML filename (e.g., 'surface_alloc').
# This allows filtering by area: ctest -L 'surface' or ctest -L 'surface_multigpu'.
surface:
  Unit_hipCreateSurfaceObject_Negative_Parameters:
    <<: *level_2
    tags: [surface_surfobj, surface_texture, surface_image]
  Unit_hipDestroySurfaceObject_Negative_Parameters:
    <<: *level_2
    tags: [surface_surfobj, surface_texture, surface_image]
  Unit_surf1Dread_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf1Dwrite_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf1D_Positive_ReadWrite:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf1DLayeredread_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf1DLayeredwrite_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf1DLayered_Positive_ReadWrite:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf2Dread_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf2Dwrite_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf2D_Positive_ReadWrite:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf2DLayeredread_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf2DLayeredwrite_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf2DLayered_Positive_ReadWrite:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf3Dread_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf3Dwrite_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surf3D_Positive_ReadWrite:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surfCubemapread_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surfCubemapwrite_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surfCubemap_Positive_ReadWrite:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surfCubemapLayeredread_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surfCubemapLayeredwrite_Positive_Basic:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
  Unit_surfCubemapLayered_Positive_ReadWrite:
    <<: *level_2
    tags: [surface_surfop, surface_texture, surface_image]
