---
# NOTE: All tags must be prefixed with the YAML filename (e.g., 'vector_types_alloc').
# This allows filtering by area: ctest -L 'vector_types' or ctest -L 'vector_types_multigpu'.
vector_types:
  Unit_make_vector_SanityCheck_Basic_Host:
    <<: *level_2
    tags: [vector_types_types]
  Unit_make_vector_SanityCheck_Basic_Device:
    <<: *level_2
    tags: [vector_types_types]
  Unit_VectorAndVectorOperations_SanityCheck_Basic_Host:
    <<: *level_2
    tags: [vector_types_types]
  Unit_VectorAndValueTypeOperations_SanityCheck_Basic_Host:
    <<: *level_2
    tags: [vector_types_types]
  Unit_VectorAndVectorOperations_SanityCheck_Basic_Device:
    <<: *level_2
    tags: [vector_types_types]
  Unit_VectorAndValueTypeOperations_SanityCheck_Basic_Device:
    <<: *level_2
    tags: [vector_types_types]
  Unit_VectorStructuredBindings_SanityCheck_Basic_host:
    <<: *level_2
    tags: [vector_types_types]
  Unit_VectorConstexpr_SanityCheck_Basic_host_device:
    <<: *level_2
    tags: [vector_types_types]
  Unit_Vector_alignment_check:
    <<: *level_2
    tags: [vector_types_types]
  Unit_Vector_size_check:
    <<: *level_2
    tags: [vector_types_types]
  Unit_dim3_Empty_Positive_Device:
    <<: *level_2
    tags: [vector_types_types]
  Unit_dim3_X_Positive_Device:
    <<: *level_2
    tags: [vector_types_types]
  Unit_dim3_XY_Positive_Device:
    <<: *level_2
    tags: [vector_types_types]
  Unit_dim3_XYZ_Positive_Device:
    <<: *level_2
    tags: [vector_types_types]
  Unit_dim3_Empty_Positive_Host:
    <<: *level_2
    tags: [vector_types_types]
  Unit_dim3_X_Positive_Host:
    <<: *level_2
    tags: [vector_types_types]
  Unit_dim3_XY_Positive_Host:
    <<: *level_2
    tags: [vector_types_types]
  Unit_dim3_XYZ_Positive_Host:
    <<: *level_2
    tags: [vector_types_types]
