#!/usr/bin/env python3
"""
Generate one translation unit per (type, redop) instantiation of
ncclCeLocalReduceKernelVec.

Previously all 40 instantiations lived in a single ce_reduce.cc, which meant
the device linker paid for all of them in one single-threaded LLVM bitcode
link + O3 codegen pass (ld.lld). Two of those 40 kernels -- int8_t/uint8_t
Min and Max -- balloon to ~56K instructions each (vs ~5-6K for Sum/Prod on
the same types) because the compiler can't vectorize a byte-granularity
compare-select the way it does packed add/mul, and that alone made the whole
TU take ~48 minutes to compile. Splitting into one file per instantiation
lets ninja build them in parallel like every other device TU, bounding the
wall-clock cost by the slowest single kernel instead of the sum of all 40.

Output: one ce_reduce_impl.h (shared VecTrait/ReduceOp/kernel-template
definitions) plus one ce_reduce_<type>_<redop>.cpp per instantiation, each
defining a small host-callable launcher that ce_reduce.cc's dispatcher calls
into. The .cpp extension is intentional: it matches the existing
gensrc/*.cpp filter in src/CMakeLists.txt so these files are automatically
included in the non-device-linker (RDC) build and automatically excluded
(compiled separately by cmake/DeviceLinker.cmake instead) in the
device-linker build, with no additional filter rules needed.
"""
import os
import shutil
import sys

out_dir = sys.argv[1]

if os.path.exists(out_dir):
    for name in os.listdir(out_dir):
        path = os.path.join(out_dir, name)
        if os.path.isfile(path) or os.path.islink(path):
            os.remove(path)
        elif os.path.isdir(path):
            shutil.rmtree(path)
else:
    os.makedirs(out_dir)

COPYRIGHT = """/*
Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
"""

IMPL_HEADER = COPYRIGHT + '''
// CE AllReduce local-reduction kernel -- vectorized 16B load/store edition.
//
// Auto-generated by src/device/ce_reduce/generate.py. Shared by every
// ce_reduce_<type>_<redop>.cpp instantiation TU under gensrc/ce_reduce/.
// Do not edit by hand -- edit generate.py instead.
#pragma once

#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>
#include <hip/hip_bfloat16.h>
#include <stdint.h>
#include <algorithm>

// *********************************************************************************
// VecTrait<T>
//   LoadT     : 16-byte HIP vector used for a single memory transaction
//   W         : number of T elements packed into one 16-byte load/store
//   GpuUnroll : compile-time unroll factor (U) to balance ILP vs VGPRs
// *********************************************************************************
template <typename T>
struct VecTrait {
  using LoadT = uint4;
  static constexpr int W = (int)(16 / sizeof(T));
  static constexpr int GpuUnroll = 4;
};

template <>
struct VecTrait<float> {
  using LoadT = float4;
  static constexpr int W = 4;
  static constexpr int GpuUnroll = 4;
};
template <>
struct VecTrait<int32_t> {
  using LoadT = int4;
  static constexpr int W = 4;
  static constexpr int GpuUnroll = 4;
};
template <>
struct VecTrait<uint32_t> {
  using LoadT = uint4;
  static constexpr int W = 4;
  static constexpr int GpuUnroll = 4;
};

template <>
struct VecTrait<double> {
  using LoadT = double2;
  static constexpr int W = 2;
  static constexpr int GpuUnroll = 2;
};
template <>
struct VecTrait<int64_t> {
  using LoadT = longlong2;
  static constexpr int W = 2;
  static constexpr int GpuUnroll = 2;
};
template <>
struct VecTrait<uint64_t> {
  using LoadT = ulonglong2;
  static constexpr int W = 2;
  static constexpr int GpuUnroll = 2;
};

template <>
struct VecTrait<__half> {
  using LoadT = uint4;
  static constexpr int W = 8;
  static constexpr int GpuUnroll = 4;
};
template <>
struct VecTrait<hip_bfloat16> {
  using LoadT = uint4;
  static constexpr int W = 8;
  static constexpr int GpuUnroll = 4;
};

template <>
struct VecTrait<int8_t> {
  using LoadT = uint4;
  static constexpr int W = 16;
  static constexpr int GpuUnroll = 4;
};
template <>
struct VecTrait<uint8_t> {
  using LoadT = uint4;
  static constexpr int W = 16;
  static constexpr int GpuUnroll = 4;
};

// *********************************************************************************
// ReduceOp<T, RedOp> -- compile-time reduction functor
// 0=Sum  1=Prod  2=Min  3=Max
// *********************************************************************************
template <typename T, int RedOp>
struct ReduceOp;
template <typename T>
struct ReduceOp<T, 0> {
  __device__ __forceinline__ static T apply(T a, T b) {
    return a + b;
  }
};
template <typename T>
struct ReduceOp<T, 1> {
  __device__ __forceinline__ static T apply(T a, T b) {
    return a * b;
  }
};
template <typename T>
struct ReduceOp<T, 2> {
  __device__ __forceinline__ static T apply(T a, T b) {
    return a < b ? a : b;
  }
};
template <typename T>
struct ReduceOp<T, 3> {
  __device__ __forceinline__ static T apply(T a, T b) {
    return a > b ? a : b;
  }
};

// *********************************************************************************
// ncclCeLocalReduceKernelVec<T, RedOp, U>
//
// scatterBuf layout after CE scatter phase:
//   in[k * chunkElems + i]  =  element i contributed by rank k
//
// NOTE on the elementwise apply loops below: they are intentionally NOT
// marked #pragma unroll (unlike the load/store loops). For byte-granularity
// T (int8_t/uint8_t, W=16) combined with Min/Max, the compiler cannot lower
// the packed compare-select to a vector op the way it can add/mul, so a
// full static unroll of U*W (=64) scalar extract/compare/select/pack
// sequences balloons a single kernel to ~56K instructions and made this
// file's device-link/codegen step take ~48 minutes on its own. Leaving
// these as real loops keeps one copy of that sequence and lets it execute
// W times at runtime instead of being duplicated W times in the binary --
// semantics are unchanged, only code size/compile time is affected.
//
// NOTE on the `for (r = 1; r < nRanks; r++)` rank loops: they always disable
// LLVM's runtime loop-unroller, because, left to its own heuristics, LLVM was
// unrolling this loop (nRanks is a runtime value, not a compile-time
// constant) by up to 64x with generated remainder handling, on top of the
// already-manual U/W unroll/vectorization -- for int8_t/uint8_t Min/Max this
// produced ~900 PHI nodes and ~150 shufflevector ops per kernel and
// dominated llc's instruction-selection/register-alloc time. The manual
// U-way unroll and 16-byte vector loads already provide the intended ILP;
// this loop does not need LLVM unrolling it again.
//
// Whether the loop *vectorizer* also stays enabled is instantiation-specific
// (CE_REDUCE_VECTORIZE_OK, defined per .cpp before including this header --
// see generate.py's VECTORIZE_OK set). Measured on gfx950, >=1MB/rank:
//   - int8_t Min/Max/Sum, uint8_t Sum:  vectorize ON is ~10-12% faster.
//   - int32_t/uint32_t Sum/Prod:        vectorize OFF is ~2.2x faster (this
//     is the dominant win from disabling the runtime unroller in the first
//     place -- with the vectorizer also left on, most of that win disappears).
//   - uint8_t Min/Max:                  vectorize OFF is ~7-8% faster.
//   - everything else:                  no measurable difference either way.
// So this isn't a single global tradeoff -- each instantiation gets whichever
// setting measured faster, keyed by (type, redop) in generate.py.
// *********************************************************************************
template <typename T, int RedOp, int U>
__global__ __launch_bounds__(256) void ncclCeLocalReduceKernelVec(const T* __restrict__ in, T* __restrict__ out,
                                                                  int nRanks, size_t chunkElems) {
  using LT = typename VecTrait<T>::LoadT;
  constexpr int W = VecTrait<T>::W;

  union alignas(16) Pack {
    LT vec;
    T v[W];
  };

  const size_t nVec = chunkElems / W;
  const size_t tid = (size_t)blockIdx.x * blockDim.x + threadIdx.x;
  const size_t stride = (size_t)blockDim.x * gridDim.x;

  size_t vi = tid;

  // Strided unroll: thread tid handles vector indices
  //   vi, vi + stride, ..., vi + (U-1)*stride per outer step.
  for (; vi + (U - 1) * stride < nVec; vi += stride * U) {
    Pack acc[U];
#pragma unroll
    for (int i = 0; i < U; i++) {
      size_t elementOffset = (vi + (size_t)i * stride) * W;
      acc[i].vec = *reinterpret_cast<const LT*>(in + elementOffset);
    }

#ifdef CE_REDUCE_VECTORIZE_OK
#pragma clang loop unroll(disable)
#else
#pragma clang loop unroll(disable) vectorize(disable)
#endif
    for (int r = 1; r < nRanks; r++) {
      Pack tmp[U];
#pragma unroll
      for (int i = 0; i < U; i++) {
        size_t rankOffset = (size_t)r * chunkElems + (vi + (size_t)i * stride) * W;
        tmp[i].vec = *reinterpret_cast<const LT*>(in + rankOffset);
      }
#pragma unroll
      for (int i = 0; i < U; i++) {
        for (int k = 0; k < W; k++) {
          acc[i].v[k] = ReduceOp<T, RedOp>::apply(acc[i].v[k], tmp[i].v[k]);
        }
      }
    }
#pragma unroll
    for (int i = 0; i < U; i++) {
      size_t outOffset = (vi + (size_t)i * stride) * W;
      *reinterpret_cast<LT*>(out + outOffset) = acc[i].vec;
    }
  }

  // Drain remaining vectorized elements (one vector per thread per step).
  for (; vi < nVec; vi += stride) {
    Pack acc;
    size_t elementOffset = vi * W;
    acc.vec = *reinterpret_cast<const LT*>(in + elementOffset);

#ifdef CE_REDUCE_VECTORIZE_OK
#pragma clang loop unroll(disable)
#else
#pragma clang loop unroll(disable) vectorize(disable)
#endif
    for (int r = 1; r < nRanks; r++) {
      Pack tmp;
      size_t rankOffset = (size_t)r * chunkElems + vi * W;
      tmp.vec = *reinterpret_cast<const LT*>(in + rankOffset);

      for (int k = 0; k < W; k++) {
        acc.v[k] = ReduceOp<T, RedOp>::apply(acc.v[k], tmp.v[k]);
      }
    }
    *reinterpret_cast<LT*>(out + elementOffset) = acc.vec;
  }

  // Scalar tail (chunkElems % W != 0).
  const size_t tailBase = nVec * W;
  const size_t tailLen = chunkElems - tailBase;
  for (size_t i = tid; i < tailLen; i += stride) {
    T a = in[tailBase + i];
    for (int r = 1; r < nRanks; r++) {
      T v = in[(size_t)r * chunkElems + tailBase + i];
      a = ReduceOp<T, RedOp>::apply(a, v);
    }
    out[tailBase + i] = a;
  }
}
'''

LAUNCHER_TEMPLATE = COPYRIGHT + '''
// Auto-generated by src/device/ce_reduce/generate.py. Do not edit by hand.
//
// One instantiation of ncclCeLocalReduceKernelVec<{ctype}, {redname} /*={redval}*/, U>
// plus its host-callable launcher. See ce_reduce.cc for the dispatcher that
// calls ncclCeLocalReduceLaunch_{tag}_{redname}().
#include <cstdio>

{vec_define}#include "ce_reduce_impl.h"
#ifdef CE_REDUCE_VECTORIZE_OK
#undef CE_REDUCE_VECTORIZE_OK
#endif
#include "nccl.h"

ncclResult_t ncclCeLocalReduceLaunch_{tag}_{redname}(const void* tmpBuf, void* output, int nRanks,
                                                     size_t chunkElems, hipStream_t stream) {{
  using T = {ctype};
  constexpr int UnrollFactor = VecTrait<T>::GpuUnroll;
  const int threads = 256;
  // Cap blocks for CE DMA headroom (mirrors NCCL_CE_VEC_BLOCKS from the original single-file version).
  const int blocks = (int)std::min((size_t)46, (chunkElems / VecTrait<T>::W + (size_t)threads * UnrollFactor - 1) /
                                                    ((size_t)threads * UnrollFactor));

  (void)hipGetLastError();
  hipLaunchKernelGGL((ncclCeLocalReduceKernelVec<T, {redval}, UnrollFactor>), dim3(blocks), dim3(threads), 0, stream,
                     (const T*)tmpBuf, (T*)output, nRanks, chunkElems);
  hipError_t e = hipGetLastError();
  if (e != hipSuccess) {{
    printf("[CE reduce] launch failed: %d (%s)\\n", (int)e, hipGetErrorString(e));
    return ncclUnhandledCudaError;
  }}
  return ncclSuccess;
}}
'''

TYPES = [
    ("f32", "float"),
    ("f64", "double"),
    ("f16", "__half"),
    ("bf16", "hip_bfloat16"),
    ("i32", "int32_t"),
    ("u32", "uint32_t"),
    ("i64", "int64_t"),
    ("u64", "uint64_t"),
    ("i8", "int8_t"),
    ("u8", "uint8_t"),
]

REDOPS = [
    ("Sum", 0),
    ("Prod", 1),
    ("Min", 2),
    ("Max", 3),
]

# (type, redop) pairs where measurement (gfx950, >=1MB/rank chunks) showed
# leaving the loop vectorizer enabled on the rank-reduction loop is faster
# than disabling it -- see the NOTE above ncclCeLocalReduceKernelVec. Not in
# this set => vectorize(disable), which is faster (or a wash) for everything
# else, most dramatically int32_t/uint32_t Sum/Prod (~2.2x).
VECTORIZE_OK = {
    ("i8", "Min"),
    ("i8", "Max"),
    ("i8", "Sum"),
    ("u8", "Sum"),
}

with open(os.path.join(out_dir, "ce_reduce_impl.h"), "w") as f:
    f.write(IMPL_HEADER)

for tag, ctype in TYPES:
    for redname, redval in REDOPS:
        fname = "ce_reduce_%s_%s.cpp" % (tag, redname)
        vec_define = "#define CE_REDUCE_VECTORIZE_OK\n" if (tag, redname) in VECTORIZE_OK else ""
        with open(os.path.join(out_dir, fname), "w") as f:
            f.write(LAUNCHER_TEMPLATE.format(tag=tag, ctype=ctype, redname=redname, redval=redval,
                                              vec_define=vec_define))

print("-- Generated %d CE-reduce kernel TUs in %s" % (len(TYPES) * len(REDOPS), out_dir))
