// Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
// SPDX-License-Identifier: MIT
//
// Generates raw FFI bindings from the gpumetrics C headers with bindgen and wires
// up linking against libgpumetrics.
//
// Overridable via environment:
//   GPUMETRICS_INCLUDE_DIR  header search dir (default: ../../include)
//   GPUMETRICS_LIB_DIR      dir containing libgpumetrics.so (default: ../../build/src)

use std::env;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // Header/include directory (contains the `gpumetrics/` subdir).
    let include_dir = env::var("GPUMETRICS_INCLUDE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("../../include"));

    // Library directory containing libgpumetrics.so.
    let lib_dir = env::var("GPUMETRICS_LIB_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("../../build/src"));

    // Link against the shared core library.
    println!("cargo:rustc-link-lib=dylib=gpumetrics");
    println!("cargo:rustc-link-search=native={}", lib_dir.display());
    // Help downstream binaries/tests find the .so at runtime without LD_LIBRARY_PATH.
    println!("cargo:rustc-link-arg=-Wl,-rpath,{}", lib_dir.display());

    // Rerun triggers.
    println!("cargo:rerun-if-changed=wrapper.h");
    println!("cargo:rerun-if-env-changed=GPUMETRICS_INCLUDE_DIR");
    println!("cargo:rerun-if-env-changed=GPUMETRICS_LIB_DIR");
    let capi = include_dir.join("gpumetrics/capi.h");
    if capi.exists() {
        println!("cargo:rerun-if-changed={}", capi.display());
    }

    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_arg(format!("-I{}", include_dir.display()))
        // Bind only the gpumetrics surface, nothing from libc headers.
        .allowlist_function("gpum_.*")
        .allowlist_type("gpum_.*")
        .allowlist_var("GPUM_.*")
        // Rich, matchable enums for status/type/kind; the ABI is stable.
        .rustified_enum("gpum_status")
        .rustified_enum("gpum_value_type")
        .rustified_enum("gpum_entity_kind")
        .rustified_enum("gpum_scope_flags")
        .generate_comments(true)
        .layout_tests(false)
        .raw_line("// @generated by bindgen; do not edit by hand.")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .expect("failed to generate gpumetrics bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("bindings.rs");
    bindings
        .write_to_file(&out_path)
        .expect("failed to write bindings.rs");
}
