/*************************************************************************
 * Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

// Tests for the ncclSymkKernelListProfile[] kernel table introduced by the
// NCCL v2.31.2-1 sync.
//
// The sync added a parallel instrumented variant kernel list
// (ncclSymkKernelListProfile[]) alongside the base list
// (ncclSymkKernelList[]).  Both arrays are generated by
// src/device/symmetric/generate.py, indexed identically, and sized by
// ncclSymkKernelCount (an extern int const from librccl).
//
// These tests require the librccl symbols and live in rccl-UnitTests
// (not rccl-UnitTestsFixtures, which is header-only).

#include <gtest/gtest.h>

#include "sym_kernels.h"

namespace RcclUnitTesting
{

class SymkProfileKernelListTests : public ::testing::Test {};

TEST_F(SymkProfileKernelListTests, KernelCountIsPositive)
{
    EXPECT_GT(ncclSymkKernelCount, 0) << "ncclSymkKernelCount must not be zero";
}

TEST_F(SymkProfileKernelListTests, KernelCountIsSane)
{
    // There are currently 18 kernel IDs each instantiated over several type/redop
    // combinations.  An upper bound of 4096 catches runaway generator bugs.
    EXPECT_LE(ncclSymkKernelCount, 4096) << "ncclSymkKernelCount unexpectedly large";
}

TEST_F(SymkProfileKernelListTests, BaseKernelListHasNoNullEntries)
{
    for (int i = 0; i < ncclSymkKernelCount; i++)
        EXPECT_NE(ncclSymkKernelList[i], nullptr)
            << "null base kernel entry at index " << i;
}

TEST_F(SymkProfileKernelListTests, ProfileKernelListHasNoNullEntries)
{
    for (int i = 0; i < ncclSymkKernelCount; i++)
        EXPECT_NE(ncclSymkKernelListProfile[i], nullptr)
            << "null profiler-variant entry at index " << i;
}

// Each EnableProfiler=true variant is a distinct device function compiled with
// profiler instrumentation; its pointer must differ from the base variant.
TEST_F(SymkProfileKernelListTests, ProfileVariantsAreDistinctFromBaseVariants)
{
    bool anyDiffers = false;
    for (int i = 0; i < ncclSymkKernelCount; i++) {
        if (ncclSymkKernelListProfile[i] != ncclSymkKernelList[i]) {
            anyDiffers = true;
            break;
        }
    }
    EXPECT_TRUE(anyDiffers)
        << "every ncclSymkKernelListProfile[] entry equals the corresponding "
           "ncclSymkKernelList[] entry; EnableProfiler=true variants must be "
           "distinct device functions";
}

} // namespace RcclUnitTesting
