# Copyright (c) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Conservative single-file checks for the rocjitsu C++ style guide."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

DECORATIVE_COMMENT_PATTERN = re.compile(r"^\s*//[/ ]*[-=*_#]{4,}\s*$")
C_HEADER_PATTERN = re.compile(
    r"^(?P<prefix>\s*#\s*include\s*)<(?P<header>[a-z]+\.h)>(?P<suffix>.*)$"
)
ENUM_DEFINITION_PATTERN = re.compile(
    r"^\s*enum(?:\s+class)?\s+"
    r"(?:(?:alignas\s*\([^)]*\)|\[\[[^]]*\]\])\s*)*"
    r"(?P<name>[A-Za-z_]\w*)[^;{]*\{",
    re.MULTILINE,
)
RECORD_DECLARATION_PATTERN = re.compile(
    r"^\s*(?P<kind>class|struct)\s+"
    r"(?:(?:alignas\s*\([^)]*\)|\[\[[^]]*\]\])\s*)*"
    r"(?P<name>[A-Za-z_]\w*)"
    r"(?P<between>[^;{]*)\{",
    re.MULTILINE,
)
CALLABLE_PATTERN = re.compile(
    r"(?P<name>operator\s*[^\s(]+|~?[A-Za-z_]\w*)\s*\([^;{}]*\)"
    r"\s*(?:const\b|noexcept\b|override\b|final\b|->[^;{]+\s*)*[;{]"
)
NAMESPACE_PATTERN = re.compile(
    r"^\s*namespace(?:\s+(?P<name>[A-Za-z_]\w*(?:::[A-Za-z_]\w*)*))?\s*\{"
)
FORBIDDEN_LOGGING_PATTERN = re.compile(
    r"(?<![A-Za-z0-9_])(?P<name>(?:std::)?(?:printf|fprintf)|std::cerr)\b"
)
ACCESS_PATTERN = re.compile(r"^\s*(public|protected|private)\s*:\s*$")
DEFINE_PATTERN = re.compile(r"^\s*#\s*define\s+(?P<name>[A-Za-z_]\w*)", re.MULTILINE)
GLOBAL_CONSTANT_PATTERN = re.compile(
    r"^\s*(?:inline\s+)?(?:static\s+)?constexpr\s+[^;{}()]+\s+"
    r"(?P<name>[A-Za-z_]\w*)\s*(?:=|\{)",
    re.MULTILINE,
)

C_HEADER_REPLACEMENTS = {
    "assert.h": "cassert",
    "ctype.h": "cctype",
    "errno.h": "cerrno",
    "float.h": "cfloat",
    "inttypes.h": "cinttypes",
    "limits.h": "climits",
    "locale.h": "clocale",
    "math.h": "cmath",
    "setjmp.h": "csetjmp",
    "signal.h": "csignal",
    "stdarg.h": "cstdarg",
    "stddef.h": "cstddef",
    "stdint.h": "cstdint",
    "stdio.h": "cstdio",
    "stdlib.h": "cstdlib",
    "string.h": "cstring",
    "time.h": "ctime",
    "uchar.h": "cuchar",
    "wchar.h": "cwchar",
    "wctype.h": "cwctype",
}


@dataclass(frozen=True)
class Violation:
    """Describe one style-guide violation in a source file."""

    line: int
    rule: str
    message: str


@dataclass(frozen=True)
class Record:
    """Describe one class or struct body found by the lightweight scanner."""

    kind: str
    name: str
    line: int
    between: str
    body: str
    body_line: int
    end_line: int


def is_semantic_check_exempt(path: Path, contents: str) -> bool:
    """Return whether a file is generated, vendored, or a C-compatible API."""
    path_parts = set(path.parts)
    return (
        "external_headers" in path_parts
        or "generated" in path_parts
        or "AUTO-GENERATED by the amdisa codegen pipeline" in contents
        or path.suffix.lower() == ".c"
        or _is_c_compatible_api(path)
    )


def _is_c_compatible_api(path: Path) -> bool:
    normalized_path = path.as_posix()
    return "/lib/rocjitsu/include/rocjitsu/" in normalized_path


def normalize_direct_rules(path: Path, contents: str) -> str:
    """Apply unambiguous local rewrites for comments and C++ headers."""
    if is_semantic_check_exempt(path, contents):
        return contents

    normalized_lines: list[str] = []
    for line in contents.splitlines(keepends=True):
        line_without_ending = line.rstrip("\r\n")
        line_ending = line[len(line_without_ending) :]
        if DECORATIVE_COMMENT_PATTERN.fullmatch(line_without_ending):
            continue
        include_match = C_HEADER_PATTERN.fullmatch(line_without_ending)
        if include_match is not None and not _is_c_compatible_api(path):
            replacement = C_HEADER_REPLACEMENTS.get(include_match.group("header"))
            if replacement is not None:
                line_without_ending = (
                    f'{include_match.group("prefix")}<{replacement}>'
                    f'{include_match.group("suffix")}'
                )
        normalized_lines.append(line_without_ending + line_ending)
    return "".join(normalized_lines)


def _scrub_comments_and_literals(contents: str) -> str:
    """Replace comments and literal bodies with spaces while preserving lines."""
    output = list(contents)
    position = 0
    state = "code"
    quote = ""
    while position < len(contents):
        character = contents[position]
        next_character = contents[position + 1] if position + 1 < len(contents) else ""
        if state == "code":
            if character == "/" and next_character == "/":
                output[position] = output[position + 1] = " "
                position += 2
                state = "line-comment"
                continue
            if character == "/" and next_character == "*":
                output[position] = output[position + 1] = " "
                position += 2
                state = "block-comment"
                continue
            if character in {'"', "'"}:
                quote = character
                output[position] = " "
                position += 1
                state = "literal"
                continue
        elif state == "line-comment":
            if character == "\n":
                state = "code"
            else:
                output[position] = " "
        elif state == "block-comment":
            if character == "*" and next_character == "/":
                output[position] = output[position + 1] = " "
                position += 2
                state = "code"
                continue
            if character != "\n":
                output[position] = " "
        else:
            if character == "\\" and next_character:
                output[position] = " "
                if next_character != "\n":
                    output[position + 1] = " "
                position += 2
                continue
            if character == quote:
                state = "code"
            if character != "\n":
                output[position] = " "
        position += 1
    return "".join(output)


def _line_number(contents: str, position: int) -> int:
    return contents.count("\n", 0, position) + 1


def _matching_brace(contents: str, opening_position: int) -> int | None:
    depth = 0
    for position in range(opening_position, len(contents)):
        character = contents[position]
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return position
    return None


def _records(scrubbed_contents: str) -> list[Record]:
    records: list[Record] = []
    for match in RECORD_DECLARATION_PATTERN.finditer(scrubbed_contents):
        opening_position = match.end() - 1
        closing_position = _matching_brace(scrubbed_contents, opening_position)
        if closing_position is None:
            continue
        records.append(
            Record(
                kind=match.group("kind"),
                name=match.group("name"),
                line=_line_number(scrubbed_contents, match.start()),
                between=match.group("between"),
                body=scrubbed_contents[opening_position + 1 : closing_position],
                body_line=_line_number(scrubbed_contents, opening_position + 1),
                end_line=_line_number(scrubbed_contents, closing_position),
            )
        )
    return records


def _record_scope_lines(record: Record) -> list[tuple[int, str]]:
    """Return lines that begin at record scope, excluding nested bodies."""
    scoped_lines: list[tuple[int, str]] = []
    brace_depth = 0
    for offset, line in enumerate(record.body.splitlines()):
        if brace_depth == 0:
            scoped_lines.append((record.body_line + offset, line))
        brace_depth += line.count("{") - line.count("}")
    return scoped_lines


def _declared_callable(line: str) -> str | None:
    """Return the callable declared by one record-scope source line."""
    stripped_line = line.strip()
    if not stripped_line or stripped_line.startswith((":", "#", "using ")):
        return None
    declaration_end = stripped_line.find("{")
    if declaration_end < 0:
        declaration_end = stripped_line.find(";")
    if declaration_end < 0:
        return None
    declaration = stripped_line[: declaration_end + 1]
    matches = list(CALLABLE_PATTERN.finditer(declaration))
    if not matches:
        return None
    return matches[0].group("name").replace(" ", "")


def _check_structs(records: list[Record]) -> list[Violation]:
    violations: list[Violation] = []
    for record in records:
        if record.kind != "struct":
            continue
        reason: str | None = None
        if ":" in record.between:
            reason = "inherits from another type"
        elif re.search(r"^\s*(?:private|protected)\s*:", record.body, re.MULTILINE):
            reason = "contains non-public access sections"
        scoped_lines = _record_scope_lines(record)
        scoped_body = "\n".join(line for _, line in scoped_lines)
        if reason is None and re.search(
            rf"\b~?{re.escape(record.name)}\s*\(", scoped_body
        ):
            reason = "declares a constructor or destructor"
        elif reason is None and re.search(r"\boperator\s*[^\s(]*\s*\(", scoped_body):
            reason = "declares an operator"
        elif reason is None and any(
            _declared_callable(line) is not None for _, line in scoped_lines
        ):
            reason = "declares behavior"
        if reason is not None:
            violations.append(
                Violation(
                    record.line,
                    "struct-pod",
                    f"struct {record.name} {reason}; use class for non-POD types",
                )
            )
    return violations


def _check_class_sections(records: list[Record]) -> list[Violation]:
    violations: list[Violation] = []
    expected_order = {"public": 0, "protected": 1, "private": 2}
    for record in records:
        if record.kind != "class":
            continue
        sections: list[tuple[int, str]] = []
        for line_number, line in _record_scope_lines(record):
            access_match = ACCESS_PATTERN.match(line)
            if access_match is not None:
                sections.append((line_number, access_match.group(1)))
        seen_sections: set[str] = set()
        previous_order = -1
        for line_number, section in sections:
            if section in seen_sections:
                violations.append(
                    Violation(
                        line_number,
                        "class-sections",
                        f"class {record.name} has more than one {section}: section",
                    )
                )
            seen_sections.add(section)
            current_order = expected_order[section]
            if current_order < previous_order:
                violations.append(
                    Violation(
                        line_number,
                        "class-sections",
                        f"class {record.name} sections must be public, protected, private",
                    )
                )
            previous_order = max(previous_order, current_order)
    return violations


def _is_camel_case(name: str) -> bool:
    return bool(re.fullmatch(r"[A-Z][A-Za-z0-9]*", name))


def _is_snake_case(name: str) -> bool:
    return bool(re.fullmatch(r"[a-z][a-z0-9]*(?:_[a-z0-9]+)*_?", name))


def _check_naming(scrubbed_contents: str, records: list[Record]) -> list[Violation]:
    violations: list[Violation] = []
    type_definitions = [(record.name, record.line) for record in records] + [
        (
            match.group("name"),
            _line_number(scrubbed_contents, match.start("name")),
        )
        for match in ENUM_DEFINITION_PATTERN.finditer(scrubbed_contents)
    ]
    for name, line_number in type_definitions:
        if not _is_camel_case(name):
            violations.append(
                Violation(
                    line_number,
                    "type-name",
                    f"type name {name} must use CamelCase",
                )
            )

    for record in records:
        access = "public" if record.kind == "struct" else "private"
        for line_number, line in _record_scope_lines(record):
            access_match = ACCESS_PATTERN.match(line)
            if access_match is not None:
                access = access_match.group(1)
                continue
            name = _declared_callable(line)
            if name is not None and (
                name.startswith("operator")
                or name.startswith("~")
                or name == record.name
                or name.isupper()
            ):
                continue
            if name is not None and not _is_snake_case(name):
                violations.append(
                    Violation(
                        line_number,
                        "method-name",
                        f"method name {name} must use snake_case",
                    )
                )
                continue
            if name is not None:
                continue
            stripped_line = line.strip()
            if (
                not stripped_line.endswith(";")
                or "(" in stripped_line
                or "constexpr" in stripped_line
                or stripped_line.startswith(
                    (
                        "using ",
                        "typedef ",
                        "friend ",
                        "class ",
                        "struct ",
                        "enum ",
                        "static_assert",
                        "#",
                    )
                )
            ):
                continue
            member_match = re.search(
                r"\b(?P<name>[A-Za-z_]\w*)\s*(?:\[[^]]*\])?" r"\s*(?:=[^;]*)?;\s*$",
                stripped_line,
            )
            if member_match is None:
                continue
            member_name = member_match.group("name")
            if not _is_snake_case(member_name):
                violations.append(
                    Violation(
                        line_number,
                        "member-name",
                        f"data member {member_name} must use snake_case",
                    )
                )
            if access in {"private", "protected"} and not member_name.endswith("_"):
                violations.append(
                    Violation(
                        line_number,
                        "member-suffix",
                        f"non-public data member {member_name} requires a trailing underscore",
                    )
                )
            if access == "public" and member_name.endswith("_"):
                violations.append(
                    Violation(
                        line_number,
                        "member-suffix",
                        f"public data member {member_name} must not have a trailing underscore",
                    )
                )
    return violations


def _expected_namespace(path: Path) -> str | None:
    normalized_path = path.as_posix()
    for module_name in ("rocjitsu", "simdojo", "util"):
        if f"/lib/{module_name}/" in normalized_path:
            return module_name
    return None


def _check_namespaces(path: Path, scrubbed_contents: str) -> list[Violation]:
    expected_namespace = _expected_namespace(path)
    if expected_namespace is None:
        return []
    violations: list[Violation] = []
    brace_depth = 0
    line_start = 0
    for line in scrubbed_contents.splitlines(keepends=True):
        namespace_match = NAMESPACE_PATTERN.match(line)
        if namespace_match is not None and brace_depth == 0:
            namespace_name = namespace_match.group("name")
            if namespace_name is not None:
                top_level_name = namespace_name.split("::", 1)[0]
                opening_position = line_start + line.find("{", namespace_match.start())
                closing_position = _matching_brace(scrubbed_contents, opening_position)
                body = (
                    scrubbed_contents[opening_position + 1 : closing_position]
                    if closing_position is not None
                    else ""
                )
                forward_declarations_only = bool(body.strip()) and all(
                    re.fullmatch(
                        r"\s*(?:template\s*<[^;{}]+>\s*)?"
                        r"(?:class|struct)\s+[A-Za-z_]\w*\s*;\s*",
                        declaration,
                    )
                    for declaration in body.splitlines()
                    if declaration.strip()
                )
                if (
                    top_level_name != expected_namespace
                    and not forward_declarations_only
                ):
                    violations.append(
                        Violation(
                            _line_number(scrubbed_contents, line_start),
                            "namespace",
                            f"top-level namespace {top_level_name} must match module "
                            f"{expected_namespace}",
                        )
                    )
        brace_depth += line.count("{") - line.count("}")
        line_start += len(line)
    return violations


def _check_forbidden_logging(path: Path, scrubbed_contents: str) -> list[Violation]:
    if path.as_posix().endswith("/lib/util/include/util/log.h"):
        return []
    return [
        Violation(
            _line_number(scrubbed_contents, match.start()),
            "logging",
            f"{match.group('name')} is forbidden; use Logger from util/log.h",
        )
        for match in FORBIDDEN_LOGGING_PATTERN.finditer(scrubbed_contents)
    ]


def _check_preprocessor(scrubbed_contents: str) -> list[Violation]:
    violations: list[Violation] = []
    for match in DEFINE_PATTERN.finditer(scrubbed_contents):
        name = match.group("name")
        if name.endswith("_H_") or name.startswith(("RJ_", "ROCJITSU_")):
            continue
        violations.append(
            Violation(
                _line_number(scrubbed_contents, match.start()),
                "macro",
                f"macro {name} requires an explicit rocjitsu compatibility prefix",
            )
        )
    return violations


def _check_global_constants(
    scrubbed_contents: str, records: list[Record]
) -> list[Violation]:
    violations: list[Violation] = []
    non_namespace_depth = 0
    for line_number, line in enumerate(scrubbed_contents.splitlines(), start=1):
        namespace_open = NAMESPACE_PATTERN.match(line) is not None
        if non_namespace_depth == 0:
            match = GLOBAL_CONSTANT_PATTERN.match(line)
            if match is not None:
                name = match.group("name")
                if not re.fullmatch(r"k[A-Z][A-Za-z0-9]*", name):
                    violations.append(
                        Violation(
                            line_number,
                            "constant-name",
                            f"global constant {name} must use a kCamelCase name",
                        )
                    )
        opening_count = line.count("{")
        closing_count = line.count("}")
        if namespace_open:
            opening_count -= 1
        non_namespace_depth = max(
            0,
            non_namespace_depth + opening_count - closing_count,
        )
        if namespace_open and closing_count:
            non_namespace_depth += min(1, closing_count)
    return violations


def _has_required_doxygen(lines: list[str], declaration_index: int) -> bool:
    comment_lines: list[str] = []
    position = declaration_index - 1
    while position >= 0:
        stripped_line = lines[position].strip()
        if not stripped_line:
            if comment_lines:
                break
            position -= 1
            continue
        if stripped_line.startswith(("///", "//!", "/**", "*", "*/")):
            comment_lines.append(stripped_line)
            position -= 1
            continue
        if stripped_line.startswith(("template ", "[[")):
            position -= 1
            continue
        break
    documentation = "\n".join(reversed(comment_lines))
    return "@brief" in documentation and "@details" in documentation


def _check_doxygen(
    path: Path, contents: str, scrubbed_contents: str
) -> list[Violation]:
    if path.suffix.lower() not in {".h", ".hh", ".hpp"}:
        return []
    lines = contents.splitlines()
    violations: list[Violation] = []
    records = _records(scrubbed_contents)
    declaration_lines: set[int] = {record.line for record in records}
    declaration_lines.update(
        _line_number(scrubbed_contents, match.start())
        for match in ENUM_DEFINITION_PATTERN.finditer(scrubbed_contents)
    )
    for record in records:
        access = "public" if record.kind == "struct" else "private"
        for line_number, line in _record_scope_lines(record):
            access_match = ACCESS_PATTERN.match(line)
            if access_match is not None:
                access = access_match.group(1)
                continue
            if access == "public" and _declared_callable(line) is not None:
                declaration_lines.add(line_number)

    record_line_ranges = [range(record.line, record.end_line + 1) for record in records]
    for line_number, line in enumerate(scrubbed_contents.splitlines(), start=1):
        if any(line_number in line_range for line_range in record_line_ranges):
            continue
        if _declared_callable(line) is not None:
            declaration_lines.add(line_number)

    for line_number in sorted(declaration_lines):
        if not _has_required_doxygen(lines, line_number - 1):
            violations.append(
                Violation(
                    line_number,
                    "doxygen",
                    "public API declaration requires Doxygen @brief and @details",
                )
            )

    return violations


def check_style_rules(
    path: Path, contents: str, strict: bool = False
) -> list[Violation]:
    """Return semantic style violations for one owned C++ file."""
    if is_semantic_check_exempt(path, contents):
        return []
    scrubbed_contents = _scrub_comments_and_literals(contents)
    records = _records(scrubbed_contents)
    violations = [
        *_check_structs(records),
        *_check_class_sections(records),
        *_check_naming(scrubbed_contents, records),
        *_check_namespaces(path, scrubbed_contents),
        *_check_forbidden_logging(path, scrubbed_contents),
        *_check_preprocessor(scrubbed_contents),
        *_check_global_constants(scrubbed_contents, records),
    ]
    if strict:
        violations.extend(_check_doxygen(path, contents, scrubbed_contents))
    return sorted(violations, key=lambda violation: (violation.line, violation.rule))
