/*
 * Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
 *
 * SPDX-License-Identifier: MIT
 */

/**
 * GOLDEN-MASTER / CHARACTERIZATION TEST
 *
 * This file encodes the (entry-point × failure-reason) → hipError_t matrix
 * that is the CURRENT, correct behavior of HIP kernel-launch APIs.  It must
 * pass green against the unmodified CLR tree before any refactoring begins,
 * and must pass green again – unchanged – after the refactor.
 *
 * DO NOT EDIT this file during the behavior-preserving refactor described in
 * reintroduce_pr3151_plan.md.  A diff here is a regression.  Only PR-D
 * (deliberate code convergence) is allowed to touch it.
 *
 * Error codes used below:
 *   IV  = hipErrorInvalidValue
 *   IC  = hipErrorInvalidConfiguration
 *   CLT = hipErrorCooperativeLaunchTooLarge
 */

#include <cmath>
#include <cstring>

#include <hip/hip_runtime_api.h>
#include "hip/hip_ext.h"  // hipExtModuleLaunchKernel
#include <hip_test_common.hh>
#include <utils.hh>

#include "hip_module_common.hh"
#include "hip_module_launch_kernel_common.hh"

// ---------------------------------------------------------------------------
// Trivial __global__ kernel used by the runtime-API test cases
// (hipLaunchCooperativeKernel / hipLaunchKernel require a host-side symbol)
// ---------------------------------------------------------------------------
static __global__ void EmptyKernel() {}

// ---------------------------------------------------------------------------
// Helper: derive a block product that is strictly greater than maxThreadsPerBlock
// while keeping each individual dim <= its per-axis maximum.
// We use dim = cbrt(max)+1 across all three axes.
// ---------------------------------------------------------------------------
static unsigned int OverBlockDim(int deviceId) {
  return static_cast<unsigned int>(
      std::ceil(std::cbrt(
          static_cast<double>(GetDeviceAttribute(hipDeviceAttributeMaxThreadsPerBlock, deviceId)))) +
      1u);
}

// ---------------------------------------------------------------------------
// TEST_CASE 1 — hipModuleLaunchKernel
//
// Source: hipamd/src/hip_module.cpp lines 601-624
// All failure reasons (zero grid, zero block, block>maxWG, shared>max) return
// hipErrorInvalidValue (IV) because every pre-check at this site uses
// HIP_RETURN(hipErrorInvalidValue).
// ---------------------------------------------------------------------------
HIP_TEST_CASE(Unit_hipLaunchErrorCodes_ModuleLaunchKernel) {
  auto mg = ModuleGuard::InitModule("launch_kernel_module.code");
  hipFunction_t f = GetKernel(mg.module(), "NOPKernel");

  const unsigned int maxShared =
      static_cast<unsigned int>(GetDeviceAttribute(hipDeviceAttributeMaxSharedMemoryPerBlock, 0));
  const unsigned int overDim = OverBlockDim(0);

  SECTION("gridX == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchKernel(f, 0, 1, 1, 1, 1, 1, 0, nullptr, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("gridY == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchKernel(f, 1, 0, 1, 1, 1, 1, 0, nullptr, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("gridZ == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchKernel(f, 1, 1, 0, 1, 1, 1, 0, nullptr, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("blockX == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchKernel(f, 1, 1, 1, 0, 1, 1, 0, nullptr, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("blockY == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchKernel(f, 1, 1, 1, 1, 0, 1, 0, nullptr, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("blockZ == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchKernel(f, 1, 1, 1, 1, 1, 0, 0, nullptr, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("block product > maxThreadsPerBlock -> IV") {
    // hip_module.cpp:603-605: HIPLaunchParams check -> !IsValidConfig() ||
    // local_.product() > maxWorkGroupSize_ -> HIP_RETURN(hipErrorInvalidValue)
    HIP_CHECK_ERROR(
        hipModuleLaunchKernel(f, 1, 1, 1, overDim, overDim, overDim, 0, nullptr, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("sharedMemBytes > maxSharedMemoryPerBlock -> IV") {
    // hip_module.cpp:608-610: explicit sharedMemBytes check -> IV
    HIP_CHECK_ERROR(
        hipModuleLaunchKernel(f, 1, 1, 1, 1, 1, 1, maxShared + 1u, nullptr, nullptr, nullptr),
        hipErrorInvalidValue);
  }
}

// ---------------------------------------------------------------------------
// TEST_CASE 2 — hipExtModuleLaunchKernel
//
// Source: hipamd/src/hip_module.cpp lines 626-673
//
// Check order at this site:
//   [A] line 652: !IsValidConfig() || local_.product() > maxWGS  -> IC
//   [B] line 657: sharedMemBytes > localMemSizePerCU             -> IV
//   [C] line 661: global_[i] == 0                                -> IV
//   [D] line 666: local_[i] == 0 (redundant after [A])           -> IV
//
// NOTE: hipExtModuleLaunchKernel uses amd::LaunchParams (not HIPLaunchParams),
// with hipParams=false.  The LaunchParams base ctor sets validConfig_=false
// when local_[i]==0 (ndrange.hpp:142-144).  Therefore a zero local dim
// fires check [A] first and returns IC — not IV from check [D].
//
// For global==0: LaunchParams base does NOT set validConfig_=false for
// global==0, so [A] passes and [C] fires -> IV.
//
// Multi-failure ordering (locks precedence for canonical checker):
//   - block==0 AND shared>max: [A] fires first -> IC (not IV from [B])
//   - grid==0 AND shared>max:  [A] passes, [B] fires first -> IV
// ---------------------------------------------------------------------------
HIP_TEST_CASE(Unit_hipLaunchErrorCodes_ExtModuleLaunchKernel) {
  auto mg = ModuleGuard::InitModule("launch_kernel_module.code");
  hipFunction_t f = GetKernel(mg.module(), "NOPKernel");

  const unsigned int maxShared =
      static_cast<unsigned int>(GetDeviceAttribute(hipDeviceAttributeMaxSharedMemoryPerBlock, 0));
  const unsigned int overDim = OverBlockDim(0);

  // Single-failure cases -------------------------------------------------------

  SECTION("globalWorkSizeX == 0 -> IV") {
    // hip_module.cpp:661-664: global_[0]==0 check -> IV
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 0, 1, 1, 1, 1, 1, 0, nullptr, nullptr, nullptr,
                                 nullptr, nullptr, 0u),
        hipErrorInvalidValue);
  }
  SECTION("globalWorkSizeY == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 1, 0, 1, 1, 1, 1, 0, nullptr, nullptr, nullptr,
                                 nullptr, nullptr, 0u),
        hipErrorInvalidValue);
  }
  SECTION("globalWorkSizeZ == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 1, 1, 0, 1, 1, 1, 0, nullptr, nullptr, nullptr,
                                 nullptr, nullptr, 0u),
        hipErrorInvalidValue);
  }
  SECTION("localWorkSizeX == 0 -> IC") {
    // hip_module.cpp:652: LaunchParams ctor sets validConfig_=false -> IC
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 1, 1, 1, 0, 1, 1, 0, nullptr, nullptr, nullptr,
                                 nullptr, nullptr, 0u),
        hipErrorInvalidConfiguration);
  }
  SECTION("localWorkSizeY == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 1, 1, 1, 1, 0, 1, 0, nullptr, nullptr, nullptr,
                                 nullptr, nullptr, 0u),
        hipErrorInvalidConfiguration);
  }
  SECTION("localWorkSizeZ == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 1, 1, 1, 1, 1, 0, 0, nullptr, nullptr, nullptr,
                                 nullptr, nullptr, 0u),
        hipErrorInvalidConfiguration);
  }
  SECTION("block product > maxThreadsPerBlock -> IC") {
    // hip_module.cpp:652-655: local_.product() > maxWorkGroupSize_ -> IC
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, overDim, overDim, overDim, overDim, overDim, overDim, 0,
                                 nullptr, nullptr, nullptr, nullptr, nullptr, 0u),
        hipErrorInvalidConfiguration);
  }
  SECTION("sharedMemBytes > maxSharedMemoryPerBlock -> IV") {
    // hip_module.cpp:657-659: explicit sharedMemBytes check -> IV
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 1, 1, 1, 1, 1, 1, maxShared + 1u, nullptr, nullptr,
                                 nullptr, nullptr, nullptr, 0u),
        hipErrorInvalidValue);
  }

  // Multi-failure ordering SECTIONs --------------------------------------------

  SECTION("block==0 AND shared>max: IC wins (check [A] before [B])") {
    // hip_module.cpp:652 fires before line 657.
    // local==0 -> validConfig_=false -> IC, regardless of shared overflow.
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 1, 1, 1, 0, 1, 1, maxShared + 1u, nullptr, nullptr,
                                 nullptr, nullptr, nullptr, 0u),
        hipErrorInvalidConfiguration);
  }
  SECTION("grid==0 AND shared>max: IV from shared wins (check [B] before [C])") {
    // hip_module.cpp: global==0 does NOT trip IsValidConfig(), so [A] passes.
    // [B] at line 657 fires before [C] at line 661 -> IV from shared check.
    HIP_CHECK_ERROR(
        hipExtModuleLaunchKernel(f, 0, 1, 1, 1, 1, 1, maxShared + 1u, nullptr, nullptr,
                                 nullptr, nullptr, nullptr, 0u),
        hipErrorInvalidValue);
  }
}

// ---------------------------------------------------------------------------
// TEST_CASE 3 — hipModuleLaunchCooperativeKernel
//
// Source: hipamd/src/hip_module.cpp lines 697-739
// All failure reasons return hipErrorInvalidValue (IV): the site uses
// HIPLaunchParams and routes every check to HIP_RETURN(hipErrorInvalidValue).
// (Verified by the existing Negative_Parameters test in
//  hipModuleLaunchCooperativeKernel.cc which asserts IV for all dims.)
// ---------------------------------------------------------------------------
HIP_TEST_CASE(Unit_hipLaunchErrorCodes_ModuleLaunchCooperativeKernel) {
  auto mg = ModuleGuard::InitModule("launch_kernel_module.code");
  if (!DeviceAttributesSupport(0, hipDeviceAttributeCooperativeLaunch)) {
    HIP_SKIP_TEST(HipTest::SkipReason::kCooperativeLaunchUnsupported);
  }
  hipFunction_t f = GetKernel(mg.module(), "NOPKernel");

  const unsigned int maxShared =
      static_cast<unsigned int>(GetDeviceAttribute(hipDeviceAttributeMaxSharedMemoryPerBlock, 0));
  const unsigned int overDim = OverBlockDim(0);

  SECTION("gridDimX == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchCooperativeKernel(f, 0, 1, 1, 1, 1, 1, 0, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("gridDimY == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchCooperativeKernel(f, 1, 0, 1, 1, 1, 1, 0, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("gridDimZ == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchCooperativeKernel(f, 1, 1, 0, 1, 1, 1, 0, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("blockDimX == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchCooperativeKernel(f, 1, 1, 1, 0, 1, 1, 0, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("blockDimY == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchCooperativeKernel(f, 1, 1, 1, 1, 0, 1, 0, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("blockDimZ == 0 -> IV") {
    HIP_CHECK_ERROR(
        hipModuleLaunchCooperativeKernel(f, 1, 1, 1, 1, 1, 0, 0, nullptr, nullptr),
        hipErrorInvalidValue);
  }
  SECTION("block product > maxThreadsPerBlock -> IV") {
    // hip_module.cpp:719-722: !IsValidConfig() || local_.product() > maxWGS -> IV
    HIP_CHECK_ERROR(
        hipModuleLaunchCooperativeKernel(f, 1, 1, 1, overDim, overDim, overDim, 0, nullptr,
                                         nullptr),
        hipErrorInvalidValue);
  }
#if HT_AMD  // Disabled on NVIDIA; see EXSWHTEC-351
  SECTION("sharedMemBytes > maxSharedMemoryPerBlock -> IV") {
    // hip_module.cpp:724-726: explicit sharedMemBytes check -> IV
    HIP_CHECK_ERROR(
        hipModuleLaunchCooperativeKernel(f, 1, 1, 1, 1, 1, 1, maxShared + 1u, nullptr, nullptr),
        hipErrorInvalidValue);
  }
#endif
}

// ---------------------------------------------------------------------------
// TEST_CASE 4 — hipDrvLaunchKernelEx
//
// Source: hipamd/src/hip_module.cpp lines 1410-1500
//
// Check order at this site:
//   [A] line 1441: !IsValidConfig() -> IC  (HIPLaunchParams: fires on overflow)
//   then dispatches to ihipModuleLaunchKernel -> ihipLaunchKernel_validate (Layer 2)
//   Layer 2 (hip_module.cpp:326-345):
//   [L2a] line 326: global_[i]==0 -> IC
//   [L2b] line 331: local_[i]==0  -> IC
//   [L2c] line 338: shared > localMem -> IV  (but Layer 2 not reached for these)
//   [L2d] line 343: local_.product() > maxWGS -> IC
//
// Zero-grid and zero-block fall through [A] (HIPLaunchParams global is
// gridDim*blockDim which is non-zero if only one of the pair is zero, but
// if blockDim!=0 and gridDim==0 then global==0).  They reach Layer 2 -> IC.
// block>maxWG: [A] does not catch this (HIPLaunchParams only checks overflow).
// It falls through to Layer 2 [L2d] -> IC.
//
// Multi-failure ordering:
//   - grid==0 AND block==0: global==0 trips [L2a] first -> IC
//   - grid==0 AND block>maxWG: global==0 trips [L2a] first -> IC
//
// TODO: cluster-indivisible SECTION omitted — no clean hipDeviceAttribute gate
// for cluster launch support was found in the test infrastructure.  The
// prop.clusterLaunch field is used in hipDrvLaunchKernelEx.cc but requires
// hipGetDeviceProperties, not a DeviceAttributesSupport() guard.
// ---------------------------------------------------------------------------
HIP_TEST_CASE(Unit_hipLaunchErrorCodes_DrvLaunchKernelEx) {
  // hipDrvLaunchKernelEx requires a loaded module; use NOPKernel from the
  // standard launch_kernel_module fixture.
  auto mg = ModuleGuard::InitModule("launch_kernel_module.code");
  hipFunction_t f = GetKernel(mg.module(), "NOPKernel");

  const unsigned int overDim = OverBlockDim(0);

  // Build a valid base config and a cooperative attribute (mirrors existing
  // hipDrvLaunchKernelEx.cc pattern).
  HIP_LAUNCH_CONFIG validCfg = {};
  validCfg.gridDimX = 1;
  validCfg.gridDimY = 1;
  validCfg.gridDimZ = 1;
  validCfg.blockDimX = 1;
  validCfg.blockDimY = 1;
  validCfg.blockDimZ = 1;
  validCfg.sharedMemBytes = 0;
  validCfg.hStream = nullptr;
  validCfg.attrs = nullptr;
  validCfg.numAttrs = 0;

  auto makeCfg = [&](unsigned int gx, unsigned int gy, unsigned int gz,
                     unsigned int bx, unsigned int by, unsigned int bz) -> HIP_LAUNCH_CONFIG {
    HIP_LAUNCH_CONFIG c = validCfg;
    c.gridDimX = gx; c.gridDimY = gy; c.gridDimZ = gz;
    c.blockDimX = bx; c.blockDimY = by; c.blockDimZ = bz;
    return c;
  };

  SECTION("gridDimX == 0 -> IC (Layer 2: global_[0]==0 -> IC)") {
    // hip_module.cpp:1441 passes (HIPLaunchParams: global=0*1=0, but ctor
    // sets global_=0 which is NOT an overflow -> validConfig_=true).
    // Falls through to Layer 2, line 326-329 -> IC.
    auto cfg = makeCfg(0, 1, 1, 1, 1, 1);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }
  SECTION("gridDimY == 0 -> IC") {
    auto cfg = makeCfg(1, 0, 1, 1, 1, 1);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }
  SECTION("gridDimZ == 0 -> IC") {
    auto cfg = makeCfg(1, 1, 0, 1, 1, 1);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }
  SECTION("blockDimX == 0 -> IC (Layer 2: local_[0]==0 -> IC)") {
    // hip_module.cpp:1441 passes; Layer 2 line 331-334 -> IC.
    auto cfg = makeCfg(1, 1, 1, 0, 1, 1);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }
  SECTION("blockDimY == 0 -> IC") {
    auto cfg = makeCfg(1, 1, 1, 1, 0, 1);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }
  SECTION("blockDimZ == 0 -> IC") {
    auto cfg = makeCfg(1, 1, 1, 1, 1, 0);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }
  SECTION("block product > maxThreadsPerBlock -> IC (Layer 2: local_.product() > maxWGS -> IC)") {
    // hip_module.cpp:1441 passes (no overflow); Layer 2 line 343-345 -> IC.
    auto cfg = makeCfg(1, 1, 1, overDim, overDim, overDim);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }

  // Multi-failure ordering SECTIONs --------------------------------------------

  SECTION("grid==0 AND block==0: Layer 2 global check [L2a] fires before local [L2b] -> IC") {
    // hip_module.cpp Layer 2 line 326 (global_[0]==0) fires before line 331 -> IC.
    auto cfg = makeCfg(0, 1, 1, 0, 1, 1);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }
  SECTION("grid==0 AND block>maxWG: Layer 2 global check [L2a] fires before [L2d] -> IC") {
    // hip_module.cpp Layer 2 line 326 fires before line 343 -> IC.
    auto cfg = makeCfg(0, 1, 1, overDim, overDim, overDim);
    HIP_CHECK_ERROR(hipDrvLaunchKernelEx(&cfg, f, nullptr, nullptr),
                    hipErrorInvalidConfiguration);
  }
}

// ---------------------------------------------------------------------------
// TEST_CASE 5 — hipLaunchCooperativeKernel (runtime API)
//
// Source: hipamd/src/hip_module.cpp lines 932-984
//   hipLaunchCooperativeKernel_common (line 932) -> ihipLaunchKernel_validate
//
// Check order at hipLaunchCooperativeKernel_common:
//   [A] line 965: !IsValidConfig() || local_.product() > maxWGS -> IC
//   [B] line 970: sharedMemBytes > localMemSizePerCU -> CoopLaunchTooLarge
//   then ihipModuleLaunchKernel -> ihipLaunchKernel_validate (Layer 2 with
//   CooperativeGroups flag, which checks grid blocks vs max -> CoopLaunchTooLarge)
//
// Gated on hipDeviceAttributeCooperativeLaunch.
// ---------------------------------------------------------------------------
HIP_TEST_CASE(Unit_hipLaunchErrorCodes_LaunchCooperativeKernel) {
  if (!DeviceAttributesSupport(0, hipDeviceAttributeCooperativeLaunch)) {
    HIP_SKIP_TEST(HipTest::SkipReason::kCooperativeLaunchUnsupported);
  }

  const unsigned int maxShared =
      static_cast<unsigned int>(GetDeviceAttribute(hipDeviceAttributeMaxSharedMemoryPerBlock, 0));
  const unsigned int overDim = OverBlockDim(0);

  SECTION("gridDim.x == 0 -> IC") {
    // hipLaunchCooperativeKernel_common line 965: HIPLaunchParams global=0*1=0
    // -> IsValidConfig() still true (no overflow), but local_.product()==1 which
    // is <= maxWGS, so [A] passes. Falls to Layer 2 line 326 -> IC.
    HIP_CHECK_ERROR(
        hipLaunchCooperativeKernel(reinterpret_cast<const void*>(EmptyKernel),
                                   dim3(0, 1, 1), dim3(1, 1, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("gridDim.y == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipLaunchCooperativeKernel(reinterpret_cast<const void*>(EmptyKernel),
                                   dim3(1, 0, 1), dim3(1, 1, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("gridDim.z == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipLaunchCooperativeKernel(reinterpret_cast<const void*>(EmptyKernel),
                                   dim3(1, 1, 0), dim3(1, 1, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("blockDim.x == 0 -> IC") {
    // HIPLaunchParams: global = 1*0 = 0; IsValidConfig() true (no overflow);
    // Layer 2 line 326 (global_[0]==0) -> IC.
    HIP_CHECK_ERROR(
        hipLaunchCooperativeKernel(reinterpret_cast<const void*>(EmptyKernel),
                                   dim3(1, 1, 1), dim3(0, 1, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("blockDim.y == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipLaunchCooperativeKernel(reinterpret_cast<const void*>(EmptyKernel),
                                   dim3(1, 1, 1), dim3(1, 0, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("blockDim.z == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipLaunchCooperativeKernel(reinterpret_cast<const void*>(EmptyKernel),
                                   dim3(1, 1, 1), dim3(1, 1, 0), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("block product > maxThreadsPerBlock -> IC") {
    // hipLaunchCooperativeKernel_common line 965:
    // local_.product() > maxWorkGroupSize_ -> IC.
    HIP_CHECK_ERROR(
        hipLaunchCooperativeKernel(reinterpret_cast<const void*>(EmptyKernel),
                                   dim3(1, 1, 1), dim3(overDim, overDim, overDim),
                                   nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("sharedMemBytes > maxSharedMemoryPerBlock -> CoopLaunchTooLarge") {
    // hipLaunchCooperativeKernel_common line 970-972:
    // sharedMemBytes > localMemSizePerCU -> hipErrorCooperativeLaunchTooLarge.
    HIP_CHECK_ERROR(
        hipLaunchCooperativeKernel(reinterpret_cast<const void*>(EmptyKernel),
                                   dim3(1, 1, 1), dim3(1, 1, 1),
                                   nullptr, maxShared + 1u, nullptr),
        hipErrorCooperativeLaunchTooLarge);
  }
}

// ---------------------------------------------------------------------------
// TEST_CASE 6 — hipLaunchKernel (runtime API)
//
// Source: hipamd/src/hip_module.cpp lines 907-912 ->
//         hipLaunchKernel_common (line 894) ->
//         ihipLaunchKernel (hip_platform.cpp line 690) ->
//         HIPLaunchParams + IsValidConfig() (line 734) -> IC
//         then falls to Layer 2 for zero dims.
//
// Zero grid/block: HIPLaunchParams produces global_[i]=0; IsValidConfig()
// does not catch zero (only 32-bit overflow); falls to Layer 2 -> IC.
// ---------------------------------------------------------------------------
HIP_TEST_CASE(Unit_hipLaunchErrorCodes_LaunchKernel) {
  SECTION("gridDim.x == 0 -> IC") {
    // hip_platform.cpp:734: IsValidConfig() passes (no overflow);
    // Layer 2 line 326 -> IC.
    HIP_CHECK_ERROR(
        hipLaunchKernel(reinterpret_cast<const void*>(EmptyKernel),
                        dim3(0, 1, 1), dim3(1, 1, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("gridDim.y == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipLaunchKernel(reinterpret_cast<const void*>(EmptyKernel),
                        dim3(1, 0, 1), dim3(1, 1, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("gridDim.z == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipLaunchKernel(reinterpret_cast<const void*>(EmptyKernel),
                        dim3(1, 1, 0), dim3(1, 1, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("blockDim.x == 0 -> IC") {
    // HIPLaunchParams: global = 1*0 = 0 -> Layer 2 line 326 -> IC.
    HIP_CHECK_ERROR(
        hipLaunchKernel(reinterpret_cast<const void*>(EmptyKernel),
                        dim3(1, 1, 1), dim3(0, 1, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("blockDim.y == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipLaunchKernel(reinterpret_cast<const void*>(EmptyKernel),
                        dim3(1, 1, 1), dim3(1, 0, 1), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
  SECTION("blockDim.z == 0 -> IC") {
    HIP_CHECK_ERROR(
        hipLaunchKernel(reinterpret_cast<const void*>(EmptyKernel),
                        dim3(1, 1, 1), dim3(1, 1, 0), nullptr, 0, nullptr),
        hipErrorInvalidConfiguration);
  }
}
