// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Advanced Micro Devices, Inc.

/* Test-only factory to construct detail::aql_queue_t + its private nested
   aql_dispatch_t.  Both classes live entirely inside queue.cpp (not in any
   header), so the factory is defined in queue.cpp where the types are
   visible; this header just forward-declares it.  Friend declarations on
   aql_queue_t and aql_queue_t::aql_dispatch_t grant access.

   The factory creates the queue and dispatch through process->create<>,
   so destruction must go through process->destroy() (the dispatch first,
   then the queue, to satisfy ~aql_queue_t's sweep-on-destroy invariant).

   Before calling the factory, set up MockOsDriver to:
     * Return aql_packet_size (64) bytes of an HSA AQL packet from
       xfer_host_memory_partial at the queue's ring_base_address.
     * Return 64 bytes of a kernel descriptor from
       xfer_global_memory_partial at the packet's kernel_object address.
   */

#ifndef AMD_DBGAPI_TEST_UNIT_SUPPORT_AQL_DISPATCH_TEST_ACCESS_H
#define AMD_DBGAPI_TEST_UNIT_SUPPORT_AQL_DISPATCH_TEST_ACCESS_H 1

#include "amd-dbgapi.h"
#include "os_driver.h"

#include <utility>

namespace amd::dbgapi
{
class agent_t;
class dispatch_t;
class process_t;
class queue_t;
} /* namespace amd::dbgapi */

namespace amd::dbgapi::test
{

/* Returns {queue, dispatch}.  Both are owned by the process; the caller
   must process.destroy(dispatch) before process.destroy(queue).  Queue
   and dispatch IDs are auto-generated by the handle_object_set_t (the
   id-providing create_object overload is not exposed on process_t).  */
std::pair<queue_t *, dispatch_t *> make_aql_queue_and_dispatch_for_test (
  process_t &process, const agent_t &agent,
  const os_queue_snapshot_entry_t &os_queue_info,
  amd_dbgapi_os_queue_packet_id_t packet_id);

} /* namespace amd::dbgapi::test */

#endif /* AMD_DBGAPI_TEST_UNIT_SUPPORT_AQL_DISPATCH_TEST_ACCESS_H */
