# TODO: add System Info
#      - title: "System Info"
#        data_path: ["1. System Info", "1.1"]
#        collapsed: true
sections:
  - title: "High Level Analysis"
    collapsed: true
    class: "sysinfo-section"
    subsections:
      - title: "System Speed-of-Light"
        data_path: ["2. System Speed-of-Light", "2.1 System Speed-of-Light"]
        collapsed: true
      - title: "Memory Chart"
        data_path: ["3. Memory Chart", "3.1 Memory Chart"]
        collapsed: true
        tui_style: "mem_chart"

  - title: "Detailed Block Analysis"
    collapsed: true
    class: "block-section"
    subsections:
      - arch_config_data: true
        exclude_keys:
          - "0. Top Stats"
          - "1. System Info"
          - "2. System Speed-of-Light"
          - "3. Memory Chart"
          - "4. Roofline"
        collapsed: true

  - title: "Source Level Analysis"
    collapsed: true
    class: "source-section"
    subsections:
      - title: "PC Sampling"
        data_path: ["21. PC Sampling", "21.1 PC Sampling"]
        collapsed: true