// Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
// SPDX-License-Identifier: MIT

//! Raw, unsafe FFI bindings to the gpumetrics C API (`libgpumetrics`).
//!
//! This is a straight `-sys` crate: it exposes exactly the symbols declared in
//! `gpumetrics/capi.h`, `types.h`, and `plugin_abi.h` as generated by `bindgen`
//! at build time. It adds no safety and no abstractions; use the safe
//! `gpumetrics` crate for idiomatic access.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
