# Copyright (c) Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# Writes one stand-in package into a prefix, for the configure-policy tests.
#
# A stand-in is exactly what find_package() looks at and nothing else: a
# <Package>Config.cmake declaring INTERFACE IMPORTED targets, and a
# <Package>ConfigVersion.cmake generated by CMake's own
# write_basic_package_version_file(). It carries no headers and no library, so
# it is only ever valid for a configure -- a build against one will not link.
# That is the point: the dependency gate is a configure-time decision, and this
# lets every branch of it be driven without installing anything.
#
# The version file is generated rather than hand-written so that the
# accept/refuse decision is made by the same code a real package's version file
# runs. COMPATIBILITY must be set to whatever the real upstream package passes,
# because the modes are not interchangeable -- see README.md.
#
# Script mode:
#   cmake -DPREFIX=<dir> -DPACKAGE=fmt -DVERSION=11.1.3 \
#         -DCOMPATIBILITY=AnyNewerVersion -DTARGETS="fmt::fmt" \
#         [-DDEFINITIONS="SPDLOG_FMT_EXTERNAL"] \
#         -P make_standin.cmake
#
# TARGETS and DEFINITIONS are CMake lists (semicolon-separated); quote them so
# the shell does not split them.

cmake_minimum_required(VERSION 3.21)

foreach(
    _required
    IN
    ITEMS PREFIX PACKAGE VERSION COMPATIBILITY TARGETS
)
    if(NOT DEFINED ${_required})
        message(
            FATAL_ERROR
            "make_standin.cmake: -D${_required}=... is required"
        )
    endif()
endforeach()

# write_basic_package_version_file() bakes CMAKE_SIZEOF_VOID_P into the version
# file so that a 64-bit package is rejected by a 32-bit consumer. In script
# mode that variable is empty, and the generated file then short-circuits:
# `if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "" STREQUAL "")` is always true,
# so it returns before the check ever runs. The stand-in would be *more*
# permissive than the installation it stands in for -- which is precisely the
# way a fixture quietly stops representing the real world. Caller passes the
# pointer size the consuming project will actually have.
if(NOT DEFINED SIZEOF_VOID_P OR SIZEOF_VOID_P STREQUAL "")
    message(
        FATAL_ERROR
        "make_standin.cmake: -DSIZEOF_VOID_P=... is required; in script mode CMAKE_SIZEOF_VOID_P is empty and the generated version file would skip its architecture check"
    )
endif()
set(CMAKE_SIZEOF_VOID_P "${SIZEOF_VOID_P}")

set(_standin_dir "${PREFIX}/lib/cmake/${PACKAGE}")
file(MAKE_DIRECTORY "${_standin_dir}")

set(_config_body
    "# Generated by make_standin.cmake. A stand-in, not an installation.\n"
)

foreach(_target IN LISTS TARGETS)
    string(APPEND _config_body "if(NOT TARGET ${_target})\n")
    string(
        APPEND _config_body
        "    add_library(${_target} INTERFACE IMPORTED)\n"
    )

    # Only spdlog needs these today, but the gate reads them off the imported
    # target rather than off the package, so any package could grow such a check.
    if(DEFINED DEFINITIONS AND NOT DEFINITIONS STREQUAL "")
        string(
            APPEND _config_body
            "    set_target_properties(\n"
            "        ${_target}\n"
            "        PROPERTIES INTERFACE_COMPILE_DEFINITIONS \"${DEFINITIONS}\"\n"
            "    )\n"
        )
    endif()

    string(APPEND _config_body "endif()\n")
endforeach()

file(WRITE "${_standin_dir}/${PACKAGE}Config.cmake" "${_config_body}")

include(CMakePackageConfigHelpers)

write_basic_package_version_file(
    "${_standin_dir}/${PACKAGE}ConfigVersion.cmake"
    VERSION "${VERSION}"
    COMPATIBILITY "${COMPATIBILITY}"
)
