#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Drive profiler-hub's dependency gate through every decision it can make.

The gate decides, per dependency, whether what is on CMAKE_PREFIX_PATH is
acceptable -- and refuses with a specific message when it is not. Those
refusals are the part nobody exercises: a CI job that has the dependencies
installed only ever walks the accept path, and a job that has none of them
fails at the first gate and never reaches the rest.

This runs the whole table instead, by staging *stand-in* packages: a
<Package>Config.cmake declaring INTERFACE IMPORTED targets plus a
<Package>ConfigVersion.cmake generated by CMake's own
write_basic_package_version_file(). find_package() cannot tell one from a real
installation, because a config-mode find_package() reads nothing else. No
downloads, no builds, no network -- see README.md for what that buys and what
it does not.

Nothing here modifies the project. The source tree is read-only to this script;
--source-dir exists so a deliberately-broken copy can be pointed at instead,
which is how the suite's own failure modes get checked.

Usage:
    python3 run_configure_policy_tests.py [--source-dir DIR] [--work-dir DIR]
                                          [--jobs N] [--verbose] [--only PAT]
"""

from __future__ import annotations

import argparse
import concurrent.futures
import os
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

HERE = Path(__file__).resolve().parent
MAKE_STANDIN = HERE / "make_standin.cmake"

ACCEPT = "accept"
REFUSE = "refuse"


# --------------------------------------------------------------------------- #
# Dependency table
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class Dependency:
    """One gated dependency, as the gate and its upstream package define it."""

    # find_package() name -- also the config filename stem and directory name.
    package: str
    # cmake/<gate_file>.cmake, and the CACHE STRING in it holding the floor.
    gate_file: str
    version_var: str
    # COMPATIBILITY the *real* upstream package passes to
    # write_basic_package_version_file(). Not uniform across these five, and
    # getting it wrong makes the whole suite green against a world that does
    # not exist -- see README.md.
    compatibility: str
    targets: tuple[str, ...]
    # Extra INTERFACE_COMPILE_DEFINITIONS the gate reads off the target.
    definitions: tuple[str, ...] = ()
    # STATUS line the gate prints when it accepts. {version} is substituted.
    accept_pattern: str = ""
    # Fragment of the FATAL_ERROR the gate prints when it refuses.
    refuse_pattern: str = ""
    # Extra assertions on the refusal text: the message has to be actionable,
    # not merely present.
    refuse_must_mention: tuple[str, ...] = ()


DEPENDENCIES = (
    Dependency(
        package="fmt",
        gate_file="fmt.cmake",
        version_var="FMT_VERSION",
        compatibility="AnyNewerVersion",
        targets=("fmt::fmt",),
        accept_pattern=r"Using system fmt \(version {version}\)",
        refuse_pattern=r"profiler-hub requires fmt {floor} or newer",
        refuse_must_mention=("PROFILER_HUB_FETCH_DEPENDENCIES=ON",),
    ),
    Dependency(
        package="spdlog",
        gate_file="spdlog.cmake",
        version_var="SPDLOG_VERSION",
        compatibility="SameMajorVersion",
        targets=("spdlog::spdlog",),
        definitions=("SPDLOG_FMT_EXTERNAL",),
        accept_pattern=r"Using system spdlog \(version {version}\)",
        refuse_pattern=r"profiler-hub requires spdlog {floor} or newer",
        refuse_must_mention=("PROFILER_HUB_FETCH_DEPENDENCIES=ON",),
    ),
    Dependency(
        package="nlohmann_json",
        gate_file="nlohmann_json.cmake",
        version_var="NLOHMANN_JSON_VERSION",
        compatibility="SameMajorVersion",
        targets=("nlohmann_json::nlohmann_json",),
        accept_pattern=r"Using system nlohmann_json \(version {version}\)",
        refuse_pattern=r"profiler-hub requires nlohmann_json {floor} or newer",
        refuse_must_mention=("PROFILER_HUB_FETCH_DEPENDENCIES=ON",),
    ),
    Dependency(
        package="GTest",
        gate_file="gtest.cmake",
        version_var="GTEST_VERSION",
        compatibility="AnyNewerVersion",
        targets=(
            "GTest::gtest",
            "GTest::gtest_main",
            "GTest::gmock",
            "GTest::gmock_main",
        ),
        accept_pattern=r"Using system GoogleTest \(version {version}\)",
        refuse_pattern=r"profiler-hub requires GoogleTest {floor} or newer",
        # A refusal that names only the fetch flag tells someone who does not
        # want the tests at all to do the wrong thing.
        refuse_must_mention=(
            "PROFILER_HUB_BUILD_TESTS=OFF",
            "PROFILER_HUB_FETCH_DEPENDENCIES=ON",
        ),
    ),
    Dependency(
        package="benchmark",
        gate_file="benchmark.cmake",
        version_var="BENCHMARK_VERSION",
        compatibility="SameMajorVersion",
        targets=("benchmark::benchmark", "benchmark::benchmark_main"),
        accept_pattern=r"Using system Google Benchmark \(version {version}\)",
        refuse_pattern=r"profiler-hub requires Google Benchmark {floor} or newer",
        refuse_must_mention=(
            "PROFILER_HUB_BUILD_BENCHMARKS=OFF",
            "PROFILER_HUB_FETCH_DEPENDENCIES=ON",
        ),
    ),
)


# --------------------------------------------------------------------------- #
# Version arithmetic
# --------------------------------------------------------------------------- #


def parse_version(text: str) -> tuple[int, int, int]:
    parts = [int(p) for p in text.split(".")[:3]]
    while len(parts) < 3:
        parts.append(0)
    return parts[0], parts[1], parts[2]


def format_version(version: tuple[int, int, int]) -> str:
    return ".".join(str(p) for p in version)


def below_floor(floor: tuple[int, int, int]) -> str:
    """The nearest version the gate must refuse for being too old."""
    major, minor, patch = floor
    if patch > 0:
        return format_version((major, minor, patch - 1))
    if minor > 0:
        return format_version((major, minor - 1, 0))
    if major > 0:
        return format_version((major - 1, 0, 0))
    raise ValueError("floor 0.0.0 has nothing below it")


def above_floor(floor: tuple[int, int, int]) -> str:
    """Newer than the floor, same major."""
    major, minor, _ = floor
    return format_version((major, minor + 1, 0))


def next_major(floor: tuple[int, int, int]) -> str:
    return format_version((floor[0] + 1, 0, 0))


def read_floor(source_dir: Path, dep: Dependency) -> tuple[int, int, int]:
    """Read the floor out of the gate file rather than duplicating it here.

    The floor is somebody else's to change. This suite tests the policy, not
    the number, so a legitimate floor bump must not turn it red.
    """
    gate = source_dir / "cmake" / dep.gate_file
    text = gate.read_text(encoding="utf-8")
    match = re.search(
        r"set\(\s*" + re.escape(dep.version_var) + r'\s+"([0-9][0-9.]*)"',
        text,
    )
    if not match:
        raise SystemExit(
            f"cannot read {dep.version_var} from {gate}: the gate file's shape "
            f"changed, so this suite no longer knows what floor it is testing"
        )
    return parse_version(match.group(1))


# --------------------------------------------------------------------------- #
# Cases
# --------------------------------------------------------------------------- #


@dataclass
class Case:
    name: str
    expect: str
    # package -> version, applied on top of the all-at-floor baseline.
    versions: dict[str, str] = field(default_factory=dict)
    # packages to leave out of the prefix entirely.
    absent: tuple[str, ...] = ()
    # package -> definitions tuple, overriding the table.
    definitions: dict[str, tuple[str, ...]] = field(default_factory=dict)
    # package -> pointer size baked into its version file, overriding the
    # consuming project's. Only used to drive the architecture check.
    pointer_sizes: dict[str, str] = field(default_factory=dict)
    extra_cmake_args: tuple[str, ...] = ()
    expect_stdout: tuple[str, ...] = ()
    expect_stderr: tuple[str, ...] = ()
    forbid_stdout: tuple[str, ...] = ()
    # Set only by the control case that is *supposed* to attempt a download.
    allow_fetch: bool = False
    why: str = ""


def build_cases(source_dir: Path) -> list[Case]:
    floors = {dep.package: read_floor(source_dir, dep) for dep in DEPENDENCIES}
    cases: list[Case] = []

    cases.append(
        Case(
            name="baseline_all_at_floor",
            expect=ACCEPT,
            expect_stdout=tuple(
                dep.accept_pattern.format(
                    version=re.escape(format_version(floors[dep.package]))
                )
                for dep in DEPENDENCIES
            ),
            why="every dependency exactly at its floor is the accept case",
        )
    )

    for dep in DEPENDENCIES:
        floor = floors[dep.package]
        floor_text = format_version(floor)
        refuse = dep.refuse_pattern.format(floor=re.escape(floor_text))

        cases.append(
            Case(
                name=f"{dep.package}_at_floor",
                expect=ACCEPT,
                versions={dep.package: floor_text},
                expect_stdout=(
                    dep.accept_pattern.format(version=re.escape(floor_text)),
                ),
                why="the floor itself is accepted, not just versions past it",
            )
        )

        above = above_floor(floor)
        cases.append(
            Case(
                name=f"{dep.package}_above_floor",
                expect=ACCEPT,
                versions={dep.package: above},
                expect_stdout=(dep.accept_pattern.format(version=re.escape(above)),),
                why="newer within the same major is accepted",
            )
        )

        below = below_floor(floor)
        cases.append(
            Case(
                name=f"{dep.package}_below_floor",
                expect=REFUSE,
                versions={dep.package: below},
                expect_stderr=(refuse,)
                + tuple(re.escape(m) for m in dep.refuse_must_mention),
                why="one patch below the floor is refused, and the refusal is actionable",
            )
        )

        cases.append(
            Case(
                name=f"{dep.package}_absent",
                expect=REFUSE,
                absent=(dep.package,),
                expect_stderr=(refuse,)
                + tuple(re.escape(m) for m in dep.refuse_must_mention),
                why="nothing on the prefix path is refused with the same message as too-old",
            )
        )

        # The interesting one. "or newer" in the refusal is not what the
        # version file actually implements for a SameMajorVersion package: a
        # newer *major* is refused, and refused with a message saying it is
        # not new enough.
        bumped = next_major(floor)
        same_major = dep.compatibility == "SameMajorVersion"
        cases.append(
            Case(
                name=f"{dep.package}_next_major",
                expect=REFUSE if same_major else ACCEPT,
                versions={dep.package: bumped},
                expect_stderr=(refuse,) if same_major else (),
                expect_stdout=(
                    ()
                    if same_major
                    else (dep.accept_pattern.format(version=re.escape(bumped)),)
                ),
                why=(
                    "upstream ships SameMajorVersion, so the next major is refused"
                    if same_major
                    else "upstream ships AnyNewerVersion, so the next major is accepted"
                ),
            )
        )

    # spdlog carries a second gate, after and independent of the version check:
    # an spdlog built against its own bundled fmt would put two fmt copies in
    # one binary. The check reads the imported target, so a stand-in can drive
    # it by simply not setting the definition.
    cases.append(
        Case(
            name="spdlog_without_fmt_external",
            expect=REFUSE,
            definitions={"spdlog": ()},
            expect_stderr=(
                r"profiler-hub requires an spdlog built with SPDLOG_FMT_EXTERNAL",
                re.escape("CMAKE_DISABLE_FIND_PACKAGE_spdlog=ON"),
            ),
            why="version-acceptable spdlog with the wrong fmt linkage is still refused",
        )
    )

    # rocpd is not a find_package() dependency -- it is a schema directory, and
    # its gate is three-way (in-tree / refuse / clone). The clone arm needs the
    # network and is deliberately not exercised; see README.md.
    cases.append(
        Case(
            name="rocpd_in_tree",
            expect=ACCEPT,
            expect_stdout=(r"Using in-tree rocprofiler-sdk-rocpd schema at",),
            forbid_stdout=(r"cloning from", r"Using cloned rocprofiler-sdk-rocpd"),
            why="the in-tree schema is used and nothing is cloned",
        )
    )
    cases.append(
        Case(
            name="rocpd_absent",
            expect=REFUSE,
            extra_cmake_args=("-DROCPD_SCHEMA_VERSION=0.0.0-no-such-version",),
            expect_stderr=(
                r"rocprofiler-sdk-rocpd schema directory not found",
                re.escape("PROFILER_HUB_FETCH_DEPENDENCIES=ON"),
            ),
            why="a schema version with no directory is refused rather than silently skipped",
        )
    )

    # An acceptable version built for the wrong architecture must still be
    # refused, and that check lives in the generated version file rather than
    # in our gate. This case exists because the stand-ins once skipped it
    # silently -- script mode leaves CMAKE_SIZEOF_VOID_P empty, and the
    # generated file then returns before the check runs. Without a case that
    # depends on it, that regression is invisible.
    cases.append(
        Case(
            name="fmt_wrong_architecture",
            expect=REFUSE,
            pointer_sizes={"fmt": "4"},
            expect_stderr=(
                DEPENDENCIES[0].refuse_pattern.format(
                    floor=re.escape(format_version(floors["fmt"]))
                ),
            ),
            why="right version, wrong pointer size, still refused",
        )
    )

    # The control for every other case's silence about the network. With
    # fetching ON and nothing to find, the gate is supposed to download -- and
    # under the block it cannot. That this one case dies on the network is what
    # makes the other cases' passing mean something.
    cases.append(
        Case(
            name="control_fetch_path_is_blocked",
            expect=REFUSE,
            absent=tuple(dep.package for dep in DEPENDENCIES),
            extra_cmake_args=("-DPROFILER_HUB_FETCH_DEPENDENCIES=ON",),
            allow_fetch=True,
            # Pin *where* it fails. A control that is allowed to fail anywhere
            # would keep passing after it stopped demonstrating anything.
            expect_stderr=(r"gitclone\.cmake", r"FetchContent\.cmake"),
            why="proves the network block is real, by taking the one path that needs it",
        )
    )

    return cases


# --------------------------------------------------------------------------- #
# Running
# --------------------------------------------------------------------------- #

# sqlite3 is not gated: cmake/sqlite3.cmake clones and configures SQLite at
# configure time unconditionally. It is not under test here, and letting it run
# would make every case need the network. Both of its "already have it" guards
# are satisfied by files in the *build* directory, so pre-staging them keeps
# the gate files untouched. Nothing is ever compiled from these -- the suite
# configures and never builds.
SQLITE3_STUBS = {
    "configure": "# placeholder: configure-policy tests never build SQLite\n",
    "sqlite3.c": "/* placeholder: configure-policy tests never build SQLite */\n",
    "sqlite3.h": "/* placeholder: configure-policy tests never build SQLite */\n",
}


# Every case must see exactly the packages this suite stages and no others.
# That does not come for free, and the failure is silent: config-mode search
# does not stop at a version-rejected candidate, it keeps going. So a real
# package installed on the host can satisfy a case meant to find nothing, or
# rescue a deliberately-too-old one, and the case still reports green.
#
# Found by mutation-testing this suite rather than by reasoning about it.
# Dropping the version floor from cmake/fmt.cmake was supposed to break exactly
# `fmt_below_floor`; it broke `fmt_absent` too, which turned out to be
# configuring happily against the host's real fmt 9.1.0 in
# /usr/lib/<arch>/cmake/fmt. The floor had been hiding that the whole time.
#
# Two settings, for two different leaks:
#   - the package registries ($HOME/.cmake/packages and the Windows registry),
#     which CMake searches after CMAKE_PREFIX_PATH;
#   - the platform's default prefixes, which it searches after those.
# The second list is read back from CMake rather than written down here, so
# this carries no absolute paths and holds on any platform. "/" is kept in it,
# unintuitive as that looks: on a usrmerge host /lib is a symlink to /usr/lib,
# so ignoring /usr alone still leaves the same package reachable as
# /lib/<arch>/cmake/<name>. Ignoring a prefix only removes it from
# find_package's search; find_program and try_compile are unaffected, which is
# why the compiler, Git and Threads are all still found.
REGISTRY_ARGS = (
    "-DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF",
    "-DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF",
    # Do not write into the invoking user's registry either.
    "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON",
)

# LANGUAGES CXX, not NONE: CMAKE_LIBRARY_ARCHITECTURE is a by-product of
# compiler detection, and without it the probe never looks in
# lib/<arch>/cmake -- which is where the host's fmt actually was. A probe that
# searches fewer paths than the real configure reports a clean bill of health
# it has not earned.
PROBE_CMAKELISTS = """cmake_minimum_required(VERSION 3.21)
project(configure_policy_probe LANGUAGES CXX)
message(STATUS "SYSTEM_PREFIX_PATH=${CMAKE_SYSTEM_PREFIX_PATH}")
message(STATUS "SIZEOF_VOID_P=${CMAKE_SIZEOF_VOID_P}")
foreach(_package IN ITEMS @PACKAGES@)
    find_package(${_package} QUIET)
    if(${_package}_FOUND)
        message(STATUS "LEAK ${_package} ${${_package}_VERSION} at ${${_package}_DIR}")
    endif()
endforeach()
"""


def cmake_version(cmake: str) -> tuple[int, ...] | None:
    """The version of the cmake we are about to drive, or None if unreadable."""
    completed = subprocess.run([cmake, "--version"], capture_output=True, text=True)
    match = re.search(r"cmake version (\d+)\.(\d+)\.(\d+)", completed.stdout)
    return tuple(int(part) for part in match.groups()) if match else None


def run_probe(
    work_dir: Path, cmake: str, extra: tuple[str, ...]
) -> tuple[list[str], list[str], str]:
    """Configure a throwaway project that finds nothing on purpose.

    Returns (system prefixes CMake would search, leak descriptions, the
    pointer size a real consuming project will have).
    """
    probe_dir = work_dir / "_probe"
    if probe_dir.exists():
        shutil.rmtree(probe_dir)
    (probe_dir / "build").mkdir(parents=True)
    (probe_dir / "CMakeLists.txt").write_text(
        PROBE_CMAKELISTS.replace(
            "@PACKAGES@", " ".join(dep.package for dep in DEPENDENCIES)
        ),
        encoding="utf-8",
    )
    completed = subprocess.run(
        [
            cmake,
            "-S",
            str(probe_dir),
            "-B",
            str(probe_dir / "build"),
            "-DCMAKE_PREFIX_PATH=",
            *REGISTRY_ARGS,
            *extra,
        ],
        capture_output=True,
        text=True,
    )
    output = completed.stdout + completed.stderr

    prefixes: list[str] = []
    for line in output.splitlines():
        if "SYSTEM_PREFIX_PATH=" in line:
            raw = line.split("SYSTEM_PREFIX_PATH=", 1)[1].strip()
            for entry in raw.split(";"):
                entry = entry.strip()
                if entry and entry not in prefixes:
                    prefixes.append(entry)

    leaks = [
        line.split("LEAK ", 1)[1].strip()
        for line in output.splitlines()
        if "LEAK " in line
    ]

    pointer_size = ""
    for line in output.splitlines():
        if "SIZEOF_VOID_P=" in line:
            pointer_size = line.split("SIZEOF_VOID_P=", 1)[1].strip()

    shutil.rmtree(probe_dir, ignore_errors=True)
    return prefixes, leaks, pointer_size


def establish_hermeticity(
    work_dir: Path, cmake: str
) -> tuple[tuple[str, ...], list[str], list[str], str]:
    """Work out what to ignore, then check that ignoring it was enough.

    Returns (args every case must pass, packages the host was offering,
    packages it is still offering afterwards, the consuming project's pointer
    size). A non-empty third value means the results would not mean what they
    say.
    """
    system_prefixes, before, pointer_size = run_probe(work_dir, cmake, ())
    args = REGISTRY_ARGS + ("-DCMAKE_IGNORE_PREFIX_PATH=" + ";".join(system_prefixes),)
    _, after, _ = run_probe(work_dir, cmake, args[len(REGISTRY_ARGS) :])
    if not pointer_size:
        raise SystemExit(
            "could not determine CMAKE_SIZEOF_VOID_P; stand-in version files "
            "would silently skip their architecture check"
        )
    return args, before, after, pointer_size


# "These cases do not touch the network" is a claim, and a claim about absence
# is worth very little unstated. Kernel-level isolation would settle it, but
# `unshare -rn` needs a user namespace and `sudo unshare --net` needs root --
# neither is available in every container this has to run in, so neither can be
# the mechanism.
#
# What is always available: point every outbound connection at a port nothing
# is listening on. Any download then fails in milliseconds. The suite checks
# that the block is real before trusting it (a `git ls-remote` through it must
# fail), and carries one control case that deliberately takes the fetch path
# and is expected to die on it. The other cases run under exactly that
# environment and pass, which is the demonstration.
UNROUTABLE = "http://127.0.0.1:1"


def blocked_network_env() -> dict:
    env = dict(os.environ)
    for name in ("http_proxy", "https_proxy", "all_proxy", "ftp_proxy"):
        env[name] = UNROUTABLE
        env[name.upper()] = UNROUTABLE
    # An inherited no_proxy would punch a hole straight back through it.
    env["no_proxy"] = ""
    env["NO_PROXY"] = ""
    # Never sit waiting for credentials that are not coming.
    env["GIT_TERMINAL_PROMPT"] = "0"
    env["GIT_ASKPASS"] = ""
    return env


def verify_network_blocked(timeout: int = 30) -> tuple[bool, str]:
    """Check the block bites, by trying to use the network through it."""
    git = shutil.which("git")
    if not git:
        return False, "git not on PATH, so the block could not be checked"
    try:
        completed = subprocess.run(
            [git, "ls-remote", "https://github.com/fmtlib/fmt.git", "HEAD"],
            capture_output=True,
            text=True,
            timeout=timeout,
            env=blocked_network_env(),
        )
    except subprocess.TimeoutExpired:
        return True, "outbound git timed out"
    if completed.returncode == 0:
        return False, "outbound git succeeded despite the block"
    first = (completed.stderr or completed.stdout).strip().splitlines()
    return True, first[0] if first else "outbound git failed"


def stage_sqlite3(build_dir: Path) -> None:
    sqlite_dir = build_dir / "external" / "sqlite3"
    sqlite_dir.mkdir(parents=True, exist_ok=True)
    for name, body in SQLITE3_STUBS.items():
        (sqlite_dir / name).write_text(body, encoding="utf-8")


def write_standin(
    cmake: str,
    prefix: Path,
    dep: Dependency,
    version: str,
    definitions: tuple[str, ...],
    pointer_size: str,
) -> None:
    command = [
        cmake,
        f"-DPREFIX={prefix}",
        f"-DPACKAGE={dep.package}",
        f"-DVERSION={version}",
        f"-DCOMPATIBILITY={dep.compatibility}",
        "-DTARGETS=" + ";".join(dep.targets),
        f"-DSIZEOF_VOID_P={pointer_size}",
    ]
    if definitions:
        command.append("-DDEFINITIONS=" + ";".join(definitions))
    command += ["-P", str(MAKE_STANDIN)]
    subprocess.run(command, check=True, capture_output=True, text=True)


@dataclass
class Result:
    case: Case
    passed: bool
    returncode: int
    stdout: str
    stderr: str
    failures: list[str]
    seconds: float


def run_case(
    case: Case,
    source_dir: Path,
    work_dir: Path,
    cmake: str,
    floors: dict,
    hermetic_args: tuple[str, ...],
    pointer_size: str,
) -> Result:
    started = time.monotonic()
    case_dir = work_dir / case.name
    if case_dir.exists():
        shutil.rmtree(case_dir)
    prefix = case_dir / "prefix"
    build = case_dir / "build"
    prefix.mkdir(parents=True)
    build.mkdir(parents=True)
    stage_sqlite3(build)

    for dep in DEPENDENCIES:
        if dep.package in case.absent:
            continue
        version = case.versions.get(dep.package, format_version(floors[dep.package]))
        definitions = case.definitions.get(dep.package, dep.definitions)
        size = case.pointer_sizes.get(dep.package, pointer_size)
        write_standin(cmake, prefix, dep, version, definitions, size)

    command = [
        cmake,
        "-S",
        str(source_dir),
        "-B",
        str(build),
        "-DPROFILER_HUB_FETCH_DEPENDENCIES=OFF",
        f"-DCMAKE_PREFIX_PATH={prefix}",
        "-DPROFILER_HUB_BUILD_TESTS=ON",
        "-DPROFILER_HUB_BUILD_BENCHMARKS=ON",
        *hermetic_args,
        *case.extra_cmake_args,
    ]
    completed = subprocess.run(
        command, capture_output=True, text=True, env=blocked_network_env()
    )

    failures: list[str] = []
    combined = completed.stdout + completed.stderr

    if case.expect == ACCEPT and completed.returncode != 0:
        failures.append(
            f"expected configure to succeed, got exit {completed.returncode}"
        )
    if case.expect == REFUSE and completed.returncode == 0:
        failures.append("expected configure to be refused, but it succeeded")

    for pattern in case.expect_stdout:
        if not re.search(pattern, combined):
            failures.append(f"missing expected output: /{pattern}/")
    for pattern in case.expect_stderr:
        if not re.search(pattern, combined):
            failures.append(f"missing expected refusal text: /{pattern}/")
    for pattern in case.forbid_stdout:
        if re.search(pattern, combined, re.IGNORECASE):
            failures.append(f"output contained forbidden text: /{pattern}/")

    # No case in this table may reach the network, bar the one control that
    # exists to show the block is real. FetchContent and the rocpd clone both
    # leave directories behind; their absence is the evidence.
    if not case.allow_fetch:
        for fetched in ("_deps", "external/rocprofiler-sdk-rocpd"):
            if (build / fetched).exists():
                failures.append(
                    f"network path was taken: {fetched} exists in the build dir"
                )

    return Result(
        case=case,
        passed=not failures,
        returncode=completed.returncode,
        stdout=completed.stdout,
        stderr=completed.stderr,
        failures=failures,
        seconds=time.monotonic() - started,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=HERE.parent.parent,
        help="profiler-hub source directory to configure (default: this checkout)",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=None,
        help="scratch directory for prefixes and build trees (default: a temp dir)",
    )
    parser.add_argument("--jobs", type=int, default=min(8, os.cpu_count() or 1))
    parser.add_argument(
        "--only", default=None, help="run only cases matching this regex"
    )
    parser.add_argument(
        "--verbose", action="store_true", help="print output of every case"
    )
    args = parser.parse_args()

    cmake = shutil.which("cmake")
    if not cmake:
        print("cmake not found on PATH", file=sys.stderr)
        return 2

    # Hermeticity rests on CMAKE_IGNORE_PREFIX_PATH, which arrived in 3.23. An
    # older cmake treats it as just another unset variable rather than an
    # error, so the guard would be silently inert -- and the preflight probe
    # only notices that on a host that has one of the five packages installed.
    # On a host that has none, every case would look green while nothing was
    # being ignored at all.
    version = cmake_version(cmake)
    if version is None:
        print("could not read `cmake --version`", file=sys.stderr)
        return 2
    if version < (3, 23):
        print(
            "cmake {} is too old: CMAKE_IGNORE_PREFIX_PATH needs 3.23, and "
            "without it a package installed on this host can satisfy a case "
            "meant to find nothing.".format(".".join(str(p) for p in version)),
            file=sys.stderr,
        )
        return 2

    source_dir = args.source_dir.resolve()
    if not (source_dir / "CMakeLists.txt").exists():
        print(f"no CMakeLists.txt under {source_dir}", file=sys.stderr)
        return 2

    work_dir = args.work_dir
    temporary = work_dir is None
    if temporary:
        import tempfile

        work_dir = Path(tempfile.mkdtemp(prefix="configure-policy-"))
    else:
        work_dir = work_dir.resolve()
        work_dir.mkdir(parents=True, exist_ok=True)

    floors = {dep.package: read_floor(source_dir, dep) for dep in DEPENDENCIES}
    cases = build_cases(source_dir)
    if args.only:
        pattern = re.compile(args.only)
        cases = [c for c in cases if pattern.search(c.name)]
        if not cases:
            print(f"no cases match /{args.only}/", file=sys.stderr)
            return 2

    print(f"source:  {source_dir}")
    print(f"work:    {work_dir}")
    print(
        "floors:  " + ", ".join(f"{k} {format_version(v)}" for k, v in floors.items())
    )
    hermetic_args, offered, still_offered, pointer_size = establish_hermeticity(
        work_dir, cmake
    )
    if offered:
        print("host installs, shut out so the cases see only what they stage:")
        for leak in offered:
            print(f"  {leak}")
    if still_offered:
        print(
            "\nHOST NOT HERMETIC -- still findable after ignoring the system prefixes:\n"
            + "\n".join(f"  {leak}" for leak in still_offered)
            + "\nA case expecting a package to be missing or too old could be satisfied\n"
            "by one of these, so the results below would not mean what they say.",
            file=sys.stderr,
        )
        return 2

    blocked, detail = verify_network_blocked()
    if blocked:
        print(f"network: blocked -- {detail}")
    else:
        print(
            f"network: NOT blocked -- {detail}\n"
            "The cases still assert that no download artefacts appear, but on this\n"
            "host the offline property is not demonstrated, only claimed.",
            file=sys.stderr,
        )

    print(f"\nrunning {len(cases)} cases on {args.jobs} jobs\n")

    started = time.monotonic()
    results: list[Result] = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = {
            pool.submit(
                run_case,
                case,
                source_dir,
                work_dir,
                cmake,
                floors,
                hermetic_args,
                pointer_size,
            ): case
            for case in cases
        }
        for future in concurrent.futures.as_completed(futures):
            results.append(future.result())

    results.sort(key=lambda r: cases.index(r.case))
    for result in results:
        mark = "PASS" if result.passed else "FAIL"
        print(
            f"{mark}  {result.case.name:<38} {result.case.expect:<7} {result.seconds:5.2f}s"
        )
        if result.case.why and args.verbose:
            print(f"      why: {result.case.why}")
        for failure in result.failures:
            print(f"      {failure}")
        if args.verbose or not result.passed:
            for line in (result.stdout + result.stderr).splitlines():
                if (
                    "profiler-hub" in line
                    or "CMake Error" in line
                    or "Using system" in line
                ):
                    print(f"      | {line.rstrip()}")

    elapsed = time.monotonic() - started
    failed = [r for r in results if not r.passed]
    print(f"\n{len(results) - len(failed)}/{len(results)} passed in {elapsed:.1f}s")

    if temporary and not failed:
        shutil.rmtree(work_dir, ignore_errors=True)
    elif failed:
        print(f"failing case trees kept under {work_dir}")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
