variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - projects/rocm-core
    exclude:
    - projects/rocm-core/CHANGELOG.md
    - projects/rocm-core/CODEOWNERS
    - projects/rocm-core/copyright
    - projects/rocm-core/README.txt

pr: none

stages:
- stage: rocm_core
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocm-core.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocm-core
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
