variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - release-staging/rocm-rel-7.*
  paths:
    include:
    - projects/rocm-smi-lib
    exclude:
    - projects/rocm-smi-lib/.github
    - projects/rocm-smi-lib/docs
    - projects/rocm-smi-lib/.*.y*ml
    - projects/rocm-smi-lib/*.md
    - projects/rocm-smi-lib/License.txt

pr: none

stages:
- stage: rocm_smi_lib
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocm_smi_lib.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocm-smi-lib
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
