variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - projects/rocminfo
    exclude:
    - projects/rocminfo/.github
    - projects/rocminfo/License.txt
    - projects/rocminfo/README.md

pr: none

stages:
- stage: rocminfo
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocminfo.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocminfo
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
