variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - release-staging/rocm-rel-7.*
  paths:
    include:
    - projects/rocprofiler-register
    exclude:
    - projects/rocprofiler-register/.github
    - projects/rocprofiler-register/LICENSE
    - projects/rocprofiler-register/README.md
    - projects/rocprofiler-register/VERSION

pr: none

stages:
- stage: rocprofiler_register
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocprofiler-register.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocprofiler-register
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
