variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - projects/rocprofiler-sdk
    exclude:
    - projects/rocprofiler-sdk/.github
    - projects/rocprofiler-sdk/ISSUE_TEMPLATE
    - projects/rocprofiler-sdk/*.md
    - projects/rocprofiler-sdk/CODEOWNERS
    - projects/rocprofiler-sdk/LICENSE

pr: none

stages:
- stage: rocprofiler_sdk
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocprofiler-sdk.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocprofiler-sdk
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
