name: cpack-opensuse

on:
  push:
    branches: [releases/**]
    tags: []

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  cpack:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: ["15.2", "15.3"]
        rocm-version: ["4.5", "5.0", "5.1"]
        extensions: ["--rocm +python --core +python"]
        exclude:
          - os: "15.2"
            rocm-version: "5.1"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Base Container
        timeout-minutes: 20
        run: |
          pushd docker
          ./build-docker.sh --distro opensuse --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }}
          popd

      - name: Build Release
        timeout-minutes: 150
        run: |
          pushd docker
          ./build-docker-release.sh --distro opensuse --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }} -- ${{ matrix.extensions }}
          popd

      - name: List Files
        timeout-minutes: 10
        run: |
          find build-release -type f | egrep '\.(sh|deb|rpm)$'

      - name: STGZ Artifacts
        timeout-minutes: 10
        uses: actions/upload-artifact@v2
        with:
          name: opensuse-stgz-installers
          path: |
            build-release/stgz/*.sh

      - name: RPM Artifacts
        timeout-minutes: 10
        uses: actions/upload-artifact@v2
        with:
          name: opensuse-rpm-installers
          path: |
            build-release/rpm/*.rpm

      # before testing remove any artifacts of the build
      - name: Remove Build
        timeout-minutes: 10
        continue-on-error: true
        run: |
          mv build-release/stgz/*.sh ./
          mv build-release/deb/*.rpm ./
          sudo rm -rf build-release
          sudo rm -rf /opt/omnitrace

      - name: Test STGZ Install
        timeout-minutes: 20
        continue-on-error: true
        run: |
          set -v
          for i in omnitrace-*.sh
          do
            ./docker/test-docker-release.sh --distro opensuse --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }} -- --stgz ${i}
          done

      - name: Test RPM Install
        timeout-minutes: 20
        continue-on-error: true
        run: |
          set -v
          for i in omnitrace-*.rpm
          do
            ./docker/test-docker-release.sh --distro opensuse --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }} -- --rpm ${i}
          done
