name: cpack-ubuntu

on:
  push:
    branches: [releases/**]
  pull_request:
    branches: [releases/**]

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  cpack:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: ["18.04", "20.04"]
        rocm-version: ["4.5", "5.0", "5.1"]
        extensions: ["--rocm +python --core +python"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Base Container
        timeout-minutes: 20
        run: |
          pushd docker
          ./build-docker.sh --distro ubuntu --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }}
          popd

      - name: Build Release
        timeout-minutes: 120
        run: |
          pushd docker
          ./build-docker-release.sh --distro ubuntu --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }} -- ${{ matrix.extensions }}
          popd

      - name: List Files
        timeout-minutes: 10
        run: |
          find build-release -type f | egrep '\.(sh|deb|rpm)$'

      - name: STGZ Artifacts
        timeout-minutes: 10
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-stgz-installers
          path: |
            build-release/stgz/*.sh

      - name: DEB Artifacts
        timeout-minutes: 10
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-deb-installers
          path: |
            build-release/deb/*.deb

      # before testing remove any artifacts of the build
      - name: Remove Build
        timeout-minutes: 10
        continue-on-error: true
        run: |
          mv build-release/stgz/*.sh ./
          mv build-release/deb/*.deb ./
          rm -rf build-release
          rm -rf /opt/omnitrace

      - name: Test STGZ Install
        timeout-minutes: 20
        continue-on-error: true
        run: |
          set -v
          mkdir /opt/omnitrace-stgz
          export PATH=/opt/omnitrace-stgz/bin:${PATH}
          export LD_LIBRARY_PATH=/opt/omnitrace-stgz/lib:${LD_LIBRARY_PATH}
          for i in omnitrace-*.sh
          do
            echo -e "\n###### Testing ${i}... #####\n"
            ./${i} --prefix=/opt/omnitrace-stgz --skip-license --exclude-dir
            omnitrace-avail --help
            omnitrace --help
            omnitrace-python --help
            set +e
            rm -rf /opt/omnitrace-stgz/*
            set -e
          done

      - name: Test DEB Install
        timeout-minutes: 20
        continue-on-error: true
        run: |
          set -v
          export PATH=/opt/omnitrace/bin:${PATH}
          export LD_LIBRARY_PATH=/opt/omnitrace/lib:${LD_LIBRARY_PATH}
          for i in omnitrace_*.deb
          do
            echo -e "\n###### Testing ${i}... #####\n"
            dpkg --contents ./${i}
            sudo dpkg -i ./${i}
            omnitrace-avail --help
            omnitrace --help
            omnitrace-python --help
            sudo apt-get remove -y omnitrace
            set +e
            rm -rf /opt/omnitrace/*
            set -e
          done
