name: cpack-ubuntu

on:
  push:
    branches: [releases/**]
    tags: []

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  cpack:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os: ["18.04", "20.04"]
        rocm-version: ["4.5", "5.0", "5.1"]
        extensions: ["--rocm +python --core +python"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Base Container
        timeout-minutes: 20
        run: |
          pushd docker
          ./build-docker.sh --distro ubuntu --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }}
          popd

      - name: Build Release
        timeout-minutes: 150
        run: |
          pushd docker
          ./build-docker-release.sh --distro ubuntu --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }} -- ${{ matrix.extensions }}
          popd

      - name: List Files
        timeout-minutes: 10
        run: |
          find build-release -type f | egrep '\.(sh|deb|rpm)$'

      - name: STGZ Artifacts
        timeout-minutes: 10
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-stgz-installers
          path: |
            build-release/stgz/*.sh

      - name: DEB Artifacts
        timeout-minutes: 10
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-deb-installers
          path: |
            build-release/deb/*.deb

      # before testing remove any artifacts of the build
      - name: Remove Build
        timeout-minutes: 10
        continue-on-error: true
        run: |
          mv build-release/stgz/*.sh ./
          mv build-release/deb/*.deb ./
          sudo rm -rf build-release
          sudo rm -rf /opt/omnitrace

      - name: Test STGZ Install
        timeout-minutes: 20
        continue-on-error: true
        run: |
          set -v
          for i in omnitrace-*.sh
          do
            ./docker/test-docker-release.sh --distro ubuntu --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }} -- --stgz ${i}
          done

      - name: Test DEB Install
        timeout-minutes: 20
        continue-on-error: true
        run: |
          set -v
          for i in omnitrace_*.deb
          do
            ./docker/test-docker-release.sh --distro ubuntu --versions ${{ matrix.os }} --rocm-versions ${{ matrix.rocm-version }} -- --deb ${i}
          done
