#!/usr/bin/env python3

################################################################################
# Copyright © 2025 Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT
################################################################################


import os
import re
import subprocess
import sys
import time

# get current working directory
CWD = os.path.dirname(os.path.realpath(__file__))

ISA_TO_ID = {
    # Kaveri - Temporary
    "gfx700": [
        0x1304,
        0x1305,
        0x1306,
        0x1307,
        0x1309,
        0x130A,
        0x130B,
        0x130C,
        0x130D,
        0x130E,
        0x130F,
        0x1310,
        0x1311,
        0x1312,
        0x1313,
        0x1315,
        0x1316,
        0x1317,
        0x1318,
        0x131B,
        0x131C,
        0x131D,
    ],
    # Hawaii
    "gfx701": [
        0x67A0,
        0x67A1,
        0x67A2,
        0x67A8,
        0x67A9,
        0x67AA,
        0x67B0,
        0x67B1,
        0x67B8,
        0x67B9,
        0x67BA,
        0x67BE,
    ],
    # Carrizo
    "gfx801": [0x9870, 0x9874, 0x9875, 0x9876, 0x9877, 0x98E4],
    # Tonga
    "gfx802": [0x6920, 0x6921, 0x6928, 0x6929, 0x692B, 0x692F, 0x6930, 0x6938, 0x6939],
    # Fiji
    "gfx803": [
        0x7300,
        0x730F,
        # Polaris10
        0x67C0,
        0x67C1,
        0x67C2,
        0x67C4,
        0x67C7,
        0x67C8,
        0x67C9,
        0x67CA,
        0x67CC,
        0x67CF,
        0x6FDF,
        # Polaris11
        0x67D0,
        0x67DF,
        0x67E0,
        0x67E1,
        0x67E3,
        0x67E7,
        0x67E8,
        0x67E9,
        0x67EB,
        0x67EF,
        0x67FF,
        # Polaris12
        0x6980,
        0x6981,
        0x6985,
        0x6986,
        0x6987,
        0x6995,
        0x6997,
        0x699F,
        # VegaM
        0x694C,
        0x694E,
        0x694F,
    ],
    # Vega10
    "gfx900": [
        0x6860,
        0x6861,
        0x6862,
        0x6863,
        0x6864,
        0x6867,
        0x6868,
        0x6869,
        0x6869,
        0x686A,
        0x686B,
        0x686C,
        0x686D,
        0x686E,
        0x686F,
        0x687F,
    ],
    # Raven
    "gfx902": [0x15DD, 0x15D8],
    # Vega12
    "gfx904": [0x69A0, 0x69A1, 0x69A2, 0x69A3, 0x69AF],
    # Vega20
    "gfx906": [0x66A0, 0x66A1, 0x66A2, 0x66A3, 0x66A4, 0x66A7, 0x66AF],
    # Arcturus
    "gfx908": [0x738C, 0x7388, 0x738E, 0x7390],
    # Aldebaran
    "gfx90a": [0x7408, 0x740C, 0x740F, 0x7410],
    # Renoir
    "gfx90c": [0x15E7, 0x1636, 0x1638, 0x164C],
    # Instinct MI300 series
    "gfx942": [0x74A1, 0x74A2, 0x74A5, 0x74A9, 0x74B5, 0x74B6, 0x74BD],
    # Navi10
    "gfx1010": [0x7310, 0x7312, 0x7318, 0x7319, 0x731A, 0x731B, 0x731E, 0x731F],
    # Navi12
    "gfx1011": [0x7360, 0x7362],
    # Navi14
    "gfx1012": [0x7340, 0x7341, 0x7347, 0x734F],
    # Cyan_Skillfish
    "gfx1013": [0x13F9, 0x13FA, 0x13FB, 0x13FC, 0x13F3],
    # Sienna_Cichlid
    "gfx1030": [
        0x73A0,
        0x73A1,
        0x73A2,
        0x73A3,
        0x73A5,
        0x73A8,
        0x73A9,
        0x73AB,
        0x73AC,
        0x73AD,
        0x73AE,
        0x73AF,
        0x73BF,
    ],
    # Navy_Flounder
    "gfx1031": [0x73C0, 0x73C1, 0x73C3, 0x73DA, 0x73DB, 0x73DC, 0x73DD, 0x73DE, 0x73DF],
    # Dimgray_Cavefish
    "gfx1032": [
        0x73E0,
        0x73E1,
        0x73E2,
        0x73E3,
        0x73E8,
        0x73E9,
        0x73EA,
        0x73EB,
        0x73EC,
        0x73ED,
        0x73EF,
        0x73FF,
    ],
    # Van Gogh
    "gfx1033": [0x163F],
    # Beige_Goby
    "gfx1034": [0x7420, 0x7421, 0x7422, 0x7423, 0x743F],
    # Yellow_Carp
    "gfx1035": [0x164D, 0x1681],
    # Navi31
    "gfx1100": [0x7448, 0x7449, 0x744A, 0x744C, 0x745E],
    # Navi32
    "gfx1101": [0x7470, 0x747E],
    # Navi33
    "gfx1102": [0x7480, 0x7483, 0x7489, 0x7499],
}


def staticVars(**kwargs):
    def deco(func):
        for k in kwargs:
            setattr(func, k, kwargs[k])
        return func

    return deco


@staticVars(search_term=re.compile(r"gfx[0-9a-fA-F]+(-[0-9a-fA-F]+)?(-generic)?"))
def getGCNISA(line, match_from_beginning=False):
    if match_from_beginning is True:
        result = getGCNISA.search_term.match(line)
    else:
        result = getGCNISA.search_term.search(line)

    if result is not None:
        return result.group(0)
    return None


@staticVars(
    search_name=re.compile(r"gfx[0-9a-fA-F]+(-[0-9a-fA-F]+)?(-generic)?(:[-+:\w]+)?")
)
def getGCNArchName(line):
    result = getGCNArchName.search_name.search(line)

    if result is not None:
        return result.group(0)
    return None


def readFromTargetLstFile():
    target_list = []

    # locate target.lst using environment variable or
    # it should be placed at the same directory with this script
    target_lst_path = os.environ.get("ROCM_TARGET_LST")
    if target_lst_path is None:
        target_lst_path = os.path.join(CWD, "target.lst")
    if os.path.isfile(target_lst_path):
        target_lst_file = open(target_lst_path, "r")
        for line in target_lst_file:
            # for target.lst match from beginning so targets can be disabled by
            # commenting it out
            target = getGCNISA(line, match_from_beginning=True)
            if target is not None:
                target_list.append(target)

    return target_list


def readFromROCMINFO(search_arch_name=False):
    target_list = []
    # locate rocminfo binary which should be placed at the same directory with
    # this script
    rocminfo_executable = os.path.join(CWD, "rocminfo")

    try:
        t0 = time.time()
        while 1:
            t1 = time.time()
            # quit after retrying rocminfo for a minute.
            if t1 - t0 > 60.0:
                print(
                    "Timeout querying rocminfo.  Are you compiling with more than 254 threads?",
                    file=sys.stderr,
                )
                break
            # run rocminfo
            rocminfo_output = (
                subprocess.Popen(rocminfo_executable, stdout=subprocess.PIPE)
                .communicate()[0]
                .decode("utf-8")
                .split("\n")
            )
            term1 = re.compile(r"Cannot allocate memory")
            term2 = re.compile(r"HSA_STATUS_ERROR_OUT_OF_RESOURCES")
            done = 1
            for line in rocminfo_output:
                if term1.search(line) is not None or term2.search(line) is not None:
                    done = 0
                    break
            if done:
                break
    except:
        rocminfo_output = []

    # search AMDGCN gfx ISA
    if search_arch_name is True:
        line_search_term = re.compile(r"\A\s+Name:\s+(amdgcn-amd-amdhsa--gfx\d+)")
    else:
        line_search_term = re.compile(r"\A\s+Name:\s+(gfx\d+)")
    for line in rocminfo_output:
        if line_search_term.match(line) is not None:
            if search_arch_name is True:
                target = getGCNArchName(line)
            else:
                target = getGCNISA(line)
            if target is not None:
                target_list.append(target)

    return target_list


def readFromLSPCI():
    target_list = []

    try:
        # run lspci
        lspci_output = (
            subprocess.Popen(
                ["/usr/bin/lspci", "-n", "-d", "1002:"], stdout=subprocess.PIPE
            )
            .communicate()[0]
            .decode("utf-8")
            .split("\n")
        )
    except:
        lspci_output = []

    target_search_term = re.compile(r"1002:\w+")
    for line in lspci_output:
        search_result = target_search_term.search(line)
        if search_result is not None:
            device_id = int(search_result.group(0).split(":")[1], 16)
            # try lookup from ISA_TO_ID dict
            for target in ISA_TO_ID.keys():
                for target_device_id in ISA_TO_ID[target]:
                    if device_id == target_device_id:
                        target_list.append(target)
                        break

    return target_list


def readFromKFD():
    target_list = []

    topology_dir = "/sys/class/kfd/kfd/topology/nodes/"
    if os.path.isdir(topology_dir):
        for node in sorted(os.listdir(topology_dir)):
            node_path = os.path.join(topology_dir, node)
            if os.path.isdir(node_path):
                prop_path = node_path + "/properties"
                if os.path.isfile(prop_path) and os.access(prop_path, os.R_OK):
                    target_search_term = re.compile(r"gfx_target_version.+")
                    with open(prop_path) as f:
                        try:
                            line = f.readline()
                        except PermissionError:
                            # We may have a subsystem (e.g. scheduler) limiting device visibility which
                            # could cause a permission error.
                            line = ""
                        while line != "":
                            search_result = target_search_term.search(line)
                            if search_result is not None:
                                device_id = int(
                                    search_result.group(0).split(" ")[1], 10
                                )
                                if device_id != 0:
                                    gfx_override = os.environ.get(
                                        "HSA_OVERRIDE_GFX_VERSION"
                                    )
                                    if gfx_override is not None:
                                        try:
                                            override_tokens = gfx_override.split(".")
                                            major_ver = int(override_tokens[0])
                                            minor_ver = int(override_tokens[1])
                                            stepping_ver = int(override_tokens[2])
                                            if (
                                                major_ver > 63
                                                or minor_ver > 255
                                                or stepping_ver > 255
                                            ):
                                                print(
                                                    "Invalid HSA_OVERRIDE_GFX_VERSION value"
                                                )
                                                major_ver = 0
                                                minor_ver = 0
                                                stepping_ver = 0
                                        except Exception as e:
                                            print(
                                                'Invalid HSA_OVERRIDE_GFX_VERSION format expected "1.2.3"'
                                            )
                                            major_ver = 0
                                            minor_ver = 0
                                            stepping_ver = 0
                                    else:
                                        major_ver = int((device_id / 10000) % 100)
                                        minor_ver = int((device_id / 100) % 100)
                                        stepping_ver = int(device_id % 100)

                                    target_list.append(
                                        "gfx"
                                        + format(major_ver, "d")
                                        + format(minor_ver, "x")
                                        + format(stepping_ver, "x")
                                    )
                            line = f.readline()

    return target_list


def main():
    if len(sys.argv) == 2 and sys.argv[1] == "-name":
        """Prints the list of available AMD GCN target names extracted from rocminfo, a tool
        shipped with this script to enumerate GPU agents available on a working ROCm stack."""
        target_list = readFromROCMINFO(True)
    else:
        """Prints the list of available AMD GCN ISA

        The program collects the list in 3 different ways, in the order of
        precendence:

        1. ROCM_TARGET_LST : a user defined environment variable, set to the path and
                           filename where to find the "target.lst" file. This can be
                           used in an install environment with sandbox, where
                           execution of "rocminfo" is not possible.
        2. target.lst : user-supplied text file. This is used in a container setting
                      where ROCm stack may usually not available.
        3. HSA topology : gathers the information from the HSA node topology in
                          /sys/class/kfd/kfd/topology/nodes/
        4. lspci : enumerate PCI bus and locate supported devices from a hard-coded
                   lookup table.
        5. rocminfo : a tool shipped with this script to enumerate GPU agents
                    available on a working ROCm stack.
        """
        target_list = readFromTargetLstFile()

        if len(target_list) == 0:
            target_list = readFromKFD()

        if len(target_list) == 0:
            target_list = readFromLSPCI()

        if len(target_list) == 0:
            target_list = readFromROCMINFO()

    for gfx in target_list:
        print(gfx)


if __name__ == "__main__":
    main()
