# Copyright (c) Advanced Micro Devices, Inc.
# SPDX-License-Identifier:  MIT

"""Static instruction execution pipeline lookup.

Map a disassembled instruction to the pipeline that runs it (VALU, MATRIX,
SCALAR, and so on) using the generated mnemonic table. This is a property of
the instruction itself, so it applies to every disassembled line, not only the
offsets PC sampling landed on.

The table is generated by ``tools/instruction_pipeline_generator.py``.
"""

import functools
import json
from typing import Optional

import config
from utils.logger import console_warning

INSTRUCTION_PIPELINES_FILE = "instruction_pipelines.json"


def classify(instruction: Optional[str]) -> Optional[str]:
    """Return the execution pipeline of a disassembly line.

    Returns None for a line whose mnemonic the table does not hold, which
    leaves the instruction type unset rather than guessing a pipeline.
    """
    if not instruction:
        return None
    mnemonic = instruction.split(maxsplit=1)[0]
    return _load_instruction_pipelines().get(mnemonic)


@functools.lru_cache(maxsize=1)
def _load_instruction_pipelines() -> dict[str, str]:
    """Load the generated mnemonic-to-pipeline map, once per process."""
    path = (
        config.rocprof_compute_home
        / "rocprof_compute_soc"
        / "analysis_configs"
        / INSTRUCTION_PIPELINES_FILE
    )
    if not path.is_file():
        console_warning(
            f"Instruction pipeline table missing ({path}); "
            "instruction types will be empty."
        )
        return {}
    return json.loads(path.read_text(encoding="utf-8")).get("pipelines", {})
