#!/bin/bash
cmake \
  -B build/release \
  -DCMAKE_CXX_COMPILER=/work/lmeadows/rocm/aomp/bin/amdclang++ \
  -DBUILD_TESTS=ON \
  -DENABLE_IFC=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_LOCAL_GPU_TARGET_ONLY=ON \
  -DROCM_PATH=/opt/rocm \
  -DENABLE_SPLIT_DEVICE_COMPILE=ON \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -G Ninja

