# - How to use:
#     python3 -m pip install pre-commit
#     pre-commit install --install hooks
# Upon a new commit - the hooks should automagically run
#
# - How to skip:
#     git commit --no-verify
# or
#     SKIP=clang-format git commit
#     SKIP=gersemi git commit

fail_fast: false
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.7
    hooks:
    - id: clang-format
      types_or: [c++, c]

  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.20.1
    hooks:
    - id: gersemi
