######################################################################################
# Name            : Rocm Validation Suite
# Developed by    : kiran.thumma@amd.com, gajeambi@amd.com
# Maintained by   : kiran.thumma@amd.com, gajendrad.ambi@amd.com
# Version         : 0.5
# Description     : This workflow will eventually call the central rocm reusable workflow.
#                   So developers should not edit/Modify this file
#                   Donot add it into .*ignore file#
# Docs            :
######################################################################################
name: Rocm Validation Suite KWS
on:
  push:
    branches: [amd-staging]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  kws:
    # runs only for PR events. Add 3 environment variables in repo's settings
    # - PROJECT_NAME : your project's name in keywordsearch.amd.com
    # - KEYWORD_SCAN_USER : your username in keywordsearch.amd.com to access the above project
    # - KEYWORD_SCAN_PASSWORD : your password in keywordsearch.amd.com to access the above project
    if: ${{ github.event_name == 'pull_request' }}
    uses: AMD-ROCm-Internal/rocm_ci_infra/.github/workflows/common.yaml@main
    secrets: inherit

  # Add your repo specific workflows (if any) below this line, edit nothing above this line.
  other-job:
    runs-on: ubuntu-latest
    steps:
      - name: KWS SCAN check
        run: echo "End of repo specific workflow"
