if(NOT DEFINED EXPECTED_ROCTX)
    set(EXPECTED_ROCTX 1)
endif()

if(NOT "$ENV{TORCH_PROFILER_EMIT_ROCTX}" STREQUAL "${EXPECTED_ROCTX}")
    message(
        FATAL_ERROR
            "Expected TORCH_PROFILER_EMIT_ROCTX=${EXPECTED_ROCTX}, got '$ENV{TORCH_PROFILER_EMIT_ROCTX}'"
        )
endif()

if(EXPECTED_ROCTX AND NOT "$ENV{ROCPROF_MARKER_API_TRACE}" STREQUAL "1")
    message(
        FATAL_ERROR
            "Expected ROCPROF_MARKER_API_TRACE=1, got '$ENV{ROCPROF_MARKER_API_TRACE}'")
endif()
