// Copyright (C) 2024 Advanced Micro Devices. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

//! Rust bindings for the AMD System Management Interface (AMD-SMI) library.
//!
//! This crate provides safe wrappers around the AMD-SMI C library, enabling
//! GPU and CPU monitoring and management on AMD hardware. It covers device
//! discovery, power/thermal monitoring, clock and performance control, memory
//! and PCIe info, ECC/RAS error tracking, process accounting, and more.
//!
//! # Prerequisites
//!
//! - **Linux only** — AMD-SMI requires the `amdgpu` kernel driver.
//! - The `libamd_smi.so` shared library must be installed. It ships with
//!   [ROCm](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/)
//!   or can be [built from source](https://github.com/ROCm/rocm-systems/tree/develop/projects/amdsmi).
//! - At runtime, ensure the library is on the linker search path
//!   (e.g. `LD_LIBRARY_PATH=/opt/rocm/lib`).
//!
//! At build time the [`build.rs`](https://github.com/ROCm/rocm-systems/blob/develop/projects/amdsmi/rust-interface/build.rs)
//! locates `libamd_smi.so` by checking, in order:
//!
//! 1. The `AMDSMI_LIB_DIR` environment variable
//! 2. `./lib/` relative to the build (used by the CMake source-tarball flow)
//! 3. `pkg-config --libs-only-L amd_smi`
//! 4. The most recently installed `/opt/rocm*/lib` directory
//!
//! # Quick start
//!
//! ```no_run
//! use amdsmi::*;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     // Initialize the library
//!     amdsmi_init(AmdsmiInitFlagsT::AmdsmiInitAmdGpus)?;
//!
//!     // Enumerate every GPU across all sockets
//!     for socket in amdsmi_get_socket_handles()? {
//!         for gpu in amdsmi_get_processor_handles(socket)? {
//!             let bdf = amdsmi_get_gpu_device_bdf(gpu)?;
//!             let busy = amdsmi_get_gpu_busy_percent(gpu)?;
//!             println!("{bdf}: {busy}% utilization");
//!         }
//!     }
//!
//!     amdsmi_shut_down()?;
//!     Ok(())
//! }
//! ```
//!
//! # RAII initialization
//!
//! [`AmdSmiGuard`] calls [`amdsmi_shut_down`] automatically when dropped,
//! so you cannot forget to clean up — including on early returns and panics:
//!
//! ```no_run
//! use amdsmi::*;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let _smi = AmdSmiGuard::new(AmdsmiInitFlagsT::AmdsmiInitAmdGpus)?;
//!     // ... use the library ...
//!     // amdsmi_shut_down() is called when `_smi` goes out of scope
//!     Ok(())
//! }
//! ```
//!
//! # Thread safety
//!
//! The underlying C library serializes access with a global mutex and is safe
//! to call from multiple threads. The handle types ([`AmdsmiProcessorHandle`],
//! [`AmdsmiSocketHandle`]) are raw pointer aliases (`*mut c_void`) and therefore
//! do **not** implement [`Send`] or [`Sync`]. To use handles across threads,
//! wrap them in a newtype that asserts the safety invariant:
//!
//! ```rust
//! use amdsmi::AmdsmiProcessorHandle;
//!
//! /// Wrapper that is safe to send across threads because the
//! /// underlying AMD-SMI library is internally synchronized.
//! #[derive(Clone, Copy)]
//! struct GpuHandle(AmdsmiProcessorHandle);
//! unsafe impl Send for GpuHandle {}
//! unsafe impl Sync for GpuHandle {}
//! ```
//!
//! # Type re-exports
//!
//! The crate re-exports the handle types generated by the low-level wrapper:
//!
//! ```
//! use amdsmi::{AmdsmiNodeHandle, AmdsmiProcessorHandle, AmdsmiSocketHandle};
//!
//! fn _accept_handles(
//!     _node: Option<AmdsmiNodeHandle>,
//!     _processor: Option<AmdsmiProcessorHandle>,
//!     _socket: Option<AmdsmiSocketHandle>,
//! ) {
//! }
//! ```

#![allow(dead_code)]
// FFI bindings use opaque pointer handles (AmdsmiProcessorHandle,
// AmdsmiSocketHandle) which are passed straight through to C functions.
// Clippy's not_unsafe_ptr_arg_deref warning is a false positive for this
// common FFI pattern - the pointers are never dereferenced in Rust code,
// they are opaque handles managed by the C library.
#![allow(clippy::not_unsafe_ptr_arg_deref)]

mod amdsmi_wrapper;

#[macro_use]
mod utils;
mod amdsmi;

pub use amdsmi::*;
pub use utils::*;
