#!/bin/bash
# Start a single-node Slurm cluster inside the container.
#
# Must be called before any srun-based test.  Generates slurm.conf and
# gres.conf dynamically so the hostname and GPU count are always correct
# regardless of which container runtime sets them.
#
# Usage:
#   bash /usr/local/bin/start_slurm.sh && export SLURM_READY=1

set -euo pipefail

SLURM_CONF=/etc/slurm/slurm.conf
GRES_CONF=/etc/slurm/gres.conf
SLURM_LOG_DIR=/var/log/slurm
SLURM_RUN_DIR=/var/run/slurm

mkdir -p /etc/slurm "${SLURM_LOG_DIR}" "${SLURM_RUN_DIR}"

# --------------------------------------------------------------------------
# Kill any stale daemons from a previous run
# --------------------------------------------------------------------------
for f in "${SLURM_RUN_DIR}/slurmctld.pid" "${SLURM_RUN_DIR}/slurmd.pid"; do
    if [[ -f "$f" ]]; then
        pid=$(cat "$f" 2>/dev/null || true)
        [[ -n "$pid" ]] && kill "$pid" 2>/dev/null || true
        rm -f "$f"
    fi
done
# Also kill by name in case pids are stale
pkill -x slurmctld 2>/dev/null || true
pkill -x slurmd    2>/dev/null || true
sleep 1

# --------------------------------------------------------------------------
# Detect resources
# --------------------------------------------------------------------------
NODE=$(hostname -s)
NCPUS=$(nproc)

if command -v rocm-smi &>/dev/null; then
    NGPUS=$(rocm-smi --showserial 2>/dev/null | grep -c "^GPU" || true)
else
    NGPUS=0
fi

echo "Slurm setup: node=${NODE} cpus=${NCPUS} gpus=${NGPUS}"

# --------------------------------------------------------------------------
# gres.conf
# --------------------------------------------------------------------------
if [[ $NGPUS -gt 0 ]]; then
    {
        echo "# Auto-generated by start_slurm.sh"
        for i in $(seq 0 $((NGPUS - 1))); do
            echo "Name=gpu File=/dev/dri/renderD$((128 + i))"
        done
    } > "${GRES_CONF}"
    GRES_LINE="GresTypes=gpu"
    NODE_GRES="Gres=gpu:${NGPUS}"
else
    echo "# No GPUs detected" > "${GRES_CONF}"
    GRES_LINE=""
    NODE_GRES=""
fi

# --------------------------------------------------------------------------
# slurm.conf — no cgroups (unavailable in containers), no accounting DB.
# CgroupPlugin=disabled keeps slurmd from trying cgroup/v2 via dbus.
# --------------------------------------------------------------------------
cat > "${SLURM_CONF}" <<EOF
# Auto-generated by start_slurm.sh — $(date)
ClusterName=rocshmem-ci
SlurmctldHost=${NODE}

AuthType=auth/munge
CryptoType=crypto/munge

SlurmctldPort=6817
SlurmdPort=6818
SlurmctldLogFile=${SLURM_LOG_DIR}/slurmctld.log
SlurmdLogFile=${SLURM_LOG_DIR}/slurmd.log
SlurmctldPidFile=${SLURM_RUN_DIR}/slurmctld.pid
SlurmdPidFile=${SLURM_RUN_DIR}/slurmd.pid
SlurmdSpoolDir=${SLURM_RUN_DIR}/slurmd

ProctrackType=proctrack/linuxproc
TaskPlugin=task/none

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

${GRES_LINE}

StateSaveLocation=/var/spool/slurmctld
ReturnToService=2

NodeName=${NODE} CPUs=${NCPUS} ${NODE_GRES} State=IDLE
PartitionName=debug Nodes=${NODE} Default=YES MaxTime=INFINITE State=UP
EOF

# --------------------------------------------------------------------------
# Munge
# --------------------------------------------------------------------------
mkdir -p /run/munge /var/log/munge
chown munge:munge /run/munge /var/log/munge /etc/munge/munge.key
chmod 400 /etc/munge/munge.key
munged --force
sleep 1

# --------------------------------------------------------------------------
# slurmctld + slurmd
# --------------------------------------------------------------------------
mkdir -p /var/spool/slurmctld "${SLURM_RUN_DIR}/slurmd"

# Slurm 23.11 requires the slurmstepd cgroup scope directory to exist before
# slurmd starts, even when cgroup constraints are disabled.  Pre-create it so
# slurmd doesn't fail trying to set it up via dbus/systemd (unavailable in
# containers without a system bus).
mkdir -p "/sys/fs/cgroup/system.slice/${NODE}_slurmstepd.scope" 2>/dev/null || true

# cgroup.conf: disable all cgroup enforcement so slurmd starts without dbus/systemd
cat > /etc/slurm/cgroup.conf << 'CGEOF'
CgroupAutomount=no
ConstrainCores=no
ConstrainDevices=no
ConstrainRAMSpace=no
ConstrainSwapSpace=no
CGEOF

# Slurm's mpi/pmix_v5 plugin was built against the system libpmix.
# Prepend the system multiarch path so slurmctld/slurmd/slurmstepd
# pick up /usr/lib/x86_64-linux-gnu/libpmix.so.2, not /opt/pmix/lib.
SYSTEM_LIB=/usr/lib/x86_64-linux-gnu
export LD_LIBRARY_PATH="${SYSTEM_LIB}:${LD_LIBRARY_PATH:-}"

slurmctld -c
sleep 2
slurmd -N "${NODE}"
sleep 2
scontrol update NodeName="${NODE}" State=RESUME 2>/dev/null || true
sleep 1

# --------------------------------------------------------------------------
# Wait for IDLE
# --------------------------------------------------------------------------
echo "Waiting for Slurm node ${NODE} to become IDLE..."
for i in $(seq 1 30); do
    STATE=$(sinfo -h -N -n "${NODE}" -o "%T" 2>/dev/null || true)
    if [[ "$STATE" == "idle" ]]; then
        echo "Slurm ready — node ${NODE} is IDLE"
        exit 0
    fi
    sleep 1
done

echo "ERROR: Slurm node ${NODE} did not reach IDLE state after 30s (state: ${STATE})"
tail -20 "${SLURM_LOG_DIR}/slurmctld.log" || true
tail -20 "${SLURM_LOG_DIR}/slurmd.log" || true
exit 1
