name: ABI Guard Workflow using libabigail

on:
  workflow_call:
    inputs:
      versioning_spec:
        description: "Path to versioning specification file."
        required: true
        type: string

      container:
        description: "Container image to use for builds."
        required: true
        type: string

      # MODE
      use_external_build_artifacts:
        description: "If true, skip building here and use artifacts supplied by the caller."
        required: false
        type: boolean
        default: false

      # Build / repo inputs (used when not using external artifacts)
      cmake_build_type:
        description: "CMAKE_BUILD_TYPE for both builds."
        required: false
        type: string
        default: "RelWithDebInfo"

      # directory containing source to build (i.e. top-level CMakeLists.txt)
      source_directory:
        description: "Path to source directory."
        required: true
        type: string

      checkout_submodules:
        description: "Whether to checkout git submodules."
        required: false
        type: boolean
        default: false

      cmake_generator:
        description: "CMake generator."
        required: false
        type: string
        default: "Ninja"

      cmake_config_args:
        description: "Extra CMake configure args (space-separated)."
        required: false
        type: string
        default: ""

      install_packages:
        description: "Extra apt packages to install (space-separated)."
        required: false
        type: string
        default: ""

      tag_pattern:
        description: "Pattern for baseline semver tags."
        required: false
        type: string
        default: "v[0-9]*.[0-9]*.[0-9]*"

      # Artifact/glob inputs
      head_artifact_name:
        description: "Artifact name for HEAD build (when use_external_build_artifacts=true)."
        required: false
        type: string
        default: "build-head"

      baseline_artifact_name:
        description: "Artifact name for baseline build (when use_external_build_artifacts=true)."
        required: false
        type: string
        default: "build-baseline"

      abidw_args:
        description: "Additional args for abidw."
        required: false
        type: string
        default: ""

      abidiff_args:
        description: "Additional args for abidiff."
        required: false
        type: string
        default: ""

jobs:
  build-head:
    if: ${{ !inputs.use_external_build_artifacts }}
    name: Build (HEAD)
    runs-on: ubuntu-latest
    container:
        image: ${{ inputs.container }}
        env:
          DEBIAN_FRONTEND: noninteractive
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    env:
      BUILD_DIR: build
      INSTALL_DIR: install
    steps:
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y git pkg-config build-essential cmake ninja-build ${{ inputs.install_packages }}

      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
          ref: ${{ github.base_ref || github.event.repository.default_branch }}
          submodules: ${{ inputs.checkout_submodules }}

      - name: Show git branch
        shell: bash
        run: |
          set -euov pipefail
          pwd
          ls -la ${PWD}
          git config --global --add safe.directory ${PWD}
          set +v
          echo -n "Branch: "
          git branch --show-current
          echo -n "Commit: "
          git rev-parse HEAD

    #   - name: Cache CMake build (HEAD)
    #     uses: actions/cache@v4
    #     with:
    #       path: ${{ env.BUILD_DIR }}
    #       key: cmake-${{ runner.os }}-head-${{ hashFiles('CMakeLists.txt', '**/*.cmake', inputs.version_file) }}
    #       restore-keys: |
    #         cmake-${{ runner.os }}-head-

      - name: Configure
        run: cmake -S ${{ inputs.source_directory }} -B ${{ inputs.source_directory }}/${BUILD_DIR} -G "${{ inputs.cmake_generator }}" -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} ${{ inputs.cmake_config_args }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }}

      - name: Build
        run: cmake --build ${{ inputs.source_directory }}/${BUILD_DIR} --config ${{ inputs.cmake_build_type }} --target all --parallel 8

      - name: Install
        run: cmake --build ${{ inputs.source_directory }}/${BUILD_DIR} --config ${{ inputs.cmake_build_type }} --target install --parallel 8

      - name: Cleanup build object and static library files
        run: find ${{ inputs.source_directory }}/${BUILD_DIR} -type f \( -name '*.o' -o -name '*.a' \) -delete

      - name: List Files
        shell: bash
        run: |
          set -euov pipefail
          pwd
          ls -la ${PWD}

      - name: Upload HEAD build
        uses: actions/upload-artifact@v4
        with:
          name: build-head
          path: |
            ${{ github.workspace }}/
          if-no-files-found: error
          retention-days: 1

  build-baseline:
    if: ${{ !inputs.use_external_build_artifacts }}
    name: Build (BASELINE)
    runs-on: ubuntu-latest
    container:
        image: ${{ inputs.container }}
        env:
          DEBIAN_FRONTEND: noninteractive
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    # outputs:
    #   tag: ${{ steps.tag.outputs.tag }}
    env:
      BUILD_DIR: build
      INSTALL_DIR: install
      OLD_SRC: baseline-src
    steps:
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y git pkg-config build-essential cmake ninja-build ${{ inputs.install_packages }}

      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
          ref: ${{ github.base_ref || github.event.repository.default_branch }}
          submodules: ${{ inputs.checkout_submodules }}

    #   - name: Determine baseline tag
    #     id: tag
    #     shell: bash
    #     run: |
    #       set -euo pipefail
    #       git fetch --tags --force
    #       BASE_BRANCH="${{ github.base_ref || github.event.repository.default_branch }}"
    #       MB=$(git merge-base HEAD "origin/${BASE_BRANCH}")
    #       TAG=$(git tag --merged "$MB" --list '${{ inputs.tag_pattern }}' --sort=-version:refname | head -n1)
    #       if [[ -z "$TAG" ]]; then
    #         echo "No baseline tag found matching pattern: ${{ inputs.tag_pattern }}"
    #         exit 1
    #       fi
    #       echo "tag=$TAG" >> "$GITHUB_OUTPUT"

    #   - name: Prepare worktree
    #     run: git worktree add "$OLD_SRC" "${{ steps.tag.outputs.tag }}"

      - name: Show git branch
        shell: bash
        run: |
          set -euov pipefail
          pwd
          ls -la ${PWD}
          git config --global --add safe.directory ${PWD}
          set +v
          echo -n "Branch: "
          git branch --show-current
          echo -n "Commit: "
          git rev-parse HEAD

    #   - name: Cache CMake build (baseline)
    #     uses: actions/cache@v4
    #     with:
    #       path: ${{ env.BUILD_DIR }}
    #       key: cmake-${{ runner.os }}-baseline-${{ steps.tag.outputs.tag }}-${{ hashFiles(format('{0}/CMakeLists.txt', env.OLD_SRC), format('{0}/**/*.cmake', env.OLD_SRC)) }}
    #       restore-keys: |
    #         cmake-${{ runner.os }}-baseline-

      - name: Configure
        run: cmake -S ${{ inputs.source_directory }} -B ${{ inputs.source_directory }}/${BUILD_DIR} -G "${{ inputs.cmake_generator }}" -DCMAKE_BUILD_TYPE=${{ inputs.cmake_build_type }} ${{ inputs.cmake_config_args }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }}

      - name: Build
        run: cmake --build ${{ inputs.source_directory }}/${BUILD_DIR} --config ${{ inputs.cmake_build_type }} --target all --parallel 8

      - name: Install
        run: cmake --build ${{ inputs.source_directory }}/${BUILD_DIR} --config ${{ inputs.cmake_build_type }} --target install --parallel 8

      - name: Cleanup build object and static library files
        run: find ${{ inputs.source_directory }}/${BUILD_DIR} -type f \( -name '*.o' -o -name '*.a' \) -delete

      - name: List Files
        shell: bash
        run: |
          set -euov pipefail
          pwd
          ls -la ${PWD}

      - name: Upload baseline build
        uses: actions/upload-artifact@v4
        with:
          name: build-baseline
          path: |
            ${{ github.workspace }}/
          if-no-files-found: error
          retention-days: 1

  # Runs when you are building inside this workflow
  abi-guard-internal:
    if: ${{ !inputs.use_external_build_artifacts }}
    needs: [build-head, build-baseline]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    env:
      VERSIONING_SPEC: ${{ inputs.versioning_spec }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
      - name: Install libabigail
        run: |
          sudo apt-get update
          sudo apt-get install -y abigail-tools python3 python3-pip
      - name: Download HEAD artifact
        uses: actions/download-artifact@v4
        with:
          name: build-head
          path: build-head/
      - name: Download baseline artifact
        uses: actions/download-artifact@v4
        with:
          name: build-baseline
          path: build-baseline/
      - name: Run ABI Guard (Python)
        run: |
          pwd
          ls -la ${PWD}
          python3 -m pip install -r scripts/requirements.txt
          ls -la build-head/
          ls -la build-baseline/
          ls -la build-head/${{ inputs.source_directory }}
          ls -la build-baseline/${{ inputs.source_directory }}
          ls -la build-head/$(dirname ${{ inputs.versioning_spec }})
          ls -la build-baseline/$(dirname ${{ inputs.versioning_spec }})
          python3 scripts/abi-guard.py check \
            -i "build-head/${{ inputs.versioning_spec }}" \
            -b "build-baseline/${{ inputs.versioning_spec }}" \
            --build-directory "build" \
            --abidw-args "${{ inputs.abidw_args }}" \
            --abidiff-args "${{ inputs.abidiff_args }}" \
            --report-dir "abi-guard/diff-reports" \
            --abi-base-dir "abi-guard/abi-base" \
            --abi-head-dir "abi-guard/abi-head"
      - name: Upload abidiff reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: abi-guard-diff-reports
          path: abi-guard/
          if-no-files-found: ignore

  # Runs when caller provides external artifacts (no build deps)
  abi-guard-external:
    if: ${{ inputs.use_external_build_artifacts }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    env:
      VERSIONING_SPEC: ${{ inputs.versioning_spec }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
      - name: Install libabigail
        run: |
          sudo apt-get update
          sudo apt-get install -y abigail-tools python3 python3-pip
      - name: Download HEAD artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.head_artifact_name }}
          path: build-head/
      - name: Download baseline artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.baseline_artifact_name }}
          path: build-baseline/
      - name: Run ABI Guard (Python)
        run: |
          pwd
          ls -la ${PWD}
          python3 -m pip install -r scripts/requirements.txt
          ls -la build-head/
          ls -la build-baseline/
          ls -la build-head/${{ inputs.source_directory }}
          ls -la build-baseline/${{ inputs.source_directory }}
          ls -la build-head/$(dirname ${{ inputs.versioning_spec }})
          ls -la build-baseline/$(dirname ${{ inputs.versioning_spec }})
          python3 scripts/abi-guard.py check \
            -i "build-head/${{ inputs.versioning_spec }}" \
            -b "build-baseline/${{ inputs.versioning_spec }}" \
            --build-directory "build" \
            --abidw-args "${{ inputs.abidw_args }}" \
            --abidiff-args "${{ inputs.abidiff_args }}" \
            --report-dir "abi-guard/diff-reports" \
            --abi-base-dir "abi-guard/abi-base" \
            --abi-head-dir "abi-guard/abi-head"
      - name: Upload abidiff reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: abi-guard-diff-reports
          path: abi-guard/
          if-no-files-found: ignore
