name: AqlProfile Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'projects/aqlprofile/**'
      - '!projects/aqlprofile/*.md'
      - '!projects/aqlprofile/CODEOWNERS'
      - '!projects/aqlprofile/source/docs/**'
      - '.github/workflows/aqlprofile-continuous_integration.yml'
  pull_request:
    paths:
      - 'projects/aqlprofile/**'
      - '!projects/aqlprofile/*.md'
      - '!projects/aqlprofile/CODEOWNERS'
      - '!projects/aqlprofile/source/docs/**'
      - '.github/workflows/aqlprofile-continuous_integration.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # TODO(jrmadsen): replace LD_RUNPATH_FLAG, GPU_TARGETS, etc. with internal handling in cmake
  PATH: "/usr/bin:$PATH"
  navi3_EXCLUDE_TESTS_REGEX: ""
  vega20_EXCLUDE_TESTS_REGEX: ""
  mi200_EXCLUDE_TESTS_REGEX: ""
  mi300_EXCLUDE_TESTS_REGEX: ""
  mi300a_EXCLUDE_TESTS_REGEX: ""
  mi325_EXCLUDE_TESTS_REGEX: ""
  navi4_EXCLUDE_TESTS_REGEX: ""
  navi3_EXCLUDE_LABEL_REGEX: ""
  vega20_EXCLUDE_LABEL_REGEX: ""
  mi200_EXCLUDE_LABEL_REGEX: ""
  mi300_EXCLUDE_LABEL_REGEX: ""
  mi300a_EXCLUDE_LABEL_REGEX: ""
  mi325_EXCLUDE_LABEL_REGEX: ""
  navi4_EXCLUDE_LABEL_REGEX: ""

jobs:
  core-deb:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        system: [
          {gpu: 'navi4', runner: 'rocprofiler-navi4', os: 'ubuntu-22.04', build-type: 'RelWithDebInfo'},
          {gpu: 'navi3', runner: 'rocprofiler-navi3', os: 'ubuntu-22.04', build-type: 'RelWithDebInfo'},
          {gpu: 'mi3xx', runner: 'linux-mi325-1gpu-ossci-rocm', os: 'ubuntu-22.04', build-type: 'RelWithDebInfo'}
        ]

    runs-on: ${{ matrix.system.runner }}

    permissions:
      contents: read
      pull-requests: write

    # define this for containers
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

    steps:
    - name: Install Latest ROCm
      if: matrix.system.runner == 'mi3xx'
      shell: bash
      working-directory: /tmp
      run: |
        sudo apt update
        sudo apt install -y wget sudo curl git
        export ROCM_JOB_NAME="compute-rocm-dkms-${ROCM_BUILD_TYPE}-hipclang"
        export ROCM_JOB_BASE_URL="http://rocm-ci.amd.com/job/${ROCM_JOB_NAME}/"
        export ROCM_JOB_API_URL_POSTFIX="/api/json?pretty=true"
        export ROCM_JOB_BUILD_NUMBER_URL_POSTFIX="/buildNumber"
        export ROCM_JOB_API_FULL_URL="${ROCM_JOB_BASE_URL}${ROCM_JOB_NUMBER}${ROCM_JOB_API_URL_POSTFIX}"
        export ROCM_JOB_BUILD_NUMBER_FULL_URL="${ROCM_JOB_BASE_URL}${ROCM_JOB_NUMBER}${ROCM_JOB_BUILD_NUMBER_URL_POSTFIX}"
        wget https://artifactory-cdn.amd.com/artifactory/list/amdgpu-deb/amdgpu-install-internal_$(curl -s ${ROCM_JOB_API_FULL_URL} | grep amdgpu-install-internal_ | sed 's/.*amdgpu-install-internal//' | awk -F'[_|-]' '{print $2}' | tr -d '\n')-22.04-1_all.deb
        sudo apt install -y ./*_all.deb
        sudo amdgpu-repo --amdgpu-build=$(curl -s ${ROCM_JOB_API_FULL_URL} | grep amdgpu-build | sed 's/.* --amdgpu-build//' | awk -F'[=| |<]' '{print $2}' | tr -d '\n') --rocm-build=${ROCM_JOB_NAME}/$(curl -s ${ROCM_JOB_BUILD_NUMBER_FULL_URL})
        sudo amdgpu-install -y --no-dkms --usecase=rocm
        rm -rf amdgpu-install-internal_*.deb
    
    - uses: actions/checkout@v4
      with:
        sparse-checkout: projects/aqlprofile
        set-safe-directory: true

    - name: Install requirements
      timeout-minutes: 10
      shell: bash
      env:
        GPU_RUNNER: "{{ matrix.system.runner }}"
      run: |
        [ "${GPU_RUNNER}" == "mi3xx" ] && export PRE_COMMAND="sudo"
        git config --global --add safe.directory '*'
        $PRE_COMMAND apt-get update
        $PRE_COMMAND apt-get install -y build-essential cmake g++-11 g++-12 python3-pip libgtest-dev libgmock-dev
        $PRE_COMMAND update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 10 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        $PRE_COMMAND update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 20 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12

    - name: List Files
      shell: bash
      run: |
        echo "PATH: ${PATH}"
        echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
        which-realpath() { echo -e "\n$1 resolves to $(realpath $(which $1))"; echo "$($(which $1) --version &> /dev/stdout | head -n 1)"; }
        for i in python3 git cmake ctest gcc g++ gcov; do which-realpath $i; done
        cat /opt/rocm/.info/version
        ls -la
        pwd

    - name: Configure, Build, and Test
      timeout-minutes: 30
      shell: bash
      run:
        LD_LIBRARY_PATH=$(pwd)/build:$LD_LIBRARY_PATH /usr/bin/ctest --output-on-failure -VV -DCTEST_SOURCE_DIRECTORY="$(pwd)"
          -DCTEST_BINARY_DIRECTORY="$(pwd)/build" -DAQLPROFILE_BUILD_NUM_JOBS="16" -DCTEST_SITE="${RUNNER_HOSTNAME}"
          -DCTEST_BUILD_NAME=PR_${{ github.ref_name }}_${{ github.repository }}-${{ matrix.os }}-${{ matrix.gpu }}-core
          -DCMAKE_CTEST_ARGUMENTS=""
          -DAQLPROFILE_BUILD_TESTS=ON
          -DAQLPROFILE_EXTRA_CONFIGURE_ARGS=""
          -S $(pwd)/projects/aqlprofile/dashboard.cmake

  core-rpm:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        runner: ['mi300']
        os: ['rhel-9', 'sles-15']
        build-type: ['RelWithDebInfo']
        ci-flags: ['--linter clang-tidy']

    runs-on: rocprofiler-${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: write

    # define this for containers
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: projects/aqlprofile
        set-safe-directory: true

    - name: Install requirements
      timeout-minutes: 10
      shell: bash
      run: git config --global --add safe.directory '*'

    - name: List Files
      shell: bash
      run: |
        echo "PATH: ${PATH}"
        echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
        which-realpath() { echo -e "\n$1 resolves to $(realpath $(which $1))"; echo "$($(which $1) --version &> /dev/stdout | head -n 1)"; }
        for i in python3 git cmake ctest gcc g++ gcov; do which-realpath $i; done
        cat /opt/rocm/.info/version
        ls -la
        pwd

    - name: Configure, Build, and Test
      timeout-minutes: 30
      shell: bash
      run:
        LD_LIBRARY_PATH=$(pwd)/build:$LD_LIBRARY_PATH ctest --output-on-failure -VV -DCTEST_SOURCE_DIRECTORY="$(pwd)"
          -DCTEST_BINARY_DIRECTORY="$(pwd)/build" -DAQLPROFILE_BUILD_NUM_JOBS="16" -DCTEST_SITE="${RUNNER_HOSTNAME}"
          -DCTEST_BUILD_NAME=PR_${{ github.ref_name }}_${{ github.repository }}-${{ matrix.os }}-${{ matrix.runner }}-core
          -DCMAKE_CTEST_ARGUMENTS=""
          -DAQLPROFILE_BUILD_TESTS=ON
          -DAQLPROFILE_EXTRA_CONFIGURE_ARGS=""
          -S $(pwd)/projects/aqlprofile/dashboard.cmake
