name: new_CI_image
run-name: Build the Docker image for hipFile CI

env:
  AIS_INPUT_ROCM_VERSION: ${{ inputs.rocm_version }}

on:
  workflow_call:
    inputs:
      ci_image_name:
        description: "Full CI image name & tag to build/push"
        required: true
        type: string
      ci_image_cache:
        description: "Full CI cache image name & tag for Docker build cache"
        required: true
        type: string
      ci_image_name_nvidia:
        description: "Full CI image name & nvidia tag to build/push"
        required: true
        type: string
      ci_image_cache_nvidia:
        description: "Full CI cache image name & nvidia tag for Docker build cache"
        required: true
        type: string
      platform:
        required: true
        type: string
      rocm_version:
        description: "Target ROCm MAJOR.MINOR.PATCH Version"
        required: true
        type: string
    outputs:
      ci_image:
        description: "The full name & tag of the CI image to use."
        value: ${{ inputs.ci_image_name }}
      ci_image_nvidia:
        description: "The full name & nvidia tag of the CI image to use."
        value: ${{ inputs.ci_image_name_nvidia }}

permissions:
  contents: read
  packages: write

jobs:
  build_AIS_image:
    runs-on: [ubuntu-24.04]
    container: docker:28.5
    steps:
      - name: Fetching code repository...
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          sparse-checkout: |
            projects/hipfile
            .github/workflows

      - name: Authenticating to GitHub Container Registry.
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Builder
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          name: ais-builder
          driver: docker-container
          cache-binary: false # True uses the GHA Cache Backend

      - name: Build base image for AIS CI
        run: |
          docker buildx build \
            -f "${GITHUB_WORKSPACE}/projects/hipfile/util/docker/DOCKERFILE.ais_ci_${{ inputs.platform }}" \
            --target base \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg ROCM_VERSION=${AIS_INPUT_ROCM_VERSION} \
            --cache-from=type=registry,ref="${{ inputs.ci_image_name }}" \
            --cache-from=type=registry,ref="${{ inputs.ci_image_cache }}" \
            --push \
            -t "${{ inputs.ci_image_name }}" \
            "${GITHUB_WORKSPACE}/projects/hipfile/util/docker"

      - name: Build NVIDIA image for AIS CI
        run: |
          docker buildx build \
            -f "${GITHUB_WORKSPACE}/projects/hipfile/util/docker/DOCKERFILE.ais_ci_${{ inputs.platform }}" \
            --target nvidia \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg ROCM_VERSION=${AIS_INPUT_ROCM_VERSION} \
            --cache-from=type=registry,ref="${{ inputs.ci_image_name_nvidia }}" \
            --cache-from=type=registry,ref="${{ inputs.ci_image_cache_nvidia }}" \
            --push \
            -t "${{ inputs.ci_image_name_nvidia }}" \
            "${GITHUB_WORKSPACE}/projects/hipfile/util/docker"
