# Formatting checks for emulation/rocjitsu/.
name: "rocjitsu-formatting"

on:
  pull_request:
    paths:
      - "emulation/rocjitsu/**"
      - ".github/workflows/rocjitsu-*.yml"
      - ".pre-commit-config.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rocjitsu actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            emulation/rocjitsu/actions

      - name: Run rocjitsu formatting checks
        uses: ./emulation/rocjitsu/actions/rocjitsu-formatting
