name: rocprofiler-systems Continuous Integration Containers
run-name: ci-containers

# nightly build
on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/rocprofiler-systems-containers.yml'
      - 'projects/rocprofiler-systems/docker/**'
  pull_request:
    paths:
      - '.github/workflows/rocprofiler-systems-containers.yml'
      - 'projects/rocprofiler-systems/docker/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  prepare_matrix_ci:
    if: github.repository == 'ROCm/rocm-systems'
    runs-on: ubuntu-latest
    outputs:
      matrix_data: ${{ steps.generate_matrix_ci_base.outputs.matrix_data }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: projects/rocprofiler-systems/docker

      - name: Output data for containers matrix
        working-directory: projects/rocprofiler-systems/docker
        id: generate_matrix_ci_base
        run: |
          MATRIX_CONTENT=$(cat containers-ci.yml | yq '.matrix' -I=0 -o=json)
          echo "matrix_data=$MATRIX_CONTENT" >> $GITHUB_OUTPUT

  rocprofiler-systems-ci-base:
    needs: prepare_matrix_ci
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare_matrix_ci.outputs.matrix_data) }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: projects/rocprofiler-systems/docker
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }}
          password: ${{ secrets.ROCPROF_SYS_DOCKER_TOKEN }}

      - name: Set up Docker variables
        id: setup_vars_base
        run: |
          if [ ${{ matrix.distro }} = "opensuse" ]; then
            DISTRO_IMAGE="opensuse/leap"
          elif [ ${{ matrix.distro }} = "rhel" ]; then
            DISTRO_IMAGE="rockylinux/rockylinux"
          else
            DISTRO_IMAGE=${{ matrix.distro }}
          fi
          echo "distro_image=${DISTRO_IMAGE}" >> $GITHUB_OUTPUT

          if [ ${{ matrix.distro }} = "debian" ]; then
            DOCKER_FILE=Dockerfile.ubuntu.ci
          else
            DOCKER_FILE=Dockerfile.${{ matrix.distro }}.ci
          fi
          echo "docker_file=${DOCKER_FILE}" >> $GITHUB_OUTPUT
          
      - name: Build CI Base Container (Does not Push on PR)
        uses: docker/build-push-action@v6
        with:
          file: projects/rocprofiler-systems/docker/${{ steps.setup_vars_base.outputs.docker_file }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            DISTRO=${{ steps.setup_vars_base.outputs.distro_image }}
            VERSION=${{ matrix.version }}
            NJOBS=2
            ELFUTILS_DOWNLOAD_VERSION=0.188
            BOOST_DOWNLOAD_VERSION=1.79.0
          tags: |
            ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }}/rocprofiler-systems:ci-base-${{ matrix.distro }}-${{ matrix.version }}

  rocprofiler-systems-ci-gfx:
    needs: prepare_matrix_ci
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJSON(needs.prepare_matrix_ci.outputs.matrix_data) }}
        gpu: [ 'gfx94X', 'gfx950' ]

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: projects/rocprofiler-systems
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker variables
        id: setup_vars_gfx
        run: |
          if [ ${{ matrix.system.distro }} = "opensuse" ]; then
            DISTRO_IMAGE="opensuse/leap"
          elif [ ${{ matrix.system.distro }} = "rhel" ]; then
            DISTRO_IMAGE="rockylinux/rockylinux"
          else
            DISTRO_IMAGE=${{ matrix.system.distro }}
          fi
          echo "distro_image=${DISTRO_IMAGE}" >> $GITHUB_OUTPUT

          if [ ${{ matrix.system.distro }} = "debian" ]; then
            DOCKER_FILE=Dockerfile.ubuntu.ci
          else
            DOCKER_FILE=Dockerfile.${{ matrix.system.distro }}.ci
          fi
          echo "docker_file=${DOCKER_FILE}" >> $GITHUB_OUTPUT
      
      - name: Get the latest build of The Rock tarball
        id: therock
        run: |
          sudo apt-get install -y python3-pip
          python3 -m pip install -U pip
          python3 -m pip install -U awscli
          export PATH=~/.local/bin:$PATH
          KEY=$(aws s3api list-objects-v2 \
                --bucket therock-nightly-tarball \
                --no-sign-request \
                --output json \
                --query "sort_by(Contents[?contains(Key, 'linux-${{ matrix.gpu }}')], &LastModified)[-1].Key")
          KEY=${KEY//\"/}
          test -n "$KEY" || { echo "No ${{ matrix.gpu }} tarball found"; exit 1; }
          echo "tarball=${KEY}" >> $GITHUB_OUTPUT
      
      - name: Build CI GFX Container (Does not Push on PR)
        uses: docker/build-push-action@v6
        with:
          file: projects/rocprofiler-systems/docker/${{ steps.setup_vars_gfx.outputs.docker_file }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            DISTRO=${{ steps.setup_vars_gfx.outputs.distro_image }}
            VERSION=${{ matrix.system.version }}
            TYPE=${{ matrix.gpu }}
            GPU_TYPE=${{ matrix.gpu }}
            GPU_TARBALL=${{ steps.therock.outputs.tarball }}
            NJOBS=2
            ELFUTILS_DOWNLOAD_VERSION=0.188
            BOOST_DOWNLOAD_VERSION=1.79.0
          tags: |
            rocprofiler-${{ matrix.system.distro }}-${{ matrix.system.version }}:ci-${{ matrix.gpu }}
          cache-from: type=gha,scope=rocprofiler-ci-${{ matrix.system.distro }}-${{ matrix.system.version }}-${{ matrix.gpu }}
          cache-to: type=gha,mode=max,scope=rocprofiler-ci-${{ matrix.system.distro }}-${{ matrix.system.version }}-${{ matrix.gpu }}

  prepare_matrix_release:
    if: github.repository == 'ROCm/rocm-systems'
    runs-on: ubuntu-latest
    outputs:
      matrix_data: ${{ steps.generate_matrix_release.outputs.matrix_data }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: projects/rocprofiler-systems

      - name: Output data for containers matrix
        working-directory: projects/rocprofiler-systems/docker
        id: generate_matrix_release
        run: |
          MATRIX_CONTENT=$(cat containers.yml | yq '.matrix' -I=0 -o=json)
          echo "matrix_data=$MATRIX_CONTENT" >> $GITHUB_OUTPUT
          
  rocprofiler-systems-release:
    needs: prepare_matrix_release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare_matrix_release.outputs.matrix_data) }}
          
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: projects/rocprofiler-systems

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }}
          password: ${{ secrets.ROCPROF_SYS_DOCKER_TOKEN }}

      - name: Build Base Container (PR - No Push)
        if: github.event_name == 'pull_request'
        timeout-minutes: 45
        uses: nick-fields/retry@v3
        with:
          retry_wait_seconds: 60
          timeout_minutes: 45
          max_attempts: 3
          command: |
            pushd projects/rocprofiler-systems/docker
            ./build-docker.sh \
              --distro ${{ matrix.os-distro }} \
              --versions ${{ matrix.os-version }} \
              --rocm-versions ${{ matrix.rocm-version }} \
              --user ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }}
            popd
      
      - name: Build Base Container (Push)
        if: github.event_name != 'pull_request'
        timeout-minutes: 45
        uses: nick-fields/retry@v3
        with:
          retry_wait_seconds: 60
          timeout_minutes: 45
          max_attempts: 3
          command: |
            pushd projects/rocprofiler-systems/docker
            ./build-docker.sh \
              --distro ${{ matrix.os-distro }} \
              --versions ${{ matrix.os-version }} \
              --rocm-versions ${{ matrix.rocm-version }} \
              --user ${{ secrets.ROCPROF_SYS_DOCKER_LOGIN }} \
              --push
            popd
