name: rocprofiler-systems Ubuntu Packaging (Release, ROCm)
run-name: ubuntu-packaging

on:
  push:
    paths:
      - '.github/workflows/rocprofiler-systems-ubuntu-packaging.yml`
      - 'projects/rocprofiler-systems/**'
      - '!projects/rocprofiler-systems/*.md'
      - '!projects/rocprofiler-systems/docs/**'
      - '!projects/rocprofiler-systems/source/docs/**'
      - '!projects/rocprofiler-systems/source/python/gui/**'
      - '!projects/rocprofiler-systems/.github/workflows/docs.yml'
      - '!projects/rocprofiler-systems/.github/workflows/cpack.yml'
      - '!projects/rocprofiler-systems/.github/workflows/containers.yml'
      - '!projects/rocprofiler-systems/.github/workflows/formatting.yml'
      - '!projects/rocprofiler-systems/.github/workflows/weekly-mainline-sync.yml'
      - '!projects/rocprofiler-systems/docker/**'
      - '!projects/rocprofiler-systems/.wordlist.txt'
      - '!projects/rocprofiler-systems/CMakePresets.json'
  pull_request:
    paths:
      - '.github/workflows/rocprofiler-systems-ubuntu-packaging.yml`
      - 'projects/rocprofiler-systems/**'
      - '!projects/rocprofiler-systems/*.md'
      - '!projects/rocprofiler-systems/docs/**'
      - '!projects/rocprofiler-systems/source/docs/**'
      - '!projects/rocprofiler-systems/source/python/gui/**'
      - '!projects/rocprofiler-systems/.github/workflows/docs.yml'
      - '!projects/rocprofiler-systems/.github/workflows/cpack.yml'
      - '!projects/rocprofiler-systems/.github/workflows/containers.yml'
      - '!projects/rocprofiler-systems/.github/workflows/formatting.yml'
      - '!projects/rocprofiler-systems/.github/workflows/weekly-mainline-sync.yml'
      - '!projects/rocprofiler-systems/docker/**'
      - '!projects/rocprofiler-systems/.wordlist.txt'
      - '!projects/rocprofiler-systems/CMakePresets.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ROCPROFSYS_CI: ON
  ROCPROFSYS_TMPDIR: "%env{PWD}%/testing-tmp"

jobs:
  ubuntu-packaging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ '20.04', '22.04', '24.04' ]
        rocm-version: [ '6.4' ]
    container:
      image: dgaliffiamd/rocprofiler-systems:ci-base-ubuntu-${{ matrix.release }}
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: projects/rocprofiler-systems/

    - name: Configure Env
      shell: bash
      run:
        echo "/opt/rocm/bin" >> $GITHUB_PATH  &&
        echo "ROCM_PATH=/opt/rocm" >> $GITHUB_ENV &&
        echo "LD_LIBRARY_PATH=/opt/rocm/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV &&
        echo "BUILD_DIR=./release" >> $GITHUB_ENV &&
        echo "INSTALL_DIR=/opt/rocprofiler-systems" >> $GITHUB_ENV &&
        echo "RELEASE=${{ matrix.release }}" >> $GITHUB_ENV &&
        env

    - name: Install ROCm
      timeout-minutes: 15
      shell: bash
      run: |
        set -v
        ROCM_VERSION=${{ matrix.rocm-version }}
        ROCM_MAJOR=$(echo ${ROCM_VERSION} | sed 's/\./ /g' | awk '{print $1}')
        ROCM_MINOR=$(echo ${ROCM_VERSION} | sed 's/\./ /g' | awk '{print $2}')
        ROCM_VERSN=$(( (${ROCM_MAJOR}*10000)+(${ROCM_MINOR}*100) ))
        RELEASE_MAJOR=${echo ${RELEASE} | sed 's/\./ /g' | awk '{print $1}'}
        if [ "${RELEASE_MAJOR}" -eq 20 ]; then RELEASE_NAME=focal; fi
        if [ "${RELEASE_MAJOR}" -eq 22 ]; then RELEASE_NAME=jammy; fi
        if [ "${RELEASE_MAJOR}" -eq 24 ]; then RELEASE_NAME=noble; fi
        wget -q https://repo.radeon.com/amdgpu-install/${{ matrix.rocm-version }}/ubuntu/${RELEASE_NAME}/amdgpu-install_${ROCM_MAJOR}.${ROCM_MINOR}.${ROCM_VERSN}-1_all.deb
        apt-get install -y ./amdgpu-install_${ROCM_MAJOR}.${ROCM_MINOR}.${ROCM_VERSN}-1_all.deb
        apt-get update
        apt-get install -y rocm-dev rocdecode-dev libavformat-dev libavcodec-dev

    - name: Build rocprofiler-systems
      timeout-minutes: 35
      shell: bash
      run: |
        set -v
        git config --global --add safe.directory ${PWD} &&
        cmake --preset release -B $BUILD_DIR -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCPACK_PACKAGING_INSTALL_PREFIX=$INSTALL_DIR
        cmake --build $BUILD_DIR --target all

    - name: Build and Install the Package
      timeout-minutes: 10
      shell: bash
      run: |
        set -v
        cd $BUILD_DIR
        cpack -G DEB
        dpkg -i *.deb

    - name: Verify Installation
      timeout-minutes: 15
      shell: bash
      run: |
        set -v
        echo "TO BE ADDED LATER"
