name: rocprofiler-systems Release

on:
  workflow_dispatch:
  push:
    paths:
      - "projects/rocprofiler-systems/**"
    tags:
      - "v[1-9].[0-9]+.[0-9]+*"
      - "rocm-[1-9].[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: projects/rocprofiler-systems/
      - name: Generate generic installer script
        shell: bash
        working-directory: projects/rocprofiler-systems/
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          cmake -D OUTPUT_DIR=${PWD} -P scripts/write-rocprof-sys-install.cmake
      - name: Generate Release
        uses: softprops/action-gh-release@v1
        with:
          draft: False
          generate_release_notes: True
          fail_on_unmatched_files: True
          files: |
            projects/rocprofiler-systems/rocprofiler-systems-install.py
