name: rocprofiler-systems Continuous Integration
run-name: rocprofiler-systems-ci

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths:
      - '.github/workflows/rocprofiler-systems-continuous-integration.yml'
      - 'projects/rocprofiler-systems/**'
      - '!projects/rocprofiler-systems/*.md'
      - '!projects/rocprofiler-systems/docs/**'
      - '!projects/rocprofiler-systems/source/docs/**'
      - '!projects/rocprofiler-systems/source/python/gui/**'
      - '!projects/rocprofiler-systems/docker/**'
      - '!projects/rocprofiler-systems/.wordlist.txt'
      - '!projects/rocprofiler-systems/CMakePresets.json'
  pull_request:
    paths:
      - '.github/workflows/rocprofiler-systems-continuous-integration.yml'
      - 'projects/rocprofiler-systems/**'
      - '!projects/rocprofiler-systems/*.md'
      - '!projects/rocprofiler-systems/docs/**'
      - '!projects/rocprofiler-systems/source/docs/**'
      - '!projects/rocprofiler-systems/source/python/gui/**'
      - '!projects/rocprofiler-systems/docker/**'
      - '!projects/rocprofiler-systems/.wordlist.txt'
      - '!projects/rocprofiler-systems/CMakePresets.json'

env:
  ROCPROFSYS_CI: ON
  ROCM_PATH: "/opt/rocm"
  ROCM_VERSION: "7.0.0"
  PYTHON_VENV_NAME: "rocprofiler-systems"
  PYTHON_VENV_ACTIVATE: "rocprofiler-systems/bin/activate"

  # TODO: Remove once Docker gfx images have these
  HIP_PLATFORM: "amd"

jobs:
  ubuntu:
    name: Ubuntu ${{ matrix.system.os-release }} • ${{ matrix.system.arch }}
    strategy:
      matrix:
        system:
          - { os-release: '22.04', gpu: 'mi355', arch: 'gfx950', runner: 'linux-mi355-1gpu-ossci-rocm'}
          - { os-release: '24.04', gpu: 'mi355', arch: 'gfx950', runner: 'linux-mi355-1gpu-ossci-rocm'}
    runs-on: ${{ matrix.system.runner }}
    container:
      # TODO: Replace with dgaliffiamd/rocprofiler-systems:ci-${{ matrix.system.arch }}-ubuntu-${{ matrix.system.os-release }}
      image: dgaliffiamd/rocprofiler-systems:ci-base-ubuntu-${{ matrix.system.os-release }}
      options: --ipc host
        --group-add video
        --device /dev/kfd
        --device /dev/dri
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: projects/rocprofiler-systems/

      - name: Setup Environment
        id: setup_env
        run: |
          if [ '${{ github.event_name }}' = 'schedule' ]; then
            MODE=Nightly
          else
            MODE=Continuous
          fi
          echo "mode=${MODE}" >> $GITHUB_OUTPUT

          if [ '${{ matrix.system.os-release }}' = '24.04']; then
            CODE_NAME=noble
          else
            CODE_NAME=jammy
          fi
          echo "code_name=${CODE_NAME}" >> $GITHUB_OUTPUT

      # TODO: Remove this step once amdgpu logic has been added to gfx Dockers
      - name: Install amdgpu (remove once added to gfx Dockers)
        shell: bash
        run: |
          wget -N -P /tmp/ https://repo.radeon.com/amdgpu-install/7.0/ubuntu/${{ steps.setup_env.outputs.code_name }}/amdgpu-install_7.0.70000-1_all.deb
          apt-get install -y /tmp/amdgpu-install_7.0.70000-1_all.deb
          apt-get update
          apt install -y amd-smi-lib rocjpeg-test rocdecode-test rccl-dev
          echo "✅ amdgpu Installed!"

      # TODO: Remove this step once the gfx Dockers are available
      - name: Download Latest Nightly ROCm (remove once gfx Dockers are available)
        id: therock
        shell: bash
        working-directory: projects/rocprofiler-systems
        run: |
          set -e
          if [ ${{ matrix.system.os-release }} = '24.04' ]; then
            apt install -y python3.12-venv
          else
            apt install -y python3.10-venv
          fi
          python3 -m venv ${{ env.PYTHON_VENV_NAME }}
          source ${{ env.PYTHON_VENV_ACTIVATE }}
          python3 -m pip install -U pip
          python3 -m pip install -U awscli
          export PATH=~/.local/bin:$PATH
          KEY=$(aws s3api list-objects-v2 \
                --bucket therock-nightly-tarball \
                --no-sign-request \
                --output json \
                --query "sort_by(Contents[?contains(Key, 'linux-${{ matrix.system.arch }}')], &LastModified)[-1].Key")
          KEY=${KEY//\"/}
          test -n "$KEY" || { echo "No ${{ matrix.system.arch }} tarball found"; exit 1; }
          aws s3 cp "s3://therock-nightly-tarball/${KEY}" rocm-${{ matrix.system.arch }}.tar.gz --no-sign-request
          mv rocm-${{ matrix.system.arch }}.tar.gz /opt/${{ matrix.system.arch }}.tar.gz
          echo "✅ Latest TheRock Tarball Release for ${{ matrix.system.arch }} Downloaded!"

      - name: Install Latest Nightly ROCm
        run: |
          set -e
          tar -xf /opt/${{ matrix.system.arch }}.tar.gz -C ${{ env.ROCM_PATH }}-${{ env.ROCM_VERSION }}
          ln -s ${{ env.ROCM_PATH }}-${{ env.ROCM_VERSION }} ${{ env.ROCM_PATH }}
          echo "ROCm installed to: ${{ env.ROCM_PATH }}"
          echo "✅ ROCm Installation Complete!"

      - name: Configure, Build, and Test
        timeout-minutes: 30
        working-directory: projects/rocprofiler-systems
        run: |
          set -e
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git config --global --add safe.directory ${PWD}
          PATH=${{ env.ROCM_PATH }}/bin:${{ env.ROCM_PATH }}/llvm/bin:$PATH \
          LD_LIBRARY_PATH=${{ env.ROCM_PATH }}/lib:${{ env.ROCM_PATH }}/llvm/lib:$LD_LIBRARY_PATH \
          python3 ./scripts/run-ci.py \
            -S ${PWD} \
            -B build \
            --name ${{ github.repository }}-${{ github.ref_name }}-ubuntu-${{ matrix.system.os-release }}-${{ matrix.system.gpu }} \
            --build-jobs 2 \
            --site ${{ matrix.system.runner }} \
            --mode ${{ steps.setup_env.outputs.mode }} \
            -- \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_PREFIX_PATH=${{ env.ROCM_PATH }} \
            -DCMAKE_INSTALL_PREFIX=${{ env.ROCM_PATH }}-${{ env.ROCM_VERSION }} \
            -DROCPROFSYS_BUILD_{DYNINST,TBB,BOOST,ELFUTILS,LIBIBERTY}=ON \
            -DROCPROFSYS_USE_PYTHON=ON \
            -DROCPROFSYS_BUILD_TESTING=ON
