name: Runfile Installer CI

on:
  pull_request:
    branches: [users/pbhandar/runfile-installer]
    paths:
      - 'projects/runfile-installer/**'
      - '.github/workflows/runfile-installer-build.yml'
  push:
    branches: [users/pbhandar/runfile-installer]
    paths:
      - 'projects/runfile-installer/**'
      - '.github/workflows/runfile-installer-build.yml'
  workflow_dispatch:
    inputs:
      rocm_version:
        description: ROCm version used to build runfile installer
        required: true
        type: string
        default: "7.11.0"
      pull_tag:
        description: Set to rc[BUILD_NUM] for prerelease builds
        required: true
        type: string
        default: "rc2"
      pull_type:
        description: Specify where to pull packages from
        type: choice
        options:
          - prerelease
          - nightly
        default: "prerelease"
      pull_run_id:
        description: Workflow run id of deb and rpm packages
        required: true
        type: string
        default: "21843385957"
      gfx_archs:
        description: gfx architectures to build
        required: true
        type: string
        # default: "gfx90x,gfx94x,gfx950,gfx110x,gfx1150,gfx1151,gfx1152,gfx120x"
        default: "gfx110x"
      pull_amdgpu:
        description: Version of amdgpu to be packaged
        required: true
        type: string
        default: "release,31.10"
      pull_pkg:
        description: Base package name with optional type prefix
        required: false
        type: string
        default: "amdrocm-core-sdk"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: Runfile Installer CI (${{ inputs.rocm_version || '7.11.0' }}, ${{ inputs.pull_type || 'prerelease' }}, ${{ inputs.pull_tag || 'rc2' }})

jobs:
  build_runfile_installer:
    name: Build Runfile Installer
    # runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-linux-scale-rocm' || 'ubuntu-24.04' }}
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:d6ae5712a9c7e8b88281d021e907b312cd8a26295b95690baef3e8dde4805858
    defaults:
      run:
        working-directory: ${{ github.workspace }}/projects/runfile-installer
    env:
      BUILD_IMAGE: ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:d6ae5712a9c7e8b88281d021e907b312cd8a26295b95690baef3e8dde4805858
      BUILD_RUNID: ${{ github.run_id }}
      OUTPUT_DIR: ${{ github.workspace }}/build
      RUNFILE_BUILD_DIR: ${{ github.workspace }}/build
      # Default values for PRs and pushes; overridden by workflow_dispatch inputs
      ROCM_VERSION: ${{ inputs.rocm_version || '7.11.0' }}
      PULL_TAG: ${{ inputs.pull_tag || 'rc2' }}
      PULL_TYPE: ${{ inputs.pull_type || 'prerelease' }}
      PULL_RUN_ID: ${{ inputs.pull_run_id || '21843385957' }}
      GFX_ARCHS: ${{ inputs.gfx_archs || 'gfx110x' }}
      PULL_AMDGPU: ${{ inputs.pull_amdgpu || 'release,31.10' }}
      PULL_PKG: ${{ inputs.pull_pkg || 'amdrocm-core-sdk' }}
      RELEASE_TYPE: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set BUILD_TAG
        working-directory: ${{ github.workspace }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          BUILD_TAG="dev-$(git rev-parse --short HEAD)"
          echo "Set value of BUILD_TAG = '$BUILD_TAG'"
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV

      - name: Run build-runfile-installer.sh
        run: |
          echo "### Runfile Build Options" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`bash build-runfile-installer.sh rocm amdgpu rocm-archs=$GFX_ARCHS pullamdgpu=$PULL_AMDGPU pull=$PULL_TYPE pulltag=$PULL_TAG pullrunid=$PULL_RUN_ID pullrocmver=$ROCM_VERSION pullpkg=$PULL_PKG buildtag=$BUILD_TAG buildrunid=$BUILD_RUNID mscomp=dev\`" >> $GITHUB_STEP_SUMMARY

          bash build-runfile-installer.sh rocm amdgpu rocm-archs=$GFX_ARCHS pullamdgpu=$PULL_AMDGPU pull=$PULL_TYPE pulltag=$PULL_TAG pullrunid=$PULL_RUN_ID pullrocmver=$ROCM_VERSION pullpkg=$PULL_PKG buildtag=$BUILD_TAG buildrunid=$BUILD_RUNID mscomp=dev

      - name: Show .run file
        run: |
          echo "### Generated Runfile" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          find . -name "*.run" -type f -exec ls -lctrh {} \; | tee -a $GITHUB_STEP_SUMMARY
