# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

name: TheRock Multi-Arch CI ASAN

on:
  push:
    branches:
      - develop
      - users/geomin12/host-asan # TODO: remove after testing
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ROCm/TheRock/.github/workflows/setup_multi_arch.yml@685f8c3b89006309b34a7c16de17e841400f0d76 # 2026-05-29 commit
    with:
      build_variant: "host-asan"

  linux_build_and_test:
    name: Linux::${{ fromJSON(needs.setup.outputs.linux_build_config || '{}').build_variant_label || 'skip' }}
    needs: setup
    if: ${{ needs.setup.outputs.linux_build_config != '' && needs.setup.outputs.enable_build_jobs == 'true' }}
    uses: ROCm/TheRock/.github/workflows/multi_arch_ci_linux.yml@685f8c3b89006309b34a7c16de17e841400f0d76 # 2026-05-29 commit
    secrets: inherit
    with:
      build_config: ${{ needs.setup.outputs.linux_build_config }}
      test_labels: ${{ needs.setup.outputs.linux_test_labels }}
      rocm_package_version: ${{ needs.setup.outputs.rocm_package_version }}
      rocm_deb_package_version: ${{ needs.setup.outputs.rocm_deb_package_version }}
      rocm_rpm_package_version: ${{ needs.setup.outputs.rocm_rpm_package_version }}
      test_type: ${{ needs.setup.outputs.test_type }}
    permissions:
      contents: read
      id-token: write
