# Supported OS combinations for continuous integration

matrix:
  # ubuntu
  - distro: "ubuntu"
    version: "22.04"
  - distro: "ubuntu"
    version: "24.04"
  # debian
  - distro: "debian"
    version: "12"
  # opensuse
  - distro: "opensuse"
    version: "15.5"
  - distro: "opensuse"
    version: "15.6"
  # RHEL8
  - distro: "rhel"
    version: "8.10"
  # RHEL9
  - distro: "rhel"
    version: "9"
  # RHEL10
  - distro: "rhel"
    version: "10"

  # Ubuntu 22.04 with ROCm
  - distro: "ubuntu"
    version: "22.04"
    rocm-version: "6.3"
  - distro: "ubuntu"
    version: "22.04"
    rocm-version: "6.4"
  - distro: "ubuntu"
    version: "22.04"
    rocm-version: "7.0"
  - distro: "ubuntu"
    version: "22.04"
    rocm-version: "7.1"
  - distro: "ubuntu"
    version: "22.04"
    rocm-version: "7.2"

  # Ubuntu 24.04 with ROCm
  - distro: "ubuntu"
    version: "24.04"
    rocm-version: "6.3"
  - distro: "ubuntu"
    version: "24.04"
    rocm-version: "6.4"
  - distro: "ubuntu"
    version: "24.04"
    rocm-version: "7.0"
  - distro: "ubuntu"
    version: "24.04"
    rocm-version: "7.1"
  - distro: "ubuntu"
    version: "24.04"
    rocm-version: "7.2"

  # RHEL 8.10 with ROCm
  - distro: "rhel"
    version: "8.10"
    rocm-version: "6.3"
  - distro: "rhel"
    version: "8.10"
    rocm-version: "6.4"
  - distro: "rhel"
    version: "8.10"
    rocm-version: "7.0"
  - distro: "rhel"
    version: "8.10"
    rocm-version: "7.1"
  - distro: "rhel"
    version: "8.10"
    rocm-version: "7.2"

  # RHEL 9 with ROCm
  - distro: "rhel"
    version: "9"
    rocm-version: "6.3"
  - distro: "rhel"
    version: "9"
    rocm-version: "6.4"
  - distro: "rhel"
    version: "9"
    rocm-version: "7.0"
  - distro: "rhel"
    version: "9"
    rocm-version: "7.1"
  - distro: "rhel"
    version: "9"
    rocm-version: "7.2"
